const PHRASELIST = [
  { word: "törstig", phrase: "Min kompis är ofta törstig. Jag börjar misstänka att han har sockersjuka.", video: "torstig-00139-fras-1.mp4" },
  { word: "törstig", phrase: "Jag har tränat och är törstig nu.", video: "torstig-00139-fras-2.mp4" },
  { word: "glad", phrase: "Barnen är verkligen glada för de ska träffa tomten.", video: "glad-00165-fras-1.mp4" },
  { word: "glad", phrase: "Vissa personer som kan verka glada på utsidan är på insidan allt annat än glad.", video: "glad-00165-fras-2.mp4" },
  { word: "vill", phrase: "Jag vill åka jorden runt.", video: "vill-00167-fras-1.mp4" },
  { word: "vill", phrase: "Jag skulle vilja åka till Dövas hus. Det verkar hända roliga saker där.", video: "vill-00167-fras-2.mp4" },
  { word: "vill", phrase: "Jag vill att du går nu.", video: "vill-00167-fras-3.mp4" },
  { word: "vår", phrase: "Vårt beslut står fast. Det går inte att ändra.", video: "var-00186-fras-1.mp4" },
  { word: "vår", phrase: "Vår gymnasietid var helt skruvad.", video: "var-00186-fras-2.mp4" },
  { word: "hund", phrase: "Mina barn tjatar om att få en hund men det kan de inte få för jag är allergisk.", video: "hund-00222-fras-1.mp4" },
  { word: "hund", phrase: "Min förra hund hette Mia.", video: "hund-00222-fras-2.mp4" },
  { word: "hund", phrase: "På torsdagarna går jag alltid till hundparken med min hund.", video: "hund-00222-fras-3.mp4" },
  { word: "barn", phrase: "Mina barn är helt sålda på TV-spel. De måste spela varje dag.", video: "barn-00257-fras-1.mp4" },
  { word: "barn", phrase: "När sommarlovet är slut är barnen fulla av iver över att komma tillbaka till skolan.", video: "barn-00257-fras-2.mp4" },
  { word: "barn", phrase: "Jag har tre barn.", video: "barn-00257-fras-3.mp4" },
  { word: "katt", phrase: "Min katt är 8 år gammal", video: "katt-00344-fras-1.mp4" },
  { word: "katt", phrase: "Jag har haft katt i 14 år.", video: "katt-00344-fras-2.mp4" },
  { word: "katt", phrase: "Katten var ungefär så här stor.", video: "katt-00344-fras-3.mp4" },
  { word: "bröd", phrase: "Nu ska jag baka bröd. Smaskens!", video: "brod-00434-fras-1.mp4" },
  { word: "bröd", phrase: "Vad är skillnaden på surdegsbröd och vanligt bröd?", video: "brod-00434-fras-2.mp4" },
  { word: "bröd", phrase: "Det finns olika sorters bröd; limpa, baguette med mera.", video: "brod-00434-fras-3.mp4" },
  { word: "natt", phrase: "Jag tycker mycket om natten eftersom jag är en nattmänniska.", video: "natt-00516-fras-1.mp4" },
  { word: "natt", phrase: "Var ska du sova imorgon natt?", video: "natt-00516-fras-2.mp4" },
  { word: "natt", phrase: "Du får sova här en natt men inte mer.", video: "natt-00516-fras-3.mp4" },
  { word: "natt", phrase: "På natten sover jag.", video: "natt-00516-fras-4.mp4" },
  { word: "baby", phrase: "Jag tycker om bebisar.", video: "baby-00573-fras-1.mp4" },
  { word: "baby", phrase: "Babyn skriker och gråter hela tiden. Jag blir så irriterad.", video: "baby-00573-fras-2.mp4" },
  { word: "baby", phrase: "Vet du hur man sköter en baby?", video: "baby-00573-fras-3.mp4" },
  { word: "kort", phrase: "Jag la i mina mynt och började köra bilspelet. Plötsligt tog spelet slut och jag fattade ingenting! Jag hade ju knappt hunnit börja köra, tyckte jag.", video: "kort-00602-fras-1.mp4" },
  { word: "kort", phrase: "Jag vet inte om jag kommer orka se hela filmen. Hur lång är den?", video: "kort-00602-fras-2.mp4" },
  { word: "morgon", phrase: "Jag är ingen morgonmänniska. Jag är alltid sur på morgonen.", video: "morgon-00623-fras-1.mp4" },
  { word: "morgon", phrase: "Var snäll och vakna tidigt imorgon bitti.", video: "morgon-00623-fras-2.mp4" },
  { word: "morgon", phrase: "Min son är alltid morgonpigg.", video: "morgon-00623-fras-3.mp4" },
  { word: "dag", phrase: "Jobba på dagen är inget för mig. Jag jobbar hellre på natten.", video: "dag-00632-fras-1.mp4" },
  { word: "dag", phrase: "Igår var verkligen inte min dag på grund av allt som hände, jag tappade min nyckel och plånbok plus att jag kom försent till jobbet.", video: "dag-00632-fras-2.mp4" },
  { word: "vad", phrase: "Vilken sport är du intresserad av?", video: "vad-00644-fras-1.mp4" },
  { word: "vad", phrase: "Vad har du för hobby eller intresse?", video: "vad-00644-fras-2.mp4" },
  { word: "vad", phrase: "Vad brukar du göra på fredagarna?", video: "vad-00644-fras-3.mp4" },
  { word: "vad", phrase: "Vad ska du göra imorgon kväll?", video: "vad-00644-fras-4.mp4" },
  { word: "inte", phrase: "Många tror att jag är gift men det är faktiskt inte så.", video: "inte-00646-fras-1.mp4" },
  { word: "inte", phrase: "Jag klarar mig inte utan min mobil.", video: "inte-00646-fras-2.mp4" },
  { word: "inte", phrase: "Du lyssnar inte.", video: "inte-00646-fras-3.mp4" },
  { word: "inte", phrase: "Kalle är inte godkänd.", video: "inte-00646-fras-4.mp4" },
  { word: "bord", phrase: "Nu ska jag leta efter ett litet bord till balkongen.", video: "bord-00664-fras-1.mp4" },
  { word: "törstig", phrase: "Min kompis är ofta törstig. Jag börjar misstänka att han har sockersjuka.", video: "torstig-00139-fras-1.mp4" },
  { word: "törstig", phrase: "Jag har tränat och är törstig nu.", video: "torstig-00139-fras-2.mp4" },
  { word: "glad", phrase: "Barnen är verkligen glada för de ska träffa tomten.", video: "glad-00165-fras-1.mp4" },
  { word: "glad", phrase: "Vissa personer som kan verka glada på utsidan är på insidan allt annat än glad.", video: "glad-00165-fras-2.mp4" },
  { word: "vill", phrase: "Jag vill åka jorden runt.", video: "vill-00167-fras-1.mp4" },
  { word: "vill", phrase: "Jag skulle vilja åka till Dövas hus. Det verkar hända roliga saker där.", video: "vill-00167-fras-2.mp4" },
  { word: "vill", phrase: "Jag vill att du går nu.", video: "vill-00167-fras-3.mp4" },
  { word: "vår", phrase: "Vårt beslut står fast. Det går inte att ändra.", video: "var-00186-fras-1.mp4" },
  { word: "vår", phrase: "Vår gymnasietid var helt skruvad.", video: "var-00186-fras-2.mp4" },
  { word: "hund", phrase: "Mina barn tjatar om att få en hund men det kan de inte få för jag är allergisk.", video: "hund-00222-fras-1.mp4" },
  { word: "hund", phrase: "Min förra hund hette Mia.", video: "hund-00222-fras-2.mp4" },
  { word: "hund", phrase: "På torsdagarna går jag alltid till hundparken med min hund.", video: "hund-00222-fras-3.mp4" },
  { word: "barn", phrase: "Mina barn är helt sålda på TV-spel. De måste spela varje dag.", video: "barn-00257-fras-1.mp4" },
  { word: "barn", phrase: "När sommarlovet är slut är barnen fulla av iver över att komma tillbaka till skolan.", video: "barn-00257-fras-2.mp4" },
  { word: "barn", phrase: "Jag har tre barn.", video: "barn-00257-fras-3.mp4" },
  { word: "katt", phrase: "Min katt är 8 år gammal", video: "katt-00344-fras-1.mp4" },
  { word: "katt", phrase: "Jag har haft katt i 14 år.", video: "katt-00344-fras-2.mp4" },
  { word: "katt", phrase: "Katten var ungefär så här stor.", video: "katt-00344-fras-3.mp4" },
  { word: "bröd", phrase: "Nu ska jag baka bröd. Smaskens!", video: "brod-00434-fras-1.mp4" },
  { word: "bröd", phrase: "Vad är skillnaden på surdegsbröd och vanligt bröd?", video: "brod-00434-fras-2.mp4" },
  { word: "bröd", phrase: "Det finns olika sorters bröd; limpa, baguette med mera.", video: "brod-00434-fras-3.mp4" },
  { word: "natt", phrase: "Jag tycker mycket om natten eftersom jag är en nattmänniska.", video: "natt-00516-fras-1.mp4" },
  { word: "natt", phrase: "Var ska du sova imorgon natt?", video: "natt-00516-fras-2.mp4" },
  { word: "natt", phrase: "Du får sova här en natt men inte mer.", video: "natt-00516-fras-3.mp4" },
  { word: "natt", phrase: "På natten sover jag.", video: "natt-00516-fras-4.mp4" },
  { word: "baby", phrase: "Jag tycker om bebisar.", video: "baby-00573-fras-1.mp4" },
  { word: "baby", phrase: "Babyn skriker och gråter hela tiden. Jag blir så irriterad.", video: "baby-00573-fras-2.mp4" },
  { word: "baby", phrase: "Vet du hur man sköter en baby?", video: "baby-00573-fras-3.mp4" },
  { word: "kort", phrase: "Jag la i mina mynt och började köra bilspelet. Plötsligt tog spelet slut och jag fattade ingenting! Jag hade ju knappt hunnit börja köra, tyckte jag.", video: "kort-00602-fras-1.mp4" },
  { word: "kort", phrase: "Jag vet inte om jag kommer orka se hela filmen. Hur lång är den?", video: "kort-00602-fras-2.mp4" },
  { word: "morgon", phrase: "Jag är ingen morgonmänniska. Jag är alltid sur på morgonen.", video: "morgon-00623-fras-1.mp4" },
  { word: "morgon", phrase: "Var snäll och vakna tidigt imorgon bitti.", video: "morgon-00623-fras-2.mp4" },
  { word: "morgon", phrase: "Min son är alltid morgonpigg.", video: "morgon-00623-fras-3.mp4" },
  { word: "dag", phrase: "Jobba på dagen är inget för mig. Jag jobbar hellre på natten.", video: "dag-00632-fras-1.mp4" },
  { word: "dag", phrase: "Igår var verkligen inte min dag på grund av allt som hände, jag tappade min nyckel och plånbok plus att jag kom försent till jobbet.", video: "dag-00632-fras-2.mp4" },
  { word: "vad", phrase: "Vilken sport är du intresserad av?", video: "vad-00644-fras-1.mp4" },
  { word: "vad", phrase: "Vad har du för hobby eller intresse?", video: "vad-00644-fras-2.mp4" },
  { word: "vad", phrase: "Vad brukar du göra på fredagarna?", video: "vad-00644-fras-3.mp4" },
  { word: "vad", phrase: "Vad ska du göra imorgon kväll?", video: "vad-00644-fras-4.mp4" },
  { word: "inte", phrase: "Många tror att jag är gift men det är faktiskt inte så.", video: "inte-00646-fras-1.mp4" },
  { word: "inte", phrase: "Jag klarar mig inte utan min mobil.", video: "inte-00646-fras-2.mp4" },
  { word: "inte", phrase: "Du lyssnar inte.", video: "inte-00646-fras-3.mp4" },
  { word: "inte", phrase: "Kalle är inte godkänd.", video: "inte-00646-fras-4.mp4" },
  { word: "bord", phrase: "Nu ska jag leta efter ett litet bord till balkongen.", video: "bord-00664-fras-1.mp4" },
  { word: "hus", phrase: "När jag gick längs med stranden fick jag syn på ett jättestort hus. Då började jag fundera över vem som kunde tänkas bo där.", video: "hus-00696-fras-1.mp4" },
  { word: "tack", phrase: "Jag har mina föräldrar att tacka för att de lärde sig teckenspråk. För tack vare det kan jag kommunicera med dem.", video: "tack-15805-fras-1.mp4" },
  { word: "tack", phrase: "Säg tack till hen!", video: "tack-15805-fras-2.mp4" },
  { word: "blå", phrase: "Jag har köpt en blå cykel.", video: "bla-07660-fras-1.mp4" },
  { word: "blå", phrase: "Om du blandar blå och gul färg så får du grön färg.", video: "bla-07660-fras-2.mp4" },
  { word: "röd", phrase: "Nu finns det ett nytt slags te som kallas för rött te.", video: "rod-02751-fras-1.mp4" },
  { word: "röd", phrase: "Jag har en röd bil, en Golf.", video: "rod-02751-fras-2.mp4" },
  { word: "grön", phrase: "Idag ska jag köpa en grön klänning.", video: "gron-00814-fras-1.mp4" },
  { word: "grön", phrase: "Under sommaren är gräset ofta vackert grönt.", video: "gron-00814-fras-2.mp4" },
  { word: "grön", phrase: "Är min tröja grön? Jag har svårt att se det på grund av att jag är färgblind.", video: "gron-00814-fras-3.mp4" },
  { word: "trött", phrase: "Är du trött?", video: "trott-00966-fras-1.mp4" },
  { word: "trött", phrase: "Idag känner jag mig trött i kroppen.", video: "trott-00966-fras-2.mp4" },
  { word: "trött", phrase: "Mina barn har varit ute länge och lekt så nu är de trötta.", video: "trott-00966-fras-3.mp4" },
  { word: "trött", phrase: "Jag undrar om jag har järnbrist eftersom jag känner mig så trött varje dag.", video: "trott-00966-fras-4.mp4" },
  { word: "kvinna", phrase: "Man brukar säga att när en tjej har fyllt 30 har hon blivit kvinna.", video: "kvinna-01106-fras-1.mp4" },
  { word: "äta", phrase: "Igår kväll efter mitt hårda träningspass mådde jag inte alls bra, det beror på att jag inte hade ätit och druckit ordentligt innan träningen.", video: "ata-01267-fras-1.mp4" },
  { word: "dricka", phrase: "Vi människor måste dricka ungefär två liter om dagen.", video: "dricka-01377-fras-1.mp4" },
  { word: "dricka", phrase: "Vad vill du dricka? Vatten, saft eller läsk?", video: "dricka-01377-fras-2.mp4" },
  { word: "dricka", phrase: "Alla barn var väldigt törstiga och drack massor med vatten.", video: "dricka-01377-fras-3.mp4" },
  { word: "dricka", phrase: "Va, drack alla vatten?", video: "dricka-01377-fras-4.mp4" },
  { word: "vatten", phrase: "Jag är törstig. Jag vill ha vatten.", video: "vatten-01384-fras-1.mp4" },
  { word: "buss", phrase: "När man har landat vid en turistort möts man ofta av väntande bussar som står i långa rader.", video: "buss-01474-fras-1.mp4" },
  { word: "kall", phrase: "Det är ofta väldigt kallt i februari och då måste man klä sig varmt.", video: "kall-01505-fras-1.mp4" },
  { word: "kall", phrase: "Om det är kallt ute och du har för lite kläder på dig, så kan det leda till att du blir sjuk.", video: "kall-01505-fras-2.mp4" },
  { word: "ledsen", phrase: "Alla kan känna sig ledsen ibland.", video: "ledsen-15383-fras-1.mp4" },
  { word: "ledsen", phrase: "Om jag inte busar med min hund så känner sig hen ledsen.", video: "ledsen-15383-fras-2.mp4" },
  { word: "jobba", phrase: "Jobbar du i natt?", video: "jobba-02063-fras-1.mp4" },
  { word: "jobba", phrase: "Min dotter jobbar varannan helg.", video: "jobba-02063-fras-2.mp4" },
  { word: "jobba", phrase: "Varför måste du jobba ikväll?", video: "jobba-02063-fras-3.mp4" },
  { word: "jobba", phrase: "Jag jobbar inte imorgon.", video: "jobba-02063-fras-4.mp4" },
  { word: "bil", phrase: "Jag har köpt en ny bil.", video: "bil-02158-fras-1.mp4" },
  { word: "bil", phrase: "Min bil är svart.", video: "bil-02158-fras-2.mp4" },
  { word: "bil", phrase: "Jag har två stycken röda bilar.", video: "bil-02158-fras-3.mp4" },
  { word: "ska", phrase: "Jag ska snart klippa mig.", video: "ska-02238-fras-1.mp4" },
  { word: "ska", phrase: "Anna ska köpa ett jättestort och fint hus.", video: "ska-02238-fras-2.mp4" },
  { word: "ska", phrase: "Imorgon ska jag på dejt, jag känner mig nervös inför det.", video: "ska-02238-fras-3.mp4" },
  { word: "ska", phrase: "Ska du spela golf idag?", video: "ska-02238-fras-4.mp4" },
  { word: "rolig", phrase: "Det är roligt att spela badminton.", video: "rolig-02354-fras-1.mp4" },
  { word: "rolig", phrase: "Det är roligt att resa ibland.", video: "rolig-02354-fras-2.mp4" },
  { word: "rolig", phrase: "I tisdags var vi ett stort gäng och kollade på bio, det var verkligen roligt.", video: "rolig-02354-fras-3.mp4" },
  { word: "kompis", phrase: "Min kompis har fått ett stipendium på 25 000 kr.", video: "kompis-02531-fras-1.mp4" },
  { word: "kompis", phrase: "Tjejen där är min bästa kompis.", video: "kompis-02531-fras-2.mp4" },
  { word: "kompis", phrase: "Mina barn ska sova hos sina kompisar nu till helgen.", video: "kompis-02531-fras-3.mp4" },
  { word: "kompis", phrase: "Hen är min kompis.", video: "kompis-02531-fras-4.mp4" },
  { word: "pappa", phrase: "Är han din pappa?", video: "pappa-02557-fras-1.mp4" },
  { word: "pappa", phrase: "Pappa är väldigt lång.", video: "pappa-02557-fras-2.mp4" },
  { word: "vit", phrase: "Jag har varit på landet i helgen. Det var så härligt för det var mycket snö och alldeles vitt.", video: "vit-02773-fras-1.mp4" },
  { word: "vit", phrase: "I Kina använder man vita kläder vid begravning.", video: "vit-02773-fras-2.mp4" },
  { word: "vit", phrase: "Du ser så blek ut i ansiktet, hur mår du? Mår du illa?", video: "vit-02773-fras-3.mp4" },
  { word: "jag", phrase: "Jag är inte hemma ikväll.", video: "jag-02798-fras-1.mp4" },
  { word: "jag", phrase: "Jag är inte godkänd.", video: "jag-02798-fras-2.mp4" },
  { word: "du", phrase: "Jag har inte gjort det. Det var du som skulle göra det.", video: "du-02817-fras-1.mp4" },
  { word: "du", phrase: "Är du sjuk?", video: "du-02817-fras-2.mp4" },
  { word: "du", phrase: "Har du feber?", video: "du-02817-fras-3.mp4" },
  { word: "du", phrase: "Du har glömt att meddela mig.", video: "du-02817-fras-4.mp4" },
  { word: "här", phrase: "Är det hen som är nyanställd här på jobbet?", video: "har-02866-fras-1.mp4" },
  { word: "sova", phrase: "Jag sov bra igår för det var ganska svalt i rummet.", video: "sova-03253-fras-1.mp4" },
  { word: "sova", phrase: "Sov nu!", video: "sova-03253-fras-2.mp4" },
  { word: "rädd", phrase: "Hur kommer det sig att du är rädd för ormar?", video: "radd-03447-fras-1.mp4" },
  { word: "rädd", phrase: "Jag kan känna mig lite rädd om jag promenerar i skogen när det är mörkt ute och det inte finns någon belysning.", video: "radd-03447-fras-2.mp4" },
  { word: "tid", phrase: "Idag är det många som tycker att tid är någonting viktigt.", video: "tid-03542-fras-1.mp4" },
  { word: "tid", phrase: "Jag har inte tid att hjälpa dig att flytta idag", video: "tid-03542-fras-2.mp4" },
  { word: "nej", phrase: "En kollega vill ha högre lön men chefen säger nej till det.", video: "nej-03952-fras-1.mp4" },
  { word: "när", phrase: "Jag vet inte när filmen startar.", video: "nar-03954-fras-1.mp4" },
  { word: "när", phrase: "När kommer min bror hem ikväll?", video: "nar-03954-fras-2.mp4" },
  { word: "när", phrase: "När ska du träna?", video: "nar-03954-fras-3.mp4" },
  { word: "titta", phrase: "Titta!", video: "titta-04101-fras-1.mp4" },
  { word: "se", phrase: "Jag har inte sett filmen.", video: "se-04104-fras-1.mp4" },
  { word: "se", phrase: "Det var roligt att se dig!", video: "se-04104-fras-2.mp4" },
  { word: "se", phrase: "Vad roligt att du såg mig på TV.", video: "se-04104-fras-3.mp4" },
  { word: "arg", phrase: "Jag flög till New York för att se på en teater, men väl framme fick jag veta att teatern var inställd. Jag blev så arg, 1800 kr helt bortkastade!", video: "arg-04321-fras-1.mp4" },
  { word: "arg", phrase: "Hen är riktigt förbannad för någon har tagit hens pengar.", video: "arg-04321-fras-2.mp4" },
  { word: "arg", phrase: "Mamman är så förbannad för barnen bråkar hela tiden.", video: "arg-04321-fras-3.mp4" },
  { word: "telefon", phrase: "Förut när jag var liten så hade mina föräldrar en gammeldags telefon med lur och fingerskiva.", video: "telefon-04490-fras-1.mp4" },
  { word: "telefon", phrase: "Får jag låna din telefon?", video: "telefon-04490-fras-2.mp4" },
  { word: "hur", phrase: "Hur kom du hit?", video: "hur-04569-fras-1.mp4" },
  { word: "hur", phrase: "Hur mycket vill du ha?", video: "hur-04569-fras-2.mp4" },
  { word: "hur", phrase: "Hur lyckades du med det?", video: "hur-04569-fras-3.mp4" },
  { word: "hur", phrase: "Hur lyckades du komma in på puben trots att du är under 18?", video: "hur-04569-fras-4.mp4" },
  { word: "farfar", phrase: "Min farfar var seg. Han levde ända tills han blev 105 år gammal.", video: "farfar-04752-fras-1.mp4" },
  { word: "vänta", phrase: "Stopp ett tag, jag är inte färdig än.", video: "vanta-12052-fras-1.mp4" },
  { word: "vänta", phrase: "Ta det lugnt nu, jag kommer sen.", video: "vanta-12052-fras-2.mp4" },
  { word: "svart", phrase: "Jag hälsade på hos en kompis och jag reagerade på att hen hade en svart vägg.", video: "svart-05037-fras-1.mp4" },
  { word: "svart", phrase: "En av mina hundar har svartvit päls.", video: "svart-05037-fras-2.mp4" },
  { word: "vem", phrase: "Vem har sagt att jag ljuger?", video: "vem-05115-fras-1.mp4" },
  { word: "vem", phrase: "Den här katten, vems är det?", video: "vem-05115-fras-2.mp4" },
  { word: "dator", phrase: "Min dator börjar bli gammal, jag behöver köpa en ny dator.", video: "dator-05190-fras-1.mp4" },
  { word: "dator", phrase: "Vilken typ av dator har du? Bärbar eller stationär?", video: "dator-05190-fras-2.mp4" },
  { word: "frisk", phrase: "Jag har varit sjuk i två veckor men nu är jag frisk.", video: "frisk-05274-fras-1.mp4" },
  { word: "frisk", phrase: "Du ser inte riktigt frisk ut, är du sjuk?", video: "frisk-05274-fras-2.mp4" },
  { word: "förstå", phrase: "Matteuppgiften var verkligen svår, jag kunde inte lösa den. Min mattelärare förklarade för mig flera gånger hur jag skulle göra, till slut förstod jag.", video: "forsta-07617-fras-1.mp4" },
  { word: "förstå", phrase: "Hur går det med uppgiften? Har du förstått hur du ska göra?", video: "forsta-07617-fras-2.mp4" },
  { word: "bror", phrase: "Förut när jag var liten så ville jag ha en bror men jag fick två systrar.", video: "bror-08032-fras-1.mp4" },
  { word: "bror", phrase: "Min äldsta bror är hörande.", video: "bror-08032-fras-2.mp4" },
  { word: "bror", phrase: "Varför kommer inte min bror hem ikväll?", video: "bror-08032-fras-3.mp4" },
  { word: "bror", phrase: "Kommer inte min bror hem ikväll?", video: "bror-08032-fras-4.mp4" },
  { word: "hungrig", phrase: "Jag måste äta något, jag är hungrig.", video: "hungrig-08446-fras-1.mp4" },
  { word: "hungrig", phrase: "Är du inte hungrig?", video: "hungrig-08446-fras-2.mp4" },
  { word: "lång", phrase: "Filmen var bra men den var lite väl lång.", video: "lang-13464-fras-1.mp4" },
  { word: "lång", phrase: "Jag tycker inte om att lyssna på långa föreläsningar för jag somnar alltid.", video: "lang-13464-fras-2.mp4" },
  { word: "lång", phrase: "Det är en jättelång historia. Jag orkar inte berätta hela den.", video: "lang-13464-fras-3.mp4" },
  { word: "lång", phrase: "Jag tycker att filmen är jättelång. Det hade varit bättre om den blev nedkortad.", video: "lang-13464-fras-4.mp4" },
  { word: "kan", phrase: "Jag kan köra båt.", video: "kan-00022-fras-1.mp4" },
  { word: "kan", phrase: "I morgon kan jag hjälpa dig.", video: "kan-00022-fras-2.mp4" },
  { word: "kan", phrase: "Jag kan fixa middagen i kväll.", video: "kan-00022-fras-3.mp4" },
  { word: "kan", phrase: "Sven kan inte simma.", video: "kan-00022-fras-4.mp4" },
  { word: "lyssna", phrase: "Det är verkligen viktigt att vi lyssnar på våra mammor.", video: "lyssna-00044-fras-1.mp4" },
  { word: "lyssna", phrase: "Barnen älskar att lyssna på musik.", video: "lyssna-00044-fras-2.mp4" },
  { word: "lyssna", phrase: "Snälla, ni måste lyssna på läraren.", video: "lyssna-00044-fras-3.mp4" },
  { word: "lyssna", phrase: "Lyssna!", video: "lyssna-00044-fras-4.mp4" },
  { word: "hem", phrase: "När jag bodde i USA flyttade jag runt bland mina kompisar i många år. Nu är det skönt att ha ett eget hem här hemma.", video: "hem-00498-fras-1.mp4" },
  { word: "hem", phrase: "Kom hem till mig för jag har öppet hus mellan fem och sju.", video: "hem-00498-fras-2.mp4" },
  { word: "skola", phrase: "Jag känner inte alls för att flytta till en ny skola.", video: "skola-00617-fras-1.mp4" },
  { word: "skola", phrase: "Läraren sa till mig att jag måste meddela dem att det inte är någon skola på måndag.", video: "skola-00617-fras-2.mp4" },
  { word: "skola", phrase: "Vad är anledningen till att du inte kom till skolan i onsdags?", video: "skola-00617-fras-3.mp4" },
  { word: "sjuk", phrase: "Om du känner dig sjuk så är det bäst att du åker till sjukhuset.", video: "sjuk-19384-fras-1.mp4" },
  { word: "sjuk", phrase: "Min morfar hade inte en sjukdag fram tills hans pension.", video: "sjuk-19384-fras-2.mp4" },
  { word: "stor", phrase: "Jag såg en jättestor hund.", video: "stor-20217-fras-1.mp4" },
];
