(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "adjektiv1",
  name: "Adjektiv 1",
  words: [
    { word: "rolig", video: "rolig-02354-tecken.mp4", gloss: "ROLIG" },
    { word: "snäll", video: "snall-01090-tecken.mp4", gloss: "SNÄLL" },
    { word: "tyst", video: "tyst-01867-tecken.mp4", gloss: "TYST" },
    { word: "hungrig", video: "hungrig-04868-tecken.mp4", gloss: "HUNGRIG" },
    { word: "nervös", video: "nervos-01072-tecken.mp4", gloss: "NERVÖS(5)" },
    { word: "enkel", video: "enkel-02927-tecken.mp4", gloss: "ENKEL" },
    { word: "tydlig", video: "tydlig-02933-tecken.mp4", gloss: "TYDLIG(L)" },
    { word: "färdig", video: "fardig-00310-tecken.mp4", gloss: "FÄRDIG" },
    { word: "nära", video: "nara-03145-tecken.mp4" },
    { word: "ont", video: "ont-02569-tecken.mp4", gloss: "ONT" },
    { word: "mätt", video: "matt-02043-tecken.mp4", gloss: "MÄTT(G)" },
    { word: "rik", video: "rik-03375-tecken.mp4", gloss: "RIK" },
    { word: "tråkig", video: "trakig-02465-tecken.mp4" },
    { word: "kylig", video: "kylig-01506-tecken.mp4", gloss: "KYLIG" },
    { word: "sista", video: "sista-10568-tecken.mp4", gloss: "SISTA" },
    { word: "låst", video: "lasa-02059-tecken.mp4", gloss: "LÅSA(ea)" },
    { word: "väldigt", video: "valdig-01912-tecken.mp4" },
    { word: "lite", video: "lite-01701-tecken.mp4", gloss: "LITE(7b)" },
    { word: "mycket", video: "mycket-02801-tecken.mp4", gloss: "MYCKET" },
    { word: "riktigt", video: "riktig-00368-tecken.mp4", gloss: "RIKTIG" },
    { word: "torr", video: "torr-05406-tecken.mp4", gloss: "TORR@b" },
    { word: "het", video: "het-04790-tecken.mp4", gloss: "HET" },
    { word: "ljus", video: "ljus-00512-tecken.mp4", gloss: "LJUS" },
    { word: "randig", video: "randig-00890-tecken.mp4" },
    { word: "bred", video: "bred-01982-tecken.mp4", gloss: "BRED(J)" },
    { word: "tjock", video: "tjock-02257-tecken.mp4", gloss: "TJOCK" },
    { word: "rak", video: "rak-12250-tecken.mp4" },
    { word: "äkta", video: "akta-03961-tecken.mp4", gloss: "ÄKTA" },
    { word: "rätt", video: "ratt-00387-tecken.mp4", gloss: "RÄTT" },
    { word: "lätt", video: "latt-00624-tecken.mp4", gloss: "LÄTT" },
    { word: "ilsken", video: "ilsken-01672-tecken.mp4" },
    { word: "lugn", video: "lugn-05086-tecken.mp4", gloss: "LUGN" },
    { word: "pigg", video: "pigg-01212-tecken.mp4" },
    { word: "död", video: "dod-00202-tecken.mp4", gloss: "DÖD(J)" },
    { word: "mjuk", video: "mjuk-00777-tecken.mp4", gloss: "MJUK" },
    { word: "ledig", video: "ledig-03088-tecken.mp4", gloss: "LEDIG(L)" },
    { word: "billig", video: "billig-03377-tecken.mp4", gloss: "BILLIG" },
    { word: "hög", video: "hog-00247-tecken.mp4", gloss: "HÖG" },
    { word: "blond", video: "blond-10905-tecken.mp4", gloss: "BLOND" },
    { word: "slät", video: "slat-17963-tecken.mp4" },
    { word: "full", video: "full-00341-tecken.mp4", gloss: "FULL(J)" },
    { word: "säker", video: "saker-00388-tecken.mp4", gloss: "SÄKER" },
    { word: "vild", video: "vild-01993-tecken.mp4" },
    { word: "grund", video: "grund-00473-tecken.mp4", gloss: "GRUND" },
    { word: "svår", video: "svar-02293-tecken.mp4", gloss: "SVÅR" },
    { word: "klar", video: "klar-01058-tecken.mp4", gloss: "KLAR" },
    { word: "fri", video: "fri-01034-tecken.mp4", gloss: "FRI" },
    { word: "smal", video: "smal-00538-tecken.mp4", gloss: "SMAL(J)" },
    { word: "ful", video: "ful-03238-tecken.mp4", gloss: "FUL" },
    { word: "lat", video: "lat-00981-tecken.mp4", gloss: "LAT" }
  ]
});
