(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "adjektiv",
  name: "Adjektiv",
  words: [
    { word: "bra", video: "bra-12077-tecken.mp4" },
    { word: "stor", video: "stor-00607-tecken.mp4" },
    { word: "ny", video: "ny-09120-tecken.mp4" },
    { word: "lång", video: "lang-01115-tecken.mp4" },
    { word: "hög", video: "hog-00247-tecken.mp4" },
    { word: "lätt", video: "latt-00624-tecken.mp4" },
    { word: "lätt", video: "latt-00624-tecken.mp4" },
    { word: "stark", video: "stark-02278-tecken.mp4" },
    { word: "grund", video: "grund-00473-tecken.mp4" },
    { word: "hel", video: "hel-00441-tecken.mp4" },
    { word: "rätt", video: "ratt-00387-tecken.mp4" },
    { word: "ung", video: "ung-01099-tecken.mp4" },
    { word: "full", video: "full-00341-tecken.mp4" },
    { word: "säker", video: "saker-00388-tecken.mp4" },
    { word: "död", video: "dod-00202-tecken.mp4" },
    { word: "ljus", video: "ljus-00512-tecken.mp4" },
    { word: "ren", video: "ren-00442-tecken.mp4" },
    { word: "vacker", video: "vacker-00755-tecken.mp4" },
    { word: "snabb", video: "snabb-00847-tecken.mp4" },
    { word: "enkel", video: "enkel-02927-tecken.mp4" },
    { word: "bred", video: "bred-01982-tecken.mp4" },
    { word: "äkta", video: "akta-03961-tecken.mp4" },
    { word: "tyst", video: "tyst-01867-tecken.mp4" },
    { word: "frisk", video: "frisk-00581-tecken.mp4" },
    { word: "lugn", video: "lugn-05086-tecken.mp4" },
    { word: "ledsen", video: "ledsen-00185-tecken.mp4" },
    { word: "kall", video: "kall-01505-tecken.mp4" },
    { word: "het", video: "het-04790-tecken.mp4" },
    { word: "rik", video: "rik-03375-tecken.mp4" },
    { word: "rolig", video: "rolig-02354-tecken.mp4" },
    { word: "mjuk", video: "mjuk-00777-tecken.mp4" },
    { word: "tjock", video: "tjock-02257-tecken.mp4" },
    { word: "ledig", video: "ledig-03088-tecken.mp4" },
    { word: "billig", video: "billig-03377-tecken.mp4" },
    { word: "torr", video: "torr-05406-tecken.mp4" },
    { word: "rak", video: "rak-12250-tecken.mp4" },
    { word: "rak", video: "rak-12250-tecken.mp4" },
    { word: "pigg", video: "pigg-01212-tecken.mp4" },
    { word: "fet", video: "fet-04764-tecken.mp4" },
    { word: "vild", video: "vild-01993-tecken.mp4" },
    { word: "formell", video: "formell-10058-tecken.mp4" },
    { word: "rund", video: "rund-18403-tecken.mp4" },
    { word: "mätt", video: "matt-02043-tecken.mp4" },
    { word: "blond", video: "blond-10905-tecken.mp4" },
    { word: "slät", video: "slat-17963-tecken.mp4" },
    { word: "ilsken", video: "ilsken-01672-tecken.mp4" },
    { word: "randig", video: "randig-00890-tecken.mp4" }
  ],
  phrases: [
    { word: "stor", phrase: "Har du besökt vår kompis nya hus? Huset är verkligen [stort].", video: "stor-00607-fras-1.mp4" },
    { word: "stor", phrase: "Mina nya säng är [bredare] än min gamla, det är så skönt!", video: "stor-00607-fras-2.mp4" },
    { word: "lång", phrase: "Alla i min familj är [långa]. Det är bara jag som är [kort].", video: "lang-01115-fras-1.mp4" },
    { word: "lång", phrase: "Alla basketspelare är [långa].", video: "lang-01115-fras-2.mp4" },
    { word: "lång", phrase: "Hur [lång] är en flicka som är 15 år? 15 cm, 150 cm eller 15 meter?", video: "lang-01115-fras-3.mp4" },
    { word: "hög", phrase: "Det byggs väldigt mycket i stan, flera [höga] hus.", video: "hog-00247-fras-1.mp4" },
    { word: "stark", phrase: "Myran är världens [starkaste] djur.", video: "stark-02278-fras-1.mp4" },
    { word: "grund", phrase: "Om man lär sig från [grunden] ordentligt, så blir det framöver lättare att utvecklas", video: "grund-00473-fras-1.mp4" },
    { word: "grund", phrase: "Vad är [anledningen] till denna konflikt?", video: "grund-00473-fras-2.mp4" },
    { word: "grund", phrase: "För en månad sedan gick Viking-båten på [grund].", video: "grund-00473-fras-3.mp4" },
    { word: "hel", phrase: "I morse cyklade jag omkull men jag klarade mig [helskinnad], [helt] utan skador.", video: "hel-00441-fras-1.mp4" },
    { word: "hel", phrase: "Jag råkade backa på en annan bil men som tur var blev det inga skador på min bil.\n\n(No occurrences of \"hel\" or its inflected/derived forms found in this phrase.)", video: "hel-00441-fras-2.mp4" },
    { word: "hel", phrase: "Jag råkade ut för ett missöde när jag skulle parkera och körde på en annan bil. Som tur var så hittade jag inga skador.", video: "hel-00441-fras-3.mp4" },
    { word: "hel", phrase: "Förra veckan var jag med om en krock, men jag klarade mig utan en skråma.\n\n(There are no occurrences of \"hel\" or its inflected/derived forms in this phrase.)", video: "hel-00441-fras-4.mp4" },
    { word: "rätt", phrase: "Jag tycker inte att det är [rätt].", video: "ratt-00387-fras-1.mp4" },
    { word: "full", phrase: "Tyvärr går det inte att komma in där. Det är [fullt].", video: "full-00341-fras-1.mp4" },
    { word: "full", phrase: "Du ska [fylla] hinken ända upp till kanten med vatten.", video: "full-00341-fras-2.mp4" },
    { word: "full", phrase: "Jag tänkte ta tåget, men när jag skulle boka biljett var det [fullbokat]. Det har aldrig hänt förut.", video: "full-00341-fras-3.mp4" },
    { word: "full", phrase: "När jag kom till föreläsningen var det [fullsatt] så jag kunde inte komma in.", video: "full-00341-fras-4.mp4" },
    { word: "säker", phrase: "Är du [säker]? Tänk om du har fel.", video: "saker-00388-fras-1.mp4" },
    { word: "säker", phrase: "Flyget imorgon blir [säkert] inställt. Om det är så blir jag inte förvånad.", video: "saker-00388-fras-2.mp4" },
    { word: "säker", phrase: "Jag är inte [säker] på min framtid.", video: "saker-00388-fras-3.mp4" },
    { word: "säker", phrase: "Förut var jag tvärsäker men det är jag inte längre.\"\n\nWait, let me reconsider. \"tvärsäker\" contains the base word \"säker\". Let me check all occurrences:\n\n- \"tvärsäker\" - contains \"säker\"\n\nHere is the corrected response:\n\n\"Förut var jag [tvärsäker] men det är jag inte längre.", video: "saker-00388-fras-4.mp4" },
    { word: "död", phrase: "Farfar låg i sängen när han lugnt och stilla somnade in.", video: "dod-00202-fras-1.mp4" },
    { word: "död", phrase: "När kriget pågick såg jag många [döda] människor.", video: "dod-00202-fras-2.mp4" },
    { word: "ljus", phrase: "Jag tycker om sommaren för då är det alltid så [ljust].", video: "ljus-00512-fras-1.mp4" },
    { word: "ljus", phrase: "Min favoritfärg är [ljusblå].", video: "ljus-00512-fras-2.mp4" },
    { word: "ren", phrase: "[Huset är rent]. Jag har dammtorkat och skurat och allt är klart.", video: "ren-00442-fras-1.mp4" },
    { word: "ren", phrase: "Igår hade jag tvättstugetid, så idag är det skönt att ha [rena] kalsonger.", video: "ren-00442-fras-2.mp4" },
    { word: "snabb", phrase: "Jag körde [jättefort].", video: "snabb-00847-fras-1.mp4" },
    { word: "snabb", phrase: "Är du redan klar? Det gick [fort]!", video: "snabb-00847-fras-2.mp4" },
    { word: "bred", phrase: "Min TV är 57 tum [bred].", video: "bred-01982-fras-1.mp4" },
    { word: "bred", phrase: "TV:n som sitter på väggen i vardagsrummet är 4 meter [bred].", video: "bred-01982-fras-2.mp4" },
    { word: "tyst", phrase: "[Var tyst]!", video: "tyst-01867-fras-1.mp4" },
    { word: "frisk", phrase: "Jag har varit sjuk i två veckor men nu är jag [frisk].", video: "frisk-00581-fras-1.mp4" },
    { word: "frisk", phrase: "Du ser inte riktigt [frisk] ut, är du sjuk?", video: "frisk-00581-fras-2.mp4" },
    { word: "lugn", phrase: "Nu kan jag känna mig [lugn] för nu har hen kommit hem.", video: "lugn-05086-fras-1.mp4" },
    { word: "lugn", phrase: "Jag har en orm hemma men den är inte giftig, så det är ingen fara.", video: "lugn-05086-fras-2.mp4" },
    { word: "ledsen", phrase: "Alla kan vara [ledsna] ibland.", video: "ledsen-00185-fras-1.mp4" },
    { word: "ledsen", phrase: "Min hund blir lätt [ledsen] om jag inte busar med den.", video: "ledsen-00185-fras-2.mp4" },
    { word: "kall", phrase: "Det är ofta väldigt [kallt] i februari och då måste man klä sig varmt.", video: "kall-01505-fras-1.mp4" },
    { word: "kall", phrase: "Om det är [kallt] ute och du har för lite [kläder] på dig, så kan det leda till att du blir sjuk.", video: "kall-01505-fras-2.mp4" },
    { word: "rik", phrase: "Jag är inte [rik].", video: "rik-03375-fras-1.mp4" },
    { word: "rik", phrase: "Jag är inte [rik].", video: "rik-03375-fras-2.mp4" },
    { word: "rolig", phrase: "Det är [roligt] att spela badminton.", video: "rolig-02354-fras-1.mp4" },
    { word: "rolig", phrase: "Det är [roligt] att resa ibland.", video: "rolig-02354-fras-2.mp4" },
    { word: "rolig", phrase: "I tisdags var vi ett stort gäng och kollade på bio, det var verkligen [roligt].", video: "rolig-02354-fras-3.mp4" },
    { word: "tjock", phrase: "Att vara för [tjock] är inte bra för hälsan. Då riskerar man att få problem av olika slag.", video: "tjock-02257-fras-1.mp4" },
    { word: "tjock", phrase: "Jag har en skjorta men jag känner mig så [tjock] så jag vill inte använda den.", video: "tjock-02257-fras-2.mp4" },
    { word: "billig", phrase: "Min pappa köpte en [billig] [bil].", video: "billig-03377-fras-1.mp4" },
    { word: "billig", phrase: "Brukar du köpa dyra eller [billiga] kläder?", video: "billig-03377-fras-2.mp4" },
    { word: "billig", phrase: "Jag hittade snygga skor som dessutom var [billiga] så jag köpte dom på en gång.", video: "billig-03377-fras-3.mp4" },
    { word: "rak", phrase: "När man rider måste man hålla ryggen [rak].", video: "rak-12250-fras-1.mp4" },
    { word: "rak", phrase: "När man rider måste man hålla ryggen [rak].", video: "rak-12250-fras-1.mp4" },
    { word: "pigg", phrase: "Min son är alltid [pigg] på morgon.", video: "pigg-01212-fras-1.mp4" },
    { word: "pigg", phrase: "Om jag dricker fem koppar kaffe så blir jag väldigt [pigg].", video: "pigg-01212-fras-2.mp4" },
    { word: "pigg", phrase: "Min pappa var alltid [pigg] förut men nu när han har blivit äldre har han blivit mer trött.", video: "pigg-01212-fras-3.mp4" },
    { word: "mätt", phrase: "Jag orkar inte äta mer, jag är [mätt].", video: "matt-02043-fras-1.mp4" },
    { word: "mätt", phrase: "Du är [mätt], inte hungrig?", video: "matt-02043-fras-2.mp4" },
    { word: "blond", phrase: "En del personer brukar bli [blonda] under sommaren på grund av solen.", video: "blond-10905-fras-1.mp4" },
    { word: "blond", phrase: "Om du vill ha [blont] hår så kan du [blondera] det.", video: "blond-10905-fras-2.mp4" },
    { word: "slät", phrase: "När jag är ute och springer, avskyr jag när det är kuperat. Jag vill att det ska vara [slät] mark.", video: "slat-17963-fras-1.mp4" },
    { word: "slät", phrase: "Tapeterna förr var vävtapet. Nu är det mer vanligt med [släta] tapeter på väggarna.", video: "slat-17963-fras-2.mp4" },
    { word: "randig", phrase: "Passar jag i [randig] tröja?", video: "randig-00890-fras-1.mp4" },
    { word: "randig", phrase: "Jag vill ha en [randig] väska.", video: "randig-00890-fras-2.mp4" }
  ]
});
