// Auto-generated — do not edit. Run: python3 gen_wordlist.py --rebuild

// --- adjektiv.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "adjektiv",
  name: "Adjektiv",
  words: [
    { word: "bra", video: "bra-12077-tecken.mp4" },
    { word: "stor", video: "stor-00607-tecken.mp4" },
    { word: "ny", video: "ny-09120-tecken.mp4" },
    { word: "lång", video: "lang-01115-tecken.mp4" },
    { word: "hög", video: "hog-00247-tecken.mp4" },
    { word: "lätt", video: "latt-00624-tecken.mp4" },
    { word: "lätt", video: "latt-00624-tecken.mp4" },
    { word: "stark", video: "stark-02278-tecken.mp4" },
    { word: "grund", video: "grund-00473-tecken.mp4" },
    { word: "hel", video: "hel-00441-tecken.mp4" },
    { word: "rätt", video: "ratt-00387-tecken.mp4" },
    { word: "ung", video: "ung-01099-tecken.mp4" },
    { word: "full", video: "full-00341-tecken.mp4" },
    { word: "säker", video: "saker-00388-tecken.mp4" },
    { word: "död", video: "dod-00202-tecken.mp4" },
    { word: "ljus", video: "ljus-00512-tecken.mp4" },
    { word: "ren", video: "ren-00442-tecken.mp4" },
    { word: "vacker", video: "vacker-00755-tecken.mp4" },
    { word: "snabb", video: "snabb-00847-tecken.mp4" },
    { word: "enkel", video: "enkel-02927-tecken.mp4" },
    { word: "bred", video: "bred-01982-tecken.mp4" },
    { word: "äkta", video: "akta-03961-tecken.mp4" },
    { word: "tyst", video: "tyst-01867-tecken.mp4" },
    { word: "frisk", video: "frisk-00581-tecken.mp4" },
    { word: "lugn", video: "lugn-05086-tecken.mp4" },
    { word: "ledsen", video: "ledsen-00185-tecken.mp4" },
    { word: "kall", video: "kall-01505-tecken.mp4" },
    { word: "het", video: "het-04790-tecken.mp4" },
    { word: "rik", video: "rik-03375-tecken.mp4" },
    { word: "rolig", video: "rolig-02354-tecken.mp4" },
    { word: "mjuk", video: "mjuk-00777-tecken.mp4" },
    { word: "tjock", video: "tjock-02257-tecken.mp4" },
    { word: "ledig", video: "ledig-03088-tecken.mp4" },
    { word: "billig", video: "billig-03377-tecken.mp4" },
    { word: "torr", video: "torr-05406-tecken.mp4" },
    { word: "rak", video: "rak-12250-tecken.mp4" },
    { word: "rak", video: "rak-12250-tecken.mp4" },
    { word: "pigg", video: "pigg-01212-tecken.mp4" },
    { word: "fet", video: "fet-04764-tecken.mp4" },
    { word: "vild", video: "vild-01993-tecken.mp4" },
    { word: "formell", video: "formell-10058-tecken.mp4" },
    { word: "rund", video: "rund-18403-tecken.mp4" },
    { word: "mätt", video: "matt-02043-tecken.mp4" },
    { word: "blond", video: "blond-10905-tecken.mp4" },
    { word: "slät", video: "slat-17963-tecken.mp4" },
    { word: "ilsken", video: "ilsken-01672-tecken.mp4" },
    { word: "randig", video: "randig-00890-tecken.mp4" }
  ],
  phrases: [
    { word: "stor", phrase: "Har du besökt vår kompis nya hus? Huset är verkligen [stort].", video: "stor-00607-fras-1.mp4" },
    { word: "stor", phrase: "Mina nya säng är [bredare] än min gamla, det är så skönt!", video: "stor-00607-fras-2.mp4" },
    { word: "lång", phrase: "Alla i min familj är [långa]. Det är bara jag som är [kort].", video: "lang-01115-fras-1.mp4" },
    { word: "lång", phrase: "Alla basketspelare är [långa].", video: "lang-01115-fras-2.mp4" },
    { word: "lång", phrase: "Hur [lång] är en flicka som är 15 år? 15 cm, 150 cm eller 15 meter?", video: "lang-01115-fras-3.mp4" },
    { word: "hög", phrase: "Det byggs väldigt mycket i stan, flera [höga] hus.", video: "hog-00247-fras-1.mp4" },
    { word: "stark", phrase: "Myran är världens [starkaste] djur.", video: "stark-02278-fras-1.mp4" },
    { word: "grund", phrase: "Om man lär sig från [grunden] ordentligt, så blir det framöver lättare att utvecklas", video: "grund-00473-fras-1.mp4" },
    { word: "grund", phrase: "Vad är [anledningen] till denna konflikt?", video: "grund-00473-fras-2.mp4" },
    { word: "grund", phrase: "För en månad sedan gick Viking-båten på [grund].", video: "grund-00473-fras-3.mp4" },
    { word: "hel", phrase: "I morse cyklade jag omkull men jag klarade mig [helskinnad], [helt] utan skador.", video: "hel-00441-fras-1.mp4" },
    { word: "hel", phrase: "Jag råkade backa på en annan bil men som tur var blev det inga skador på min bil.\n\n(No occurrences of \"hel\" or its inflected/derived forms found in this phrase.)", video: "hel-00441-fras-2.mp4" },
    { word: "hel", phrase: "Jag råkade ut för ett missöde när jag skulle parkera och körde på en annan bil. Som tur var så hittade jag inga skador.", video: "hel-00441-fras-3.mp4" },
    { word: "hel", phrase: "Förra veckan var jag med om en krock, men jag klarade mig utan en skråma.\n\n(There are no occurrences of \"hel\" or its inflected/derived forms in this phrase.)", video: "hel-00441-fras-4.mp4" },
    { word: "rätt", phrase: "Jag tycker inte att det är [rätt].", video: "ratt-00387-fras-1.mp4" },
    { word: "full", phrase: "Tyvärr går det inte att komma in där. Det är [fullt].", video: "full-00341-fras-1.mp4" },
    { word: "full", phrase: "Du ska [fylla] hinken ända upp till kanten med vatten.", video: "full-00341-fras-2.mp4" },
    { word: "full", phrase: "Jag tänkte ta tåget, men när jag skulle boka biljett var det [fullbokat]. Det har aldrig hänt förut.", video: "full-00341-fras-3.mp4" },
    { word: "full", phrase: "När jag kom till föreläsningen var det [fullsatt] så jag kunde inte komma in.", video: "full-00341-fras-4.mp4" },
    { word: "säker", phrase: "Är du [säker]? Tänk om du har fel.", video: "saker-00388-fras-1.mp4" },
    { word: "säker", phrase: "Flyget imorgon blir [säkert] inställt. Om det är så blir jag inte förvånad.", video: "saker-00388-fras-2.mp4" },
    { word: "säker", phrase: "Jag är inte [säker] på min framtid.", video: "saker-00388-fras-3.mp4" },
    { word: "säker", phrase: "Förut var jag tvärsäker men det är jag inte längre.\"\n\nWait, let me reconsider. \"tvärsäker\" contains the base word \"säker\". Let me check all occurrences:\n\n- \"tvärsäker\" - contains \"säker\"\n\nHere is the corrected response:\n\n\"Förut var jag [tvärsäker] men det är jag inte längre.", video: "saker-00388-fras-4.mp4" },
    { word: "död", phrase: "Farfar låg i sängen när han lugnt och stilla somnade in.", video: "dod-00202-fras-1.mp4" },
    { word: "död", phrase: "När kriget pågick såg jag många [döda] människor.", video: "dod-00202-fras-2.mp4" },
    { word: "ljus", phrase: "Jag tycker om sommaren för då är det alltid så [ljust].", video: "ljus-00512-fras-1.mp4" },
    { word: "ljus", phrase: "Min favoritfärg är [ljusblå].", video: "ljus-00512-fras-2.mp4" },
    { word: "ren", phrase: "[Huset är rent]. Jag har dammtorkat och skurat och allt är klart.", video: "ren-00442-fras-1.mp4" },
    { word: "ren", phrase: "Igår hade jag tvättstugetid, så idag är det skönt att ha [rena] kalsonger.", video: "ren-00442-fras-2.mp4" },
    { word: "snabb", phrase: "Jag körde [jättefort].", video: "snabb-00847-fras-1.mp4" },
    { word: "snabb", phrase: "Är du redan klar? Det gick [fort]!", video: "snabb-00847-fras-2.mp4" },
    { word: "bred", phrase: "Min TV är 57 tum [bred].", video: "bred-01982-fras-1.mp4" },
    { word: "bred", phrase: "TV:n som sitter på väggen i vardagsrummet är 4 meter [bred].", video: "bred-01982-fras-2.mp4" },
    { word: "tyst", phrase: "[Var tyst]!", video: "tyst-01867-fras-1.mp4" },
    { word: "frisk", phrase: "Jag har varit sjuk i två veckor men nu är jag [frisk].", video: "frisk-00581-fras-1.mp4" },
    { word: "frisk", phrase: "Du ser inte riktigt [frisk] ut, är du sjuk?", video: "frisk-00581-fras-2.mp4" },
    { word: "lugn", phrase: "Nu kan jag känna mig [lugn] för nu har hen kommit hem.", video: "lugn-05086-fras-1.mp4" },
    { word: "lugn", phrase: "Jag har en orm hemma men den är inte giftig, så det är ingen fara.", video: "lugn-05086-fras-2.mp4" },
    { word: "ledsen", phrase: "Alla kan vara [ledsna] ibland.", video: "ledsen-00185-fras-1.mp4" },
    { word: "ledsen", phrase: "Min hund blir lätt [ledsen] om jag inte busar med den.", video: "ledsen-00185-fras-2.mp4" },
    { word: "kall", phrase: "Det är ofta väldigt [kallt] i februari och då måste man klä sig varmt.", video: "kall-01505-fras-1.mp4" },
    { word: "kall", phrase: "Om det är [kallt] ute och du har för lite [kläder] på dig, så kan det leda till att du blir sjuk.", video: "kall-01505-fras-2.mp4" },
    { word: "rik", phrase: "Jag är inte [rik].", video: "rik-03375-fras-1.mp4" },
    { word: "rik", phrase: "Jag är inte [rik].", video: "rik-03375-fras-2.mp4" },
    { word: "rolig", phrase: "Det är [roligt] att spela badminton.", video: "rolig-02354-fras-1.mp4" },
    { word: "rolig", phrase: "Det är [roligt] att resa ibland.", video: "rolig-02354-fras-2.mp4" },
    { word: "rolig", phrase: "I tisdags var vi ett stort gäng och kollade på bio, det var verkligen [roligt].", video: "rolig-02354-fras-3.mp4" },
    { word: "tjock", phrase: "Att vara för [tjock] är inte bra för hälsan. Då riskerar man att få problem av olika slag.", video: "tjock-02257-fras-1.mp4" },
    { word: "tjock", phrase: "Jag har en skjorta men jag känner mig så [tjock] så jag vill inte använda den.", video: "tjock-02257-fras-2.mp4" },
    { word: "billig", phrase: "Min pappa köpte en [billig] [bil].", video: "billig-03377-fras-1.mp4" },
    { word: "billig", phrase: "Brukar du köpa dyra eller [billiga] kläder?", video: "billig-03377-fras-2.mp4" },
    { word: "billig", phrase: "Jag hittade snygga skor som dessutom var [billiga] så jag köpte dom på en gång.", video: "billig-03377-fras-3.mp4" },
    { word: "rak", phrase: "När man rider måste man hålla ryggen [rak].", video: "rak-12250-fras-1.mp4" },
    { word: "rak", phrase: "När man rider måste man hålla ryggen [rak].", video: "rak-12250-fras-1.mp4" },
    { word: "pigg", phrase: "Min son är alltid [pigg] på morgon.", video: "pigg-01212-fras-1.mp4" },
    { word: "pigg", phrase: "Om jag dricker fem koppar kaffe så blir jag väldigt [pigg].", video: "pigg-01212-fras-2.mp4" },
    { word: "pigg", phrase: "Min pappa var alltid [pigg] förut men nu när han har blivit äldre har han blivit mer trött.", video: "pigg-01212-fras-3.mp4" },
    { word: "mätt", phrase: "Jag orkar inte äta mer, jag är [mätt].", video: "matt-02043-fras-1.mp4" },
    { word: "mätt", phrase: "Du är [mätt], inte hungrig?", video: "matt-02043-fras-2.mp4" },
    { word: "blond", phrase: "En del personer brukar bli [blonda] under sommaren på grund av solen.", video: "blond-10905-fras-1.mp4" },
    { word: "blond", phrase: "Om du vill ha [blont] hår så kan du [blondera] det.", video: "blond-10905-fras-2.mp4" },
    { word: "slät", phrase: "När jag är ute och springer, avskyr jag när det är kuperat. Jag vill att det ska vara [slät] mark.", video: "slat-17963-fras-1.mp4" },
    { word: "slät", phrase: "Tapeterna förr var vävtapet. Nu är det mer vanligt med [släta] tapeter på väggarna.", video: "slat-17963-fras-2.mp4" },
    { word: "randig", phrase: "Passar jag i [randig] tröja?", video: "randig-00890-fras-1.mp4" },
    { word: "randig", phrase: "Jag vill ha en [randig] väska.", video: "randig-00890-fras-2.mp4" }
  ]
});

// --- bokstavering.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "bokstavering",
  name: "Bokstavering",
  words: [
    { word: "i", video: "i-04473-tecken.mp4" },
    { word: "att", video: "att-08812-tecken.mp4" },
    { word: "av", video: "av-08815-tecken.mp4" },
    { word: "han", video: "han-00812-tecken.mp4" },
    { word: "var", video: "var-13524-tecken.mp4" },
    { word: "hon", video: "hon-05389-tecken.mp4" },
    { word: "vara", video: "vara-09261-tecken.mp4" },
    { word: "år", video: "ar-09291-tecken.mp4" },
    { word: "få", video: "fa-07345-tecken.mp4" },
    { word: "än", video: "an-09287-tecken.mp4" },
    { word: "kronor", video: "kronor-09044-tecken.mp4" },
    { word: "alla", video: "alla-08804-tecken.mp4" },
    { word: "varit", video: "varit-18168-tecken.mp4" },
    { word: "då", video: "da-04724-tecken.mp4" },
    { word: "vet", video: "vet-12741-tecken.mp4" },
    { word: "åt", video: "at-20598-tecken.mp4" },
    { word: "tid", video: "tid-12742-tecken.mp4" },
    { word: "väl", video: "val-05515-tecken.mp4" },
    { word: "usa", video: "usa-09249-tecken.mp4" },
    { word: "bör", video: "bor-10535-tecken.mp4" },
    { word: "par", video: "par-14570-tecken.mp4" },
    { word: "per", video: "per-19723-tecken.mp4" },
    { word: "nej", video: "nej-08300-tecken.mp4" },
    { word: "exempel", video: "exempel-09418-tecken.mp4" },
    { word: "sex", video: "sex-06075-tecken.mp4" },
    { word: "cirka", video: "cirka-19495-tecken.mp4" },
    { word: "ens", video: "ens-17649-tecken.mp4" },
    { word: "tv", video: "tv-05428-tecken.mp4" },
    { word: "alls", video: "alls-17582-tecken.mp4" },
    { word: "mina", video: "mina-24957-tecken.mp4" },
    { word: "vore", video: "vore-16038-tecken.mp4" },
    { word: "fall", video: "fall-22739-tecken.mp4" },
    { word: "maj", video: "maj-09098-tecken.mp4" },
    { word: "jobb", video: "jobb-04920-tecken.mp4" },
    { word: "bok", video: "bok-15763-tecken.mp4" },
    { word: "malmö", video: "malmo-06398-tecken.mp4" },
    { word: "annars", video: "annars-04624-tecken.mp4" },
    { word: "hel", video: "hel-17313-tecken.mp4" },
    { word: "mars", video: "mars-09097-tecken.mp4" },
    { word: "juni", video: "juni-08253-tecken.mp4" },
    { word: "tur", video: "tur-04221-tecken.mp4" },
    { word: "september", video: "september-09196-tecken.mp4" },
    { word: "december", video: "december-08853-tecken.mp4" },
    { word: "inne", video: "inne-14280-tecken.mp4" },
    { word: "februari", video: "februari-08892-tecken.mp4" },
    { word: "gott", video: "gott-12746-tecken.mp4" },
    { word: "augusti", video: "augusti-08814-tecken.mp4" },
    { word: "maria", video: "maria-07001-tecken.mp4" },
    { word: "emu", video: "emu-24709-tecken.mp4" },
    { word: "vm", video: "vm-08678-tecken.mp4" },
    { word: "november", video: "november-09121-tecken.mp4" },
    { word: "michael", video: "michael-10967-tecken.mp4" },
    { word: "juli", video: "juli-08252-tecken.mp4" },
    { word: "aik", video: "aik-08316-tecken.mp4" },
    { word: "volvo", video: "volvo-12266-tecken.mp4" },
    { word: "illa", video: "illa-22781-tecken.mp4" },
    { word: "oktober", video: "oktober-09131-tecken.mp4" },
    { word: "håll", video: "hall-13353-tecken.mp4" },
    { word: "tag", video: "tag-17510-tecken.mp4" },
    { word: "ton", video: "ton-11214-tecken.mp4" },
    { word: "miljö", video: "miljo-07639-tecken.mp4" },
    { word: "känd", video: "kand-01855-tecken.mp4" },
    { word: "nato", video: "nato-20413-tecken.mp4" },
    { word: "skatt", video: "skatt-05261-tecken.mp4" },
    { word: "råd", video: "rad-09182-tecken.mp4" },
    { word: "fin", video: "fin-09695-tecken.mp4" },
    { word: "mil", video: "mil-02392-tecken.mp4" },
    { word: "idé", video: "ide-17750-tecken.mp4" },
    { word: "lund", video: "lund-06389-tecken.mp4" },
    { word: "klass", video: "klass-04942-tecken.mp4" },
    { word: "saab", video: "saab-10003-tecken.mp4" },
    { word: "vin", video: "vin-05498-tecken.mp4" },
    { word: "vare", video: "vare-20034-tecken.mp4" },
    { word: "stil", video: "stil-11622-tecken.mp4" },
    { word: "hellre", video: "hellre-07645-tecken.mp4" },
    { word: "solna", video: "solna-06492-tecken.mp4" },
    { word: "kilometer", video: "kilometer-07232-tecken.mp4" },
    { word: "folkpartiet", video: "folkpartiet-04779-tecken.mp4" },
    { word: "fn", video: "fn-07423-tecken.mp4" },
    { word: "gustaf", video: "gustaf-07561-tecken.mp4" },
    { word: "bar", video: "bar-08816-tecken.mp4" },
    { word: "pass", video: "pass-02040-tecken.mp4" },
    { word: "olja", video: "olja-09138-tecken.mp4" },
    { word: "division", video: "division-08861-tecken.mp4" },
    { word: "skönt", video: "skont-09195-tecken.mp4" },
    { word: "täby", video: "taby-17506-tecken.mp4" },
    { word: "ben", video: "ben-04657-tecken.mp4" },
    { word: "bud", video: "bud-10761-tecken.mp4" },
    { word: "sollentuna", video: "sollentuna-17176-tecken.mp4" },
    { word: "lidingö", video: "lidingo-06378-tecken.mp4" },
    { word: "telia", video: "telia-19390-tecken.mp4" },
    { word: "öde", video: "ode-17616-tecken.mp4" },
    { word: "cup", video: "cup-08464-tecken.mp4" },
    { word: "rom", video: "rom-13060-tecken.mp4" },
    { word: "va", video: "va-16650-tecken.mp4" },
    { word: "miljöpartiet", video: "miljopartiet-07279-tecken.mp4" },
    { word: "city", video: "city-09458-tecken.mp4" },
    { word: "kurs", video: "kurs-07663-tecken.mp4" },
    { word: "humor", video: "humor-12415-tecken.mp4" },
    { word: "salt", video: "salt-09210-tecken.mp4" },
    { word: "nyss", video: "nyss-12735-tecken.mp4" },
    { word: "drev", video: "drev-15890-tecken.mp4" },
    { word: "bas", video: "bas-17637-tecken.mp4" },
    { word: "fötter", video: "fotter-07935-tecken.mp4" },
    { word: "doktor", video: "doktor-19496-tecken.mp4" },
    { word: "ränta", video: "ranta-01735-tecken.mp4" },
    { word: "succé", video: "succe-05341-tecken.mp4" },
    { word: "kvadratmeter", video: "kvadratmeter-18650-tecken.mp4" },
    { word: "led", video: "led-08499-tecken.mp4" },
    { word: "helhet", video: "helhet-22769-tecken.mp4" },
    { word: "index", video: "index-03146-tecken.mp4" },
    { word: "van", video: "van-09257-tecken.mp4" },
    { word: "fan", video: "fan-09694-tecken.mp4" },
    { word: "klassisk", video: "klassisk-03666-tecken.mp4" },
    { word: "knä", video: "kna-13481-tecken.mp4" },
    { word: "farfar", video: "farfar-04752-tecken.mp4" },
    { word: "offer", video: "offer-07060-tecken.mp4" },
    { word: "sl", video: "sl-17512-tecken.mp4" },
    { word: "ovan", video: "ovan-05151-tecken.mp4" },
    { word: "hål", video: "hal-08755-tecken.mp4" },
    { word: "kök", video: "kok-09691-tecken.mp4" },
    { word: "kön", video: "kon-05858-tecken.mp4" },
    { word: "bråk", video: "brak-04242-tecken.mp4" },
    { word: "yta", video: "yta-09280-tecken.mp4" },
    { word: "tuff", video: "tuff-24476-tecken.mp4" },
    { word: "rasism", video: "rasism-18447-tecken.mp4" },
    { word: "moral", video: "moral-08732-tecken.mp4" },
    { word: "centimeter", video: "centimeter-04696-tecken.mp4" },
    { word: "miljard", video: "miljard-11924-tecken.mp4" },
    { word: "pund", video: "pund-10406-tecken.mp4" },
    { word: "by", video: "by-11251-tecken.mp4" },
    { word: "ära", video: "ara-09166-tecken.mp4" },
    { word: "te", video: "te-05377-tecken.mp4" },
    { word: "öst", video: "ost-16468-tecken.mp4" },
    { word: "moms", video: "moms-05082-tecken.mp4" },
    { word: "taxi", video: "taxi-01728-tecken.mp4" },
    { word: "docent", video: "docent-14326-tecken.mp4" },
    { word: "jaha", video: "jaha-17475-tecken.mp4" },
    { word: "kund", video: "kund-07469-tecken.mp4" },
    { word: "jazz", video: "jazz-15391-tecken.mp4" },
    { word: "farsta", video: "farsta-03840-tecken.mp4" },
    { word: "fot", video: "fot-04778-tecken.mp4" },
    { word: "vana", video: "vana-17348-tecken.mp4" },
    { word: "källa", video: "kalla-01847-tecken.mp4" },
    { word: "sas", video: "sas-17514-tecken.mp4" },
    { word: "fordon", video: "fordon-18645-tecken.mp4" },
    { word: "udda", video: "udda-02001-tecken.mp4" },
    { word: "is", video: "is-04912-tecken.mp4" },
    { word: "omgång", video: "omgang-14557-tecken.mp4" },
    { word: "ris", video: "ris-09164-tecken.mp4" },
    { word: "galleri", video: "galleri-03574-tecken.mp4" },
    { word: "väsby", video: "vasby-17175-tecken.mp4" },
    { word: "skit", video: "skit-05272-tecken.mp4" },
    { word: "moster", video: "moster-05089-tecken.mp4" },
    { word: "ost", video: "ost-09129-tecken.mp4" },
    { word: "hej", video: "hej-12747-tecken.mp4" },
    { word: "järfälla", video: "jarfalla-17807-tecken.mp4" },
    { word: "trend", video: "trend-20450-tecken.mp4" },
    { word: "ort", video: "ort-18877-tecken.mp4" },
    { word: "organ", video: "organ-09494-tecken.mp4" },
    { word: "ro", video: "ro-09402-tecken.mp4" },
    { word: "nhl", video: "nhl-08798-tecken.mp4" },
    { word: "utbud", video: "utbud-19096-tecken.mp4" },
    { word: "torr", video: "torr-05406-tecken.mp4" },
    { word: "ram", video: "ram-05208-tecken.mp4" },
    { word: "talang", video: "talang-09476-tecken.mp4" },
    { word: "hallå", video: "halla-22765-tecken.mp4" },
    { word: "arbetsförmedlingen", video: "arbetsformedlingen-04613-tecken.mp4" },
    { word: "nyår", video: "nyar-16240-tecken.mp4" },
    { word: "lök", video: "lok-09068-tecken.mp4" },
    { word: "västbanken", video: "vastbanken-24684-tecken.mp4" },
    { word: "set", video: "set-14724-tecken.mp4" },
    { word: "ford", video: "ford-17542-tecken.mp4" },
    { word: "debut", video: "debut-13988-tecken.mp4" },
    { word: "spånga", video: "spanga-20637-tecken.mp4" },
    { word: "florida", video: "florida-12623-tecken.mp4" },
    { word: "gas", video: "gas-15525-tecken.mp4" },
    { word: "atlanten", video: "atlanten-02823-tecken.mp4" },
    { word: "toner", video: "toner-05404-tecken.mp4" },
    { word: "fenomen", video: "fenomen-02095-tecken.mp4" },
    { word: "team", video: "team-17614-tecken.mp4" },
    { word: "etik", video: "etik-08874-tecken.mp4" },
    { word: "bitter", video: "bitter-10826-tecken.mp4" },
    { word: "uppror", video: "uppror-10585-tecken.mp4" },
    { word: "odds", video: "odds-19268-tecken.mp4" },
    { word: "myt", video: "myt-03204-tecken.mp4" },
    { word: "ip", video: "ip-14266-tecken.mp4" },
    { word: "rå", video: "ra-01953-tecken.mp4" },
    { word: "kol", video: "kol-09038-tecken.mp4" },
    { word: "data", video: "data-04706-tecken.mp4" },
    { word: "uno", video: "uno-17879-tecken.mp4" },
    { word: "nora", video: "nora-06425-tecken.mp4" },
    { word: "ironi", video: "ironi-08992-tecken.mp4" },
    { word: "försäkringskassan", video: "forsakringskassan-00040-tecken.mp4" },
    { word: "pigg", video: "pigg-24871-tecken.mp4" },
    { word: "gram", video: "gram-10387-tecken.mp4" },
    { word: "otur", video: "otur-09728-tecken.mp4" },
    { word: "monopol", video: "monopol-15262-tecken.mp4" },
    { word: "bet", video: "bet-13908-tecken.mp4" },
    { word: "gais", video: "gais-08534-tecken.mp4" }
  ]
});

// --- djur.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "djur",
  name: "Djur",
  words: [
    { word: "får", video: "far-04143-tecken.mp4" },
    { word: "björn", video: "bjorn-00010-tecken.mp4" },
    { word: "val", video: "val-00564-tecken.mp4" },
    { word: "ren", video: "ren-12326-tecken.mp4" },
    { word: "ko", video: "ko-03058-tecken.mp4" },
    { word: "gris", video: "gris-01149-tecken.mp4" },
    { word: "svin", video: "svin-02953-tecken.mp4" },
    { word: "älg", video: "alg-00931-tecken.mp4" },
    { word: "apa", video: "apa-01539-tecken.mp4" },
    { word: "kamel", video: "kamel-01086-tecken.mp4" },
    { word: "räv", video: "rav-00820-tecken.mp4" },
    { word: "varg", video: "varg-15818-tecken.mp4" },
    { word: "get", video: "get-01382-tecken.mp4" },
    { word: "elefant", video: "elefant-01374-tecken.mp4" },
    { word: "rådjur", video: "radjur-12181-tecken.mp4" },
    { word: "hjort", video: "hjort-12327-tecken.mp4" },
    { word: "kalv", video: "kalv-00547-tecken.mp4" },
    { word: "tjur", video: "tjur-03326-tecken.mp4" },
    { word: "hare", video: "hare-04079-tecken.mp4" },
    { word: "kanin", video: "kanin-04080-tecken.mp4" },
    { word: "rovdjur", video: "rovdjur-02876-tecken.mp4" },
    { word: "åsna", video: "asna-00506-tecken.mp4" },
    { word: "oxe", video: "oxe-03325-tecken.mp4" },
    { word: "flodhäst", video: "flodhast-01624-tecken.mp4" },
    { word: "järv", video: "jarv-14613-tecken.mp4" },
    { word: "gorilla", video: "gorilla-02134-tecken.mp4" },
    { word: "bock", video: "bock-03714-tecken.mp4" },
    { word: "lama", video: "lama-15602-tecken.mp4" },
    { word: "känguru", video: "kanguru-00213-tecken.mp4" },
    { word: "vildsvin", video: "vildsvin-04644-tecken.mp4" },
    { word: "igelkott", video: "igelkott-00113-tecken.mp4" },
    { word: "zebra", video: "zebra-01661-tecken.mp4" },
    { word: "isbjörn", video: "isbjorn-12323-tecken.mp4" },
    { word: "killing", video: "killing-12665-tecken.mp4" },
    { word: "noshörning", video: "noshorning-01373-tecken.mp4" },
    { word: "smådjur", video: "smadjur-05169-tecken.mp4" },
    { word: "panter", video: "panter-17206-tecken.mp4" },
    { word: "giraff", video: "giraff-01386-tecken.mp4" },
    { word: "buffel", video: "buffel-04456-tecken.mp4" },
    { word: "gasell", video: "gasell-03866-tecken.mp4" },
    { word: "koala", video: "koala-02423-tecken.mp4" },
    { word: "valross", video: "valross-18337-tecken.mp4" },
    { word: "tapir", video: "tapir-19610-tecken.mp4" },
    { word: "piggsvin", video: "piggsvin-02478-tecken.mp4" },
    { word: "späckhuggare", video: "spackhuggare-18340-tecken.mp4" },
    { word: "panda", video: "panda-02463-tecken.mp4" },
    { word: "antilop", video: "antilop-02755-tecken.mp4" },
    { word: "fladdermus", video: "fladdermus-12063-tecken.mp4" },
    { word: "gepard", video: "gepard-03701-tecken.mp4" }
  ]
});

// --- familj.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "familj",
  name: "Familj",
  words: [
    { word: "man", video: "man-05036-tecken.mp4" },
    { word: "barn", video: "barn-00257-tecken.mp4" },
    { word: "mamma", video: "mamma-00188-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4" },
    { word: "föräldrar", video: "foraldrar-13821-tecken.mp4" },
    { word: "familj", video: "familj-00773-tecken.mp4" },
    { word: "son", video: "son-01944-tecken.mp4" },
    { word: "fru", video: "fru-04582-tecken.mp4" },
    { word: "dotter", video: "dotter-00111-tecken.mp4" },
    { word: "syster", video: "syster-03513-tecken.mp4" },
    { word: "bror", video: "bror-03462-tecken.mp4" },
    { word: "mormor", video: "mormor-01938-tecken.mp4" },
    { word: "farfar", video: "farfar-01932-tecken.mp4" },
    { word: "farbror", video: "farbror-02752-tecken.mp4" },
    { word: "farmor", video: "farmor-01933-tecken.mp4" },
    { word: "släkt", video: "slakt-03156-tecken.mp4" },
    { word: "barnbarn", video: "barnbarn-04647-tecken.mp4" },
    { word: "moster", video: "moster-00176-tecken.mp4" },
    { word: "syskon", video: "syskon-03564-tecken.mp4" },
    { word: "morfar", video: "morfar-01937-tecken.mp4" },
    { word: "lillebror", video: "lillebror-16156-tecken.mp4" },
    { word: "kusin", video: "kusin-03155-tecken.mp4" },
    { word: "sambo", video: "sambo-05067-tecken.mp4" },
    { word: "flickvän", video: "flickvan-11970-tecken.mp4" },
    { word: "pojkvän", video: "pojkvan-12482-tecken.mp4" },
    { word: "storebror", video: "storebror-15963-tecken.mp4" },
    { word: "släkting", video: "slakting-20134-tecken.mp4" },
    { word: "faster", video: "faster-01399-tecken.mp4" },
    { word: "morbror", video: "morbror-05083-tecken.mp4" },
    { word: "svärmor", video: "svarmor-05352-tecken.mp4" },
    { word: "fästmö", video: "fastmo-02487-tecken.mp4" },
    { word: "svåger", video: "svager-03157-tecken.mp4" },
    { word: "svärfar", video: "svarfar-05350-tecken.mp4" },
    { word: "storasyster", video: "storasyster-15946-tecken.mp4" },
    { word: "styvmor", video: "styvmor-08496-tecken.mp4" },
    { word: "fästman", video: "fastman-15888-tecken.mp4" },
    { word: "brorson", video: "brorson-18608-tecken.mp4" },
    { word: "styvfar", video: "styvfar-00433-tecken.mp4" },
    { word: "halvbror", video: "halvbror-19344-tecken.mp4" },
    { word: "systerdotter", video: "systerdotter-18612-tecken.mp4" },
    { word: "systerson", video: "systerson-18613-tecken.mp4" },
    { word: "svärföräldrar", video: "svarforaldrar-05351-tecken.mp4" },
    { word: "halvsyster", video: "halvsyster-24352-tecken.mp4" },
    { word: "brorsdotter", video: "brorsdotter-18609-tecken.mp4" },
    { word: "måg", video: "mag-19339-tecken.mp4" },
    { word: "sladdbarn", video: "sladdbarn-16325-tecken.mp4" },
    { word: "släktmiddag", video: "slaktmiddag-24729-tecken.mp4" },
    { word: "morförälder", video: "morforalder-04257-tecken.mp4" },
    { word: "gammelfarmor", video: "gammelfarmor-08414-tecken.mp4" },
    { word: "långsläkt", video: "langslakt-24771-tecken.mp4" }
  ],
  phrases: [
    { word: "man", phrase: "Min systers [man] vet inte om att jag har fyra barn.", video: "man-05036-fras-1.mp4" },
    { word: "barn", phrase: "Mina [barn] är helt sålda på TV-spel. De måste spela varje dag.", video: "barn-00257-fras-1.mp4" },
    { word: "barn", phrase: "När sommarlovet är slut är [barnen] fulla av iver över att komma tillbaka till skolan.", video: "barn-00257-fras-2.mp4" },
    { word: "barn", phrase: "Jag har tre [barn].", video: "barn-00257-fras-3.mp4" },
    { word: "mamma", phrase: "[Mamma] är alltid bäst!", video: "mamma-00188-fras-1.mp4" },
    { word: "pappa", phrase: "Är han din [pappa]?", video: "pappa-02557-fras-1.mp4" },
    { word: "pappa", phrase: "[Pappa] är väldigt lång.", video: "pappa-02557-fras-2.mp4" },
    { word: "föräldrar", phrase: "Tack vare att mina [föräldrar] lärde sig teckenspråk kan jag kommunicera med dem.", video: "foraldrar-13821-fras-1.mp4" },
    { word: "föräldrar", phrase: "Är det där dina [föräldrar]?", video: "foraldrar-13821-fras-2.mp4" },
    { word: "son", phrase: "Min [son] vill gå med i en fäktningsklubb men han är för liten. Han får vänta två år till.", video: "son-01944-fras-1.mp4" },
    { word: "son", phrase: "Min systers [son] har födelsedag imorgon.", video: "son-01944-fras-2.mp4" },
    { word: "son", phrase: "Är det din [son]?", video: "son-01944-fras-3.mp4" },
    { word: "fru", phrase: "Min [frus] föräldrar kan inte teckenspråk.", video: "fru-04582-fras-1.mp4" },
    { word: "dotter", phrase: "Min äldsta [dotter] är tio år gammal.", video: "dotter-00111-fras-1.mp4" },
    { word: "dotter", phrase: "Vad heter din [dotter]?", video: "dotter-00111-fras-2.mp4" },
    { word: "dotter", phrase: "Är hon din [dotter]?", video: "dotter-00111-fras-3.mp4" },
    { word: "syster", phrase: "Min familj består av mamma, pappa, mig själv och två systrar.", video: "syster-03513-fras-1.mp4" },
    { word: "syster", phrase: "Min [syster] är snäll.", video: "syster-03513-fras-2.mp4" },
    { word: "mormor", phrase: "Min [mormor] är proffs på att baka bullar och bröd. De är alltid goda.", video: "mormor-01938-fras-1.mp4" },
    { word: "farmor", phrase: "Är hon min [farmor]?", video: "farmor-01933-fras-1.mp4" },
    { word: "släkt", phrase: "De flesta av mina [släktingar] bor i Spanien.", video: "slakt-03156-fras-1.mp4" },
    { word: "släkt", phrase: "Alla andra i min [släkt] är hörande. Det är bara jag som är döv.", video: "slakt-03156-fras-2.mp4" },
    { word: "släkt", phrase: "I min [släkt] är det bara jag som är döv. Alla andra är hörande.", video: "slakt-03156-fras-3.mp4" },
    { word: "släkt", phrase: "Hon och jag är [släkt] med varandra.", video: "slakt-03156-fras-4.mp4" },
    { word: "barnbarn", phrase: "Ett [barnbarn] till min arbetskamrat går i samma klass som min son.", video: "barnbarn-04647-fras-1.mp4" },
    { word: "barnbarn", phrase: "När jag hälsar på mitt [barnbarn] har jag alltid med en klubba till hen.", video: "barnbarn-04647-fras-2.mp4" },
    { word: "moster", phrase: "Jag har biobiljetter till oss som jag fått av min [moster].", video: "moster-00176-fras-1.mp4" },
    { word: "moster", phrase: "[Moster] är benämningen för din mammas syster.", video: "moster-00176-fras-2.mp4" },
    { word: "moster", phrase: "Har du bra kontakt med din [moster] eller???", video: "moster-00176-fras-3.mp4" },
    { word: "syskon", phrase: "Vi är fem [syskon] och jag är näst äldst.", video: "syskon-03564-fras-1.mp4" },
    { word: "syskon", phrase: "Jag har tre [syskon].", video: "syskon-03564-fras-2.mp4" },
    { word: "morfar", phrase: "Min [morfar] heter Anders.", video: "morfar-01937-fras-1.mp4" },
    { word: "sambo", phrase: "Förut var det inte så vanligt med [sambor] men det är det idag.", video: "sambo-05067-fras-1.mp4" },
    { word: "sambo", phrase: "Nu har min [sambo] gått iväg för att handla mat.", video: "sambo-05067-fras-2.mp4" },
    { word: "sambo", phrase: "Det här är Erik, min [sambo].", video: "sambo-05067-fras-3.mp4" },
    { word: "sambo", phrase: "Igår sprang jag på hennes [sambo].", video: "sambo-05067-fras-4.mp4" },
    { word: "svåger", phrase: "Min syster fyller snart 40 år så min [svåger] och jag tänker hitta på något.", video: "svager-03157-fras-1.mp4" }
  ]
});

// --- grunder1.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "blandat1",
  name: "Blandat 1",
  words: [
    // Greetings & basics
    { word: "hej", video: "hej-12747-tecken.mp4" },
    { word: "tack", video: "tack-15805-tecken.mp4" },
    { word: "ja", video: "ja-11810-tecken.mp4" },
    { word: "nej", video: "nej-03952-tecken.mp4" },
    { word: "bra", video: "bra-09363-tecken.mp4" },

    // Pronouns
    { word: "jag", video: "jag-02798-tecken.mp4" },
    { word: "du", video: "du-02817-tecken.mp4" },
    { word: "vi", video: "vi-08535-tecken.mp4" },
    { word: "han", video: "han-00812-tecken.mp4" },
    { word: "hon", video: "hon-05389-tecken.mp4" },
    { word: "de", video: "de-20126-tecken.mp4" },
    { word: "den", video: "den-03690-tecken.mp4" },

    // Question words
    { word: "vad", video: "vad-00644-tecken.mp4" },
    { word: "vem", video: "vem-05115-tecken.mp4" },
    { word: "hur", video: "hur-04569-tecken.mp4" },
    { word: "var", video: "var-10249-tecken.mp4" },
    { word: "när", video: "nar-03954-tecken.mp4" },

    // Common verbs/helpers
    { word: "kan", video: "kan-00022-tecken.mp4" },
    { word: "ska", video: "ska-02238-tecken.mp4" },
    { word: "vill", video: "vill-00167-tecken.mp4" },
    { word: "inte", video: "inte-00646-tecken.mp4" },
    { word: "komma", video: "komma-09684-tecken.mp4" },
    { word: "se", video: "se-04104-tecken.mp4" },
    { word: "titta", video: "titta-04101-tecken.mp4" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4" },
    { word: "prata", video: "prata-19393-tecken.mp4" },
    { word: "tala", video: "tala-10183-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "höra", video: "hora-02663-tecken.mp4" },
    { word: "gå", video: "ga-09593-tecken.mp4" },
    { word: "springa", video: "springa-02208-tecken.mp4" },
    { word: "äta", video: "ata-01267-tecken.mp4" },
    { word: "dricka", video: "dricka-01377-tecken.mp4" },
    { word: "sova", video: "sova-03253-tecken.mp4" },
    { word: "leka", video: "leka-01092-tecken.mp4" },
    { word: "jobba", video: "jobba-02063-tecken.mp4" },
    { word: "köpa", video: "kopa-05587-tecken.mp4" },
    { word: "ringa", video: "ringa-03775-tecken.mp4" },
    { word: "hjälpa", video: "hjalpa-09611-tecken.mp4" },
    { word: "vänta", video: "vanta-00207-tecken.mp4" },
    { word: "börja", video: "borja-02945-tecken.mp4" },
    { word: "sluta", video: "sluta-20073-tecken.mp4" },
    { word: "förstå", video: "forsta-07617-tecken.mp4" },

    // Family
    { word: "mamma", video: "mamma-09798-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4" },
    { word: "barn", video: "barn-00257-tecken.mp4" },
    { word: "familj", video: "familj-20361-tecken.mp4" },
    { word: "syster", video: "syster-03892-tecken.mp4" },
    { word: "bror", video: "bror-08032-tecken.mp4" },
    { word: "mormor", video: "mormor-07412-tecken.mp4" },
    { word: "morfar", video: "morfar-07408-tecken.mp4" },
    { word: "farmor", video: "farmor-07541-tecken.mp4" },
    { word: "farfar", video: "farfar-04752-tecken.mp4" },
    { word: "kompis", video: "kompis-02531-tecken.mp4" },

    // People
    { word: "pojke", video: "pojke-05903-tecken.mp4" },
    { word: "flicka", video: "flicka-05777-tecken.mp4" },
    { word: "kvinna", video: "kvinna-01106-tecken.mp4" },
    { word: "man", video: "man-05870-tecken.mp4" },
    { word: "baby", video: "baby-00573-tecken.mp4" },

    // Adjectives
    { word: "glad", video: "glad-00165-tecken.mp4" },
    { word: "arg", video: "arg-04321-tecken.mp4" },
    { word: "ledsen", video: "ledsen-15383-tecken.mp4" },
    { word: "rädd", video: "radd-03447-tecken.mp4" },
    { word: "trött", video: "trott-00966-tecken.mp4" },
    { word: "hungrig", video: "hungrig-08446-tecken.mp4" },
    { word: "törstig", video: "torstig-00139-tecken.mp4" },
    { word: "sjuk", video: "sjuk-19384-tecken.mp4" },
    { word: "frisk", video: "frisk-05274-tecken.mp4" },
    { word: "stor", video: "stor-20217-tecken.mp4" },
    { word: "liten", video: "liten-19410-tecken.mp4" },
    { word: "gammal", video: "gammal-09565-tecken.mp4" },
    { word: "ung", video: "ung-10228-tecken.mp4" },
    { word: "ny", video: "ny-09120-tecken.mp4" },
    { word: "fin", video: "fin-09695-tecken.mp4" },
    { word: "ful", video: "ful-08136-tecken.mp4" },
    { word: "snabb", video: "snabb-03935-tecken.mp4" },
    { word: "varm", video: "varm-10259-tecken.mp4" },
    { word: "kall", video: "kall-01505-tecken.mp4" },
    { word: "rolig", video: "rolig-02354-tecken.mp4" },
    { word: "vacker", video: "vacker-10246-tecken.mp4" },
    { word: "stark", video: "stark-10124-tecken.mp4" },
    { word: "lång", video: "lang-13464-tecken.mp4" },
    { word: "kort", video: "kort-00602-tecken.mp4" },

    // Colors
    { word: "röd", video: "rod-02751-tecken.mp4" },
    { word: "blå", video: "bla-07660-tecken.mp4" },
    { word: "grön", video: "gron-00814-tecken.mp4" },
    { word: "gul", video: "gul-09588-tecken.mp4" },
    { word: "vit", video: "vit-02773-tecken.mp4" },
    { word: "svart", video: "svart-05037-tecken.mp4" },

    // Food & drink
    { word: "mat", video: "mat-05565-tecken.mp4" },
    { word: "vatten", video: "vatten-01384-tecken.mp4" },
    { word: "mjölk", video: "mjolk-07492-tecken.mp4" },
    { word: "bröd", video: "brod-00434-tecken.mp4" },
    { word: "ost", video: "ost-02449-tecken.mp4" },
    { word: "kaffe", video: "kaffe-09670-tecken.mp4" },
    { word: "te", video: "te-05376-tecken.mp4" },

    // Places & things
    { word: "hem", video: "hem-00498-tecken.mp4" },
    { word: "hus", video: "hus-00696-tecken.mp4" },
    { word: "skola", video: "skola-00617-tecken.mp4" },
    { word: "arbete", video: "arbete-00562-tecken.mp4" },
    { word: "bil", video: "bil-02158-tecken.mp4" },
    { word: "buss", video: "buss-01474-tecken.mp4" },
    { word: "bok", video: "bok-09354-tecken.mp4" },
    { word: "telefon", video: "telefon-04490-tecken.mp4" },
    { word: "dator", video: "dator-05190-tecken.mp4" },
    { word: "stol", video: "stol-03997-tecken.mp4" },
    { word: "bord", video: "bord-00664-tecken.mp4" },
    { word: "dörr", video: "dorr-11721-tecken.mp4" },
    { word: "fönster", video: "fonster-03150-tecken.mp4" },

    // Time
    { word: "dag", video: "dag-00632-tecken.mp4" },
    { word: "morgon", video: "morgon-00623-tecken.mp4" },
    { word: "kväll", video: "kvall-09732-tecken.mp4" },
    { word: "natt", video: "natt-00516-tecken.mp4" },
    { word: "vecka", video: "vecka-08056-tecken.mp4" },
    { word: "tid", video: "tid-03542-tecken.mp4" },

    // Other
    { word: "vår", video: "var-00186-tecken.mp4" },
    { word: "här", video: "har-02866-tecken.mp4" },

    // Animals
    { word: "hund", video: "hund-00222-tecken.mp4" },
    { word: "katt", video: "katt-00344-tecken.mp4" },
  ]
});

// --- handalfabetet.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "handalfabetet",
  name: "Handalfabetet",
  words: [
    { word: "i", video: "i-11929-tecken.mp4" },
    { word: "t", video: "t-11940-tecken.mp4" },
    { word: "a", video: "a-09531-tecken.mp4" },
    { word: "s", video: "s-11939-tecken.mp4" },
    { word: "m", video: "m-11933-tecken.mp4" },
    { word: "b", video: "b-09532-tecken.mp4" },
    { word: "g", video: "g-11927-tecken.mp4" },
    { word: "h", video: "h-11928-tecken.mp4" },
    { word: "j", video: "j-11930-tecken.mp4" },
    { word: "e", video: "e-11925-tecken.mp4" },
    { word: "o", video: "o-11935-tecken.mp4" },
    { word: "l", video: "l-11932-tecken.mp4" },
    { word: "f", video: "f-11926-tecken.mp4" },
    { word: "k", video: "k-11931-tecken.mp4" },
    { word: "c", video: "c-09011-tecken.mp4" },
    { word: "å", video: "a-11947-tecken.mp4" },
    { word: "p", video: "p-11936-tecken.mp4" },
    { word: "r", video: "r-11938-tecken.mp4" },
    { word: "d", video: "d-09533-tecken.mp4" },
    { word: "ö", video: "o-11949-tecken.mp4" },
    { word: "w", video: "w-11943-tecken.mp4" },
    { word: "n", video: "n-11934-tecken.mp4" },
    { word: "ä", video: "a-11948-tecken.mp4" },
    { word: "u", video: "u-11941-tecken.mp4" },
    { word: "v", video: "v-11942-tecken.mp4" },
    { word: "x", video: "x-11944-tecken.mp4" },
    { word: "q", video: "q-11937-tecken.mp4" },
    { word: "y", video: "y-11945-tecken.mp4" },
    { word: "z", video: "z-11946-tecken.mp4" }
  ]
});

// --- mat.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "mat",
  name: "Mat och dryck",
  words: [
    { word: "vatten", video: "vatten-00132-tecken.mp4" },
    { word: "mat", video: "mat-01266-tecken.mp4" },
    { word: "bär", video: "bar-01840-tecken.mp4" },
    { word: "kaffe", video: "kaffe-02042-tecken.mp4" },
    { word: "vin", video: "vin-04129-tecken.mp4" },
    { word: "middag", video: "middag-04024-tecken.mp4" },
    { word: "alkohol", video: "alkohol-09659-tecken.mp4" },
    { word: "rom", video: "rom-13060-tecken.mp4" },
    { word: "bröd", video: "brod-00434-tecken.mp4" },
    { word: "salt", video: "salt-03998-tecken.mp4" },
    { word: "öl", video: "ol-01793-tecken.mp4" },
    { word: "potatis", video: "potatis-05539-tecken.mp4" },
    { word: "lunch", video: "lunch-02756-tecken.mp4" },
    { word: "skiva", video: "skiva-16400-tecken.mp4" },
    { word: "kött", video: "kott-01913-tecken.mp4" },
    { word: "banan", video: "banan-03309-tecken.mp4" },
    { word: "smör", video: "smor-00480-tecken.mp4" },
    { word: "mjölk", video: "mjolk-02184-tecken.mp4" },
    { word: "ägg", video: "agg-04013-tecken.mp4" },
    { word: "sprit", video: "sprit-02334-tecken.mp4" },
    { word: "socker", video: "socker-02920-tecken.mp4" },
    { word: "te", video: "te-05376-tecken.mp4" },
    { word: "frukt", video: "frukt-01923-tecken.mp4" },
    { word: "ris", video: "ris-09164-tecken.mp4" },
    { word: "ost", video: "ost-02449-tecken.mp4" },
    { word: "pressa", video: "pressa-16461-tecken.mp4" },
    { word: "skala", video: "skala-03678-tecken.mp4" },
    { word: "frukost", video: "frukost-03353-tecken.mp4" },
    { word: "livsmedel", video: "livsmedel-01265-tecken.mp4" },
    { word: "kärna", video: "karna-13861-tecken.mp4" },
    { word: "recept", video: "recept-03682-tecken.mp4" },
    { word: "röka", video: "roka-11843-tecken.mp4" },
    { word: "koka", video: "koka-01700-tecken.mp4" },
    { word: "sallad", video: "sallad-04254-tecken.mp4" },
    { word: "korv", video: "korv-00916-tecken.mp4" },
    { word: "dryck", video: "dryck-11620-tecken.mp4" },
    { word: "sås", video: "sas-09206-tecken.mp4" },
    { word: "peppar", video: "peppar-01408-tecken.mp4" },
    { word: "mjöl", video: "mjol-00899-tecken.mp4" },
    { word: "grädde", video: "gradde-00420-tecken.mp4" },
    { word: "coca-cola", video: "coca-cola-09690-tecken.mp4" },
    { word: "celsius", video: "celsius-18766-tecken.mp4" },
    { word: "champagne", video: "champagne-01830-tecken.mp4" },
    { word: "choklad", video: "choklad-00821-tecken.mp4" },
    { word: "vitlök", video: "vitlok-09067-tecken.mp4" },
    { word: "whisky", video: "whisky-01988-tecken.mp4" },
    { word: "soppa", video: "soppa-00599-tecken.mp4" },
    { word: "matlagning", video: "matlagning-17874-tecken.mp4" },
    { word: "brännvin", video: "brannvin-03224-tecken.mp4" },
    { word: "ekologisk", video: "ekologisk-00517-tecken.mp4" }
  ]
});

// --- sport.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "sport",
  name: "Sport",
  words: [
  ]
});

// --- teknik.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "teknik",
  name: "Data och teknik",
  words: [
    { word: "tv", video: "tv-05428-tecken.mp4" },
    { word: "foto", video: "foto-00751-tecken.mp4" },
    { word: "tag", video: "tag-17510-tecken.mp4" },
    { word: "teknik", video: "teknik-04215-tecken.mp4" },
    { word: "internet", video: "internet-04907-tecken.mp4" },
    { word: "inställning", video: "installning-03523-tecken.mp4" },
    { word: "telefon", video: "telefon-03776-tecken.mp4" },
    { word: "radio", video: "radio-01498-tecken.mp4" },
    { word: "kurs", video: "kurs-07663-tecken.mp4" },
    { word: "version", video: "version-09270-tecken.mp4" },
    { word: "band", video: "band-16648-tecken.mp4" },
    { word: "dator", video: "dator-00304-tecken.mp4" },
    { word: "led", video: "led-08499-tecken.mp4" },
    { word: "nätverk", video: "natverk-12464-tecken.mp4" },
    { word: "ström", video: "strom-04386-tecken.mp4" },
    { word: "nät", video: "nat-00914-tecken.mp4" },
    { word: "ram", video: "ram-05208-tecken.mp4" },
    { word: "toner", video: "toner-05404-tecken.mp4" },
    { word: "data", video: "data-04706-tecken.mp4" },
    { word: "x", video: "x-24685-tecken.mp4" },
    { word: "morse", video: "morse-22969-tecken.mp4" },
    { word: "fält", video: "falt-24651-tecken.mp4" },
    { word: "konto", video: "konto-04525-tecken.mp4" },
    { word: "kamera", video: "kamera-03530-tecken.mp4" },
    { word: "plattform", video: "plattform-19795-tecken.mp4" },
    { word: "cd", video: "cd-04694-tecken.mp4" },
    { word: "fax", video: "fax-04761-tecken.mp4" },
    { word: "format", video: "format-19466-tecken.mp4" },
    { word: "fil", video: "fil-09318-tecken.mp4" },
    { word: "nokia", video: "nokia-16739-tecken.mp4" },
    { word: "digital", video: "digital-05734-tecken.mp4" },
    { word: "telefonsamtal", video: "telefonsamtal-19398-tecken.mp4" },
    { word: "play", video: "play-20219-tecken.mp4" },
    { word: "inspelning", video: "inspelning-00194-tecken.mp4" },
    { word: "gilla", video: "gilla-17566-tecken.mp4" },
    { word: "grafik", video: "grafik-04820-tecken.mp4" },
    { word: "högtalare", video: "hogtalare-05658-tecken.mp4" },
    { word: "box", video: "box-04435-tecken.mp4" },
    { word: "windows", video: "windows-17554-tecken.mp4" },
    { word: "installera", video: "installera-01343-tecken.mp4" },
    { word: "ladda", video: "ladda-19127-tecken.mp4" },
    { word: "kabel-tv", video: "kabel-tv-02639-tecken.mp4" },
    { word: "skärm", video: "skarm-01795-tecken.mp4" },
    { word: "växel", video: "vaxel-20415-tecken.mp4" },
    { word: "pc", video: "pc-09157-tecken.mp4" },
    { word: "bandspelare", video: "bandspelare-03233-tecken.mp4" },
    { word: "klicka", video: "klicka-17314-tecken.mp4" },
    { word: "batteri", video: "batteri-03634-tecken.mp4" },
    { word: "telefonsvarare", video: "telefonsvarare-19498-tecken.mp4" },
    { word: "cd-rom", video: "cd-rom-11342-tecken.mp4" },
    { word: "surfa", video: "surfa-20278-tecken.mp4" },
    { word: "hacka", video: "hacka-17526-tecken.mp4" },
    { word: "mus", video: "mus-04443-tecken.mp4" },
    { word: "mobil", video: "mobil-05076-tecken.mp4" },
    { word: "modem", video: "modem-02100-tecken.mp4" },
    { word: "dataspel", video: "dataspel-11443-tecken.mp4" },
    { word: "www", video: "www-09271-tecken.mp4" },
    { word: "dataprogram", video: "dataprogram-11442-tecken.mp4" },
    { word: "kabel", video: "kabel-03199-tecken.mp4" },
    { word: "kod", video: "kod-09050-tecken.mp4" },
    { word: "hybrid", video: "hybrid-20125-tecken.mp4" },
    { word: "doc", video: "doc-09994-tecken.mp4" },
    { word: "filter", video: "filter-19848-tecken.mp4" },
    { word: "mekanik", video: "mekanik-19241-tecken.mp4" },
    { word: "tredimensionell", video: "tredimensionell-05032-tecken.mp4" },
    { word: "dvd", video: "dvd-08770-tecken.mp4" },
    { word: "beta", video: "beta-04301-tecken.mp4" },
    { word: "bärbar", video: "barbar-10500-tecken.mp4" },
    { word: "vidarebefordra", video: "vidarebefordra-17570-tecken.mp4" },
    { word: "gsm", video: "gsm-09630-tecken.mp4" },
    { word: "webb", video: "webb-09268-tecken.mp4" },
    { word: "dropp", video: "dropp-07506-tecken.mp4" },
    { word: "hårddisk", video: "harddisk-08966-tecken.mp4" },
    { word: "wish", video: "wish-11196-tecken.mp4" },
    { word: "programmerare", video: "programmerare-09741-tecken.mp4" },
    { word: "macintosh", video: "macintosh-05925-tecken.mp4" },
    { word: "omstart", video: "omstart-04710-tecken.mp4" },
    { word: "online", video: "online-17593-tecken.mp4" },
    { word: "operativsystem", video: "operativsystem-19281-tecken.mp4" },
    { word: "strömbrytare", video: "strombrytare-09543-tecken.mp4" },
    { word: "diskett", video: "diskett-01286-tecken.mp4" },
    { word: "tangentbord", video: "tangentbord-18753-tecken.mp4" },
    { word: "textad", video: "textad-03667-tecken.mp4" },
    { word: "plasma", video: "plasma-08315-tecken.mp4" },
    { word: "vista", video: "vista-10731-tecken.mp4" },
    { word: "gps", video: "gps-03704-tecken.mp4" },
    { word: "uppgradera", video: "uppgradera-04190-tecken.mp4" },
    { word: "tv-spel", video: "tv-spel-12294-tecken.mp4" },
    { word: "bildspel", video: "bildspel-10776-tecken.mp4" },
    { word: "word", video: "word-19472-tecken.mp4" },
    { word: "cd-spelare", video: "cd-spelare-08184-tecken.mp4" },
    { word: "antenn", video: "antenn-01048-tecken.mp4" },
    { word: "zoom", video: "zoom-17590-tecken.mp4" },
    { word: "cd-skiva", video: "cd-skiva-11343-tecken.mp4" },
    { word: "elan", video: "elan-11749-tecken.mp4" },
    { word: "konvertera", video: "konvertera-19471-tecken.mp4" },
    { word: "server", video: "server-19306-tecken.mp4" },
    { word: "navigera", video: "navigera-19526-tecken.mp4" },
    { word: "processor", video: "processor-11539-tecken.mp4" },
    { word: "datorskärm", video: "datorskarm-11449-tecken.mp4" }
  ]
});

// --- verb.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "verb",
  name: "Verb",
  words: [
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "ha", video: "ha-00958-tecken.mp4" },
    { word: "få", video: "fa-00193-tecken.mp4" },
    { word: "bli", video: "bli-03181-tecken.mp4" },
    { word: "kunna", video: "kunna-05045-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "se", video: "se-04104-tecken.mp4" },
    { word: "gå", video: "ga-04238-tecken.mp4" },
    { word: "ge", video: "ge-00721-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "komma", video: "komma-09684-tecken.mp4" },
    { word: "betala", video: "betala-02433-tecken.mp4" },
    { word: "spela", video: "spela-01876-tecken.mp4" },
    { word: "försöka", video: "forsoka-04350-tecken.mp4" },
    { word: "skapa", video: "skapa-00933-tecken.mp4" },
    { word: "tala", video: "tala-02696-tecken.mp4" },
    { word: "börja", video: "borja-03852-tecken.mp4" },
    { word: "stå", video: "sta-03035-tecken.mp4" },
    { word: "fortsätta", video: "fortsatta-00331-tecken.mp4" },
    { word: "hitta", video: "hitta-01495-tecken.mp4" },
    { word: "hålla", video: "halla-02177-tecken.mp4" },
    { word: "köpa", video: "kopa-01301-tecken.mp4" },
    { word: "låta", video: "lata-05599-tecken.mp4" },
    { word: "använda", video: "anvanda-02375-tecken.mp4" },
    { word: "bygga", video: "bygga-00557-tecken.mp4" },
    { word: "visa", video: "visa-00649-tecken.mp4" },
    { word: "öka", video: "oka-00995-tecken.mp4" },
    { word: "höra", video: "hora-02663-tecken.mp4" },
    { word: "arbeta", video: "arbeta-08062-tecken.mp4" },
    { word: "tro", video: "tro-07173-tecken.mp4" },
    { word: "förstå", video: "forsta-02570-tecken.mp4" },
    { word: "lämna", video: "lamna-02056-tecken.mp4" },
    { word: "skriva", video: "skriva-03410-tecken.mp4" },
    { word: "leva", video: "leva-00849-tecken.mp4" },
    { word: "läsa", video: "lasa-00277-tecken.mp4" },
    { word: "vinna", video: "vinna-01585-tecken.mp4" },
    { word: "åka", video: "aka-04036-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" },
    { word: "sälja", video: "salja-01571-tecken.mp4" },
    { word: "nå", video: "na-00358-tecken.mp4" },
    { word: "bo", video: "bo-00050-tecken.mp4" },
    { word: "minska", video: "minska-01152-tecken.mp4" },
    { word: "sitta", video: "sitta-04009-tecken.mp4" },
    { word: "välja", video: "valja-03284-tecken.mp4" },
    { word: "leda", video: "leda-01706-tecken.mp4" },
    { word: "vilja", video: "vilja-00534-tecken.mp4" },
    { word: "vänta", video: "vanta-00207-tecken.mp4" },
    { word: "hjälpa", video: "hjalpa-00625-tecken.mp4" },
    { word: "ligga", video: "ligga-00411-tecken.mp4" },
    { word: "berätta", video: "beratta-00333-tecken.mp4" },
    { word: "behöva", video: "behova-04769-tecken.mp4" },
    { word: "satsa", video: "satsa-03628-tecken.mp4" },
    { word: "ske", video: "ske-11080-tecken.mp4" },
    { word: "prata", video: "prata-00835-tecken.mp4" },
    { word: "flytta", video: "flytta-01873-tecken.mp4" },
    { word: "titta", video: "titta-04101-tecken.mp4" },
    { word: "köra", video: "kora-02160-tecken.mp4" },
    { word: "diskutera", video: "diskutera-02702-tecken.mp4" },
    { word: "stanna", video: "stanna-00684-tecken.mp4" },
    { word: "känna", video: "kanna-04004-tecken.mp4" },
    { word: "behålla", video: "behalla-01972-tecken.mp4" },
    { word: "söka", video: "soka-04382-tecken.mp4" },
    { word: "äta", video: "ata-01267-tecken.mp4" },
    { word: "lösa", video: "losa-01869-tecken.mp4" },
    { word: "lägga", video: "lagga-00427-tecken.mp4" },
    { word: "utveckla", video: "utveckla-03100-tecken.mp4" },
    { word: "fungera", video: "fungera-00969-tecken.mp4" },
    { word: "hända", video: "handa-03023-tecken.mp4" },
    { word: "dra", video: "dra-02113-tecken.mp4" },
    { word: "jobba", video: "jobba-02063-tecken.mp4" },
    { word: "möta", video: "mota-02260-tecken.mp4" },
    { word: "svara", video: "svara-05673-tecken.mp4" },
    { word: "påverka", video: "paverka-01899-tecken.mp4" },
    { word: "rädda", video: "radda-01684-tecken.mp4" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4" },
    { word: "sluta", video: "sluta-00312-tecken.mp4" },
    { word: "förklara", video: "forklara-01820-tecken.mp4" },
    { word: "räkna", video: "rakna-01614-tecken.mp4" },
    { word: "slå", video: "sla-11468-tecken.mp4" },
    { word: "acceptera", video: "acceptera-09672-tecken.mp4" },
    { word: "delta", video: "delta-12376-tecken.mp4" },
    { word: "handla", video: "handla-02539-tecken.mp4" }
  ],
  phrases: [
    { word: "ha", phrase: "Jag [har] en stor lägenhet på åttio kvadratmeter.", video: "ha-00958-fras-1.mp4" },
    { word: "få", phrase: "Jag har inte [fått] ditt mail. Hur kommer det sig?", video: "fa-00193-fras-1.mp4" },
    { word: "få", phrase: "Jag ska [få] kattungar.", video: "fa-00193-fras-2.mp4" },
    { word: "få", phrase: "När jag var liten [fick] jag väldigt mycket i veckopeng. Det var för att jag var yngst i familjen.", video: "fa-00193-fras-3.mp4" },
    { word: "bli", phrase: "I framtiden vill jag [bli] doktor.", video: "bli-03181-fras-1.mp4" },
    { word: "bli", phrase: "Om du steker köttet för länge [blir] det alldeles för hårt.", video: "bli-03181-fras-2.mp4" },
    { word: "kunna", phrase: "Om man vill vara med på simlägret måste man [kunna] simma minst 200 meter.", video: "kunna-05045-fras-1.mp4" },
    { word: "göra", phrase: "1. Vad ska du [göra]? 2. Vad [gör] du?", video: "gora-00563-fras-1.mp4" },
    { word: "göra", phrase: "Vad brukar du [göra] på torsdagarna?", video: "gora-00563-fras-2.mp4" },
    { word: "göra", phrase: "Vad [gör] du på lördag kväll?", video: "gora-00563-fras-3.mp4" },
    { word: "göra", phrase: "1. Vad ska du [göra]? 2. Vad [gör] du?", video: "gora-00563-fras-1.mp4" },
    { word: "göra", phrase: "Vad brukar du [göra] på torsdagarna?", video: "gora-00563-fras-2.mp4" },
    { word: "göra", phrase: "Vad [gör] du på lördag kväll?", video: "gora-00563-fras-3.mp4" },
    { word: "se", phrase: "Jag har inte [sett] filmen.", video: "se-04104-fras-1.mp4" },
    { word: "se", phrase: "Det var roligt att [se] dig!", video: "se-04104-fras-2.mp4" },
    { word: "se", phrase: "Vad roligt att du [såg] mig på TV.", video: "se-04104-fras-3.mp4" },
    { word: "gå", phrase: "Om vi [går] i minst en halvtimme blir vi piggare.", video: "ga-04238-fras-1.mp4" },
    { word: "gå", phrase: "[Gå] nu!", video: "ga-04238-fras-2.mp4" },
    { word: "ge", phrase: "Jag har alltid svårt att bestämma mig för vad jag ska [ge] mina syskonbarn i [julklapp].", video: "ge-00721-fras-1.mp4" },
    { word: "ta", phrase: "Har du [tagit] med dig nycklarna och mobilen?", video: "ta-01548-fras-1.mp4" },
    { word: "ta", phrase: "Har du [tagit] med dig nycklarna och mobilen?", video: "ta-01548-fras-1.mp4" },
    { word: "betala", phrase: "Vem ska [betala]? Du eller jag?", video: "betala-02433-fras-1.mp4" },
    { word: "betala", phrase: "Man måste [betala] [avgiften]", video: "betala-02433-fras-2.mp4" },
    { word: "betala", phrase: "Du måste [betala] medlemsavgiften till dövföreningen.", video: "betala-02433-fras-3.mp4" },
    { word: "betala", phrase: "Det finns mycket vi måste [betala] för, el, mat, boende m.m.", video: "betala-02433-fras-4.mp4" },
    { word: "tala", phrase: "När jag var liten fick jag öva [talet] i skolan. Jag minns att jag avskydde [talövningarna].", video: "tala-02696-fras-1.mp4" },
    { word: "börja", phrase: "Teatern [börjar] klockan sju.", video: "borja-03852-fras-1.mp4" },
    { word: "börja", phrase: "Vi [börjar] styrelsemötet när alla har kommit.", video: "borja-03852-fras-2.mp4" },
    { word: "börja", phrase: "Starta nu!\n\n(Note: \"starta\" is not an inflected or derived form of \"börja\". The phrase contains no forms of \"börja\".)", video: "borja-03852-fras-3.mp4" },
    { word: "börja", phrase: "Mötet skulle [börja] kl 13.00 men är nu fram[flyttat] till kl. 15.00.\n\nWait, let me reconsider. The base word is \"börja\" (to begin/start). I need to find \"börja\" and its inflected or derived forms.\n\nLooking at the phrase: \"starta\" is not a form of \"börja\", and \"framflyttat\" is not a form of \"börja\" either.\n\nActually, there are no occurrences of \"börja\" or its inflected/derived forms in this phrase.\n\nMötet skulle starta kl 13.00 men är nu framflyttat till kl. 15.00.", video: "borja-03852-fras-4.mp4" },
    { word: "stå", phrase: "Det är helt omöjligt för mig att [stå] [still] en lång stund. Jag är tvungen att röra på mig.", video: "sta-03035-fras-1.mp4" },
    { word: "fortsätta", phrase: "För att hålla en brasa vid liv måste man då och då se till att fylla på med ved\n\n(The word \"fortsätta\" does not appear in this phrase.)", video: "fortsatta-00331-fras-1.mp4" },
    { word: "fortsätta", phrase: "Om jag inte blir godkänd, så tänker jag inte [fortsätta].", video: "fortsatta-00331-fras-2.mp4" },
    { word: "köpa", phrase: "Jag är sugen på att [köpa] en ny TV.", video: "kopa-01301-fras-1.mp4" },
    { word: "köpa", phrase: "Du kan [köpa] en bok men du kan aldrig [köpa] kunskap.", video: "kopa-01301-fras-2.mp4" },
    { word: "använda", phrase: "När jag har rakat mig brukar jag [använda] Boss, en aftershave, för att det inte ska klia så mycket.", video: "anvanda-02375-fras-1.mp4" },
    { word: "använda", phrase: "Många döva [använder] bildtelefon för jämnan.", video: "anvanda-02375-fras-2.mp4" },
    { word: "använda", phrase: "Jag älskar mina jeans och jag [använder] dem hela tiden.", video: "anvanda-02375-fras-3.mp4" },
    { word: "använda", phrase: "Jag [använder] datorn varje dag.", video: "anvanda-02375-fras-4.mp4" },
    { word: "bygga", phrase: "Stockholms invånarantal ökar och är snart uppe i två miljoner. Det medför att fler bostäder måste [byggas].", video: "bygga-00557-fras-1.mp4" },
    { word: "öka", phrase: "Användningen av 3D-skrivare har [ökat].", video: "oka-00995-fras-1.mp4" },
    { word: "arbeta", phrase: "Vad [arbetar] du med?", video: "arbeta-08062-fras-1.mp4" },
    { word: "arbeta", phrase: "Jag har mycket [arbete] att göra idag.", video: "arbeta-08062-fras-2.mp4" },
    { word: "förstå", phrase: "[Förstod] du det jag nyss förklarade?", video: "forsta-02570-fras-1.mp4" },
    { word: "skriva", phrase: "Att [skriva] brev är inte lika vanligt nu som det var förut.", video: "skriva-03410-fras-1.mp4" },
    { word: "skriva", phrase: "Jag läser hellre än [skriver].", video: "skriva-03410-fras-2.mp4" },
    { word: "läsa", phrase: "Jag brukar [läsa] sagor för mina barn innan de ska sova.", video: "lasa-00277-fras-1.mp4" },
    { word: "läsa", phrase: "Det är viktigt att [läsa] för att kunna samla på sig mycket kunskap.", video: "lasa-00277-fras-2.mp4" },
    { word: "vinna", phrase: "Jag [vann] på lotteri igår så nu är jag rik.", video: "vinna-01585-fras-1.mp4" },
    { word: "vinna", phrase: "Personen som [vann] 100 meter igår hade innan dess haft en dålig säsong. Känns inte rimligt att hen kunde [vinna], kanske var hen dopad?", video: "vinna-01585-fras-2.mp4" },
    { word: "tänka", phrase: "Från början [tänkte] jag vara med på klassträffen men efter en viss tvekan struntade jag i den.", video: "tanka-02584-fras-1.mp4" },
    { word: "tänka", phrase: "Från början [tänkte] jag vara med på klassträffen men efter en viss tvekan struntade jag i den.", video: "tanka-02584-fras-1.mp4" },
    { word: "sälja", phrase: "Om jag skulle [sälja] nu så skulle jag inte få ut lika mycket pengar som jag köpte varan för.", video: "salja-01571-fras-1.mp4" },
    { word: "bo", phrase: "[Var] [bor] du?\n\nWait, let me reconsider. \"Var\" is not derived from \"bo\". Let me correct:\n\nVar [bor] du?", video: "bo-00050-fras-1.mp4" },
    { word: "bo", phrase: "Var [bor] du?", video: "bo-00050-fras-2.mp4" },
    { word: "vänta", phrase: "Jag har [väntat] i tjugo minuter.", video: "vanta-00207-fras-1.mp4" },
    { word: "hjälpa", phrase: "Jag förstår mig inte på deklarationen, kan du [hjälpa] mig?", video: "hjalpa-00625-fras-1.mp4" },
    { word: "hjälpa", phrase: "Min styvfar [hjälper] alltid mig med att fylla i deklarationen.", video: "hjalpa-00625-fras-2.mp4" },
    { word: "hjälpa", phrase: "Vi mår bra om vi [hjälper] varandra.", video: "hjalpa-00625-fras-3.mp4" },
    { word: "hjälpa", phrase: "Han vill inte [hjälpa] mig vilket gör mig deppad.", video: "hjalpa-00625-fras-4.mp4" },
    { word: "berätta", phrase: "Jag tycker det är roligt att [berätta] sagor.", video: "beratta-00333-fras-1.mp4" },
    { word: "berätta", phrase: "Sluta fråga så mycket. Jag tänker inte [berätta] något.", video: "beratta-00333-fras-2.mp4" },
    { word: "behöva", phrase: "Jag [behöver] 100 kronor!", video: "behova-04769-fras-1.mp4" },
    { word: "titta", phrase: "[Titta]!", video: "titta-04101-fras-1.mp4" },
    { word: "diskutera", phrase: "Elevrådet [diskuterar] alltid viktiga skolfrågor.", video: "diskutera-02702-fras-1.mp4" },
    { word: "diskutera", phrase: "Regeringen har nu stora [diskussioner] angående budgeten.", video: "diskutera-02702-fras-2.mp4" },
    { word: "behålla", phrase: "Egentligen tänkte jag kasta alla papper men jag [behåller] nog några i alla fall.", video: "behalla-01972-fras-1.mp4" },
    { word: "äta", phrase: "Igår kväll efter mitt hårda träningspass mådde jag inte alls bra, det beror på att jag inte hade [ätit] och druckit ordentligt innan träningen.", video: "ata-01267-fras-1.mp4" },
    { word: "lösa", phrase: "Jag mår så dåligt eftersom vi har bråkat. Kan vi [lösa] det tillsammans?", video: "losa-01869-fras-1.mp4" },
    { word: "lösa", phrase: "Det ser ut som du inte vet riktigt hur du ska göra. Jag [löser] det.", video: "losa-01869-fras-2.mp4" },
    { word: "utveckla", phrase: "En del studenter [utvecklas] snabbt medan andra behöver längre tid på sig. Det är lite olika.", video: "utveckla-03100-fras-1.mp4" },
    { word: "utveckla", phrase: "De företag som vill överleva idag måste [utveckla] sina produkter.", video: "utveckla-03100-fras-2.mp4" },
    { word: "jobba", phrase: "[Jobbar] du i natt?", video: "jobba-02063-fras-1.mp4" },
    { word: "jobba", phrase: "Min dotter [jobbar] varannan helg.", video: "jobba-02063-fras-2.mp4" },
    { word: "jobba", phrase: "Varför måste du [jobba] ikväll?", video: "jobba-02063-fras-3.mp4" },
    { word: "jobba", phrase: "Jag [jobbar] inte imorgon.", video: "jobba-02063-fras-4.mp4" },
    { word: "svara", phrase: "Jag fick en [svår] fråga som jag blev helt ställd av, jag visste inte hur jag skulle [svara].", video: "svara-05673-fras-1.mp4" },
    { word: "svara", phrase: "Jag hade ett prov nyss och jag lyckades [svara] på några av frågorna som var med på provet.", video: "svara-05673-fras-2.mp4" },
    { word: "svara", phrase: "Jag kan inte [svara] på det just nu, jag måste få fundera lite först.", video: "svara-05673-fras-3.mp4" },
    { word: "svara", phrase: "Jag måste [svara] i bildtelefonen.", video: "svara-05673-fras-4.mp4" },
    { word: "påverka", phrase: "Finanskrisen kan [påverka] din ekonomi.", video: "paverka-01899-fras-1.mp4" },
    { word: "lyssna", phrase: "Det är verkligen viktigt att vi [lyssnar] på våra mammor.", video: "lyssna-00044-fras-1.mp4" },
    { word: "lyssna", phrase: "Barnen älskar att [lyssna] på musik.", video: "lyssna-00044-fras-2.mp4" },
    { word: "lyssna", phrase: "Snälla, ni måste [lyssna] på läraren.", video: "lyssna-00044-fras-3.mp4" },
    { word: "lyssna", phrase: "[Lyssna]!", video: "lyssna-00044-fras-4.mp4" },
    { word: "sluta", phrase: "Kan du [sluta] skrika!", video: "sluta-00312-fras-1.mp4" },
    { word: "sluta", phrase: "Jag [slutade] skolan när jag var 17 år gammal.", video: "sluta-00312-fras-2.mp4" },
    { word: "sluta", phrase: "När [slutar] du idag?", video: "sluta-00312-fras-3.mp4" },
    { word: "sluta", phrase: "[Sluta] med dina frågor, jag tänker ändå inte berätta.", video: "sluta-00312-fras-4.mp4" },
    { word: "förklara", phrase: "Kan du [förklara] för mig?", video: "forklara-01820-fras-1.mp4" },
    { word: "förklara", phrase: "Jag minns att jag för längesedan hade en bänkkamrat som jag ofta fick [förklara] en massa saker för när vi hade matte.", video: "forklara-01820-fras-2.mp4" },
    { word: "förklara", phrase: "Jag har [förklarat] hur datorer fungerar.", video: "forklara-01820-fras-3.mp4" },
    { word: "räkna", phrase: "Han hade lätt för att [räkna].", video: "rakna-01614-fras-1.mp4" },
    { word: "acceptera", phrase: "Jag [accepterar].", video: "acceptera-09672-fras-1.mp4" },
    { word: "acceptera", phrase: "Du får [acceptera] att man har olika åsikter.", video: "acceptera-09672-fras-2.mp4" },
    { word: "acceptera", phrase: "Okej, jag går med på det. Men på ett villkor och det är att jag får betala mindre.", video: "acceptera-09672-fras-3.mp4" },
    { word: "acceptera", phrase: "Varför kan du inte [acceptera] att vi två är tillsammans?", video: "acceptera-09672-fras-4.mp4" }
  ]
});

// --- yrken.js ---
(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "farger",
  name: "Färger",
  words: [
    { word: "svart", video: "svart-05037-tecken.mp4" },
    { word: "vit", video: "vit-02773-tecken.mp4" },
    { word: "röd", video: "rod-02751-tecken.mp4" },
    { word: "blå", video: "bla-02647-tecken.mp4" },
    { word: "grön", video: "gron-00419-tecken.mp4" },
    { word: "gul", video: "gul-03390-tecken.mp4" },
    { word: "grå", video: "gra-00451-tecken.mp4" },
    { word: "rosa", video: "rosa-01098-tecken.mp4" },
    { word: "brun", video: "brun-03441-tecken.mp4" },
    { word: "lila", video: "lila-03478-tecken.mp4" },
    { word: "orange", video: "orange-01765-tecken.mp4" },
    { word: "turkos", video: "turkos-05426-tecken.mp4" },
    { word: "beige", video: "beige-04499-tecken.mp4" },
    { word: "vinröd", video: "vinrod-19777-tecken.mp4" },
    { word: "aprikos", video: "aprikos-02769-tecken.mp4" },
    { word: "grundfärg", video: "grundfarg-23218-tecken.mp4" },
    { word: "svart vitt", video: "svart-vitt-03903-tecken.mp4" }
  ]
});
