(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "allmant2",
  name: "Allmänt 2",
  words: [
    { word: "kväll", video: "kvall-00514-tecken.mp4" },
    { word: "ung", video: "ung-01099-tecken.mp4" },
    { word: "mat", video: "mat-01266-tecken.mp4" },
    { word: "vänta", video: "vanta-00207-tecken.mp4" },
    { word: "hjälpa", video: "hjalpa-00625-tecken.mp4" },
    { word: "skola", video: "skola-00617-tecken.mp4" },
    { word: "rädd", video: "radd-03447-tecken.mp4" },
    { word: "familj", video: "familj-00773-tecken.mp4" },
    { word: "kort", video: "kort-00602-tecken.mp4" },
    { word: "glad", video: "glad-00165-tecken.mp4" },
    { word: "prata", video: "prata-00835-tecken.mp4" },
    { word: "titta", video: "titta-04101-tecken.mp4" },
    { word: "äta", video: "ata-01267-tecken.mp4" },
    { word: "morgon", video: "morgon-00623-tecken.mp4" },
    { word: "jobba", video: "jobba-02063-tecken.mp4" },
    { word: "flicka", video: "flicka-05777-tecken.mp4" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4" },
    { word: "sluta", video: "sluta-00312-tecken.mp4" },
    { word: "fin", video: "fin-04606-tecken.mp4" },
    { word: "svart", video: "svart-05037-tecken.mp4" },
    { word: "kaffe", video: "kaffe-02042-tecken.mp4" },
    { word: "trött", video: "trott-00966-tecken.mp4" },
    { word: "vit", video: "vit-02773-tecken.mp4" },
    { word: "vacker", video: "vacker-00755-tecken.mp4" },
    { word: "snabb", video: "snabb-00847-tecken.mp4" },
    { word: "sjuk", video: "sjuk-08776-tecken.mp4" },
    { word: "tack", video: "tack-15805-tecken.mp4" },
    { word: "telefon", video: "telefon-03776-tecken.mp4" },
    { word: "syster", video: "syster-03513-tecken.mp4" },
    { word: "ringa", video: "ringa-03775-tecken.mp4" },
    { word: "natt", video: "natt-00516-tecken.mp4" },
    { word: "pojke", video: "pojke-05903-tecken.mp4" },
    { word: "varm", video: "varm-11320-tecken.mp4" },
    { word: "bord", video: "bord-00664-tecken.mp4" },
    { word: "frisk", video: "frisk-00581-tecken.mp4" },
    { word: "bror", video: "bror-03462-tecken.mp4" },
    { word: "sova", video: "sova-03253-tecken.mp4" },
    { word: "dricka", video: "dricka-01377-tecken.mp4" },
    { word: "röd", video: "rod-02751-tecken.mp4" },
    { word: "hund", video: "hund-00222-tecken.mp4" },
    { word: "springa", video: "springa-02208-tecken.mp4" },
    { word: "bröd", video: "brod-00434-tecken.mp4" },
    { word: "mormor", video: "mormor-01938-tecken.mp4" },
    { word: "buss", video: "buss-01176-tecken.mp4" },
    { word: "dator", video: "dator-00304-tecken.mp4" },
    { word: "ledsen", video: "ledsen-00185-tecken.mp4" },
    { word: "arg", video: "arg-01670-tecken.mp4" },
    { word: "mjölk", video: "mjolk-02184-tecken.mp4" },
    { word: "kall", video: "kall-01505-tecken.mp4" },
    { word: "stol", video: "stol-03997-tecken.mp4" }
  ],
  phrases: [
    { word: "kväll", phrase: "Imorgon [kväll] är det fotboll på TV:n.", video: "kvall-00514-fras-1.mp4" },
    { word: "kväll", phrase: "Igår [kväll] var jag ute på promenad med hunden i en timme.", video: "kvall-00514-fras-2.mp4" },
    { word: "kväll", phrase: "Vill du gå ut och äta middag ikväll och sedan gå på bio?", video: "kvall-00514-fras-3.mp4" },
    { word: "mat", phrase: "Vi måste handla [mat], vi ska ju ha fest på lördag.", video: "mat-01266-fras-1.mp4" },
    { word: "mat", phrase: "Vilken [mat] gillar du bäst?", video: "mat-01266-fras-2.mp4" },
    { word: "vänta", phrase: "Jag har [väntat] i tjugo minuter.", video: "vanta-00207-fras-1.mp4" },
    { word: "hjälpa", phrase: "Jag förstår mig inte på deklarationen, kan du [hjälpa] mig?", video: "hjalpa-00625-fras-1.mp4" },
    { word: "hjälpa", phrase: "Min styvfar hjälper alltid mig med att fylla i deklarationen.", video: "hjalpa-00625-fras-2.mp4" },
    { word: "hjälpa", phrase: "Vi mår bra om vi hjälper varandra.", video: "hjalpa-00625-fras-3.mp4" },
    { word: "hjälpa", phrase: "Han vill inte [hjälpa] mig vilket gör mig deppad.", video: "hjalpa-00625-fras-4.mp4" },
    { word: "skola", phrase: "Jag känner inte alls för att flytta till en ny [skola].", video: "skola-00617-fras-1.mp4" },
    { word: "skola", phrase: "Läraren sa till mig att jag måste meddela dem att det inte är någon [skola] på måndag.", video: "skola-00617-fras-2.mp4" },
    { word: "skola", phrase: "Vad är anledningen till att du inte kom till [skolan] i onsdags?", video: "skola-00617-fras-3.mp4" },
    { word: "rädd", phrase: "Hur kommer det sig att du är [rädd] för ormar?", video: "radd-03447-fras-1.mp4" },
    { word: "rädd", phrase: "Jag kan känna mig lite [rädd] om jag promenerar i skogen när det är mörkt ute och det inte finns någon belysning.", video: "radd-03447-fras-2.mp4" },
    { word: "kort", phrase: "Jag la i mina mynt och började köra bilspelet. Plötsligt tog spelet slut och jag fattade ingenting! Jag hade ju knappt hunnit börja köra, tyckte jag.", video: "kort-00602-fras-1.mp4" },
    { word: "kort", phrase: "Jag vet inte om jag kommer orka se hela filmen. Hur lång är den?", video: "kort-00602-fras-2.mp4" },
    { word: "glad", phrase: "Barnen är verkligen [glada] för de ska träffa tomten.", video: "glad-00165-fras-1.mp4" },
    { word: "glad", phrase: "Vissa personer som kan verka [glada] på utsidan är på insidan allt annat än [glad].", video: "glad-00165-fras-2.mp4" },
    { word: "titta", phrase: "[Titta]!", video: "titta-04101-fras-1.mp4" },
    { word: "äta", phrase: "Igår kväll efter mitt hårda träningspass mådde jag inte alls bra, det beror på att jag inte hade ätit och druckit ordentligt innan träningen.", video: "ata-01267-fras-1.mp4" },
    { word: "morgon", phrase: "Jag är ingen [morgonmänniska]. Jag är alltid sur på [morgonen].", video: "morgon-00623-fras-1.mp4" },
    { word: "morgon", phrase: "Var snäll och vakna tidigt imorgon bitti.", video: "morgon-00623-fras-2.mp4" },
    { word: "morgon", phrase: "Min son är alltid [morgonpigg].", video: "morgon-00623-fras-3.mp4" },
    { word: "jobba", phrase: "[Jobbar] du i natt?", video: "jobba-02063-fras-1.mp4" },
    { word: "jobba", phrase: "Min dotter [jobbar] varannan helg.", video: "jobba-02063-fras-2.mp4" },
    { word: "jobba", phrase: "Varför måste du [jobba] ikväll?", video: "jobba-02063-fras-3.mp4" },
    { word: "jobba", phrase: "Jag [jobbar] inte imorgon.", video: "jobba-02063-fras-4.mp4" },
    { word: "lyssna", phrase: "Det är verkligen viktigt att vi [lyssnar] på våra mammor.", video: "lyssna-00044-fras-1.mp4" },
    { word: "lyssna", phrase: "Barnen älskar att [lyssna] på musik.", video: "lyssna-00044-fras-2.mp4" },
    { word: "lyssna", phrase: "Snälla, ni måste [lyssna] på läraren.", video: "lyssna-00044-fras-3.mp4" },
    { word: "lyssna", phrase: "[Lyssna]!", video: "lyssna-00044-fras-4.mp4" },
    { word: "sluta", phrase: "Kan du [sluta] skrika!", video: "sluta-00312-fras-1.mp4" },
    { word: "sluta", phrase: "Jag [slutade] skolan när jag var 17 år gammal.", video: "sluta-00312-fras-2.mp4" },
    { word: "sluta", phrase: "När [slutar] du idag?", video: "sluta-00312-fras-3.mp4" },
    { word: "sluta", phrase: "[Sluta] med dina frågor, jag tänker ändå inte berätta.", video: "sluta-00312-fras-4.mp4" },
    { word: "fin", phrase: "Jag hittade en annons på ett riktigt [fint] hus som jag ville ha så jag åkte dit för att köpa det.", video: "fin-04606-fras-1.mp4" },
    { word: "fin", phrase: "Vilken färg tycker du är [finast]?", video: "fin-04606-fras-2.mp4" },
    { word: "svart", phrase: "Jag hälsade på hos en kompis och jag reagerade på att hen hade en [svart] vägg.", video: "svart-05037-fras-1.mp4" },
    { word: "svart", phrase: "En av mina hundar har [svartvit] päls.", video: "svart-05037-fras-2.mp4" },
    { word: "kaffe", phrase: "Jag dricker [kaffe] varje dag, ungefär 4 - 5 koppar brukar det bli.", video: "kaffe-02042-fras-1.mp4" },
    { word: "kaffe", phrase: "Förut drack jag mycket [kaffe] men nu försöker jag dra ner på det.", video: "kaffe-02042-fras-2.mp4" },
    { word: "trött", phrase: "Är du [trött]?", video: "trott-00966-fras-1.mp4" },
    { word: "trött", phrase: "Idag känner jag mig [trött] i kroppen.", video: "trott-00966-fras-2.mp4" },
    { word: "trött", phrase: "Mina barn har varit ute länge och lekt så nu är de [trötta].", video: "trott-00966-fras-3.mp4" },
    { word: "trött", phrase: "Jag undrar om jag har järnbrist eftersom jag känner mig så [trött] varje dag.", video: "trott-00966-fras-4.mp4" },
    { word: "vit", phrase: "Jag har varit på landet i helgen. Det var så härligt för det var mycket snö och alldeles [vitt].", video: "vit-02773-fras-1.mp4" },
    { word: "vit", phrase: "I Kina använder man [vita] kläder vid begravning.", video: "vit-02773-fras-2.mp4" },
    { word: "vit", phrase: "Du ser så blek ut i ansiktet, hur mår du? Mår du illa?", video: "vit-02773-fras-3.mp4" },
    { word: "snabb", phrase: "Jag körde jättefort.", video: "snabb-00847-fras-1.mp4" },
    { word: "snabb", phrase: "Är du redan klar? Det gick fort!", video: "snabb-00847-fras-2.mp4" },
    { word: "sjuk", phrase: "Min morfar hade inte en enda [sjukdag] fram till pensionen.", video: "sjuk-08776-fras-1.mp4" },
    { word: "sjuk", phrase: "Om du känner dig riktigt [sjuk] är det bäst att du åker till [sjukhuset].", video: "sjuk-08776-fras-2.mp4" },
    { word: "sjuk", phrase: "Hen är inte alls [sjuk].", video: "sjuk-08776-fras-3.mp4" },
    { word: "sjuk", phrase: "Hen är inte [sjuk].", video: "sjuk-08776-fras-4.mp4" },
    { word: "tack", phrase: "Jag har mina föräldrar att [tacka] för att de lärde sig teckenspråk. För [tack] vare det kan jag kommunicera med dem.", video: "tack-15805-fras-1.mp4" },
    { word: "tack", phrase: "Säg [tack] till hen!", video: "tack-15805-fras-2.mp4" },
    { word: "syster", phrase: "Min familj består av mamma, pappa, mig själv och två systrar.", video: "syster-03513-fras-1.mp4" },
    { word: "syster", phrase: "Min [syster] är snäll.", video: "syster-03513-fras-2.mp4" },
    { word: "natt", phrase: "Jag tycker mycket om [natten] eftersom jag är en [nattmänniska].", video: "natt-00516-fras-1.mp4" },
    { word: "natt", phrase: "Var ska du sova imorgon [natt]?", video: "natt-00516-fras-2.mp4" },
    { word: "natt", phrase: "Du får sova här en [natt] men inte mer.", video: "natt-00516-fras-3.mp4" },
    { word: "natt", phrase: "På [natten] sover jag.", video: "natt-00516-fras-4.mp4" },
    { word: "varm", phrase: "Akta dig, spisen är väldigt [varm].", video: "varm-11320-fras-1.mp4" },
    { word: "varm", phrase: "Det är kallt ute idag, så det är bäst att ha på sig [varma] kläder.", video: "varm-11320-fras-2.mp4" },
    { word: "bord", phrase: "Nu ska jag leta efter ett litet [bord] till balkongen.", video: "bord-00664-fras-1.mp4" },
    { word: "frisk", phrase: "Jag har varit sjuk i två veckor men nu är jag [frisk].", video: "frisk-00581-fras-1.mp4" },
    { word: "frisk", phrase: "Du ser inte riktigt [frisk] ut, är du sjuk?", video: "frisk-00581-fras-2.mp4" },
    { word: "sova", phrase: "Jag sov bra igår för det var ganska svalt i rummet.", video: "sova-03253-fras-1.mp4" },
    { word: "sova", phrase: "Sov nu!", video: "sova-03253-fras-2.mp4" },
    { word: "dricka", phrase: "Vi människor måste [dricka] ungefär två liter om dagen.", video: "dricka-01377-fras-1.mp4" },
    { word: "dricka", phrase: "Vad vill du [dricka]? Vatten, saft eller läsk?", video: "dricka-01377-fras-2.mp4" },
    { word: "dricka", phrase: "Alla barn var väldigt törstiga och drack massor med vatten.", video: "dricka-01377-fras-3.mp4" },
    { word: "dricka", phrase: "Va, drack alla vatten?", video: "dricka-01377-fras-4.mp4" },
    { word: "röd", phrase: "Nu finns det ett nytt slags te som kallas för rött te.", video: "rod-02751-fras-1.mp4" },
    { word: "röd", phrase: "Jag har en [röd] bil, en Golf.", video: "rod-02751-fras-2.mp4" },
    { word: "hund", phrase: "Mina barn tjatar om att få en [hund] men det kan de inte få för jag är allergisk.", video: "hund-00222-fras-1.mp4" },
    { word: "hund", phrase: "Min förra [hund] hette Mia.", video: "hund-00222-fras-2.mp4" },
    { word: "hund", phrase: "På torsdagarna går jag alltid till [hundparken] med min [hund].", video: "hund-00222-fras-3.mp4" },
    { word: "bröd", phrase: "Nu ska jag baka [bröd]. Smaskens!", video: "brod-00434-fras-1.mp4" },
    { word: "bröd", phrase: "Vad är skillnaden på surdegsbröd och vanligt [bröd]?", video: "brod-00434-fras-2.mp4" },
    { word: "bröd", phrase: "Det finns olika sorters [bröd]; limpa, baguette med mera.", video: "brod-00434-fras-3.mp4" },
    { word: "mormor", phrase: "Min [mormor] är proffs på att baka bullar och bröd. De är alltid goda.", video: "mormor-01938-fras-1.mp4" },
    { word: "dator", phrase: "Jag behöver en ny [dator].", video: "dator-00304-fras-1.mp4" },
    { word: "dator", phrase: "Vilken [dator] är bäst? Är det en PC eller en Mac?", video: "dator-00304-fras-2.mp4" },
    { word: "dator", phrase: "Är du duktig på att installera program i [datorn]?", video: "dator-00304-fras-3.mp4" },
    { word: "ledsen", phrase: "Alla kan vara ledsna ibland.", video: "ledsen-00185-fras-1.mp4" },
    { word: "ledsen", phrase: "Min hund blir lätt [ledsen] om jag inte busar med den.", video: "ledsen-00185-fras-2.mp4" },
    { word: "arg", phrase: "Min kompis är [arg] på mig på grund av att jag av misstag råkade ta hens jacka.", video: "arg-01670-fras-1.mp4" },
    { word: "arg", phrase: "I morse var hen glad men senare på dagen var hen [arg], jag förstår inte varför?", video: "arg-01670-fras-2.mp4" },
    { word: "kall", phrase: "Det är ofta väldigt [kallt] i februari och då måste man klä sig varmt.", video: "kall-01505-fras-1.mp4" },
    { word: "kall", phrase: "Om det är [kallt] ute och du har för lite kläder på dig, så kan det leda till att du blir sjuk.", video: "kall-01505-fras-2.mp4" }
  ]
});
