(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "allmant1",
  name: "Allmänt 1",
  words: [
    { word: "inte", video: "inte-00646-tecken.mp4" },
    { word: "den", video: "den-03690-tecken.mp4" },
    { word: "han", video: "han-00479-tecken.mp4" },
    { word: "var", video: "var-02847-tecken.mp4" },
    { word: "de", video: "de-20126-tecken.mp4" },
    { word: "jag", video: "jag-02798-tecken.mp4" },
    { word: "kan", video: "kan-00022-tecken.mp4" },
    { word: "man", video: "man-05036-tecken.mp4" },
    { word: "vi", video: "vi-05491-tecken.mp4" },
    { word: "hon", video: "hon-05389-tecken.mp4" },
    { word: "när", video: "nar-03954-tecken.mp4" },
    { word: "ska", video: "ska-02238-tecken.mp4" },
    { word: "vill", video: "vill-00167-tecken.mp4" },
    { word: "du", video: "du-02817-tecken.mp4" },
    { word: "hur", video: "hur-04569-tecken.mp4" },
    { word: "vad", video: "vad-00644-tecken.mp4" },
    { word: "här", video: "har-02866-tecken.mp4" },
    { word: "dag", video: "dag-00632-tecken.mp4" },
    { word: "bra", video: "bra-12077-tecken.mp4" },
    { word: "stor", video: "stor-00607-tecken.mp4" },
    { word: "se", video: "se-04104-tecken.mp4" },
    { word: "tid", video: "tid-00268-tecken.mp4" },
    { word: "ny", video: "ny-09120-tecken.mp4" },
    { word: "gå", video: "ga-04238-tecken.mp4" },
    { word: "barn", video: "barn-00257-tecken.mp4" },
    { word: "vår", video: "var-00186-tecken.mp4" },
    { word: "ja", video: "ja-09027-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "komma", video: "komma-09684-tecken.mp4" },
    { word: "liten", video: "liten-00604-tecken.mp4" },
    { word: "nej", video: "nej-00274-tecken.mp4" },
    { word: "arbete", video: "arbete-00562-tecken.mp4" },
    { word: "lång", video: "lang-01115-tecken.mp4" },
    { word: "gammal", video: "gammal-00789-tecken.mp4" },
    { word: "vecka", video: "vecka-03700-tecken.mp4" },
    { word: "kvinna", video: "kvinna-01106-tecken.mp4" },
    { word: "mamma", video: "mamma-00188-tecken.mp4" },
    { word: "tala", video: "tala-02696-tecken.mp4" },
    { word: "börja", video: "borja-03852-tecken.mp4" },
    { word: "hus", video: "hus-00696-tecken.mp4" },
    { word: "bok", video: "bok-00610-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4" },
    { word: "köpa", video: "kopa-01301-tecken.mp4" },
    { word: "vem", video: "vem-00123-tecken.mp4" },
    { word: "vatten", video: "vatten-00132-tecken.mp4" },
    { word: "stark", video: "stark-02278-tecken.mp4" },
    { word: "höra", video: "hora-02663-tecken.mp4" },
    { word: "förstå", video: "forsta-02570-tecken.mp4" },
    { word: "bil", video: "bil-02158-tecken.mp4" },
    { word: "hem", video: "hem-00498-tecken.mp4" }
  ],
  phrases: [
    { word: "inte", phrase: "Många tror att jag är gift men det är faktiskt [inte] så.", video: "inte-00646-fras-1.mp4" },
    { word: "inte", phrase: "Jag klarar mig [inte] utan min mobil.", video: "inte-00646-fras-2.mp4" },
    { word: "inte", phrase: "Du lyssnar [inte].", video: "inte-00646-fras-3.mp4" },
    { word: "inte", phrase: "Kalle är [inte] godkänd.", video: "inte-00646-fras-4.mp4" },
    { word: "han", phrase: "Kommer hen imorgon?", video: "han-00479-fras-1.mp4" },
    { word: "han", phrase: "Hen är väldigt snäll.", video: "han-00479-fras-3.mp4" },
    { word: "han", phrase: "Hen är från Norrland.", video: "han-00479-fras-4.mp4" },
    { word: "var", phrase: "Jag vet inte [var] Anna är.", video: "var-02847-fras-1.mp4" },
    { word: "var", phrase: "[Var] någonstans hemma har du glömt nyckeln?", video: "var-02847-fras-2.mp4" },
    { word: "var", phrase: "[Var] handlar du mat?", video: "var-02847-fras-3.mp4" },
    { word: "jag", phrase: "[Jag] är inte hemma ikväll.", video: "jag-02798-fras-1.mp4" },
    { word: "jag", phrase: "[Jag] är inte godkänd.", video: "jag-02798-fras-2.mp4" },
    { word: "kan", phrase: "Jag [kan] köra båt.", video: "kan-00022-fras-1.mp4" },
    { word: "kan", phrase: "I morgon [kan] jag hjälpa dig.", video: "kan-00022-fras-2.mp4" },
    { word: "kan", phrase: "Jag [kan] fixa middagen i kväll.", video: "kan-00022-fras-3.mp4" },
    { word: "kan", phrase: "Sven [kan] inte simma.", video: "kan-00022-fras-4.mp4" },
    { word: "man", phrase: "Min systers [man] vet inte om att jag har fyra barn.", video: "man-05036-fras-1.mp4" },
    { word: "när", phrase: "Jag vet inte [när] filmen startar.", video: "nar-03954-fras-1.mp4" },
    { word: "när", phrase: "[När] kommer min bror hem ikväll?", video: "nar-03954-fras-2.mp4" },
    { word: "när", phrase: "[När] ska du träna?", video: "nar-03954-fras-3.mp4" },
    { word: "ska", phrase: "Jag [ska] snart klippa mig.", video: "ska-02238-fras-1.mp4" },
    { word: "ska", phrase: "Anna [ska] köpa ett jättestort och fint hus.", video: "ska-02238-fras-2.mp4" },
    { word: "ska", phrase: "Imorgon [ska] jag på dejt, jag känner mig nervös inför det.", video: "ska-02238-fras-3.mp4" },
    { word: "ska", phrase: "[Ska] du spela golf idag?", video: "ska-02238-fras-4.mp4" },
    { word: "vill", phrase: "Jag [vill] åka jorden runt.", video: "vill-00167-fras-1.mp4" },
    { word: "vill", phrase: "Jag skulle vilja åka till Dövas hus. Det verkar hända roliga saker där.", video: "vill-00167-fras-2.mp4" },
    { word: "vill", phrase: "Jag [vill] att du går nu.", video: "vill-00167-fras-3.mp4" },
    { word: "du", phrase: "Jag har inte gjort det. Det var [du] som skulle göra det.", video: "du-02817-fras-1.mp4" },
    { word: "du", phrase: "Är [du] sjuk?", video: "du-02817-fras-2.mp4" },
    { word: "du", phrase: "Har [du] feber?", video: "du-02817-fras-3.mp4" },
    { word: "du", phrase: "[Du] har glömt att meddela mig.", video: "du-02817-fras-4.mp4" },
    { word: "hur", phrase: "[Hur] kom du hit?", video: "hur-04569-fras-1.mp4" },
    { word: "hur", phrase: "[Hur] mycket vill du ha?", video: "hur-04569-fras-2.mp4" },
    { word: "hur", phrase: "[Hur] lyckades du med det?", video: "hur-04569-fras-3.mp4" },
    { word: "hur", phrase: "[Hur] lyckades du komma in på puben trots att du är under 18?", video: "hur-04569-fras-4.mp4" },
    { word: "vad", phrase: "Vilken sport är du intresserad av?", video: "vad-00644-fras-1.mp4" },
    { word: "vad", phrase: "[Vad] har du för hobby eller intresse?", video: "vad-00644-fras-2.mp4" },
    { word: "vad", phrase: "[Vad] brukar du göra på fredagarna?", video: "vad-00644-fras-3.mp4" },
    { word: "vad", phrase: "[Vad] ska du göra imorgon kväll?", video: "vad-00644-fras-4.mp4" },
    { word: "här", phrase: "Är det hen som är nyanställd [här] på jobbet?", video: "har-02866-fras-1.mp4" },
    { word: "dag", phrase: "Jobba på [dagen] är inget för mig. Jag jobbar hellre på natten.", video: "dag-00632-fras-1.mp4" },
    { word: "dag", phrase: "Igår var verkligen inte min [dag] på grund av allt som hände, jag tappade min nyckel och plånbok plus att jag kom försent till jobbet.", video: "dag-00632-fras-2.mp4" },
    { word: "stor", phrase: "Har du besökt vår kompis nya hus? Huset är verkligen [stort].", video: "stor-00607-fras-1.mp4" },
    { word: "stor", phrase: "Mina nya säng är bredare än min gamla, det är så skönt!", video: "stor-00607-fras-2.mp4" },
    { word: "se", phrase: "Jag har inte [sett] filmen.", video: "se-04104-fras-1.mp4" },
    { word: "se", phrase: "Det var roligt att [se] dig!", video: "se-04104-fras-2.mp4" },
    { word: "se", phrase: "Vad roligt att du såg mig på TV.", video: "se-04104-fras-3.mp4" },
    { word: "tid", phrase: "Under min [tid] på gymnasiet så festade jag mycket.", video: "tid-00268-fras-1.mp4" },
    { word: "tid", phrase: "På min [tid] fanns det inga mobiltelefoner.", video: "tid-00268-fras-2.mp4" },
    { word: "gå", phrase: "Om vi [går] i minst en halvtimme blir vi piggare.", video: "ga-04238-fras-1.mp4" },
    { word: "gå", phrase: "[Gå] nu!", video: "ga-04238-fras-2.mp4" },
    { word: "barn", phrase: "Mina [barn] är helt sålda på TV-spel. De måste spela varje dag.", video: "barn-00257-fras-1.mp4" },
    { word: "barn", phrase: "När sommarlovet är slut är [barnen] fulla av iver över att komma tillbaka till skolan.", video: "barn-00257-fras-2.mp4" },
    { word: "barn", phrase: "Jag har tre [barn].", video: "barn-00257-fras-3.mp4" },
    { word: "vår", phrase: "[Vårt] beslut står fast. Det går inte att ändra.", video: "var-00186-fras-1.mp4" },
    { word: "vår", phrase: "[Vår] gymnasietid var helt skruvad.", video: "var-00186-fras-2.mp4" },
    { word: "liten", phrase: "Min allra första lägenhet var pytteliten.", video: "liten-00604-fras-1.mp4" },
    { word: "liten", phrase: "Har du sett hennes kattunge? Den är pytteliten.", video: "liten-00604-fras-2.mp4" },
    { word: "liten", phrase: "Morfar har en [liten] bil.", video: "liten-00604-fras-3.mp4" },
    { word: "nej", phrase: "Neej, jag har inte sagt någonting till mamma.", video: "nej-00274-fras-1.mp4" },
    { word: "lång", phrase: "Alla i min familj är [långa]. Det är bara jag som är kort.", video: "lang-01115-fras-1.mp4" },
    { word: "lång", phrase: "Alla basketspelare är [långa].", video: "lang-01115-fras-2.mp4" },
    { word: "lång", phrase: "Hur [lång] är en flicka som är 15 år? 15 cm, 150 cm eller 15 meter?", video: "lang-01115-fras-3.mp4" },
    { word: "gammal", phrase: "Min jacka är så [gammal] att jag måste köpa en ny.", video: "gammal-00789-fras-1.mp4" },
    { word: "gammal", phrase: "Jag har ofta [gammal] mjölk i kylskåpet.", video: "gammal-00789-fras-2.mp4" },
    { word: "gammal", phrase: "Mitt köksbord är [gammalt]. Det är från 1800-talet.", video: "gammal-00789-fras-3.mp4" },
    { word: "vecka", phrase: "Vilken [vecka] är det nu?", video: "vecka-03700-fras-1.mp4" },
    { word: "vecka", phrase: "Jag är arbetslös i bara en [vecka].", video: "vecka-03700-fras-2.mp4" },
    { word: "vecka", phrase: "Jag har inte tränat på åtta veckor på grund av min axelskada.", video: "vecka-03700-fras-3.mp4" },
    { word: "vecka", phrase: "Hur många dagar har en [vecka]?", video: "vecka-03700-fras-4.mp4" },
    { word: "kvinna", phrase: "Man brukar säga att när en tjej har fyllt 30 har hon blivit [kvinna].", video: "kvinna-01106-fras-1.mp4" },
    { word: "mamma", phrase: "[Mamma] är alltid bäst!", video: "mamma-00188-fras-1.mp4" },
    { word: "tala", phrase: "När jag var liten fick jag öva talet i skolan. Jag minns att jag avskydde talövningarna.", video: "tala-02696-fras-1.mp4" },
    { word: "börja", phrase: "Teatern [börjar] klockan sju.", video: "borja-03852-fras-1.mp4" },
    { word: "börja", phrase: "Vi [börjar] styrelsemötet när alla har kommit.", video: "borja-03852-fras-2.mp4" },
    { word: "börja", phrase: "Starta nu!", video: "borja-03852-fras-3.mp4" },
    { word: "börja", phrase: "Mötet skulle starta kl 13.00 men är nu framflyttat till kl. 15.00.", video: "borja-03852-fras-4.mp4" },
    { word: "hus", phrase: "När jag gick längs med stranden fick jag syn på ett jättestort [hus]. Då började jag fundera över vem som kunde tänkas bo där.", video: "hus-00696-fras-1.mp4" },
    { word: "bok", phrase: "När jag var liten läste jag aldrig en [bok], nu däremot läser jag många böcker.", video: "bok-00610-fras-1.mp4" },
    { word: "bok", phrase: "[Boken] var stor och tjock.", video: "bok-00610-fras-2.mp4" },
    { word: "bok", phrase: "Hon ögnade igenom [boken].", video: "bok-00610-fras-3.mp4" },
    { word: "pappa", phrase: "Är han din [pappa]?", video: "pappa-02557-fras-1.mp4" },
    { word: "pappa", phrase: "[Pappa] är väldigt lång.", video: "pappa-02557-fras-2.mp4" },
    { word: "köpa", phrase: "Jag är sugen på att [köpa] en ny TV.", video: "kopa-01301-fras-1.mp4" },
    { word: "köpa", phrase: "Du kan [köpa] en bok men du kan aldrig [köpa] kunskap.", video: "kopa-01301-fras-2.mp4" },
    { word: "vem", phrase: "[Vem] har tagit mina strumpor?", video: "vem-00123-fras-1.mp4" },
    { word: "vem", phrase: "Tanten som står där borta känner jag igen. [Vem] kan det vara?", video: "vem-00123-fras-2.mp4" },
    { word: "vem", phrase: "Nummerpresentatören är till för att man ska kunna se [vem] som har ringt.", video: "vem-00123-fras-3.mp4" },
    { word: "stark", phrase: "Myran är världens [starkaste] djur.", video: "stark-02278-fras-1.mp4" },
    { word: "förstå", phrase: "Förstod du det jag nyss förklarade?", video: "forsta-02570-fras-1.mp4" },
    { word: "bil", phrase: "Jag har köpt en ny [bil].", video: "bil-02158-fras-1.mp4" },
    { word: "bil", phrase: "Min [bil] är svart.", video: "bil-02158-fras-2.mp4" },
    { word: "bil", phrase: "Jag har två stycken röda [bilar].", video: "bil-02158-fras-3.mp4" },
    { word: "hem", phrase: "När jag bodde i USA flyttade jag runt bland mina kompisar i många år. Nu är det skönt att ha ett eget [hem] här [hemma].", video: "hem-00498-fras-1.mp4" },
    { word: "hem", phrase: "Kom [hem] till mig för jag har öppet hus mellan fem och sju.", video: "hem-00498-fras-2.mp4" }
  ]
});
