(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "bokstavering1",
  name: "Bokstavering 1",
  words: [
    { word: "i", video: "i-04473-tecken.mp4", gloss: "I@b" },
    { word: "att", video: "att-08812-tecken.mp4", gloss: "ATT@b" },
    { word: "av", video: "av-08815-tecken.mp4", gloss: "AV@b" },
    { word: "han", video: "han-00812-tecken.mp4", gloss: "HAN@b" },
    { word: "var", video: "var-13524-tecken.mp4", gloss: "VAR@b" },
    { word: "hon", video: "hon-05389-tecken.mp4", gloss: "HON@b" },
    { word: "vara", video: "vara-09261-tecken.mp4", gloss: "VARA@b" },
    { word: "år", video: "ar-09291-tecken.mp4", gloss: "ÅR@b" },
    { word: "få", video: "fa-07345-tecken.mp4", gloss: "FÅ@b" },
    { word: "än", video: "an-09287-tecken.mp4", gloss: "ÄN@b" },
    { word: "kronor", video: "kronor-09044-tecken.mp4", gloss: "KR@b" },
    { word: "alla", video: "alla-08804-tecken.mp4", gloss: "ALLA@b" },
    { word: "varit", video: "varit-18168-tecken.mp4", gloss: "VARIT@b" },
    { word: "då", video: "da-04724-tecken.mp4", gloss: "DÅ@b" },
    { word: "vet", video: "vet-12741-tecken.mp4", gloss: "VET@b" },
    { word: "åt", video: "at-20598-tecken.mp4", gloss: "ÅT@b" },
    { word: "tid", video: "tid-12742-tecken.mp4", gloss: "TID@b" },
    { word: "väl", video: "val-05515-tecken.mp4", gloss: "VÄL@b" },
    { word: "usa", video: "usa-09249-tecken.mp4", gloss: "USA@b@en" },
    { word: "bör", video: "bor-10535-tecken.mp4", gloss: "BÖR@b" },
    { word: "par", video: "par-14570-tecken.mp4", gloss: "PAR@b" },
    { word: "per", video: "per-19723-tecken.mp4" },
    { word: "nej", video: "nej-08300-tecken.mp4", gloss: "NEJ@b" },
    { word: "exempel", video: "exempel-09418-tecken.mp4", gloss: "EX@b" },
    { word: "sex", video: "sex-06075-tecken.mp4" },
    { word: "cirka", video: "cirka-19495-tecken.mp4" },
    { word: "ens", video: "ens-17649-tecken.mp4", gloss: "ENS@b" },
    { word: "tv", video: "tv-05428-tecken.mp4", gloss: "TV@b" },
    { word: "alls", video: "alls-17582-tecken.mp4", gloss: "ALLS@b" },
    { word: "mina", video: "mina-24957-tecken.mp4", gloss: "MINA@b" },
    { word: "vore", video: "vore-16038-tecken.mp4" },
    { word: "fall", video: "fall-22739-tecken.mp4", gloss: "FALL@b" },
    { word: "maj", video: "maj-09098-tecken.mp4", gloss: "MAJ@b" },
    { word: "jobb", video: "jobb-04920-tecken.mp4", gloss: "JOBB@b" },
    { word: "bok", video: "bok-15763-tecken.mp4" },
    { word: "malmö", video: "malmo-06398-tecken.mp4", gloss: "MALMÖ@b@en" },
    { word: "annars", video: "annars-04624-tecken.mp4", gloss: "ANNARS@b" },
    { word: "hel", video: "hel-17313-tecken.mp4", gloss: "HEL@b" },
    { word: "mars", video: "mars-09097-tecken.mp4", gloss: "MARS@b" },
    { word: "juni", video: "juni-08253-tecken.mp4", gloss: "JUNI@b" },
    { word: "tur", video: "tur-04221-tecken.mp4", gloss: "TUR@b" },
    { word: "september", video: "september-09196-tecken.mp4", gloss: "SEPT@b" },
    { word: "december", video: "december-08853-tecken.mp4", gloss: "DEC@b" },
    { word: "inne", video: "inne-14280-tecken.mp4" },
    { word: "februari", video: "februari-08892-tecken.mp4", gloss: "FEB@b" },
    { word: "gott", video: "gott-12746-tecken.mp4" },
    { word: "augusti", video: "augusti-08814-tecken.mp4", gloss: "AUG@b" },
    { word: "maria", video: "maria-07001-tecken.mp4" },
    { word: "emu", video: "emu-24709-tecken.mp4" },
    { word: "vm", video: "vm-08678-tecken.mp4", gloss: "VM@b" }
  ]
});
