(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "datum2",
  name: "Tid & datum 2",
  words: [
    { word: "fredagar", video: "fredagar-17732-tecken.mp4" },
    { word: "måndagar", video: "mandagar-17727-tecken.mp4" },
    { word: "onsdagar", video: "onsdagar-17729-tecken.mp4" },
    { word: "torsdagar", video: "torsdagar-17730-tecken.mp4" },
    { word: "årstid", video: "arstid-05584-tecken.mp4" },
    { word: "tisdagar", video: "tisdagar-17728-tecken.mp4" },
    { word: "kalender", video: "kalender-17114-tecken.mp4" },
    { word: "weekend", video: "weekend-17856-tecken.mp4" },
    { word: "veckodag", video: "veckodag-08632-tecken.mp4" },
    { word: "veckodagar", video: "veckodagar-17725-tecken.mp4" },
    { word: "skottår", video: "skottar-12019-tecken.mp4" },
    { word: "mitt på dagen", video: "mitt-pa-dagen-00265-tecken.mp4" },
    { word: "hela dagen", video: "hela-dagen-01196-tecken.mp4" },
    { word: "i dag", video: "i-dag-04485-tecken.mp4" },
    { word: "i morse", video: "i-morse-04892-tecken.mp4" },
    { word: "kvart i", video: "kvart-i-08219-tecken.mp4" },
    { word: "i kväll", video: "i-kvall-10033-tecken.mp4" },
    { word: "klockan två", video: "klockan-tva-01060-tecken.mp4" },
    { word: "klockan tre", video: "klockan-tre-01064-tecken.mp4" },
    { word: "klockan fyra", video: "klockan-fyra-01067-tecken.mp4" },
    { word: "klockan fem", video: "klockan-fem-01088-tecken.mp4" },
    { word: "ungefär klockan två", video: "ungefar-klockan-tva-01118-tecken.mp4" },
    { word: "ungefär klockan tre", video: "ungefar-klockan-tre-01119-tecken.mp4" },
    { word: "för ett år sedan", video: "for-ett-ar-sedan-01576-tecken.mp4" },
    { word: "ungefär klockan ett", video: "ungefar-klockan-ett-01612-tecken.mp4" },
    { word: "ungefär klockan fyra", video: "ungefar-klockan-fyra-01616-tecken.mp4" },
    { word: "ungefär klockan fem", video: "ungefar-klockan-fem-01617-tecken.mp4" },
    { word: "ungefär klockan sex", video: "ungefar-klockan-sex-01623-tecken.mp4" },
    { word: "ungefär klockan sju", video: "ungefar-klockan-sju-01626-tecken.mp4" },
    { word: "ungefär klockan åtta", video: "ungefar-klockan-atta-01629-tecken.mp4" },
    { word: "ungefär klockan nio", video: "ungefar-klockan-nio-01630-tecken.mp4" },
    { word: "klockan ett", video: "klockan-ett-02851-tecken.mp4" },
    { word: "klockan sex", video: "klockan-sex-01193-tecken.mp4" },
    { word: "klockan sju", video: "klockan-sju-01246-tecken.mp4" },
    { word: "klockan åtta", video: "klockan-atta-01367-tecken.mp4" },
    { word: "vårdagsjämning", video: "vardagsjamning-15580-tecken.mp4" },
    { word: "höstdagsjämning", video: "hostdagsjamning-15581-tecken.mp4" },
    { word: "en dag", video: "en-dag-17632-tecken.mp4" },
    { word: "klockan nio", video: "klockan-nio-17681-tecken.mp4" },
    { word: "i lördags", video: "i-lordags-17718-tecken.mp4" },
    { word: "i söndags", video: "i-sondags-17719-tecken.mp4" },
    { word: "i måndags", video: "i-mandags-17720-tecken.mp4" },
    { word: "i tisdags", video: "i-tisdags-17721-tecken.mp4" },
    { word: "i onsdags", video: "i-onsdags-17722-tecken.mp4" },
    { word: "i torsdags", video: "i-torsdags-17723-tecken.mp4" },
    { word: "i fredags", video: "i-fredags-17724-tecken.mp4" },
    { word: "nästa dag", video: "nasta-dag-17738-tecken.mp4" },
    { word: "i höstas", video: "i-hostas-17788-tecken.mp4" },
    { word: "i våras", video: "i-varas-19407-tecken.mp4" },
    { word: "i vintras", video: "i-vintras-19408-tecken.mp4" }
  ],
  phrases: [
    { word: "fredagar", phrase: "Min favorit veckodag är [fredagar].", video: "fredagar-17732-fras-1.mp4" },
    { word: "måndagar", phrase: "Jag har väldigt svårt att vakna och att kliva upp på måndagsmorgnar.", video: "mandagar-17727-fras-1.mp4" },
    { word: "onsdagar", phrase: "Det är vår tradition att alltid ha grillkväll på [onsdagar].", video: "onsdagar-17729-fras-1.mp4" },
    { word: "onsdagar", phrase: "På [onsdagar] visas min favoritserie på TV.", video: "onsdagar-17729-fras-2.mp4" },
    { word: "torsdagar", phrase: "I min familj brukar vi äta ärtsoppa med fläsk och pannkaka på [torsdagar].", video: "torsdagar-17730-fras-1.mp4" },
    { word: "weekend", phrase: "Jag brukar segla i skärgården fredag till söndag.", video: "weekend-17856-fras-1.mp4" },
    { word: "weekend", phrase: "Jag brukar vara i Örebro fredag till söndag.", video: "weekend-17856-fras-2.mp4" },
    { word: "veckodag", phrase: "Idag är det måndag. Vilken dag är det imorgon?", video: "veckodag-08632-fras-1.mp4" },
    { word: "veckodag", phrase: "Den nionde januari är en måndag. Vilken dag är den trettonde januari?", video: "veckodag-08632-fras-2.mp4" },
    { word: "mitt på dagen", phrase: "Kan vi träffas kl 10 eller [mitt på dagen]?", video: "mitt-pa-dagen-00265-fras-1.mp4" },
    { word: "mitt på dagen", phrase: "Solen står oftast högst [mitt på dagen].", video: "mitt-pa-dagen-00265-fras-2.mp4" },
    { word: "hela dagen", phrase: "I går regnade det [hela dagen]. Trist!", video: "hela-dagen-01196-fras-1.mp4" },
    { word: "hela dagen", phrase: "Om du inte har ätit på [hela dagen], finns det risk för att du blir yr för att du inte fått i dig tillräckligt med energi.", video: "hela-dagen-01196-fras-2.mp4" },
    { word: "hela dagen", phrase: "Gårdagens föreläsning pågick [hela dagen].", video: "hela-dagen-01196-fras-3.mp4" },
    { word: "hela dagen", phrase: "De låg [hela dagen] och solade.", video: "hela-dagen-01196-fras-4.mp4" },
    { word: "i dag", phrase: "Äntligen! Idag är det fredag.", video: "i-dag-04485-fras-1.mp4" },
    { word: "i dag", phrase: "På sjuttiotalet skulle jeansen vara utsvängda och det är modernt nu igen.", video: "i-dag-04485-fras-2.mp4" },
    { word: "i morse", phrase: "Tvättade du kläderna [i morse]?", video: "i-morse-04892-fras-1.mp4" },
    { word: "i morse", phrase: "Jag glömde ta med min matlåda [i morse].", video: "i-morse-04892-fras-2.mp4" },
    { word: "i kväll", phrase: "Jag kan inte laga mat ikväll.", video: "i-kvall-10033-fras-1.mp4" },
    { word: "i kväll", phrase: "Min bror kommer hem klockan åtta ikväll.", video: "i-kvall-10033-fras-2.mp4" },
    { word: "i kväll", phrase: "Varför är du hemma ikväll?", video: "i-kvall-10033-fras-3.mp4" },
    { word: "i kväll", phrase: "Är du inte hemma ikväll?", video: "i-kvall-10033-fras-4.mp4" },
    { word: "klockan två", phrase: "Jag måste gå nu för jag ska träffa en kompis [klockan två].", video: "klockan-tva-01060-fras-1.mp4" },
    { word: "klockan tre", phrase: "Skynda dig iväg nu, ditt tåg går ju [klockan tre]!", video: "klockan-tre-01064-fras-1.mp4" },
    { word: "klockan fyra", phrase: "Jag har bokat en festlokal till barnen. Vi börjar [klockan fyra] och håller på till åtta.", video: "klockan-fyra-01067-fras-1.mp4" },
    { word: "klockan fyra", phrase: "Idag [klockan fyra] på eftermiddagen ska jag till läkaren.", video: "klockan-fyra-01067-fras-2.mp4" },
    { word: "klockan fem", phrase: "Alt 1: Kan vi träffas klockan tre idag istället för fem, för jag kommer att sluta lite tidigare? Alt 2: Vi skulle ju träffas [klockan fem] idag. Kan vi ändra till klockan tre istället för jag kommer att sluta lite tidigare?", video: "klockan-fem-01088-fras-1.mp4" },
    { word: "klockan fem", phrase: "Peter slutar aldrig halv fem. Han går alltid hem efter [klockan fem]", video: "klockan-fem-01088-fras-2.mp4" },
    { word: "klockan fem", phrase: "Idag ska jag göra anställd intervju på [klockan fem].", video: "klockan-fem-01088-fras-3.mp4" },
    { word: "ungefär klockan två", phrase: "Kan vi träffas nu på lördag någon gång mellan två och tre.", video: "ungefar-klockan-tva-01118-fras-1.mp4" },
    { word: "ungefär klockan två", phrase: "Jag tror att frisörsalongen stänger vid två tiden.", video: "ungefar-klockan-tva-01118-fras-2.mp4" },
    { word: "ungefär klockan tre", phrase: "Kan du hämta barnen vid tre tiden?", video: "ungefar-klockan-tre-01119-fras-1.mp4" },
    { word: "ungefär klockan tre", phrase: "Nu på fredag vid tretiden ska jag hälsa på en kompis.", video: "ungefar-klockan-tre-01119-fras-2.mp4" },
    { word: "ungefär klockan tre", phrase: "Nu på fredag slutar jag tidigt, redan vid tre tiden.", video: "ungefar-klockan-tre-01119-fras-3.mp4" },
    { word: "för ett år sedan", phrase: "[För ett år sedan] vann jag tusen kronor på triss.", video: "for-ett-ar-sedan-01576-fras-1.mp4" },
    { word: "för ett år sedan", phrase: "[För ett år sedan] fick vi riktigt mycket snö medan vi nästan inte har fått någon snö alls iår. Nu hoppas jag att det blir bättre nästa år.", video: "for-ett-ar-sedan-01576-fras-2.mp4" },
    { word: "för ett år sedan", phrase: "[För ett år sedan] blev Göteborg svenska mästare i fotboll", video: "for-ett-ar-sedan-01576-fras-3.mp4" },
    { word: "för ett år sedan", phrase: "Ifjol backpackande jag i Östeuropa.", video: "for-ett-ar-sedan-01576-fras-4.mp4" },
    { word: "ungefär klockan ett", phrase: "Jag vet inte när teatern börjar på lördag. Jag tror att det är omkring klockan ett men jag är inte säker.", video: "ungefar-klockan-ett-01612-fras-1.mp4" },
    { word: "ungefär klockan ett", phrase: "Kan du gå och fika i morgon vid ett tiden?", video: "ungefar-klockan-ett-01612-fras-2.mp4" },
    { word: "ungefär klockan fyra", phrase: "Imorgon ska vi ha ett möte som börjar klockan ett och slutar [ungefär klockan fyra].", video: "ungefar-klockan-fyra-01616-fras-1.mp4" },
    { word: "ungefär klockan fyra", phrase: "De som jobbar på Posten stiger alltid upp tidigt på morgonen vid fyra-, femtiden Men de slutar redan vid tolv-, ettiden.", video: "ungefar-klockan-fyra-01616-fras-2.mp4" },
    { word: "ungefär klockan fem", phrase: "Jag ska få en dator levererad hem till mig idag. Den kommer vid femtiden så jag måste sticka härifrån klockan fyra.", video: "ungefar-klockan-fem-01617-fras-1.mp4" },
    { word: "ungefär klockan fem", phrase: "Igår när jag var ute och promenerade var det så fint väder ända fram till klockan var ungefär fem. Då kom det en störtskur och jag blev alldeles genomblöt.", video: "ungefar-klockan-fem-01617-fras-2.mp4" },
    { word: "ungefär klockan sex", phrase: "Jag brukar få tidningen vid sextiden på morgonen.", video: "ungefar-klockan-sex-01623-fras-1.mp4" },
    { word: "ungefär klockan sju", phrase: "Jag ska träna vid sjutiden ikväll.", video: "ungefar-klockan-sju-01626-fras-1.mp4" },
    { word: "ungefär klockan sju", phrase: "Ikväll kommer jag hem till dig omkring klockan sju.", video: "ungefar-klockan-sju-01626-fras-2.mp4" },
    { word: "ungefär klockan åtta", phrase: "Jag har för mig att filmen börjar vid åttatiden på kvällen. Stämmer det?", video: "ungefar-klockan-atta-01629-fras-1.mp4" },
    { word: "ungefär klockan nio", phrase: "Nu på lördag tänker vi vandra i skogen och vi åker iväg [ungefär klockan nio] på morgonen", video: "ungefar-klockan-nio-01630-fras-1.mp4" },
    { word: "klockan ett", phrase: "Vi skulle ju träffas idag [klockan ett]. Kan vi skjuta på det till klockan två istället?", video: "klockan-ett-02851-fras-1.mp4" },
    { word: "klockan ett", phrase: "Imorgon har vi möte mellan ett och fyra.", video: "klockan-ett-02851-fras-2.mp4" },
    { word: "klockan ett", phrase: "Jag ska hämta min bil [klockan ett] idag.", video: "klockan-ett-02851-fras-3.mp4" },
    { word: "klockan sju", phrase: "På lördag kl 19 ska jag ha killmiddag hemma hos mig.", video: "klockan-sju-01246-fras-1.mp4" },
    { word: "klockan sju", phrase: "Jag brukar alltid gå upp [klockan sju] på morgonen.", video: "klockan-sju-01246-fras-2.mp4" },
    { word: "en dag", phrase: "Nästa vecka är jag bara ledig [en dag].", video: "en-dag-17632-fras-1.mp4" },
    { word: "en dag", phrase: "Ifjol var jag sjuk endast [en dag].", video: "en-dag-17632-fras-2.mp4" },
    { word: "i lördags", phrase: "[I lördags] var jag i Åre och åkte slalom.", video: "i-lordags-17718-fras-1.mp4" },
    { word: "i lördags", phrase: "[I lördags] blåste det massor ute.", video: "i-lordags-17718-fras-2.mp4" },
    { word: "i måndags", phrase: "[I måndags] bröt jag armen, den är fortfarande lite svullen.", video: "i-mandags-17720-fras-1.mp4" },
    { word: "i måndags", phrase: "Minns du jordgubbarna vi köpte [i måndags]? De är redan slut!", video: "i-mandags-17720-fras-2.mp4" },
    { word: "i tisdags", phrase: "[I tisdags] träffade jag hens mamma inne i stan. Hon var verkligen trevlig!", video: "i-tisdags-17721-fras-1.mp4" },
    { word: "i tisdags", phrase: "Vart tog du vägen [i tisdags]? Du kom ju aldrig, jag stod länge och väntade på dig!", video: "i-tisdags-17721-fras-2.mp4" },
    { word: "i onsdags", phrase: "[I onsdags] hade kvinnoföreningen en föreläsning om kvinnors situation förr och idag. Det var en väldigt intressant föreläsning.", video: "i-onsdags-17722-fras-1.mp4" },
    { word: "i onsdags", phrase: "[I onsdags] missade jag föreningsmötet.", video: "i-onsdags-17722-fras-2.mp4" },
    { word: "i onsdags", phrase: "Jag var till läkaren [i onsdags].", video: "i-onsdags-17722-fras-3.mp4" },
    { word: "i fredags", phrase: "Tyst teater hade premiär [i fredags].", video: "i-fredags-17724-fras-1.mp4" }
  ]
});
