(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "datum1",
  name: "Tid & datum 1",
  words: [
    { word: "år", video: "ar-02861-tecken.mp4" },
    { word: "dag", video: "dag-00632-tecken.mp4" },
    { word: "vår", video: "var-00776-tecken.mp4" },
    { word: "dagar", video: "dagar-14989-tecken.mp4" },
    { word: "månader", video: "manader-17334-tecken.mp4" },
    { word: "vecka", video: "vecka-03700-tecken.mp4" },
    { word: "veckor", video: "veckor-03544-tecken.mp4" },
    { word: "timmar", video: "timmar-15858-tecken.mp4" },
    { word: "maj", video: "maj-01829-tecken.mp4" },
    { word: "mars", video: "mars-00774-tecken.mp4" },
    { word: "juni", video: "juni-03218-tecken.mp4" },
    { word: "september", video: "september-00887-tecken.mp4" },
    { word: "januari", video: "januari-00270-tecken.mp4" },
    { word: "månad", video: "manad-00414-tecken.mp4" },
    { word: "december", video: "december-03203-tecken.mp4" },
    { word: "kväll", video: "kvall-00514-tecken.mp4" },
    { word: "februari", video: "februari-04530-tecken.mp4" },
    { word: "april", video: "april-00815-tecken.mp4" },
    { word: "augusti", video: "augusti-01922-tecken.mp4" },
    { word: "november", video: "november-05113-tecken.mp4" },
    { word: "höst", video: "host-01522-tecken.mp4" },
    { word: "juli", video: "juli-08252-tecken.mp4" },
    { word: "söndag", video: "sondag-01416-tecken.mp4" },
    { word: "oktober", video: "oktober-05132-tecken.mp4" },
    { word: "sommar", video: "sommar-05072-tecken.mp4" },
    { word: "lördag", video: "lordag-02839-tecken.mp4" },
    { word: "morgon", video: "morgon-00623-tecken.mp4" },
    { word: "timme", video: "timme-03019-tecken.mp4" },
    { word: "fredag", video: "fredag-04567-tecken.mp4" },
    { word: "måndag", video: "mandag-04457-tecken.mp4" },
    { word: "torsdag", video: "torsdag-03453-tecken.mp4" },
    { word: "tisdag", video: "tisdag-03455-tecken.mp4" },
    { word: "natt", video: "natt-00516-tecken.mp4" },
    { word: "onsdag", video: "onsdag-01781-tecken.mp4" },
    { word: "vinter", video: "vinter-01931-tecken.mp4" },
    { word: "minut", video: "minut-03008-tecken.mp4" },
    { word: "eftermiddag", video: "eftermiddag-00490-tecken.mp4" },
    { word: "sekund", video: "sekund-03555-tecken.mp4" },
    { word: "vardag", video: "vardag-01398-tecken.mp4" },
    { word: "dygn", video: "dygn-00518-tecken.mp4" },
    { word: "halvtimme", video: "halvtimme-03017-tecken.mp4" },
    { word: "kvällar", video: "kvallar-01242-tecken.mp4" },
    { word: "helg", video: "helg-00609-tecken.mp4" },
    { word: "midnatt", video: "midnatt-04068-tecken.mp4" },
    { word: "nätter", video: "natter-20127-tecken.mp4" },
    { word: "förmiddag", video: "formiddag-00488-tecken.mp4" },
    { word: "helger", video: "helger-17735-tecken.mp4" },
    { word: "kvartal", video: "kvartal-04461-tecken.mp4" },
    { word: "lördagar", video: "lordagar-17717-tecken.mp4" },
    { word: "söndagar", video: "sondagar-17726-tecken.mp4" }
  ],
  phrases: [
    { word: "år", phrase: "På kongressen i Milano 1880 bestämde man att teckenspråket skulle förbjudas.", video: "ar-02861-fras-1.mp4" },
    { word: "år", phrase: "Jag har haft ett dåligt [år] och hoppas att nästa [år] blir bättre.", video: "ar-02861-fras-2.mp4" },
    { word: "dag", phrase: "Jobba på [dagen] är inget för mig. Jag jobbar hellre på natten.", video: "dag-00632-fras-1.mp4" },
    { word: "dag", phrase: "Igår var verkligen inte min [dag] på grund av allt som hände, jag tappade min nyckel och plånbok plus att jag kom försent till jobbet.", video: "dag-00632-fras-2.mp4" },
    { word: "månader", phrase: "Hur många [månader] är det på ett år?", video: "manader-17334-fras-1.mp4" },
    { word: "månader", phrase: "För tre [månader] sen sålde jag min bil.", video: "manader-17334-fras-2.mp4" },
    { word: "vecka", phrase: "Vilken [vecka] är det nu?", video: "vecka-03700-fras-1.mp4" },
    { word: "vecka", phrase: "Jag är arbetslös i bara en [vecka].", video: "vecka-03700-fras-2.mp4" },
    { word: "vecka", phrase: "Jag har inte tränat på åtta veckor på grund av min axelskada.", video: "vecka-03700-fras-3.mp4" },
    { word: "vecka", phrase: "Hur många dagar har en [vecka]?", video: "vecka-03700-fras-4.mp4" },
    { word: "veckor", phrase: "Hur många [veckor] är det i april?", video: "veckor-03544-fras-1.mp4" },
    { word: "timmar", phrase: "Hur många [timmar] jobbar du sammanlagt idag?", video: "timmar-15858-fras-1.mp4" },
    { word: "timmar", phrase: "Jag är verkligen hungrig men det är bara två [timmar] kvar till lunch.", video: "timmar-15858-fras-2.mp4" },
    { word: "maj", phrase: "Min födelsedag är den 31 [maj].", video: "maj-01829-fras-1.mp4" },
    { word: "maj", phrase: "Vill du vara med och demonstrera den 1:a [maj]?", video: "maj-01829-fras-2.mp4" },
    { word: "mars", phrase: "[Mars] månad har 31 dagar.", video: "mars-00774-fras-1.mp4" },
    { word: "mars", phrase: "Vi i familjen funderar på att åka till fjällen i slutet av [mars] och åka slalom.", video: "mars-00774-fras-2.mp4" },
    { word: "juni", phrase: "De flesta som är yrkesarbetande brukar arbeta fram till slutet av [juni] och sedan ta semester.", video: "juni-03218-fras-1.mp4" },
    { word: "juni", phrase: "Min namnsdag är den 13 [juni].", video: "juni-03218-fras-2.mp4" },
    { word: "september", phrase: "Under [september] månad finns det mycket svamp.", video: "september-00887-fras-1.mp4" },
    { word: "september", phrase: "I [september] köpte jag en ny bil som jag är väldigt nöjd med.", video: "september-00887-fras-2.mp4" },
    { word: "januari", phrase: "Jag fyller år den 13 [januari].", video: "januari-00270-fras-1.mp4" },
    { word: "januari", phrase: "Det snöar alltid mycket under [januari] månad.", video: "januari-00270-fras-2.mp4" },
    { word: "december", phrase: "Min syster Anna har namnsdag den 9 [december].", video: "december-03203-fras-1.mp4" },
    { word: "december", phrase: "Min son skulle födas i slutet av [december] men han föddes först i januari.", video: "december-03203-fras-2.mp4" },
    { word: "kväll", phrase: "Imorgon [kväll] är det fotboll på TV:n.", video: "kvall-00514-fras-1.mp4" },
    { word: "kväll", phrase: "Igår [kväll] var jag ute på promenad med hunden i en timme.", video: "kvall-00514-fras-2.mp4" },
    { word: "kväll", phrase: "Vill du gå ut och äta middag ikväll och sedan gå på bio?", video: "kvall-00514-fras-3.mp4" },
    { word: "februari", phrase: "Hur många dagar är det i [februari] månad?", video: "februari-04530-fras-1.mp4" },
    { word: "februari", phrase: "Nu under [februari] månad ska jag byta lägenhet.", video: "februari-04530-fras-2.mp4" },
    { word: "april", phrase: "I dag är det 25:e [april].", video: "april-00815-fras-1.mp4" },
    { word: "april", phrase: "Jag avskyr [april] månad för då regnar det alltid .", video: "april-00815-fras-2.mp4" },
    { word: "april", phrase: "Jag älskar [april] för då kommer våren.", video: "april-00815-fras-3.mp4" },
    { word: "augusti", phrase: "Ungdomar brukar samlas i Kungsträdgården, särskilt innan skolstarten i början av [augusti].", video: "augusti-01922-fras-1.mp4" },
    { word: "augusti", phrase: "Jag har många vänner som fyller år under [augusti] månad.", video: "augusti-01922-fras-2.mp4" },
    { word: "november", phrase: "I [november] 2016 var det mycket snö här i Stockholm, 40 cm.", video: "november-05113-fras-1.mp4" },
    { word: "november", phrase: "Jag funderar på att åka på semester till ett varmt land under [november] månad eftersom det är så mörkt och tråkigt i Sverige då.", video: "november-05113-fras-2.mp4" },
    { word: "höst", phrase: "Jag har gått på färganalys och fick veta att min färgskala ryms inom årstiderna [höst] och vår.", video: "host-01522-fras-1.mp4" },
    { word: "höst", phrase: "Det regnar alltid mycket på [hösten].", video: "host-01522-fras-2.mp4" },
    { word: "juli", phrase: "Vädret i Sverige under [juli] månad brukar vara sisådär, däremot brukar det vara fint väder månaden innan och efter [juli].", video: "juli-08252-fras-1.mp4" },
    { word: "juli", phrase: "Jag ska ha semester hela [juli] månad.", video: "juli-08252-fras-2.mp4" },
    { word: "söndag", phrase: "Dövgudstjänsten är inte nu på [söndag] utan nästa [söndag].", video: "sondag-01416-fras-1.mp4" },
    { word: "söndag", phrase: "Hur många [söndagar] är det normalt under januari månad?", video: "sondag-01416-fras-2.mp4" },
    { word: "oktober", phrase: "Har du tips på resmål som jag kan åka till under [oktober] månad?", video: "oktober-05132-fras-1.mp4" },
    { word: "oktober", phrase: "När under [oktober] månad ska du och jag ha vårat möte?", video: "oktober-05132-fras-2.mp4" },
    { word: "sommar", phrase: "Förra [sommaren] var det fruktansvärt hett.", video: "sommar-05072-fras-1.mp4" },
    { word: "sommar", phrase: "Vilka kläder har du på [sommaren]?", video: "sommar-05072-fras-2.mp4" },
    { word: "lördag", phrase: "På [lördag] är det ett viktigt tv-program. Det är fotboll.", video: "lordag-02839-fras-1.mp4" },
    { word: "lördag", phrase: "Jag kan inte komma på [lördag].", video: "lordag-02839-fras-2.mp4" },
    { word: "lördag", phrase: "Har inte Inger sagt att jag inte kommer på [lördag]?", video: "lordag-02839-fras-3.mp4" },
    { word: "morgon", phrase: "Jag är ingen [morgonmänniska]. Jag är alltid sur på [morgonen].", video: "morgon-00623-fras-1.mp4" },
    { word: "morgon", phrase: "Var snäll och vakna tidigt imorgon bitti.", video: "morgon-00623-fras-2.mp4" },
    { word: "morgon", phrase: "Min son är alltid [morgonpigg].", video: "morgon-00623-fras-3.mp4" },
    { word: "timme", phrase: "I den där butiken kan man få sina foton framkallade på en [timme].", video: "timme-03019-fras-1.mp4" },
    { word: "timme", phrase: "Det är en [timme] kvar till after work.", video: "timme-03019-fras-2.mp4" },
    { word: "fredag", phrase: "Jag har frågat mina arbetskamrater vilken veckodag de tycker är den bästa och de flesta svarade [fredag].", video: "fredag-04567-fras-1.mp4" },
    { word: "fredag", phrase: "På [fredag] ska hen gå på bio.", video: "fredag-04567-fras-2.mp4" },
    { word: "fredag", phrase: "Ska du träna fotboll på [fredag] kväll?", video: "fredag-04567-fras-3.mp4" },
    { word: "måndag", phrase: "Jag brukar undervisa vissa [måndagar].", video: "mandag-04457-fras-1.mp4" },
    { word: "måndag", phrase: "Jag brukar undervisa vissa [måndagar], inte varje [måndag].", video: "mandag-04457-fras-2.mp4" },
    { word: "måndag", phrase: "Jag kan jobba på [måndag].", video: "mandag-04457-fras-3.mp4" },
    { word: "måndag", phrase: "I [måndags] hade vi prov i matte.", video: "mandag-04457-fras-4.mp4" },
    { word: "torsdag", phrase: "Nästa vecka ska jag till Barcelona [torsdag] till söndag.", video: "torsdag-03453-fras-1.mp4" },
    { word: "torsdag", phrase: "Min favorit veckodag är [torsdag] för att då är det snart fredag.", video: "torsdag-03453-fras-2.mp4" },
    { word: "torsdag", phrase: "Nu på [torsdag] fyller min mamma år så jag måste köpa en present och ge henne.", video: "torsdag-03453-fras-3.mp4" },
    { word: "tisdag", phrase: "Uppskjutningen skulle ha varit i [tisdags] men blev framflyttad till fredag.", video: "tisdag-03455-fras-1.mp4" },
    { word: "tisdag", phrase: "Jag brukar träna [tisdag] och torsdag.", video: "tisdag-03455-fras-2.mp4" },
    { word: "natt", phrase: "Jag tycker mycket om [natten] eftersom jag är en [nattmänniska].", video: "natt-00516-fras-1.mp4" },
    { word: "natt", phrase: "Var ska du sova imorgon [natt]?", video: "natt-00516-fras-2.mp4" },
    { word: "natt", phrase: "Du får sova här en [natt] men inte mer.", video: "natt-00516-fras-3.mp4" },
    { word: "natt", phrase: "På [natten] sover jag.", video: "natt-00516-fras-4.mp4" },
    { word: "onsdag", phrase: "Idag är det [onsdagen] den 17 mars. Nästa [onsdag] vilken datum är det då?", video: "onsdag-01781-fras-1.mp4" },
    { word: "onsdag", phrase: "Nu på [onsdag] ska jag simträna.", video: "onsdag-01781-fras-2.mp4" },
    { word: "onsdag", phrase: "På [onsdag] kväll ska jag på tjejkväll. Ska du följa med?", video: "onsdag-01781-fras-3.mp4" },
    { word: "minut", phrase: "Hur många [minuter] går det på en timme?", video: "minut-03008-fras-1.mp4" },
    { word: "minut", phrase: "Hur många sekunder går det på en [minut]?", video: "minut-03008-fras-2.mp4" },
    { word: "eftermiddag", phrase: "Min pappa ska till pensionärsföreningen i [eftermiddag].", video: "eftermiddag-00490-fras-1.mp4" },
    { word: "eftermiddag", phrase: "Lektionen i [eftermiddag] är inställd.", video: "eftermiddag-00490-fras-2.mp4" },
    { word: "eftermiddag", phrase: "Många slutar tidigt på fredag [eftermiddag].", video: "eftermiddag-00490-fras-3.mp4" },
    { word: "eftermiddag", phrase: "På fredagseftermiddagarna brukar det vara bilköer ut från stan.", video: "eftermiddag-00490-fras-4.mp4" },
    { word: "sekund", phrase: "3600 [sekunder] är lika med en timme.", video: "sekund-03555-fras-1.mp4" },
    { word: "sekund", phrase: "Det är några [sekunder] kvar tills matchen börjar.", video: "sekund-03555-fras-2.mp4" },
    { word: "vardag", phrase: "Jag har två garderober, en för [vardagskläder] och en för finkläder.", video: "vardag-01398-fras-1.mp4" },
    { word: "dygn", phrase: "Tre [dygn] utan sömn är mitt personliga rekord.", video: "dygn-00518-fras-1.mp4" },
    { word: "dygn", phrase: "Hur många timmar är ett [dygn]?", video: "dygn-00518-fras-2.mp4" },
    { word: "halvtimme", phrase: "Mitt jobb ligger i närheten. Det tar mig bara en [halvtimme] att gå dit.", video: "halvtimme-03017-fras-1.mp4" },
    { word: "halvtimme", phrase: "Jag har bara en [halvtimmes] lunchrast.", video: "halvtimme-03017-fras-2.mp4" },
    { word: "halvtimme", phrase: "Hur många minuter går det på en [halvtimme]?", video: "halvtimme-03017-fras-3.mp4" },
    { word: "kvällar", phrase: "På [kvällarna] är det många polisbilar ute på stan.", video: "kvallar-01242-fras-1.mp4" },
    { word: "kvällar", phrase: "Under fotbolls-VM är det alltid mycket folk ute på [kvällarna].", video: "kvallar-01242-fras-2.mp4" },
    { word: "helg", phrase: "Jag åker ofta till landet varannan [helg].", video: "helg-00609-fras-1.mp4" },
    { word: "helg", phrase: "Jag längtar så till [helgen] för då ska jag åka till mitt fritidshus.", video: "helg-00609-fras-2.mp4" },
    { word: "helg", phrase: "Mina föräldrar brukar åka till sommarstugan varje [helg], fredag till söndag.", video: "helg-00609-fras-3.mp4" },
    { word: "helg", phrase: "Vad ska du göra till [helgen]?", video: "helg-00609-fras-4.mp4" },
    { word: "midnatt", phrase: "Imorgon ska jag jobba fram tills [midnatt].", video: "midnatt-04068-fras-1.mp4" },
    { word: "midnatt", phrase: "Förra veckan körde jag bil från Skåne - Göteborg, jag kom fram till Göteborg mitt i natten.", video: "midnatt-04068-fras-2.mp4" },
    { word: "förmiddag", phrase: "Jag tycker bättre om att jobba på [förmiddagen], för på eftermiddagen blir jag alltid så trött.", video: "formiddag-00488-fras-1.mp4" },
    { word: "förmiddag", phrase: "Du kan komma till mig i morgon [förmiddag].", video: "formiddag-00488-fras-2.mp4" },
    { word: "söndagar", phrase: "Förr brukade man äta söndagsstek med brunsås på [söndagarna].", video: "sondagar-17726-fras-1.mp4" }
  ]
});
