(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "djur1",
  name: "Djur 1",
  words: [
    { word: "får", video: "far-04143-tecken.mp4" },
    { word: "björn", video: "bjorn-00010-tecken.mp4" },
    { word: "emu", video: "emu-24709-tecken.mp4" },
    { word: "val", video: "val-00564-tecken.mp4" },
    { word: "ren", video: "ren-12326-tecken.mp4" },
    { word: "lo", video: "lo-02428-tecken.mp4" },
    { word: "fisk", video: "fisk-00234-tecken.mp4" },
    { word: "hund", video: "hund-00222-tecken.mp4" },
    { word: "and", video: "and-12328-tecken.mp4" },
    { word: "falk", video: "falk-03597-tecken.mp4" },
    { word: "katt", video: "katt-00344-tecken.mp4" },
    { word: "lax", video: "lax-09069-tecken.mp4" },
    { word: "fågel", video: "fagel-03275-tecken.mp4" },
    { word: "kyckling", video: "kyckling-03347-tecken.mp4" },
    { word: "tiger", video: "tiger-01660-tecken.mp4" },
    { word: "ko", video: "ko-03058-tecken.mp4" },
    { word: "mask", video: "mask-03538-tecken.mp4" },
    { word: "sill", video: "sill-02896-tecken.mp4" },
    { word: "svan", video: "svan-03616-tecken.mp4" },
    { word: "lejon", video: "lejon-01639-tecken.mp4" },
    { word: "höns", video: "hons-03346-tecken.mp4" },
    { word: "fjäril", video: "fjaril-00567-tecken.mp4" },
    { word: "torsk", video: "torsk-03276-tecken.mp4" },
    { word: "gris", video: "gris-01149-tecken.mp4" },
    { word: "strömming", video: "stromming-02897-tecken.mp4" },
    { word: "fluga", video: "fluga-03942-tecken.mp4" },
    { word: "svin", video: "svin-02953-tecken.mp4" },
    { word: "svala", video: "svala-04157-tecken.mp4" },
    { word: "älg", video: "alg-00931-tecken.mp4" },
    { word: "apa", video: "apa-01539-tecken.mp4" },
    { word: "kamel", video: "kamel-01086-tecken.mp4" },
    { word: "anka", video: "anka-00548-tecken.mp4" },
    { word: "skälla", video: "skalla-07577-tecken.mp4" },
    { word: "råtta", video: "ratta-03354-tecken.mp4" },
    { word: "räv", video: "rav-00820-tecken.mp4" },
    { word: "varg", video: "varg-15818-tecken.mp4" },
    { word: "get", video: "get-01382-tecken.mp4" },
    { word: "elefant", video: "elefant-01374-tecken.mp4" },
    { word: "rådjur", video: "radjur-12181-tecken.mp4" },
    { word: "pippi", video: "pippi-05637-tecken.mp4" },
    { word: "mus", video: "mus-03635-tecken.mp4" },
    { word: "hjort", video: "hjort-12327-tecken.mp4" },
    { word: "kalv", video: "kalv-00547-tecken.mp4" },
    { word: "tjur", video: "tjur-03326-tecken.mp4" },
    { word: "hare", video: "hare-04079-tecken.mp4" },
    { word: "gädda", video: "gadda-01237-tecken.mp4" },
    { word: "örn", video: "orn-09139-tecken.mp4" },
    { word: "spindel", video: "spindel-01715-tecken.mp4" },
    { word: "gås", video: "gas-04840-tecken.mp4" },
    { word: "tupp", video: "tupp-04311-tecken.mp4" }
  ],
  phrases: [
    { word: "får", phrase: "I helgen var jag med familjen ute på en 4-H gård och tittade på [får], kor och grisar.", video: "far-04143-fras-1.mp4" },
    { word: "får", phrase: "Ull kommer från [får].", video: "far-04143-fras-2.mp4" },
    { word: "björn", phrase: "På ett zoo finns det olika typer av [björnar].", video: "bjorn-00010-fras-1.mp4" },
    { word: "björn", phrase: "I Norrland finns det gott om [björn] men jag undrar om det finns [björn] i Örebro?", video: "bjorn-00010-fras-2.mp4" },
    { word: "björn", phrase: "Min pappa kan se farlig ut men han är egentligen snäll som en [björn].", video: "bjorn-00010-fras-3.mp4" },
    { word: "fisk", phrase: "Vid kinarestaurangen i stan finns en damm där [fiskar] simmar omkring.", video: "fisk-00234-fras-1.mp4" },
    { word: "hund", phrase: "Mina barn tjatar om att få en [hund] men det kan de inte få för jag är allergisk.", video: "hund-00222-fras-1.mp4" },
    { word: "hund", phrase: "Min förra [hund] hette Mia.", video: "hund-00222-fras-2.mp4" },
    { word: "hund", phrase: "På torsdagarna går jag alltid till [hundparken] med min [hund].", video: "hund-00222-fras-3.mp4" },
    { word: "katt", phrase: "Min [katt] är 8 år gammal", video: "katt-00344-fras-1.mp4" },
    { word: "katt", phrase: "Jag har haft [katt] i 14 år.", video: "katt-00344-fras-2.mp4" },
    { word: "katt", phrase: "[Katten] var ungefär så här stor.", video: "katt-00344-fras-3.mp4" },
    { word: "lax", phrase: "I Sverige finns det en plats som är känd för sitt [laxfiske], nämligen Mörrum.", video: "lax-09069-fras-1.mp4" },
    { word: "lax", phrase: "Imorgon får jag gäster. Då tänker jag bjuda på [lax].", video: "lax-09069-fras-2.mp4" },
    { word: "tiger", phrase: "[Tigern] tillhör kattdjuren precis som lejonet och leoparden m.fl.", video: "tiger-01660-fras-1.mp4" },
    { word: "sill", phrase: "Jag vill gärna ha [sill] särskilt på julafton och påskafton.", video: "sill-02896-fras-1.mp4" },
    { word: "sill", phrase: "Jag gillar inte [sill].", video: "sill-02896-fras-2.mp4" },
    { word: "strömming", phrase: "[Strömming] serveras ofta med potatismos.", video: "stromming-02897-fras-1.mp4" },
    { word: "apa", phrase: "När jag var liten hade jag en favorit, en [apa] som heter Nicke Nyfiken.", video: "apa-01539-fras-1.mp4" },
    { word: "anka", phrase: "Om du vill få god smak på din [anka] så är rekommendationen att du har den i ugnen under lång tid på låg temperatur.", video: "anka-00548-fras-1.mp4" },
    { word: "anka", phrase: "Vilka kryddor passar bäst till [anka] i ugn?", video: "anka-00548-fras-2.mp4" },
    { word: "skälla", phrase: "Vår hund skäller mycket när den känner vittringen av ett annat djur.", video: "skalla-07577-fras-1.mp4" },
    { word: "skälla", phrase: "Jag blev fundersam i morse när min hund sprang till dörren och började [skälla]. När jag öppnade dörren så förstod jag varför, det stod en dammsugarförsäljare där utanför.", video: "skalla-07577-fras-2.mp4" },
    { word: "skälla", phrase: "När jag är ute och rastar min hund så skäller hen alltid åt mötande bilar.", video: "skalla-07577-fras-3.mp4" },
    { word: "mus", phrase: "Jag är inte ett dugg rädd för möss.", video: "mus-03635-fras-1.mp4" }
  ]
});
