(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "djur2",
  name: "Djur 2",
  words: [
    { word: "kanin", video: "kanin-04080-tecken.mp4" },
    { word: "rovdjur", video: "rovdjur-02876-tecken.mp4" },
    { word: "kalkon", video: "kalkon-04933-tecken.mp4" },
    { word: "åsna", video: "asna-00506-tecken.mp4" },
    { word: "regnbåge", video: "regnbage-12490-tecken.mp4" },
    { word: "oxe", video: "oxe-03325-tecken.mp4" },
    { word: "gös", video: "gos-04012-tecken.mp4" },
    { word: "däggdjur", video: "daggdjur-23191-tecken.mp4" },
    { word: "uggla", video: "uggla-03561-tecken.mp4" },
    { word: "säl", video: "sal-00549-tecken.mp4" },
    { word: "ål", video: "al-05544-tecken.mp4" },
    { word: "öring", video: "oring-09141-tecken.mp4" },
    { word: "makrill", video: "makrill-01657-tecken.mp4" },
    { word: "insekt", video: "insekt-07296-tecken.mp4" },
    { word: "duva", video: "duva-06770-tecken.mp4" },
    { word: "ekorre", video: "ekorre-15531-tecken.mp4" },
    { word: "kryp", video: "kryp-07280-tecken.mp4" },
    { word: "tax", video: "tax-17613-tecken.mp4" },
    { word: "abborre", video: "abborre-01811-tecken.mp4" },
    { word: "struts", video: "struts-12522-tecken.mp4" },
    { word: "schäfer", video: "schafer-01371-tecken.mp4" },
    { word: "valp", video: "valp-00605-tecken.mp4" },
    { word: "kråka", video: "kraka-03987-tecken.mp4" },
    { word: "bi", video: "bi-03334-tecken.mp4" },
    { word: "larv", video: "larv-05872-tecken.mp4" },
    { word: "tonfisk", video: "tonfisk-09372-tecken.mp4" },
    { word: "flodhäst", video: "flodhast-01624-tecken.mp4" },
    { word: "järv", video: "jarv-14613-tecken.mp4" },
    { word: "gorilla", video: "gorilla-02134-tecken.mp4" },
    { word: "geting", video: "geting-03335-tecken.mp4" },
    { word: "hackspett", video: "hackspett-07780-tecken.mp4" },
    { word: "fasan", video: "fasan-08910-tecken.mp4" },
    { word: "kattunge", video: "kattunge-04937-tecken.mp4" },
    { word: "haj", video: "haj-12401-tecken.mp4" },
    { word: "bock", video: "bock-03714-tecken.mp4" },
    { word: "hundvalp", video: "hundvalp-02553-tecken.mp4" },
    { word: "lama", video: "lama-15602-tecken.mp4" },
    { word: "krokodil", video: "krokodil-01625-tecken.mp4" },
    { word: "humla", video: "humla-02416-tecken.mp4" },
    { word: "lus", video: "lus-17294-tecken.mp4" },
    { word: "skata", video: "skata-10765-tecken.mp4" },
    { word: "kiwi", video: "kiwi-05626-tecken.mp4" },
    { word: "känguru", video: "kanguru-00213-tecken.mp4" },
    { word: "sköldpadda", video: "skoldpadda-02408-tecken.mp4" },
    { word: "röding", video: "roding-11475-tecken.mp4" },
    { word: "mygga", video: "mygga-03337-tecken.mp4" },
    { word: "myra", video: "myra-05101-tecken.mp4" },
    { word: "leopard", video: "leopard-01954-tecken.mp4" },
    { word: "vildsvin", video: "vildsvin-04644-tecken.mp4" },
    { word: "braxen", video: "braxen-17218-tecken.mp4" }
  ],
  phrases: [
    { word: "abborre", phrase: "I morse när jag fiskade fick jag en [abborre].", video: "abborre-01811-fras-1.mp4" },
    { word: "gorilla", phrase: "Jag vill åka till Afrika för att se vilda djur, t.ex. gorillor och elefanter.", video: "gorilla-02134-fras-1.mp4" },
    { word: "krokodil", phrase: "När jag var i Australien provade jag att äta [krokodil]. Det var gott.", video: "krokodil-01625-fras-1.mp4" },
    { word: "känguru", phrase: "När jag var i Australien körde jag på en [känguru].", video: "kanguru-00213-fras-1.mp4" },
    { word: "känguru", phrase: "Har du smakat på [kängurukött]? Det är faktiskt gott!", video: "kanguru-00213-fras-2.mp4" },
    { word: "känguru", phrase: "Vet du vad det här är för kött? Det är [känguru].", video: "kanguru-00213-fras-3.mp4" },
    { word: "känguru", phrase: "[Kängurun] bär sin lilla unge i pungen.", video: "kanguru-00213-fras-4.mp4" }
  ]
});
