(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "familj",
  name: "Familj",
  words: [
    { word: "man", video: "man-05036-tecken.mp4" },
    { word: "barn", video: "barn-00257-tecken.mp4" },
    { word: "mamma", video: "mamma-00188-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4" },
    { word: "föräldrar", video: "foraldrar-13821-tecken.mp4" },
    { word: "familj", video: "familj-00773-tecken.mp4" },
    { word: "son", video: "son-01944-tecken.mp4" },
    { word: "fru", video: "fru-04582-tecken.mp4" },
    { word: "dotter", video: "dotter-00111-tecken.mp4" },
    { word: "syster", video: "syster-03513-tecken.mp4" },
    { word: "bror", video: "bror-03462-tecken.mp4" },
    { word: "mormor", video: "mormor-01938-tecken.mp4" },
    { word: "farfar", video: "farfar-01932-tecken.mp4" },
    { word: "farbror", video: "farbror-02752-tecken.mp4" },
    { word: "farmor", video: "farmor-01933-tecken.mp4" },
    { word: "släkt", video: "slakt-03156-tecken.mp4" },
    { word: "barnbarn", video: "barnbarn-04647-tecken.mp4" },
    { word: "moster", video: "moster-00176-tecken.mp4" },
    { word: "syskon", video: "syskon-03564-tecken.mp4" },
    { word: "morfar", video: "morfar-01937-tecken.mp4" },
    { word: "lillebror", video: "lillebror-16156-tecken.mp4" },
    { word: "kusin", video: "kusin-03155-tecken.mp4" },
    { word: "sambo", video: "sambo-05067-tecken.mp4" },
    { word: "flickvän", video: "flickvan-11970-tecken.mp4" },
    { word: "pojkvän", video: "pojkvan-12482-tecken.mp4" },
    { word: "storebror", video: "storebror-15963-tecken.mp4" },
    { word: "släkting", video: "slakting-20134-tecken.mp4" },
    { word: "faster", video: "faster-01399-tecken.mp4" },
    { word: "morbror", video: "morbror-05083-tecken.mp4" },
    { word: "svärmor", video: "svarmor-05352-tecken.mp4" },
    { word: "fästmö", video: "fastmo-02487-tecken.mp4" },
    { word: "svåger", video: "svager-03157-tecken.mp4" },
    { word: "svärfar", video: "svarfar-05350-tecken.mp4" },
    { word: "storasyster", video: "storasyster-15946-tecken.mp4" },
    { word: "styvmor", video: "styvmor-08496-tecken.mp4" },
    { word: "fästman", video: "fastman-15888-tecken.mp4" },
    { word: "brorson", video: "brorson-18608-tecken.mp4" },
    { word: "styvfar", video: "styvfar-00433-tecken.mp4" },
    { word: "halvbror", video: "halvbror-19344-tecken.mp4" },
    { word: "systerdotter", video: "systerdotter-18612-tecken.mp4" },
    { word: "systerson", video: "systerson-18613-tecken.mp4" },
    { word: "svärföräldrar", video: "svarforaldrar-05351-tecken.mp4" },
    { word: "halvsyster", video: "halvsyster-24352-tecken.mp4" },
    { word: "brorsdotter", video: "brorsdotter-18609-tecken.mp4" },
    { word: "måg", video: "mag-19339-tecken.mp4" },
    { word: "sladdbarn", video: "sladdbarn-16325-tecken.mp4" },
    { word: "släktmiddag", video: "slaktmiddag-24729-tecken.mp4" },
    { word: "morförälder", video: "morforalder-04257-tecken.mp4" },
    { word: "gammelfarmor", video: "gammelfarmor-08414-tecken.mp4" },
    { word: "långsläkt", video: "langslakt-24771-tecken.mp4" }
  ],
  phrases: [
    { word: "man", phrase: "Min systers [man] vet inte om att jag har fyra barn.", video: "man-05036-fras-1.mp4" },
    { word: "barn", phrase: "Mina [barn] är helt sålda på TV-spel. De måste spela varje dag.", video: "barn-00257-fras-1.mp4" },
    { word: "barn", phrase: "När sommarlovet är slut är [barnen] fulla av iver över att komma tillbaka till skolan.", video: "barn-00257-fras-2.mp4" },
    { word: "barn", phrase: "Jag har tre [barn].", video: "barn-00257-fras-3.mp4" },
    { word: "mamma", phrase: "[Mamma] är alltid bäst!", video: "mamma-00188-fras-1.mp4" },
    { word: "pappa", phrase: "Är han din [pappa]?", video: "pappa-02557-fras-1.mp4" },
    { word: "pappa", phrase: "[Pappa] är väldigt lång.", video: "pappa-02557-fras-2.mp4" },
    { word: "föräldrar", phrase: "Tack vare att mina [föräldrar] lärde sig teckenspråk kan jag kommunicera med dem.", video: "foraldrar-13821-fras-1.mp4" },
    { word: "föräldrar", phrase: "Är det där dina [föräldrar]?", video: "foraldrar-13821-fras-2.mp4" },
    { word: "son", phrase: "Min [son] vill gå med i en fäktningsklubb men han är för liten. Han får vänta två år till.", video: "son-01944-fras-1.mp4" },
    { word: "son", phrase: "Min systers [son] har födelsedag imorgon.", video: "son-01944-fras-2.mp4" },
    { word: "son", phrase: "Är det din [son]?", video: "son-01944-fras-3.mp4" },
    { word: "fru", phrase: "Min [frus] föräldrar kan inte teckenspråk.", video: "fru-04582-fras-1.mp4" },
    { word: "dotter", phrase: "Min äldsta [dotter] är tio år gammal.", video: "dotter-00111-fras-1.mp4" },
    { word: "dotter", phrase: "Vad heter din [dotter]?", video: "dotter-00111-fras-2.mp4" },
    { word: "dotter", phrase: "Är hon din [dotter]?", video: "dotter-00111-fras-3.mp4" },
    { word: "syster", phrase: "Min familj består av mamma, pappa, mig själv och två systrar.", video: "syster-03513-fras-1.mp4" },
    { word: "syster", phrase: "Min [syster] är snäll.", video: "syster-03513-fras-2.mp4" },
    { word: "mormor", phrase: "Min [mormor] är proffs på att baka bullar och bröd. De är alltid goda.", video: "mormor-01938-fras-1.mp4" },
    { word: "farmor", phrase: "Är hon min [farmor]?", video: "farmor-01933-fras-1.mp4" },
    { word: "släkt", phrase: "De flesta av mina [släktingar] bor i Spanien.", video: "slakt-03156-fras-1.mp4" },
    { word: "släkt", phrase: "Alla andra i min [släkt] är hörande. Det är bara jag som är döv.", video: "slakt-03156-fras-2.mp4" },
    { word: "släkt", phrase: "I min [släkt] är det bara jag som är döv. Alla andra är hörande.", video: "slakt-03156-fras-3.mp4" },
    { word: "släkt", phrase: "Hon och jag är [släkt] med varandra.", video: "slakt-03156-fras-4.mp4" },
    { word: "barnbarn", phrase: "Ett [barnbarn] till min arbetskamrat går i samma klass som min son.", video: "barnbarn-04647-fras-1.mp4" },
    { word: "barnbarn", phrase: "När jag hälsar på mitt [barnbarn] har jag alltid med en klubba till hen.", video: "barnbarn-04647-fras-2.mp4" },
    { word: "moster", phrase: "Jag har biobiljetter till oss som jag fått av min [moster].", video: "moster-00176-fras-1.mp4" },
    { word: "moster", phrase: "[Moster] är benämningen för din mammas syster.", video: "moster-00176-fras-2.mp4" },
    { word: "moster", phrase: "Har du bra kontakt med din [moster] eller???", video: "moster-00176-fras-3.mp4" },
    { word: "syskon", phrase: "Vi är fem [syskon] och jag är näst äldst.", video: "syskon-03564-fras-1.mp4" },
    { word: "syskon", phrase: "Jag har tre [syskon].", video: "syskon-03564-fras-2.mp4" },
    { word: "morfar", phrase: "Min [morfar] heter Anders.", video: "morfar-01937-fras-1.mp4" },
    { word: "sambo", phrase: "Förut var det inte så vanligt med [sambor] men det är det idag.", video: "sambo-05067-fras-1.mp4" },
    { word: "sambo", phrase: "Nu har min [sambo] gått iväg för att handla mat.", video: "sambo-05067-fras-2.mp4" },
    { word: "sambo", phrase: "Det här är Erik, min [sambo].", video: "sambo-05067-fras-3.mp4" },
    { word: "sambo", phrase: "Igår sprang jag på hennes [sambo].", video: "sambo-05067-fras-4.mp4" },
    { word: "svåger", phrase: "Min syster fyller snart 40 år så min [svåger] och jag tänker hitta på något.", video: "svager-03157-fras-1.mp4" }
  ]
});
