(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "fraser3",
  name: "Fraser, 3 ord",
  words: [
    { word: "Barn älskar godisklubbor!", video: "klubba-03830-fras-3.mp4" },
    { word: "Du lyssnar inte.", video: "inte-00646-fras-3.mp4" },
    { word: "Du är lättlurad.", video: "latt-00631-fras-1.mp4" },
    { word: "Har du cigaretter?", video: "cigarett-04122-fras-1.mp4" },
    { word: "Har du feber?", video: "du-02817-fras-3.mp4" },
    { word: "Hjälp mig inte!", video: "mig-03622-fras-3.mp4" },
    { word: "Hur många kommer?", video: "hur-manga-01062-fras-1.mp4" },
    { word: "Jag avskyr ärtsoppa.", video: "avsky-12048-fras-2.mp4" },
    { word: "Jag har texttelefon.", video: "texttelefon-16551-fras-1.mp4" },
    { word: "Jag körde jättefort.", video: "snabb-00847-fras-1.mp4" },
    { word: "Jag vet inte.", video: "vet-inte-01663-fras-3.mp4" },
    { word: "Jag älskar dig.", video: "alska-06012-fras-1.mp4" },
    { word: "Jag älskar lasagne.", video: "lasagne-09944-fras-1.mp4" },
    { word: "Kaffet är svagt.", video: "svag-00970-fras-2.mp4" },
    { word: "Kalle är godkänd.", video: "godkanna-02631-fras-4.mp4" },
    { word: "Kasta inte kvittot!", video: "kvitto-12446-fras-1.mp4" },
    { word: "Kommer hen imorgon?", video: "han-00479-fras-1.mp4" },
    { word: "Koncentrera dig nu!", video: "koncentrera-07613-fras-1.mp4" },
    { word: "Känner du producenten?", video: "producent-00725-fras-1.mp4" },
    { word: "Köp aktier nu!", video: "aktie-03744-fras-2.mp4" },
    { word: "Mamma nöjesläste tidningen.", video: "tidning-05203-fras-1.mp4" },
    { word: "Mikromat är bekvämt.", video: "enkelt-11877-fras-3.mp4" },
    { word: "När slutar kursen?", video: "kurs-01259-fras-1.mp4" },
    { word: "Sluta fåna dig!", video: "bete-sig-fanigt-01292-fras-3.mp4" },
    { word: "Snart börjar finalen.", video: "final-00251-fras-1.mp4" },
    { word: "Snart börjar fotbollsfinalen.", video: "final-00251-fras-2.mp4" },
    { word: "Stör mig inte!", video: "stora-00353-fras-3.mp4" },
    { word: "Undersökte läkaren dig?", video: "doktor-00033-fras-2.mp4" },
    { word: "Uteliggarna är hemlösa.", video: "hemlos-19811-fras-1.mp4" },
    { word: "Vad tycker du?", video: "tycka-00182-fras-2.mp4" },
    { word: "Var bor du?", video: "bo-00050-fras-1.mp4" },
    { word: "Var är tändstickorna?", video: "tandsticka-03388-fras-1.mp4" },
    { word: "Vi ses imorgon.", video: "ses-19004-fras-1.mp4" },
    { word: "Vänta, jag återkommer.", video: "aterkomma-00296-fras-1.mp4" },
    { word: "Är du nervös?", video: "nervos-01072-fras-1.mp4" },
    { word: "Är du sjuk?", video: "du-02817-fras-2.mp4" },
    { word: "Är du trött?", video: "trott-00966-fras-1.mp4" },
    { word: "Är ni kompisar?", video: "kompisar-17327-fras-1.mp4" },
    { word: "Är ni kusiner?", video: "kusin-04483-fras-1.mp4" },
    { word: "Är vi överens?", video: "overens-04951-fras-2.mp4" }
  ]
});
