(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "handalfabetet",
  name: "Handalfabetet",
  words: [
    { word: "i", video: "i-11929-tecken.mp4" },
    { word: "t", video: "t-11940-tecken.mp4", gloss: "T@b" },
    { word: "a", video: "a-09531-tecken.mp4", gloss: "A@b" },
    { word: "s", video: "s-11939-tecken.mp4", gloss: "S@b" },
    { word: "m", video: "m-11933-tecken.mp4", gloss: "M@b" },
    { word: "b", video: "b-09532-tecken.mp4", gloss: "B@b" },
    { word: "g", video: "g-11927-tecken.mp4", gloss: "G@b" },
    { word: "h", video: "h-11928-tecken.mp4" },
    { word: "j", video: "j-11930-tecken.mp4", gloss: "J@b" },
    { word: "e", video: "e-11925-tecken.mp4", gloss: "E@b" },
    { word: "o", video: "o-11935-tecken.mp4", gloss: "O@b" },
    { word: "l", video: "l-11932-tecken.mp4", gloss: "L@b" },
    { word: "f", video: "f-11926-tecken.mp4", gloss: "F@b" },
    { word: "k", video: "k-11931-tecken.mp4", gloss: "K@b" },
    { word: "c", video: "c-09011-tecken.mp4", gloss: "C@b" },
    { word: "å", video: "a-11947-tecken.mp4", gloss: "Å@b" },
    { word: "p", video: "p-11936-tecken.mp4", gloss: "P@b" },
    { word: "r", video: "r-11938-tecken.mp4", gloss: "R@b" },
    { word: "d", video: "d-09533-tecken.mp4", gloss: "D@b" },
    { word: "ö", video: "o-11949-tecken.mp4", gloss: "Ö@b" },
    { word: "w", video: "w-11943-tecken.mp4", gloss: "W@b" },
    { word: "n", video: "n-11934-tecken.mp4" },
    { word: "ä", video: "a-11948-tecken.mp4" },
    { word: "u", video: "u-11941-tecken.mp4", gloss: "U@b" },
    { word: "v", video: "v-11942-tecken.mp4", gloss: "V@b" },
    { word: "x", video: "x-11944-tecken.mp4" },
    { word: "q", video: "q-11937-tecken.mp4" },
    { word: "y", video: "y-11945-tecken.mp4" },
    { word: "z", video: "z-11946-tecken.mp4" }
  ]
});
