(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "kortafraser",
  name: "Korta fraser",
  words: [
    { word: "ASL", video: "asl-17584-tecken.mp4", gloss: "ASL@b" },
    { word: "Firefox", video: "firefox-17562-tecken.mp4" },
    { word: "Macintosh", video: "macintosh-05946-tecken.mp4" },
    { word: "Monster", video: "monster-18667-tecken.mp4" },
    { word: "Nike", video: "nike-16388-tecken.mp4" },
    { word: "Twitter", video: "twitter-03248-tecken.mp4" },
    { word: "abort", video: "abort-00865-tecken.mp4" },
    { word: "acceptera", video: "acceptera-09672-tecken.mp4", gloss: "ACCEPTERA(Jv)" },
    { word: "advokat", video: "advokat-04027-tecken.mp4", gloss: "ADVOKAT" },
    { word: "aktie", video: "aktie-03744-tecken.mp4" },
    { word: "alla", video: "alla-07844-tecken.mp4", gloss: "ALLA" },
    { word: "ansikte", video: "ansikte-02544-tecken.mp4", gloss: "ANSIKTE(L)" },
    { word: "antal", video: "antal-02859-tecken.mp4", gloss: "ANTAL" },
    { word: "arbeta", video: "arbeta-08062-tecken.mp4", gloss: "ARBETA(G)" },
    { word: "avgöra", video: "avgora-00250-tecken.mp4", gloss: "AVGÖRA" },
    { word: "avsky", video: "avsky-12048-tecken.mp4" },
    { word: "baby", video: "baby-00573-tecken.mp4", gloss: "BABY" },
    { word: "badkar", video: "badkar-00189-tecken.mp4", gloss: "BADA^KAR" },
    { word: "bakom", video: "bakom-00297-tecken.mp4", gloss: "BAKOM" },
    { word: "barn", video: "barn-00257-tecken.mp4", gloss: "BARN" },
    { word: "bedöva", video: "bedova-10554-tecken.mp4" },
    { word: "bege sig hem", video: "bege-sig-hem-10533-tecken.mp4", gloss: "BEGE-SIG-HEM" },
    { word: "behöva", video: "behova-04769-tecken.mp4", gloss: "BEHÖVA(B)" },
    { word: "behöver inte", video: "behover-inte-00118-tecken.mp4", gloss: "BEHÖVA(J)|INTE" },
    { word: "besvärlig", video: "besvarlig-02295-tecken.mp4", gloss: "BESVÄRLIG" },
    { word: "betala", video: "betala-02433-tecken.mp4", gloss: "BETALA(B)" },
    { word: "bete sig fånigt", video: "bete-sig-fanigt-01292-tecken.mp4" },
    { word: "bil", video: "bil-02158-tecken.mp4", gloss: "BIL" },
    { word: "blåbärskräm", video: "blabarskram-09958-tecken.mp4" },
    { word: "bo", video: "bo-00050-tecken.mp4", gloss: "BO" },
    { word: "bok", video: "bok-00610-tecken.mp4", gloss: "BOK" },
    { word: "bruka", video: "bruka-02712-tecken.mp4", gloss: "BRUKA" },
    { word: "bullar", video: "bullar-10959-tecken.mp4" },
    { word: "bättre", video: "battre-07101-tecken.mp4", gloss: "BÄTTRE(J>B)" },
    { word: "börja", video: "borja-03852-tecken.mp4" },
    { word: "celibat", video: "celibat-19857-tecken.mp4" },
    { word: "cigarett", video: "cigarett-04122-tecken.mp4", gloss: "CIGARETT-RÖKA" },
    { word: "dagar", video: "dagar-16261-tecken.mp4", gloss: "DAGAR" },
    { word: "din", video: "din-00275-tecken.mp4", gloss: "POSS" },
    { word: "diska", video: "diska-02081-tecken.mp4", gloss: "DISKA" },
    { word: "doktor", video: "doktor-00033-tecken.mp4", gloss: "DOKTOR" },
    { word: "dotter", video: "dotter-00111-tecken.mp4", gloss: "DOTTER(J)" },
    { word: "dricka", video: "dricka-01377-tecken.mp4", gloss: "DRICKA" },
    { word: "du", video: "du-02817-tecken.mp4", gloss: "PEK" },
    { word: "duscha", video: "duscha-10520-tecken.mp4", gloss: "DUSCHA" },
    { word: "döv", video: "dov-02686-tecken.mp4", gloss: "DÖV(L)" },
    { word: "egentligen", video: "egentligen-03955-tecken.mp4", gloss: "PI" },
    { word: "enkelt", video: "enkelt-11877-tecken.mp4" },
    { word: "falsk", video: "falsk-03487-tecken.mp4", gloss: "FALSK" },
    { word: "farmor", video: "farmor-01933-tecken.mp4", gloss: "FARMOR" },
    { word: "favoritfärg", video: "favoritfarg-19921-tecken.mp4" },
    { word: "fem", video: "fem-11882-tecken.mp4", gloss: "FEM" },
    { word: "fem kronor", video: "fem-kronor-01182-tecken.mp4", gloss: "KRONA+FEM" },
    { word: "final", video: "final-00251-tecken.mp4", gloss: "FINAL" },
    { word: "flyga", video: "flyga-04496-tecken.mp4", gloss: "FLYGA(It)" },
    { word: "fråga", video: "fraga-04568-tecken.mp4", gloss: "FRÅGA" },
    { word: "fylla år", video: "fylla-ar-00545-tecken.mp4", gloss: "FYLLA-ÅR(J)" },
    { word: "färdig", video: "fardig-00310-tecken.mp4", gloss: "FÄRDIG" },
    { word: "färg", video: "farg-04007-tecken.mp4", gloss: "FÄRG(N)" },
    { word: "få", video: "fa-00193-tecken.mp4", gloss: "FÅ1" },
    { word: "får", video: "far-04143-tecken.mp4", gloss: "FÅR(V)" },
    { word: "född", video: "fodd-07278-tecken.mp4", gloss: "FÖDD" },
    { word: "fönster", video: "fonster-00737-tecken.mp4", gloss: "FÖNSTER(Jvs)" },
    { word: "föredra", video: "foredra-02616-tecken.mp4", gloss: "FÖREDRA" },
    { word: "försenad", video: "forsenad-04808-tecken.mp4" },
    { word: "förskingra", video: "forskingra-00829-tecken.mp4" },
    { word: "ge sig iväg", video: "ge-sig-ivag-03281-tecken.mp4", gloss: "BEGE-SIG-IVÄG" },
    { word: "gift", video: "gift-00647-tecken.mp4", gloss: "GIFT" },
    { word: "glitter", video: "glitter-18681-tecken.mp4" },
    { word: "godkänna", video: "godkanna-02631-tecken.mp4", gloss: "GODKÄNNA" },
    { word: "golf", video: "golf-14156-tecken.mp4", gloss: "GOLF" },
    { word: "gott om", video: "gott-om-05106-tecken.mp4", gloss: "GOTT-OM" },
    { word: "grubbla", video: "grubbla-00793-tecken.mp4" },
    { word: "gå", video: "ga-04238-tecken.mp4", gloss: "GÅ" },
    { word: "han", video: "han-00479-tecken.mp4", gloss: "PEK" },
    { word: "har gjort", video: "har-gjort-00699-tecken.mp4", gloss: "PERF" },
    { word: "hemlös", video: "hemlos-19811-tecken.mp4" },
    { word: "hemma", video: "hemma-00683-tecken.mp4", gloss: "HEMMA" },
    { word: "heta", video: "heta-02892-tecken.mp4", gloss: "HETA" },
    { word: "himmel", video: "himmel-00005-tecken.mp4", gloss: "HIMMEL" },
    { word: "hitta på", video: "hitta-pa-14309-tecken.mp4", gloss: "HITTA-PÅ(4)" },
    { word: "hungrig", video: "hungrig-04868-tecken.mp4", gloss: "HUNGRIG" },
    { word: "hur", video: "hur-04569-tecken.mp4", gloss: "HUR" },
    { word: "hur många", video: "hur-manga-01062-tecken.mp4", gloss: "HUR-MÅNGA" },
    { word: "hälsa", video: "halsa-00076-tecken.mp4" },
    { word: "hämta", video: "hamta-01547-tecken.mp4", gloss: "HÄMTA" },
    { word: "hörande", video: "horande-07687-tecken.mp4", gloss: "HÖRANDE" },
    { word: "i dag", video: "i-dag-17210-tecken.mp4", gloss: "IDAG" },
    { word: "inte", video: "inte-00646-tecken.mp4", gloss: "INTE" },
    { word: "internetanslutning", video: "internetanslutning-09976-tecken.mp4" },
    { word: "intresserad", video: "intresserad-00532-tecken.mp4", gloss: "INTRESSE" },
    { word: "jag", video: "jag-02798-tecken.mp4", gloss: "PRO1" },
    { word: "jaså", video: "jasa-04516-tecken.mp4", gloss: "PI-JASÅ" },
    { word: "jobba", video: "jobba-02063-tecken.mp4", gloss: "JOBBA" },
    { word: "jul", video: "jul-06912-tecken.mp4", gloss: "JUL" },
    { word: "kan", video: "kan-00022-tecken.mp4", gloss: "KAN" },
    { word: "karma", video: "karma-17954-tecken.mp4" },
    { word: "karusell", video: "karusell-07731-tecken.mp4" },
    { word: "kasta", video: "kasta-01784-tecken.mp4", gloss: "KASTA" },
    { word: "kille", video: "kille-05831-tecken.mp4", gloss: "KILLE" },
    { word: "klippa av", video: "klippa-av-07289-tecken.mp4" },
    { word: "klubba", video: "klubba-03830-tecken.mp4" },
    { word: "knappa fjärrkontroll", video: "knappa-fjarrkontroll-17333-tecken.mp4", gloss: "KNAPPA-FJÄRRKONTROLL" },
    { word: "kock", video: "kock-00503-tecken.mp4" },
    { word: "komma hit", video: "komma-hit-02809-tecken.mp4", gloss: "KOMMA-HIT(Lb)" },
    { word: "kompis", video: "kompis-02531-tecken.mp4", gloss: "KOMPIS" },
    { word: "kompisar", video: "kompisar-17327-tecken.mp4", gloss: "KOMPIS.PL" },
    { word: "koncentrera", video: "koncentrera-07613-tecken.mp4" },
    { word: "kosta", video: "kosta-01300-tecken.mp4", gloss: "KOSTA" },
    { word: "kurs", video: "kurs-01259-tecken.mp4", gloss: "KURS" },
    { word: "kusin", video: "kusin-04483-tecken.mp4", gloss: "KUSIN(I)" },
    { word: "kvitto", video: "kvitto-12446-tecken.mp4" },
    { word: "kylig", video: "kylig-01506-tecken.mp4", gloss: "KYLIG" },
    { word: "käbbla", video: "kabbla-07662-tecken.mp4", gloss: "KÄBBLA" },
    { word: "kökspapper", video: "kokspapper-07185-tecken.mp4" },
    { word: "kött", video: "kott-01913-tecken.mp4", gloss: "KÖTT" },
    { word: "lakan", video: "lakan-00140-tecken.mp4" },
    { word: "lasagne", video: "lasagne-09944-tecken.mp4" },
    { word: "lego", video: "lego-02456-tecken.mp4" },
    { word: "ligga", video: "ligga-04191-tecken.mp4", gloss: "LIGGA(V)" },
    { word: "ljus", video: "ljus-00512-tecken.mp4", gloss: "LJUS" },
    { word: "luft", video: "luft-00509-tecken.mp4", gloss: "LUFT" },
    { word: "lyckas", video: "lyckas-01553-tecken.mp4", gloss: "LYCKAS(ea)" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4", gloss: "LYSSNA" },
    { word: "läkarmottagning", video: "lakarmottagning-00470-tecken.mp4" },
    { word: "lära sig", video: "lara-sig-05564-tecken.mp4", gloss: "LÄRA-SIG" },
    { word: "lärare", video: "larare-01353-tecken.mp4", gloss: "LÄRARE" },
    { word: "lätt", video: "latt-00631-tecken.mp4", gloss: "LÄTT" },
    { word: "lång", video: "lang-01115-tecken.mp4", gloss: "LÅNG-PERSON(J)" },
    { word: "låsa", video: "lasa-07453-tecken.mp4", gloss: "LÅSA(ml)" },
    { word: "mamma", video: "mamma-00188-tecken.mp4", gloss: "MAMMA" },
    { word: "medlem", video: "medlem-00496-tecken.mp4", gloss: "MEDLEM" },
    { word: "mig", video: "mig-03622-tecken.mp4", gloss: "OBJPRO1" },
    { word: "morfar", video: "morfar-01937-tecken.mp4", gloss: "MORFAR" },
    { word: "moster", video: "moster-05632-tecken.mp4", gloss: "MOSTER" },
    { word: "mäta", video: "mata-17848-tecken.mp4", gloss: "MÄTA(BB)" },
    { word: "må", video: "ma-00173-tecken.mp4", gloss: "MÅ" },
    { word: "nacke", video: "nacke-00129-tecken.mp4" },
    { word: "natt", video: "natt-00516-tecken.mp4", gloss: "NATT" },
    { word: "nervös", video: "nervos-01072-tecken.mp4", gloss: "NERVÖS(5)" },
    { word: "ni", video: "ni-15855-tecken.mp4", gloss: "PEK.FL" },
    { word: "njuta", video: "njuta-08282-tecken.mp4", gloss: "NJUTA(da)" },
    { word: "nu", video: "nu-03965-tecken.mp4", gloss: "NU@b" },
    { word: "nummer sex", video: "nummer-sex-01324-tecken.mp4" },
    { word: "nyckel", video: "nyckel-03826-tecken.mp4", gloss: "NYCKEL" },
    { word: "när", video: "nar-03954-tecken.mp4", gloss: "NÄR" },
    { word: "nästa vecka", video: "nasta-vecka-08028-tecken.mp4", gloss: "VECKA-FRAMTID+EN" },
    { word: "opposition", video: "opposition-03772-tecken.mp4" },
    { word: "ordernummer", video: "ordernummer-09949-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4", gloss: "PAPPA" },
    { word: "pengar", video: "pengar-01282-tecken.mp4", gloss: "PENGAR(ea)" },
    { word: "penna", video: "penna-03378-tecken.mp4", gloss: "PENNA" },
    { word: "polis", video: "polis-05635-tecken.mp4", gloss: "POLIS" },
    { word: "producent", video: "producent-00725-tecken.mp4", gloss: "PRODUCENT" },
    { word: "promenera", video: "promenera-04240-tecken.mp4", gloss: "PROMENERA" },
    { word: "respekt", video: "respekt-00680-tecken.mp4", gloss: "RESPEKTERA" },
    { word: "rik", video: "rik-03375-tecken.mp4", gloss: "RIK" },
    { word: "se upp", video: "se-upp-07320-tecken.mp4", gloss: "SE|UPP" },
    { word: "semester", video: "semester-00676-tecken.mp4", gloss: "SEMESTER" },
    { word: "ses", video: "ses-19004-tecken.mp4" },
    { word: "sill", video: "sill-02896-tecken.mp4" },
    { word: "simma", video: "simma-00666-tecken.mp4", gloss: "SIMMA" },
    { word: "sisådär", video: "sisadar-00873-tecken.mp4", gloss: "SÅDÄR" },
    { word: "sjuk", video: "sjuk-08776-tecken.mp4", gloss: "SJUK" },
    { word: "sko", video: "sko-02224-tecken.mp4", gloss: "SKO" },
    { word: "skratta", video: "skratta-01704-tecken.mp4", gloss: "SKRATTA(5b)" },
    { word: "skynda", video: "skynda-02244-tecken.mp4", gloss: "SKYNDA" },
    { word: "sluta", video: "sluta-00312-tecken.mp4", gloss: "SLUTA" },
    { word: "slå vad", video: "sla-vad-00252-tecken.mp4", gloss: "SLÅ-VAD(J)" },
    { word: "snabb", video: "snabb-00847-tecken.mp4", gloss: "HÖG-HASTIGHET" },
    { word: "son", video: "son-01944-tecken.mp4", gloss: "SON" },
    { word: "sova", video: "sova-03253-tecken.mp4", gloss: "SOVA(7v)" },
    { word: "spela teater", video: "spela-teater-00302-tecken.mp4", gloss: "TEATER-SPELA" },
    { word: "sprida", video: "sprida-01882-tecken.mp4", gloss: "SPRIDA" },
    { word: "standardmjölk", video: "standardmjolk-12265-tecken.mp4" },
    { word: "stick", video: "stick-18671-tecken.mp4" },
    { word: "störa", video: "stora-00353-tecken.mp4", gloss: "STÖRA" },
    { word: "stövel", video: "stovel-01457-tecken.mp4", gloss: "STÖVEL(G)" },
    { word: "svag", video: "svag-00970-tecken.mp4" },
    { word: "svart", video: "svart-00017-tecken.mp4", gloss: "SVART" },
    { word: "synskadad", video: "synskadad-05358-tecken.mp4", gloss: "SYN^SKADA" },
    { word: "syskon", video: "syskon-03564-tecken.mp4", gloss: "SYSKON" },
    { word: "syster", video: "syster-03513-tecken.mp4", gloss: "SYSTER" },
    { word: "sällskapsspel", video: "sallskapsspel-17368-tecken.mp4" },
    { word: "tack", video: "tack-15805-tecken.mp4", gloss: "TACK" },
    { word: "taxi", video: "taxi-00001-tecken.mp4", gloss: "TAXI(J)" },
    { word: "teckna", video: "teckna-00998-tecken.mp4", gloss: "TECKNA" },
    { word: "texttelefon", video: "texttelefon-16551-tecken.mp4", gloss: "TEXTTELEFON" },
    { word: "tidning", video: "tidning-05203-tecken.mp4", gloss: "TIDNING" },
    { word: "titta", video: "titta-04101-tecken.mp4", gloss: "TITTA" },
    { word: "tolk", video: "tolk-05214-tecken.mp4", gloss: "TOLK" },
    { word: "torka", video: "torka-00510-tecken.mp4" },
    { word: "träna", video: "trana-02436-tecken.mp4", gloss: "TRÄNA(B)" },
    { word: "träningspass", video: "traningspass-18881-tecken.mp4" },
    { word: "tråkig", video: "trakig-17194-tecken.mp4", gloss: "TRÅKIG" },
    { word: "trött", video: "trott-00966-tecken.mp4", gloss: "TRÖTT" },
    { word: "tycka", video: "tycka-00182-tecken.mp4", gloss: "TYCKA" },
    { word: "tyst", video: "tyst-01867-tecken.mp4", gloss: "TYST" },
    { word: "tändsticka", video: "tandsticka-03388-tecken.mp4", gloss: "TÄNDSTICKA" },
    { word: "tåg", video: "tag-04408-tecken.mp4", gloss: "TÅG" },
    { word: "under", video: "under-00464-tecken.mp4", gloss: "UNDER" },
    { word: "ursäkta", video: "ursakta-00056-tecken.mp4", gloss: "URSÄKTA" },
    { word: "utan problem", video: "utan-problem-06706-tecken.mp4" },
    { word: "va", video: "va-16650-tecken.mp4", gloss: "VA@b" },
    { word: "var", video: "var-02847-tecken.mp4", gloss: "VAR" },
    { word: "vegetarian", video: "vegetarian-00919-tecken.mp4" },
    { word: "vet inte", video: "vet-inte-01663-tecken.mp4", gloss: "VETA|INTE" },
    { word: "vilodag", video: "vilodag-19219-tecken.mp4" },
    { word: "vodka", video: "vodka-00377-tecken.mp4" },
    { word: "väga", video: "vaga-12239-tecken.mp4" },
    { word: "välling", video: "valling-11845-tecken.mp4" },
    { word: "wienerbröd", video: "wienerbrod-03753-tecken.mp4" },
    { word: "älska", video: "alska-06012-tecken.mp4", gloss: "ÄLSKA" },
    { word: "är", video: "ar-00239-tecken.mp4", gloss: "VARA" },
    { word: "återkomma", video: "aterkomma-00296-tecken.mp4" },
    { word: "ödet", video: "odet-19149-tecken.mp4" },
    { word: "öppna", video: "oppna-15301-tecken.mp4", gloss: "ÖPPEN" },
    { word: "örhänge", video: "orhange-11915-tecken.mp4" },
    { word: "överens", video: "overens-04951-tecken.mp4", gloss: "ÖVERENS" }
  ],
  phrases: [
    { word: "ASL", phrase: "Hen använder rent [ASL].", video: "asl-17584-fras-1.mp4" },
    { word: "Firefox", phrase: "[Firefox] är en webbläsare.", video: "firefox-17562-fras-2.mp4" },
    { word: "Macintosh", phrase: "Jag använder endast [Macintosh].", video: "macintosh-05946-fras-1.mp4" },
    { word: "Monster", phrase: "[Monster] är min favoritdryck.", video: "monster-18667-fras-1.mp4" },
    { word: "Monster", phrase: "[Monster] är en energidryck.", video: "monster-18667-fras-2.mp4" },
    { word: "Nike", phrase: "Jag har [Nike] gympaskor.", video: "nike-16388-fras-1.mp4" },
    { word: "Twitter", phrase: "Många kändisar använder [Twitter].", video: "twitter-03248-fras-2.mp4" },
    { word: "abort", phrase: "Jag har gjort [abort].", video: "abort-00865-fras-2.mp4" },
    { word: "abort", phrase: "Har du gjort [abort]?", video: "abort-00865-fras-3.mp4" },
    { word: "acceptera", phrase: "Jag [accepterar].", video: "acceptera-09672-fras-1.mp4" },
    { word: "advokat", phrase: "Mitt drömjobb är [advokat].", video: "advokat-04027-fras-1.mp4" },
    { word: "advokat", phrase: "Mitt drömyrke är [advokat].", video: "advokat-18688-fras-1.mp4" },
    { word: "aktie", phrase: "Köp [aktier] nu!", video: "aktie-03744-fras-2.mp4" },
    { word: "alla", phrase: "Är [alla] här nu?", video: "alla-07844-fras-2.mp4" },
    { word: "ansikte", phrase: "Hur såg pojken ut?", video: "ansikte-02544-fras-2.mp4" },
    { word: "antal", phrase: "Dövföreningens medlemsantal har ökat.", video: "antal-02859-fras-1.mp4" },
    { word: "arbeta", phrase: "Vad [arbetar] du med?", video: "arbeta-08062-fras-1.mp4" },
    { word: "avgöra", phrase: "Sista målet är [avgörande].", video: "avgora-00250-fras-1.mp4" },
    { word: "avsky", phrase: "Jag [avskyr] ärtsoppa.", video: "avsky-12048-fras-2.mp4" },
    { word: "baby", phrase: "Jag tycker om bebisar.", video: "baby-00573-fras-1.mp4" },
    { word: "badkar", phrase: "Jag har [badkar] hemma.", video: "badkar-00189-fras-2.mp4" },
    { word: "bakom", phrase: "Katten är [bakom] soffan.", video: "bakom-00297-fras-3.mp4" },
    { word: "bakom", phrase: "Mobilladdaren är [bakom] soffan.", video: "bakom-05189-fras-2.mp4" },
    { word: "barn", phrase: "Jag har tre [barn].", video: "barn-00257-fras-3.mp4" },
    { word: "bedöva", phrase: "Bedövningen gör inte ont.", video: "bedova-10554-fras-1.mp4" },
    { word: "bege sig hem", phrase: "Jag ska hem nu.", video: "bege-sig-hem-10533-fras-2.mp4" },
    { word: "behöva", phrase: "Jag behöver 100 kronor!", video: "behova-04769-fras-1.mp4" },
    { word: "behöver inte", phrase: "Du [behöver inte] städa.", video: "behover-inte-00118-fras-1.mp4" },
    { word: "besvärlig", phrase: "Du är väldigt [besvärlig].", video: "besvarlig-02295-fras-3.mp4" },
    { word: "betala", phrase: "Man måste [betala] avgiften", video: "betala-02433-fras-2.mp4" },
    { word: "bete sig fånigt", phrase: "Sluta fåna dig!", video: "bete-sig-fanigt-01292-fras-3.mp4" },
    { word: "bil", phrase: "Min [bil] är svart.", video: "bil-02158-fras-2.mp4" },
    { word: "blåbärskräm", phrase: "[Blåbärskrämen] är riktigt smaskens.", video: "blabarskram-09958-fras-1.mp4" },
    { word: "blåbärskräm", phrase: "Mina barn föredrar [blåbärskräm].", video: "blabarskram-09958-fras-2.mp4" },
    { word: "bo", phrase: "Var [bor] du?", video: "bo-00050-fras-1.mp4" },
    { word: "bok", phrase: "Hon ögnade igenom [boken].", video: "bok-00610-fras-3.mp4" },
    { word: "bruka", phrase: "[Brukar] du laga mat?", video: "bruka-02712-fras-4.mp4" },
    { word: "bullar", phrase: "Hembakta [bullar] är bäst.", video: "bullar-10959-fras-1.mp4" },
    { word: "bättre", phrase: "Jag mår lite [bättre].", video: "battre-07101-fras-2.mp4" },
    { word: "börja", phrase: "Teatern [börjar] klockan sju.", video: "borja-03852-fras-1.mp4" },
    { word: "börja", phrase: "Starta nu!", video: "borja-03852-fras-3.mp4" },
    { word: "celibat", phrase: "Buddister lever i [celibat].", video: "celibat-19857-fras-2.mp4" },
    { word: "cigarett", phrase: "Har du [cigaretter]?", video: "cigarett-04122-fras-1.mp4" },
    { word: "dagar", phrase: "Vilka [dagar] jobbar du?", video: "dagar-16261-fras-2.mp4" },
    { word: "din", phrase: "Är det huset ditt?", video: "din-00275-fras-2.mp4" },
    { word: "diska", phrase: "Jag har inte [diskat].", video: "diska-02081-fras-2.mp4" },
    { word: "doktor", phrase: "Undersökte läkaren dig?", video: "doktor-00033-fras-2.mp4" },
    { word: "dotter", phrase: "Vad heter din [dotter]?", video: "dotter-00111-fras-2.mp4" },
    { word: "dotter", phrase: "Är hon din [dotter]?", video: "dotter-00111-fras-3.mp4" },
    { word: "dricka", phrase: "Va, drack alla vatten?", video: "dricka-01377-fras-4.mp4" },
    { word: "du", phrase: "Är [du] sjuk?", video: "du-02817-fras-2.mp4" },
    { word: "du", phrase: "Har [du] feber?", video: "du-02817-fras-3.mp4" },
    { word: "duscha", phrase: "Jag [duschar] varje morgon.", video: "duscha-10520-fras-1.mp4" },
    { word: "döv", phrase: "Är du inte [döv]?", video: "dov-02686-fras-3.mp4" },
    { word: "döv", phrase: "Jag är född [döv].", video: "dov-00042-fras-1.mp4" },
    { word: "döv", phrase: "När blev du [döv]?", video: "dov-00042-fras-3.mp4" },
    { word: "egentligen", phrase: "Är du verkligen trött?", video: "egentligen-03955-fras-3.mp4" },
    { word: "enkelt", phrase: "Mikromat är bekvämt.", video: "enkelt-11877-fras-3.mp4" },
    { word: "falsk", phrase: "Det finns [falska] människor.", video: "falsk-03487-fras-1.mp4" },
    { word: "farmor", phrase: "Är hon min [farmor]?", video: "farmor-01933-fras-1.mp4" },
    { word: "favoritfärg", phrase: "Röd är min [favoritfärg].", video: "favoritfarg-19921-fras-1.mp4" },
    { word: "fem", phrase: "Jag har [fem] barnbarn.", video: "fem-11882-fras-1.mp4" },
    { word: "fem kronor", phrase: "Jag samlar på femkronorsmynt.", video: "fem-kronor-01182-fras-2.mp4" },
    { word: "final", phrase: "Snart börjar [finalen].", video: "final-00251-fras-1.mp4" },
    { word: "final", phrase: "Snart börjar fotbollsfinalen.", video: "final-00251-fras-2.mp4" },
    { word: "flyga", phrase: "Flyg inte!", video: "flyga-04496-fras-1.mp4" },
    { word: "fråga", phrase: "Har du fler frågor?", video: "fraga-04568-fras-2.mp4" },
    { word: "fylla år", phrase: "När fyller du år?", video: "fylla-ar-00545-fras-2.mp4" },
    { word: "färdig", phrase: "Jag är [färdig] nu.", video: "fardig-00310-fras-1.mp4" },
    { word: "färg", phrase: "Vilken är din favoritfärg?", video: "farg-04007-fras-4.mp4" },
    { word: "färg", phrase: "Vad är din favoritfärg?", video: "farg-07727-fras-4.mp4" },
    { word: "få", phrase: "Jag ska [få] kattungar.", video: "fa-00193-fras-2.mp4" },
    { word: "får", phrase: "Ull kommer från [får].", video: "far-04143-fras-2.mp4" },
    { word: "född", phrase: "Var är du [född]?", video: "fodd-07278-fras-2.mp4" },
    { word: "fönster", phrase: "Stäng fönstret!", video: "fonster-00737-fras-2.mp4" },
    { word: "fönster", phrase: "Hen putsade fönstret noggrant.", video: "fonster-01045-fras-3.mp4" },
    { word: "föredra", phrase: "Vilken idrott gillar du?", video: "foredra-02616-fras-2.mp4" },
    { word: "försenad", phrase: "Varför är du [försenad]?", video: "forsenad-04808-fras-1.mp4" },
    { word: "förskingra", phrase: "Bankmannen [förskingrade] våra sparpengar.", video: "forskingra-00829-fras-1.mp4" },
    { word: "ge sig iväg", phrase: "Vilken tid sticker du?", video: "ge-sig-ivag-03281-fras-3.mp4" },
    { word: "gift", phrase: "Hen är inte [gift].", video: "gift-00647-fras-1.mp4" },
    { word: "glitter", phrase: "Min favoritfärg är [glitterosa].", video: "glitter-18681-fras-2.mp4" },
    { word: "godkänna", phrase: "Kalle är godkänd.", video: "godkanna-02631-fras-4.mp4" },
    { word: "golf", phrase: "Kan du spela [golf]?", video: "golf-14156-fras-3.mp4" },
    { word: "golf", phrase: "Ska du [golfa] idag?", video: "golf-14156-fras-4.mp4" },
    { word: "gott om", phrase: "Direktören är väldigt rik.", video: "gott-om-05106-fras-1.mp4" },
    { word: "grubbla", phrase: "Vad [grubblar] du på?", video: "grubbla-00793-fras-2.mp4" },
    { word: "gå", phrase: "[Gå] nu!", video: "ga-04238-fras-2.mp4" },
    { word: "han", phrase: "Kommer hen imorgon?", video: "han-00479-fras-1.mp4" },
    { word: "han", phrase: "Hen är väldigt snäll.", video: "han-00479-fras-3.mp4" },
    { word: "han", phrase: "Hen är från Norrland.", video: "han-00479-fras-4.mp4" },
    { word: "har gjort", phrase: "Jag har betalat medlemsavgiften.", video: "har-gjort-00699-fras-3.mp4" },
    { word: "hemlös", phrase: "Uteliggarna är [hemlösa].", video: "hemlos-19811-fras-1.mp4" },
    { word: "hemma", phrase: "Jag är [hemma] ikväll.", video: "hemma-00683-fras-2.mp4" },
    { word: "hemma", phrase: "Är du [hemma] ikväll?", video: "hemma-00683-fras-4.mp4" },
    { word: "hemma", phrase: "Jag glömde nyckeln [hemma].", video: "hemma-15960-fras-1.mp4" },
    { word: "heta", phrase: "Min bror heter Jan.", video: "heta-02892-fras-1.mp4" },
    { word: "heta", phrase: "Min katt heter Pelle.", video: "heta-02892-fras-2.mp4" },
    { word: "himmel", phrase: "Himlen är alldeles klarblå.", video: "himmel-00005-fras-1.mp4" },
    { word: "hitta på", phrase: "Är din historia påhittad?", video: "hitta-pa-14309-fras-1.mp4" },
    { word: "hungrig", phrase: "Är du inte [hungrig]?", video: "hungrig-04868-fras-2.mp4" },
    { word: "hur", phrase: "[Hur] kom du hit?", video: "hur-04569-fras-1.mp4" },
    { word: "hur många", phrase: "[Hur många] kommer?", video: "hur-manga-01062-fras-1.mp4" },
    { word: "hälsa", phrase: "[Hälsa] till din flickvän.", video: "halsa-00076-fras-3.mp4" },
    { word: "hämta", phrase: "[Hämta] kaffe!", video: "hamta-01547-fras-1.mp4" },
    { word: "hörande", phrase: "Nej, jag är [hörande].", video: "horande-07687-fras-2.mp4" },
    { word: "i dag", phrase: "Skönt med fredag idag!", video: "i-dag-17210-fras-1.mp4" },
    { word: "inte", phrase: "Du lyssnar [inte].", video: "inte-00646-fras-3.mp4" },
    { word: "inte", phrase: "Kalle är [inte] godkänd.", video: "inte-00646-fras-4.mp4" },
    { word: "internetanslutning", phrase: "Jag behöver fixa [internetanslutning].", video: "internetanslutning-09976-fras-1.mp4" },
    { word: "intresserad", phrase: "Är du fortfarande [intresserad]?", video: "intresserad-00532-fras-1.mp4" },
    { word: "jag", phrase: "[Jag] är inte godkänd.", video: "jag-02798-fras-2.mp4" },
    { word: "jaså", phrase: "[Jaså], du menar allvar.", video: "jasa-04516-fras-1.mp4" },
    { word: "jaså", phrase: "[Jaså], har hen flyttat", video: "jasa-04062-fras-1.mp4" },
    { word: "jobba", phrase: "[Jobbar] du i natt?", video: "jobba-02063-fras-1.mp4" },
    { word: "jobba", phrase: "Jag [jobbar] inte imorgon.", video: "jobba-02063-fras-4.mp4" },
    { word: "jul", phrase: "När är det [jul]?", video: "jul-06912-fras-3.mp4" },
    { word: "kan", phrase: "Jag [kan] köra båt.", video: "kan-00022-fras-1.mp4" },
    { word: "karma", phrase: "Tror du på [karma]?", video: "karma-17954-fras-2.mp4" },
    { word: "karusell", phrase: "Många barn föredrar [karuseller].", video: "karusell-07731-fras-2.mp4" },
    { word: "kasta", phrase: "[Kasta] bollen!", video: "kasta-01784-fras-3.mp4" },
    { word: "kille", phrase: "Är han din [kille]?", video: "kille-05831-fras-3.mp4" },
    { word: "klippa av", phrase: "Gå och klipp håret!", video: "klippa-av-07289-fras-1.mp4" },
    { word: "klubba", phrase: "Barn älskar godisklubbor!", video: "klubba-03830-fras-3.mp4" },
    { word: "knappa fjärrkontroll", phrase: "Stäng av TV:n!", video: "knappa-fjarrkontroll-17333-fras-4.mp4" },
    { word: "kock", phrase: "[Kockyrket] är verkligen tråkigt.", video: "kock-00503-fras-1.mp4" },
    { word: "komma hit", phrase: "Kom hit!", video: "komma-hit-02809-fras-1.mp4" },
    { word: "kompis", phrase: "Hen är min [kompis].", video: "kompis-02531-fras-4.mp4" },
    { word: "kompisar", phrase: "Är ni [kompisar]?", video: "kompisar-17327-fras-1.mp4" },
    { word: "koncentrera", phrase: "[Koncentrera] dig nu!", video: "koncentrera-07613-fras-1.mp4" },
    { word: "kosta", phrase: "[Kostar] kaffet åtta kronor?", video: "kosta-01300-fras-2.mp4" },
    { word: "kurs", phrase: "När slutar [kursen]?", video: "kurs-01259-fras-1.mp4" },
    { word: "kusin", phrase: "Är ni [kusiner]?", video: "kusin-04483-fras-1.mp4" },
    { word: "kvitto", phrase: "Kasta inte [kvittot]!", video: "kvitto-12446-fras-1.mp4" },
    { word: "kylig", phrase: "Det är [kyligt] ute.", video: "kylig-01506-fras-1.mp4" },
    { word: "käbbla", phrase: "Sluta tjafsa.", video: "kabbla-07662-fras-1.mp4" },
    { word: "käbbla", phrase: "Varför tjafsar ni två?", video: "kabbla-07662-fras-2.mp4" },
    { word: "kökspapper", phrase: "Kan jag få hushållspapperet!", video: "kokspapper-07185-fras-2.mp4" },
    { word: "kött", phrase: "Hen äter inte [kött].", video: "kott-01913-fras-2.mp4" },
    { word: "lakan", phrase: "Jag ska byta [lakan].", video: "lakan-00140-fras-2.mp4" },
    { word: "lasagne", phrase: "Jag älskar [lasagne].", video: "lasagne-09944-fras-1.mp4" },
    { word: "lego", phrase: "Många småbarn älskar [lego].", video: "lego-02456-fras-1.mp4" },
    { word: "ligga", phrase: "Uddevalla ligger nära Vänersborg.", video: "ligga-04191-fras-1.mp4" },
    { word: "ljus", phrase: "Min favoritfärg är [ljusblå].", video: "ljus-00512-fras-2.mp4" },
    { word: "luft", phrase: "Provet handlar om [luften].", video: "luft-00509-fras-2.mp4" },
    { word: "lyckas", phrase: "Jag lyckades ta körkort.", video: "lyckas-01553-fras-2.mp4" },
    { word: "lyssna", phrase: "[Lyssna]!", video: "lyssna-00044-fras-4.mp4" },
    { word: "läkarmottagning", phrase: "Vilken är din [läkarmottagning]?", video: "lakarmottagning-00470-fras-1.mp4" },
    { word: "lära sig", phrase: "Jag lärde mig ingenting!", video: "lara-sig-05564-fras-1.mp4" },
    { word: "lärare", phrase: "Jag vill bli [lärare].", video: "larare-01353-fras-1.mp4" },
    { word: "lärare", phrase: "Vill du bli [lärare]?", video: "larare-01353-fras-2.mp4" },
    { word: "lätt", phrase: "Du är [lättlurad].", video: "latt-00631-fras-1.mp4" },
    { word: "lång", phrase: "Alla basketspelare är [långa].", video: "lang-01115-fras-2.mp4" },
    { word: "låsa", phrase: "Varför är dörren låst?", video: "lasa-07453-fras-1.mp4" },
    { word: "mamma", phrase: "[Mamma] är alltid bäst!", video: "mamma-00188-fras-1.mp4" },
    { word: "medlem", phrase: "Hen är inte [medlem].", video: "medlem-00496-fras-2.mp4" },
    { word: "medlem", phrase: "Är du inte [medlem]?", video: "medlem-00496-fras-3.mp4" },
    { word: "mig", phrase: "Hjälp [mig]!", video: "mig-03622-fras-2.mp4" },
    { word: "mig", phrase: "Hjälp [mig] inte!", video: "mig-03622-fras-3.mp4" },
    { word: "morfar", phrase: "Min [morfar] heter Anders.", video: "morfar-01937-fras-1.mp4" },
    { word: "moster", phrase: "Hon är min [moster].", video: "moster-05632-fras-1.mp4" },
    { word: "mäta", phrase: "Har du mätt väggen?", video: "mata-17848-fras-2.mp4" },
    { word: "må", phrase: "Jag [mår] bättre nu.", video: "ma-00173-fras-2.mp4" },
    { word: "må", phrase: "Hur [mår] du inombords?", video: "ma-00173-fras-3.mp4" },
    { word: "nacke", phrase: "Är din [nacke] okej?", video: "nacke-00129-fras-2.mp4" },
    { word: "natt", phrase: "På [natten] sover jag.", video: "natt-00516-fras-4.mp4" },
    { word: "nervös", phrase: "Är du [nervös]?", video: "nervos-01072-fras-1.mp4" },
    { word: "nervös", phrase: "Varför är du [nervös]?", video: "nervos-01654-fras-2.mp4" },
    { word: "ni", phrase: "Paketet är till er.", video: "ni-15855-fras-2.mp4" },
    { word: "njuta", phrase: "Njut!", video: "njuta-08282-fras-4.mp4" },
    { word: "nu", phrase: "Jag måste sticka [nu].", video: "nu-03965-fras-2.mp4" },
    { word: "nu", phrase: "Nej, matchen spelas [nu].", video: "nu-11274-fras-3.mp4" },
    { word: "nummer sex", phrase: "Sex är mitt turnummer.", video: "nummer-sex-01324-fras-1.mp4" },
    { word: "nyckel", phrase: "Glömde du [nyckeln] hemma?", video: "nyckel-03826-fras-2.mp4" },
    { word: "när", phrase: "[När] ska du träna?", video: "nar-03954-fras-3.mp4" },
    { word: "nästa vecka", phrase: "Jag jobbar [nästa vecka].", video: "nasta-vecka-08028-fras-2.mp4" },
    { word: "opposition", phrase: "Är din [opposition] färdig?", video: "opposition-03772-fras-1.mp4" },
    { word: "opposition", phrase: "Rektorn har många opponenter.", video: "opposition-03772-fras-3.mp4" },
    { word: "ordernummer", phrase: "Mitt [ordernummer] är 0481.", video: "ordernummer-09949-fras-1.mp4" },
    { word: "pappa", phrase: "Är han din [pappa]?", video: "pappa-02557-fras-1.mp4" },
    { word: "pappa", phrase: "[Pappa] är väldigt lång.", video: "pappa-02557-fras-2.mp4" },
    { word: "pengar", phrase: "Har du inga [pengar]?", video: "pengar-01282-fras-3.mp4" },
    { word: "penna", phrase: "Köp inte fler pennor!", video: "penna-03378-fras-1.mp4" },
    { word: "polis", phrase: "[Polisyrket] verkar riktigt roligt.", video: "polis-05635-fras-1.mp4" },
    { word: "producent", phrase: "Känner du [producenten]?", video: "producent-00725-fras-1.mp4" },
    { word: "producent", phrase: "Filmens [producent] heter Kevin.", video: "producent-00725-fras-2.mp4" },
    { word: "promenera", phrase: "Gå ut och [promenera]!", video: "promenera-04240-fras-2.mp4" },
    { word: "respekt", phrase: "Var är din [respekt]?", video: "respekt-00680-fras-2.mp4" },
    { word: "rik", phrase: "Jag är inte [rik].", video: "rik-03375-fras-1.mp4" },
    { word: "se upp", phrase: "[Se upp]!", video: "se-upp-07320-fras-2.mp4" },
    { word: "semester", phrase: "När har du [semester]?", video: "semester-00676-fras-1.mp4" },
    { word: "ses", phrase: "Vi [ses] imorgon.", video: "ses-19004-fras-1.mp4" },
    { word: "ses", phrase: "[Ses] vi nästa vecka?", video: "ses-19004-fras-3.mp4" },
    { word: "sill", phrase: "Jag gillar inte [sill].", video: "sill-02896-fras-2.mp4" },
    { word: "simma", phrase: "Sven kan inte [simma].", video: "simma-00666-fras-2.mp4" },
    { word: "sisådär", phrase: "Maten smakar inget vidare.", video: "sisadar-00873-fras-3.mp4" },
    { word: "sjuk", phrase: "Hen är inte [sjuk].", video: "sjuk-08776-fras-4.mp4" },
    { word: "sko", phrase: "[Skon] var väldigt liten.", video: "sko-02224-fras-1.mp4" },
    { word: "skratta", phrase: "Mamma [skrattar].", video: "skratta-01704-fras-1.mp4" },
    { word: "skynda", phrase: "[Skynda] dig och köp!", video: "skynda-02244-fras-2.mp4" },
    { word: "sluta", phrase: "Kan du [sluta] skrika!", video: "sluta-00312-fras-1.mp4" },
    { word: "sluta", phrase: "När [slutar] du idag?", video: "sluta-00312-fras-3.mp4" },
    { word: "slå vad", phrase: "Ska vi [slå vad]?", video: "sla-vad-00252-fras-1.mp4" },
    { word: "snabb", phrase: "Jag körde jättefort.", video: "snabb-00847-fras-1.mp4" },
    { word: "son", phrase: "Är det din [son]?", video: "son-01944-fras-3.mp4" },
    { word: "sova", phrase: "Sov nu!", video: "sova-03253-fras-2.mp4" },
    { word: "sova", phrase: "Gå och sov nu!", video: "sova-00049-fras-2.mp4" },
    { word: "spela teater", phrase: "Skojar du nu, eller?", video: "spela-teater-00302-fras-2.mp4" },
    { word: "sprida", phrase: "Rykten kan [spridas] snabbt.", video: "sprida-01882-fras-1.mp4" },
    { word: "standardmjölk", phrase: "[Standardmjölk] har 3 % fetthalt.", video: "standardmjolk-12265-fras-2.mp4" },
    { word: "stick", phrase: "Försvinn!", video: "stick-18671-fras-1.mp4" },
    { word: "störa", phrase: "Stör mig inte!", video: "stora-00353-fras-3.mp4" },
    { word: "stövel", phrase: "Flickan har gröna stövlar.", video: "stovel-01457-fras-1.mp4" },
    { word: "svag", phrase: "Kaffet är [svagt].", video: "svag-00970-fras-2.mp4" },
    { word: "svart", phrase: "Min tröja är [svart].", video: "svart-00017-fras-3.mp4" },
    { word: "synskadad", phrase: "Min bror är [synskadad].", video: "synskadad-05358-fras-1.mp4" },
    { word: "syskon", phrase: "Jag har tre [syskon].", video: "syskon-03564-fras-2.mp4" },
    { word: "syster", phrase: "Min [syster] är snäll.", video: "syster-03513-fras-2.mp4" },
    { word: "syster", phrase: "Har du någon [syster]?", video: "syster-18803-fras-1.mp4" },
    { word: "sällskapsspel", phrase: "Vill du spela brädspel?", video: "sallskapsspel-17368-fras-1.mp4" },
    { word: "tack", phrase: "Säg [tack] till hen!", video: "tack-15805-fras-2.mp4" },
    { word: "taxi", phrase: "Jag har beställt [taxi].", video: "taxi-00001-fras-2.mp4" },
    { word: "teckna", phrase: "[Teckna] tydligt!", video: "teckna-00998-fras-1.mp4" },
    { word: "texttelefon", phrase: "Jag har [texttelefon].", video: "texttelefon-16551-fras-1.mp4" },
    { word: "tidning", phrase: "Mamma nöjesläste [tidningen].", video: "tidning-05203-fras-1.mp4" },
    { word: "titta", phrase: "[Titta]!", video: "titta-04101-fras-1.mp4" },
    { word: "tolk", phrase: "Jag ser inte [tolken].", video: "tolk-05214-fras-3.mp4" },
    { word: "torka", phrase: "Jag älskar [torkade] äpplen.", video: "torka-00510-fras-1.mp4" },
    { word: "träna", phrase: "Imorgon ska jag [träna].", video: "trana-02436-fras-4.mp4" },
    { word: "träningspass", phrase: "Mitt favoritträningspass är benlyft.", video: "traningspass-18881-fras-1.mp4" },
    { word: "tråkig", phrase: "Jag har [tråkiga] nyheter.", video: "trakig-17194-fras-1.mp4" },
    { word: "trött", phrase: "Är du [trött]?", video: "trott-00966-fras-1.mp4" },
    { word: "tycka", phrase: "Vad tycker du?", video: "tycka-00182-fras-2.mp4" },
    { word: "tyst", phrase: "Var [tyst]!", video: "tyst-01867-fras-1.mp4" },
    { word: "tändsticka", phrase: "Var är tändstickorna?", video: "tandsticka-03388-fras-1.mp4" },
    { word: "tåg", phrase: "Kom det inget [tåg]?", video: "tag-04408-fras-1.mp4" },
    { word: "under", phrase: "Cigaretterna finns [under] bordet.", video: "under-00464-fras-1.mp4" },
    { word: "ursäkta", phrase: "[Ursäkta] att jag stör.", video: "ursakta-00056-fras-2.mp4" },
    { word: "utan problem", phrase: "Provet var verkligen enkelt.", video: "utan-problem-06706-fras-2.mp4" },
    { word: "va", phrase: "[Va], [vad] sa du?", video: "va-16650-fras-2.mp4" },
    { word: "var", phrase: "[Var] handlar du mat?", video: "var-02847-fras-3.mp4" },
    { word: "vegetarian", phrase: "Min kompis är [vegetarian].", video: "vegetarian-00919-fras-1.mp4" },
    { word: "vet inte", phrase: "Jag [vet inte].", video: "vet-inte-01663-fras-3.mp4" },
    { word: "vilodag", phrase: "Onsdagar är mina [vilodagar].", video: "vilodag-19219-fras-1.mp4" },
    { word: "vodka", phrase: "Jag gillar inte [vodka].", video: "vodka-00377-fras-2.mp4" },
    { word: "väga", phrase: "Jag väger 58 kilo.", video: "vaga-12239-fras-1.mp4" },
    { word: "väga", phrase: "Hur mycket väger du?", video: "vaga-05301-fras-1.mp4" },
    { word: "välling", phrase: "[Vällingpulver] innehåller mycket socker.", video: "valling-11845-fras-1.mp4" },
    { word: "wienerbröd", phrase: "Tycker du om [wienerbröd]?", video: "wienerbrod-03753-fras-3.mp4" },
    { word: "älska", phrase: "Jag [älskar] dig.", video: "alska-06012-fras-1.mp4" },
    { word: "är", phrase: "[Är] hen verkligen norrlänning?", video: "ar-00239-fras-2.mp4" },
    { word: "återkomma", phrase: "Vänta, jag återkommer.", video: "aterkomma-00296-fras-1.mp4" },
    { word: "ödet", phrase: "Tror du på [ödet]?", video: "odet-19149-fras-1.mp4" },
    { word: "öppna", phrase: "Affären [öppnar] klockan tio.", video: "oppna-15301-fras-1.mp4" },
    { word: "örhänge", phrase: "Brukar du använda [örhängen]?", video: "orhange-11915-fras-1.mp4" },
    { word: "överens", phrase: "Är vi [överens]?", video: "overens-04951-fras-2.mp4" }
  ]
});
