(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "mat1",
  name: "Mat och dryck 1",
  words: [
    { word: "vatten", video: "vatten-00132-tecken.mp4" },
    { word: "mat", video: "mat-01266-tecken.mp4" },
    { word: "kaffe", video: "kaffe-02042-tecken.mp4" },
    { word: "vin", video: "vin-04129-tecken.mp4" },
    { word: "middag", video: "middag-04024-tecken.mp4" },
    { word: "alkohol", video: "alkohol-09659-tecken.mp4" },
    { word: "rom", video: "rom-13060-tecken.mp4" },
    { word: "bröd", video: "brod-00434-tecken.mp4" },
    { word: "salt", video: "salt-03998-tecken.mp4" },
    { word: "öl", video: "ol-01793-tecken.mp4" },
    { word: "potatis", video: "potatis-05539-tecken.mp4" },
    { word: "lunch", video: "lunch-02756-tecken.mp4" },
    { word: "kött", video: "kott-01913-tecken.mp4" },
    { word: "banan", video: "banan-03309-tecken.mp4" },
    { word: "smör", video: "smor-00480-tecken.mp4" },
    { word: "mjölk", video: "mjolk-02184-tecken.mp4" },
    { word: "ägg", video: "agg-04013-tecken.mp4" },
    { word: "sprit", video: "sprit-02334-tecken.mp4" },
    { word: "socker", video: "socker-02920-tecken.mp4" },
    { word: "te", video: "te-05376-tecken.mp4" },
    { word: "frukt", video: "frukt-01923-tecken.mp4" },
    { word: "ris", video: "ris-09164-tecken.mp4" },
    { word: "ost", video: "ost-02449-tecken.mp4" },
    { word: "frukost", video: "frukost-03353-tecken.mp4" },
    { word: "livsmedel", video: "livsmedel-01265-tecken.mp4" },
    { word: "kärna", video: "karna-13861-tecken.mp4" },
    { word: "recept", video: "recept-03682-tecken.mp4" },
    { word: "röka", video: "roka-11843-tecken.mp4" },
    { word: "sallad", video: "sallad-04254-tecken.mp4" },
    { word: "korv", video: "korv-00916-tecken.mp4" },
    { word: "dryck", video: "dryck-11620-tecken.mp4" },
    { word: "sås", video: "sas-09206-tecken.mp4" },
    { word: "peppar", video: "peppar-01408-tecken.mp4" },
    { word: "mjöl", video: "mjol-00899-tecken.mp4" },
    { word: "grädde", video: "gradde-00420-tecken.mp4" },
    { word: "coca-cola", video: "coca-cola-09690-tecken.mp4" },
    { word: "celsius", video: "celsius-18766-tecken.mp4" },
    { word: "champagne", video: "champagne-01830-tecken.mp4" },
    { word: "vitlök", video: "vitlok-09067-tecken.mp4" },
    { word: "whisky", video: "whisky-01988-tecken.mp4" },
    { word: "soppa", video: "soppa-00599-tecken.mp4" },
    { word: "brännvin", video: "brannvin-03224-tecken.mp4" },
    { word: "ekologisk", video: "ekologisk-00517-tecken.mp4" },
    { word: "glass", video: "glass-03799-tecken.mp4" },
    { word: "citron", video: "citron-01508-tecken.mp4" },
    { word: "skinka", video: "skinka-00215-tecken.mp4" },
    { word: "olivolja", video: "olivolja-12825-tecken.mp4" },
    { word: "drink", video: "drink-12232-tecken.mp4" },
    { word: "senap", video: "senap-03970-tecken.mp4" },
    { word: "rester", video: "rester-17534-tecken.mp4" }
  ],
  phrases: [
    { word: "mat", phrase: "Vi måste handla [mat], vi ska ju ha fest på lördag.", video: "mat-01266-fras-1.mp4" },
    { word: "mat", phrase: "Vilken [mat] gillar du bäst?", video: "mat-01266-fras-2.mp4" },
    { word: "kaffe", phrase: "Jag dricker [kaffe] varje dag, ungefär 4 - 5 koppar brukar det bli.", video: "kaffe-02042-fras-1.mp4" },
    { word: "kaffe", phrase: "Förut drack jag mycket [kaffe] men nu försöker jag dra ner på det.", video: "kaffe-02042-fras-2.mp4" },
    { word: "middag", phrase: "Jag brukar äta [middag] vid åttatiden eftersom jag tränar och kommer hem sent.", video: "middag-04024-fras-1.mp4" },
    { word: "middag", phrase: "Jag har inte sagt att hen inte kommer på [middagen].", video: "middag-04024-fras-2.mp4" },
    { word: "alkohol", phrase: "[Alkohol] finns i till exempel vin, öl och rengöringsmedel.", video: "alkohol-09659-fras-1.mp4" },
    { word: "alkohol", phrase: "En del personer dricker [alkohol] för att fly från sina problem.", video: "alkohol-09659-fras-2.mp4" },
    { word: "alkohol", phrase: "Din andedräkt luktar [alkohol], drack du igår?", video: "alkohol-09659-fras-3.mp4" },
    { word: "bröd", phrase: "Nu ska jag baka [bröd]. Smaskens!", video: "brod-00434-fras-1.mp4" },
    { word: "bröd", phrase: "Vad är skillnaden på surdegsbröd och vanligt [bröd]?", video: "brod-00434-fras-2.mp4" },
    { word: "bröd", phrase: "Det finns olika sorters [bröd]; limpa, baguette med mera.", video: "brod-00434-fras-3.mp4" },
    { word: "potatis", phrase: "Förut åt man mycket [potatis] men så är det inte längre för nu kan man välja ris eller pasta istället.", video: "potatis-05539-fras-1.mp4" },
    { word: "potatis", phrase: "På sommaren är jag extra förtjust i färskt [potatis].", video: "potatis-05539-fras-2.mp4" },
    { word: "potatis", phrase: "Min familj har odlat [potatis] i flera generationer.", video: "potatis-05539-fras-3.mp4" },
    { word: "lunch", phrase: "Äter du [lunch] på jobbet?", video: "lunch-02756-fras-1.mp4" },
    { word: "kött", phrase: "Hen äter absolut inte [kött].", video: "kott-01913-fras-1.mp4" },
    { word: "kött", phrase: "Hen äter inte [kött].", video: "kott-01913-fras-2.mp4" },
    { word: "smör", phrase: "Du vill ha en [smörgås], men jag har inget [smör]. Hur gör vi nu då?", video: "smor-00480-fras-1.mp4" },
    { word: "smör", phrase: "Till det här receptet måste man ha [smör], men jag har inget.", video: "smor-00480-fras-2.mp4" },
    { word: "frukt", phrase: "Jag har handlat [frukt]. Allt som allt gick det på 20 kr.", video: "frukt-01923-fras-1.mp4" },
    { word: "ris", phrase: "Ikväll blir det [ris] och köttbullar till middag.", video: "ris-09164-fras-1.mp4" },
    { word: "frukost", phrase: "Jag äter alltid [frukost] för att orka hela dagen.", video: "frukost-03353-fras-1.mp4" },
    { word: "sallad", phrase: "I [salladen] är det tomat och gurka.", video: "sallad-04254-fras-1.mp4" },
    { word: "grädde", phrase: "Jag måste absolut ha [grädde] till chokladpudding.", video: "gradde-00420-fras-1.mp4" },
    { word: "brännvin", phrase: "Det finns olika sorters [brännvin] som vodka och whisky med mera.", video: "brannvin-03224-fras-1.mp4" },
    { word: "brännvin", phrase: "Vilken typ av [brännvin] är din favorit?", video: "brannvin-03224-fras-2.mp4" },
    { word: "glass", phrase: "Du har tjugo kronor och köper en [glass] som kostar sexton kronor. Hur mycket ska du få tillbaka?", video: "glass-03799-fras-1.mp4" },
    { word: "skinka", phrase: "När jag gör toast brukar jag fylla dem med ost och [skinka].", video: "skinka-00215-fras-1.mp4" }
  ]
});
