(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "mat2",
  name: "Mat och dryck 2",
  words: [
    { word: "äpple", video: "apple-01924-tecken.mp4" },
    { word: "honung", video: "honung-03269-tecken.mp4" },
    { word: "vodka", video: "vodka-00377-tecken.mp4" },
    { word: "saft", video: "saft-01425-tecken.mp4" },
    { word: "oliver", video: "oliver-24422-tecken.mp4" },
    { word: "köttbullar", video: "kottbullar-01140-tecken.mp4" },
    { word: "svartpeppar", video: "svartpeppar-12195-tecken.mp4" },
    { word: "fläsk", video: "flask-02343-tecken.mp4" },
    { word: "rödvin", video: "rodvin-12211-tecken.mp4" },
    { word: "konjak", video: "konjak-00355-tecken.mp4" },
    { word: "pasta", video: "pasta-06194-tecken.mp4" },
    { word: "morot", video: "morot-01927-tecken.mp4" },
    { word: "monster", video: "monster-18667-tecken.mp4" },
    { word: "gröt", video: "grot-01996-tecken.mp4" },
    { word: "gurka", video: "gurka-04837-tecken.mp4" },
    { word: "smörgås", video: "smorgas-00481-tecken.mp4" },
    { word: "kost", video: "kost-12237-tecken.mp4" },
    { word: "folköl", video: "folkol-05717-tecken.mp4" },
    { word: "saffran", video: "saffran-08648-tecken.mp4" },
    { word: "hamburgare", video: "hamburgare-04501-tecken.mp4" },
    { word: "paprika", video: "paprika-05636-tecken.mp4" },
    { word: "pizza", video: "pizza-02957-tecken.mp4" },
    { word: "bönor", video: "bonor-11326-tecken.mp4" },
    { word: "chips", video: "chips-17316-tecken.mp4" },
    { word: "potatismos", video: "potatismos-09105-tecken.mp4" },
    { word: "rödbetor", video: "rodbetor-10524-tecken.mp4" },
    { word: "krydda", video: "krydda-01407-tecken.mp4" },
    { word: "läsk", video: "lask-01831-tecken.mp4" },
    { word: "dill", video: "dill-11522-tecken.mp4" },
    { word: "kål", video: "kal-05342-tecken.mp4" },
    { word: "tårta", video: "tarta-03709-tecken.mp4" },
    { word: "efterrätt", video: "efterratt-03623-tecken.mp4" },
    { word: "förrätt", video: "forratt-09178-tecken.mp4" },
    { word: "buljong", video: "buljong-01466-tecken.mp4" },
    { word: "majs", video: "majs-05554-tecken.mp4" },
    { word: "kanel", video: "kanel-09052-tecken.mp4" },
    { word: "ingefära", video: "ingefara-04140-tecken.mp4" },
    { word: "apelsin", video: "apelsin-01236-tecken.mp4" },
    { word: "basilika", video: "basilika-19427-tecken.mp4" },
    { word: "kaviar", video: "kaviar-03710-tecken.mp4" },
    { word: "strösocker", video: "strosocker-09220-tecken.mp4" },
    { word: "jäst", video: "jast-09029-tecken.mp4" },
    { word: "sylt", video: "sylt-09223-tecken.mp4" },
    { word: "russin", video: "russin-12169-tecken.mp4" },
    { word: "gräslök", video: "graslok-02600-tecken.mp4" },
    { word: "tomat", video: "tomat-05402-tecken.mp4" },
    { word: "purjolök", video: "purjolok-04239-tecken.mp4" },
    { word: "timjan", video: "timjan-15869-tecken.mp4" },
    { word: "ketchup", video: "ketchup-04938-tecken.mp4" },
    { word: "sparris", video: "sparris-19285-tecken.mp4" }
  ],
  phrases: [
    { word: "vodka", phrase: "Förut drack jag mycket [vodka].", video: "vodka-00377-fras-1.mp4" },
    { word: "vodka", phrase: "Jag gillar inte [vodka].", video: "vodka-00377-fras-2.mp4" },
    { word: "vodka", phrase: "Du har hällt i alldeles för mycket [vodka] och för lite cola. Det är väldigt starkt!", video: "vodka-00377-fras-3.mp4" },
    { word: "konjak", phrase: "Jag brukar aldrig servera [konjak] till kaffet.", video: "konjak-00355-fras-1.mp4" },
    { word: "monster", phrase: "[Monster] är min favoritdryck.", video: "monster-18667-fras-1.mp4" },
    { word: "monster", phrase: "[Monster] är en energidryck.", video: "monster-18667-fras-2.mp4" },
    { word: "monster", phrase: "Det finns både [Monster] och Red Bull men jag föredrar [Monster].", video: "monster-18667-fras-3.mp4" },
    { word: "hamburgare", phrase: "Jag älskar [hamburgare] och pommes frites.", video: "hamburgare-04501-fras-1.mp4" },
    { word: "chips", phrase: "Jag har alltid [chips] när jag ska kolla på film eller bio.", video: "chips-17316-fras-1.mp4" },
    { word: "tårta", phrase: "Det finns en oskriven regel som säger att om man har födelsedag ska man bjuda på [tårta].", video: "tarta-03709-fras-1.mp4" },
    { word: "förrätt", phrase: "På lördag ska jag bjuda på middag hemma hos mig. Jag funderar på vilken [förrätt] jag ska bjuda på.", video: "forratt-09178-fras-1.mp4" }
  ]
});
