(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "siffror",
  name: "Siffror",
  words: [
    { word: "en", video: "en-02852-tecken.mp4", aliases: ["1"] },
    { word: "två", video: "tva-11879-tecken.mp4", aliases: ["2"] },
    { word: "andra", video: "andra-04621-tecken.mp4", aliases: ["2:a"] },
    { word: "första", video: "forsta-12054-tecken.mp4", aliases: ["1:a"] },
    { word: "tre", video: "tre-11880-tecken.mp4", aliases: ["3"] },
    { word: "fyra", video: "fyra-11881-tecken.mp4", aliases: ["4"] },
    { word: "fem", video: "fem-11882-tecken.mp4", aliases: ["5"] },
    { word: "tio", video: "tio-04475-tecken.mp4", aliases: ["10"] },
    { word: "sex", video: "sex-11950-tecken.mp4", aliases: ["6"] },
    { word: "tredje", video: "tredje-01129-tecken.mp4", aliases: ["3:e"] },
    { word: "sju", video: "sju-11884-tecken.mp4", aliases: ["7"] },
    { word: "åtta", video: "atta-11885-tecken.mp4", aliases: ["8"] },
    { word: "nio", video: "nio-11886-tecken.mp4", aliases: ["9"] },
    { word: "tolv", video: "tolv-11890-tecken.mp4", aliases: ["12"] },
    { word: "hundra", video: "hundra-04866-tecken.mp4", aliases: ["100"] },
    { word: "fjärde", video: "fjarde-01136-tecken.mp4", aliases: ["4:e"] },
    { word: "tusen", video: "tusen-03451-tecken.mp4", aliases: ["1000"] },
    { word: "elva", video: "elva-11953-tecken.mp4", aliases: ["11"] },
    { word: "miljon", video: "miljon-01027-tecken.mp4", aliases: ["1000000"] },
    { word: "femte", video: "femte-01842-tecken.mp4", aliases: ["5:e"] },
    { word: "tjugo", video: "tjugo-11898-tecken.mp4", aliases: ["20"] },
    { word: "femton", video: "femton-11893-tecken.mp4", aliases: ["15"] },
    { word: "trettio", video: "trettio-11908-tecken.mp4", aliases: ["30"] },
    { word: "sjätte", video: "sjatte-01155-tecken.mp4", aliases: ["6:e"] },
    { word: "femtio", video: "femtio-11910-tecken.mp4", aliases: ["50"] },
    { word: "miljard", video: "miljard-05069-tecken.mp4", aliases: ["1000000000"] },
    { word: "sjunde", video: "sjunde-01157-tecken.mp4", aliases: ["7:e"] },
    { word: "fjorton", video: "fjorton-11892-tecken.mp4", aliases: ["14"] },
    { word: "fyrtio", video: "fyrtio-11909-tecken.mp4", aliases: ["40"] },
    { word: "tretton", video: "tretton-11891-tecken.mp4", aliases: ["13"] },
    { word: "åttonde", video: "attonde-01159-tecken.mp4", aliases: ["8:e"] },
    { word: "sjutton", video: "sjutton-11895-tecken.mp4", aliases: ["17"] },
    { word: "noll", video: "noll-24273-tecken.mp4", aliases: ["0"] },
    { word: "sexton", video: "sexton-11894-tecken.mp4", aliases: ["16"] },
    { word: "arton", video: "arton-10280-tecken.mp4", aliases: ["18"] },
    { word: "tjugofem", video: "tjugofem-11903-tecken.mp4", aliases: ["25"] },
    { word: "sextio", video: "sextio-11911-tecken.mp4", aliases: ["60"] },
    { word: "nitton", video: "nitton-11897-tecken.mp4", aliases: ["19"] },
    { word: "åttio", video: "attio-11913-tecken.mp4", aliases: ["80"] },
    { word: "sjuttio", video: "sjuttio-11912-tecken.mp4", aliases: ["70"] },
    { word: "nittio", video: "nittio-11914-tecken.mp4", aliases: ["90"] },
    { word: "tjugofyra", video: "tjugofyra-11902-tecken.mp4", aliases: ["24"] },
    { word: "tjugotvå", video: "tjugotva-11900-tecken.mp4", aliases: ["22"] },
    { word: "tjugotre", video: "tjugotre-11901-tecken.mp4", aliases: ["23"] },
    { word: "tjugoåtta", video: "tjugoatta-11906-tecken.mp4", aliases: ["28"] },
    { word: "tjugoett", video: "tjugoett-11899-tecken.mp4", aliases: ["21"] },
    { word: "tjugosju", video: "tjugosju-11905-tecken.mp4", aliases: ["27"] },
    { word: "tjugosex", video: "tjugosex-11904-tecken.mp4", aliases: ["26"] },
    { word: "tjugonio", video: "tjugonio-11907-tecken.mp4", aliases: ["29"] },
    { word: "ett tusen", video: "ett-tusen-00965-tecken.mp4", aliases: ["1000"] },
    { word: "tio tusen", video: "tio-tusen-00976-tecken.mp4", aliases: ["10000"] },
    { word: "ett hundratusen", video: "ett-hundratusen-00982-tecken.mp4", aliases: ["100000"] },
    { word: "en miljon", video: "en-miljon-00987-tecken.mp4", aliases: ["1000000"] },
    { word: "en miljard", video: "en-miljard-01015-tecken.mp4", aliases: ["1000000000"] },
    { word: "ett hundra", video: "ett-hundra-01841-tecken.mp4", aliases: ["100"] }
  ],
  phrases: [
    { word: "en", phrase: "Förut hade jag två bilar men nu har jag bara [en] för att priset på bensin har stigit så mycket.", video: "en-02852-fras-1.mp4" },
    { word: "två", phrase: "Mina [två] halvsyskon har varsitt barn.", video: "tva-11879-fras-1.mp4" },
    { word: "andra", phrase: "Min bror är född [andra] januari.", video: "andra-04621-fras-1.mp4" },
    { word: "andra", phrase: "Nu startar [andra] halvleken i hockeymatchen på TV:n.", video: "andra-04621-fras-2.mp4" },
    { word: "första", phrase: "[Första] delen av en film brukar vara bra medan andra och tredje delen brukar vara betydligt sämre.", video: "forsta-12054-fras-1.mp4" },
    { word: "första", phrase: "Jag har sett [första] James Bond filmen sju gånger.", video: "forsta-12054-fras-2.mp4" },
    { word: "första", phrase: "Tidigare fanns det [första] klass och ekonomiklass på flyget. Så är det inte längre utan nu är det budgetklass och ekonomiklass som gäller.", video: "forsta-12054-fras-3.mp4" },
    { word: "tre", phrase: "Min kompis Peter har [tre] barn.", video: "tre-11880-fras-1.mp4" },
    { word: "fyra", phrase: "Emmas faster har [fyra] kusiner.", video: "fyra-11881-fras-1.mp4" },
    { word: "fyra", phrase: "Familjen Svenssons yngsta flicka är [fyra] år.", video: "fyra-11881-fras-2.mp4" },
    { word: "fem", phrase: "Jag har [fem] barnbarn.", video: "fem-11882-fras-1.mp4" },
    { word: "fem", phrase: "Det finns ett bra barnprogram, \"[Fem] myror är fler än fyra elefanter\".", video: "fem-11882-fras-2.mp4" },
    { word: "tio", phrase: "Peter fick [tio] parkeringsböter ifjol.", video: "tio-04475-fras-1.mp4" },
    { word: "tio", phrase: "De flesta duktiga fotbollsspelare brukar ofta ha siffran [tio] på ryggen.", video: "tio-04475-fras-2.mp4" },
    { word: "sex", phrase: "Sven som jobbar som fotograf har [sex] olika kameror.", video: "sex-11950-fras-1.mp4" },
    { word: "sex", phrase: "Hur mycket bensin går det i en full tank på bilen? 1. 6 liter. 2. 60 liter. 3. 600 liter.", video: "sex-11950-fras-2.mp4" },
    { word: "sju", phrase: "En vecka har [sju] dagar.", video: "sju-11884-fras-1.mp4" },
    { word: "åtta", phrase: "Jag har haft en tenta och den innehöll bara [åtta] frågor.", video: "atta-11885-fras-1.mp4" },
    { word: "nio", phrase: "Nu är min son [nio] år och om [nio] år kan han faktiskt ta körkort.", video: "nio-11886-fras-1.mp4" },
    { word: "nio", phrase: "Om det är [nio] personer är det faktiskt billigare att hyra en minibuss än att hyra två bilar.", video: "nio-11886-fras-2.mp4" },
    { word: "nio", phrase: "Jag har nyss köpt en kavaj som är lite ovanlig för den knäpps med [nio] stycken knappar.", video: "nio-11886-fras-3.mp4" },
    { word: "nio", phrase: "Min granne som bor ovanför mig har [nio] stycken kaniner.", video: "nio-11886-fras-4.mp4" },
    { word: "tolv", phrase: "Jag har [tolv] enkronor i fickan.", video: "tolv-11890-fras-1.mp4" },
    { word: "tolv", phrase: "Det är bara [tolv] biljetter kvar till dövas filmfestival.", video: "tolv-11890-fras-2.mp4" },
    { word: "tolv", phrase: "Det är lunch mellan halv [tolv] och ett.", video: "tolv-11890-fras-3.mp4" },
    { word: "fjärde", phrase: "När jag tävlade i go-kart fick jag punktering i [fjärde] heatet. Det grämer mig så.", video: "fjarde-01136-fras-1.mp4" },
    { word: "fjärde", phrase: "Jag kan inte vara med på mötet den tjugonde januari. Kan vi flytta fram det till [fjärde] februari istället?", video: "fjarde-01136-fras-2.mp4" },
    { word: "elva", phrase: "Om [elva] dagar ska jag flyga till Skåne.", video: "elva-11953-fras-1.mp4" },
    { word: "femte", phrase: "Min katt har firat sin [femte] födelsedag.", video: "femte-01842-fras-1.mp4" },
    { word: "femte", phrase: "Först kör du rakt fram och när du ser ser första avfarten ska du strunta i den och svänga av vid den [femte].", video: "femte-01842-fras-2.mp4" },
    { word: "tjugo", phrase: "Fotbollslaget Leeds har förlorat [tjugo] matcher i rad. Helt klart kommer laget att bli nedflyttat.", video: "tjugo-11898-fras-1.mp4" },
    { word: "femton", phrase: "En bok med titeln \"Det blå havet\" kommer ut den 15 april.", video: "femton-11893-fras-1.mp4" },
    { word: "trettio", phrase: "Under den sista tiden har bensinpriset stigit med [trettio] procent.", video: "trettio-11908-fras-1.mp4" },
    { word: "trettio", phrase: "Jag skulle vilja ha en segelbåt på ca [trettio] fot men jag har inte råd.", video: "trettio-11908-fras-2.mp4" },
    { word: "sjätte", phrase: "Det är [sjätte] gången som skrivaren går sönder.", video: "sjatte-01155-fras-1.mp4" },
    { word: "sjätte", phrase: "Min kompis har varit med i en pokertävling med tusen deltagare. Det blev en [sjätteplacering] och det tycker jag är fantastiskt.", video: "sjatte-01155-fras-2.mp4" },
    { word: "femtio", phrase: "För nio år sedan köptes Volvo upp av bilföretaget Ford för [femtio] miljarder kronor.", video: "femtio-11910-fras-1.mp4" },
    { word: "sjunde", phrase: "Jag känner mig som om jag vore i [sjunde] himlen.", video: "sjunde-01157-fras-1.mp4" },
    { word: "fjorton", phrase: "Den [fjortonde] mars har Matilda namnsdag.", video: "fjorton-11892-fras-1.mp4" },
    { word: "fyrtio", phrase: "Jag vet att det förekommer något som brukar kallas för trettio års kris men frågan är om det finns en [fyrtio] års kris också.", video: "fyrtio-11909-fras-1.mp4" },
    { word: "tretton", phrase: "Fredagen den [trettonde] är en dag som många ogillar.", video: "tretton-11891-fras-1.mp4" },
    { word: "tretton", phrase: "Den 13 december är det Lucia", video: "tretton-11891-fras-2.mp4" },
    { word: "åttonde", phrase: "Stämmer det att du kommer och hälsar på mig [åttonde] januari?", video: "attonde-01159-fras-1.mp4" },
    { word: "åttonde", phrase: "Just idag är det [åttonde] gången som du hälsar på mig.", video: "attonde-01159-fras-2.mp4" },
    { word: "sjutton", phrase: "Om du vill övningsköra lastbil måste du vara minst [sjutton] år och sex månader.", video: "sjutton-11895-fras-1.mp4" },
    { word: "sjutton", phrase: "Vill du vara snäll och kopiera [sjutton] stycken åt mig.", video: "sjutton-11895-fras-2.mp4" },
    { word: "sexton", phrase: "Min syster Lenas äldsta barn fyller snart [sexton] år.", video: "sexton-11894-fras-1.mp4" },
    { word: "sexton", phrase: "Soffan som jag har beställt kommer om [sexton] dagar.", video: "sexton-11894-fras-2.mp4" },
    { word: "arton", phrase: "Många ungdomar brukar längta efter att fylla [arton] för då får de gå på puben", video: "arton-10280-fras-1.mp4" },
    { word: "tjugofem", phrase: "Min farfars födelsedag är 25 december.", video: "tjugofem-11903-fras-1.mp4" },
    { word: "tjugofem", phrase: "Det finns två typer av tävlingsbassänger. Det är 25 meters och 50 meters bassäng.", video: "tjugofem-11903-fras-2.mp4" },
    { word: "sextio", phrase: "Min pappa är [sextio] år och blir snart pensionär.", video: "sextio-11911-fras-1.mp4" },
    { word: "sextio", phrase: "Min pappa är [sextio] år och går i pension om fem år.", video: "sextio-11911-fras-2.mp4" },
    { word: "sextio", phrase: "Igår fyllde min granne [sextio] år.", video: "sextio-11911-fras-3.mp4" },
    { word: "nitton", phrase: "Hemma har jag en dataskärm som är 19 tum.", video: "nitton-11897-fras-1.mp4" },
    { word: "nitton", phrase: "Telefonnumret till Taxi Stockholm är 08 19 19 19.", video: "nitton-11897-fras-2.mp4" },
    { word: "nitton", phrase: "Min son är 19 år gammal.", video: "nitton-11897-fras-3.mp4" },
    { word: "åttio", phrase: "Jag har funderat på att köpa en ny bil, en Audi 80.", video: "attio-11913-fras-1.mp4" },
    { word: "sjuttio", phrase: "I Österrike finns en slalombacke som är enormt brant. Lutningen är hela [sjuttio] grader.", video: "sjuttio-11912-fras-1.mp4" },
    { word: "sjuttio", phrase: "En vanlig bastutemperatur i badhus brukar ligga på ca 70 grader.", video: "sjuttio-11912-fras-2.mp4" },
    { word: "nittio", phrase: "I vår familj har vi precis skaffat oss en gasolgrill. Den är 90 cm bred och 1,2 m hög.", video: "nittio-11914-fras-1.mp4" },
    { word: "nittio", phrase: "För tre år sedan vägde jag [nittio] kilo men nu har jag gått ner i vikt och väger åttiotre kilo.", video: "nittio-11914-fras-2.mp4" },
    { word: "tjugofyra", phrase: "Min adress är Grusvägen 24.", video: "tjugofyra-11902-fras-1.mp4" },
    { word: "tjugotvå", phrase: "Jag kan inte vara med den 22 maj. Kan vi inte ta det dagen därpå istället?", video: "tjugotva-11900-fras-1.mp4" },
    { word: "tjugotvå", phrase: "Nu är det bestämt att jag åker för att hälsar på min syster i England den 22 maj.", video: "tjugotva-11900-fras-2.mp4" },
    { word: "tjugotre", phrase: "Emma var hörande tills hon var 23. Då avtog hörseln och nu är hon döv.", video: "tjugotre-11901-fras-1.mp4" },
    { word: "tjugoåtta", phrase: "Under helgen som gick var det riktigt hett. Det var 28 grader här.", video: "tjugoatta-11906-fras-1.mp4" },
    { word: "tjugoåtta", phrase: "Titta i Aftonbladet på sidan 28 för där finns du med.", video: "tjugoatta-11906-fras-2.mp4" },
    { word: "tjugoett", phrase: "Av en gammal TV serie som heter Dallas har jag bara avsnitt ett till och med [tjugoett].", video: "tjugoett-11899-fras-1.mp4" },
    { word: "tjugoett", phrase: "Jag har tittat på tjugoen lägenheter utan att hitta någon som jag tycker är riktigt bra.", video: "tjugoett-11899-fras-2.mp4" },
    { word: "tjugosju", phrase: "James har nyligen kommit ut ur fängelset där han satt i [tjugosju] år.", video: "tjugosju-11905-fras-1.mp4" },
    { word: "tjugosju", phrase: "Jag har varit på [tjugosju] olika anställningsintervjuer utan att lyckas få något jobb.", video: "tjugosju-11905-fras-2.mp4" },
    { word: "tjugosex", phrase: "Jag har precis fått min tågbiljett. Jag fick vagn nummer nio och plats 26. Vad fick du?", video: "tjugosex-11904-fras-1.mp4" },
    { word: "tjugonio", phrase: "Min sambo är [tjugonio] år.", video: "tjugonio-11907-fras-1.mp4" },
    { word: "tjugonio", phrase: "För två veckor sedan var det en basketfinal som var så spännande för en av spelarna satte [tjugonio] poäng i sista perioden.", video: "tjugonio-11907-fras-2.mp4" },
    { word: "ett tusen", phrase: "Jag har ett lån på bilen och betalar av det med 1000 kr i månaden.", video: "ett-tusen-00965-fras-1.mp4" },
    { word: "ett tusen", phrase: "Ett par snygga jeans kostar ca 1000 kr.", video: "ett-tusen-00965-fras-2.mp4" },
    { word: "ett tusen", phrase: "Jag sparar 1000 kr i månaden till min kommande pension", video: "ett-tusen-00965-fras-3.mp4" },
    { word: "tio tusen", phrase: "Jag skulle vilja ha en villa med en stor tomt på ungefär [tio tusen] kvadrat meter.", video: "tio-tusen-00976-fras-1.mp4" },
    { word: "tio tusen", phrase: "Det är farligt att leka på tågtak därför att de strömförande ledningarna ovanför är på över [tio tusen] volt.", video: "tio-tusen-00976-fras-2.mp4" },
    { word: "ett hundratusen", phrase: "I dagsläget finns det ungefär 100.000 etanolbilar i Sverige.", video: "ett-hundratusen-00982-fras-1.mp4" },
    { word: "ett hundratusen", phrase: "I Borås bor det ca 100.000 invånare.", video: "ett-hundratusen-00982-fras-2.mp4" },
    { word: "en miljon", phrase: "I dagsläget finns det ca [en miljon] datavirus.", video: "en-miljon-00987-fras-1.mp4" },
    { word: "en miljon", phrase: "En lägenhet i Täby kostar ungefär [en miljon].", video: "en-miljon-00987-fras-2.mp4" },
    { word: "en miljon", phrase: "Glasriket i Småland brukar ha ca [en miljon] besökare per år.", video: "en-miljon-00987-fras-3.mp4" },
    { word: "en miljard", phrase: "Det har nyligen kommit en delårsrapport som visar att SAS har gjort en förlust på [en miljard].", video: "en-miljard-01015-fras-1.mp4" },
    { word: "ett hundra", phrase: "I videobutiker där man hyr filmer brukar det finnas något som heter Topp 100. De hundra bästa filmerna ligger då framme väl synliga.", video: "ett-hundra-01841-fras-1.mp4" },
    { word: "ett hundra", phrase: "Det bästa är att hålla en hastighet under 100 km/tim för då drar bilen inte så mycket bensin.", video: "ett-hundra-01841-fras-2.mp4" },
    { word: "ett hundra", phrase: "Hur många centimeter går det på en meter? 1. 10 centimeter. 2. 100 centimeter. 3. 1000 centimeter.", video: "ett-hundra-01841-fras-3.mp4" }
  ]
});
