(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "smaord",
  name: "Småord",
  words: [
    { word: "och", video: "och-00579-tecken.mp4", gloss: "OCH(J)" },
    { word: "i", video: "i-04473-tecken.mp4", gloss: "I@b" },
    { word: "på", video: "pa-00469-tecken.mp4", gloss: "PÅ" },
    { word: "att", video: "att-00224-tecken.mp4", gloss: "ATT" },
    { word: "som", video: "som-04289-tecken.mp4", gloss: "SOM" },
    { word: "av", video: "av-00335-tecken.mp4", gloss: "AV" },
    { word: "för", video: "for-02850-tecken.mp4", gloss: "FÖR" },
    { word: "med", video: "med-05055-tecken.mp4", gloss: "MED" },
    { word: "inte", video: "inte-00646-tecken.mp4", gloss: "INTE" },
    { word: "till", video: "till-00328-tecken.mp4", gloss: "TILL" },
    { word: "den", video: "den-03690-tecken.mp4" },
    { word: "han", video: "han-00479-tecken.mp4", gloss: "PEK" },
    { word: "om", video: "om-05133-tecken.mp4", gloss: "OM@b" },
    { word: "de", video: "de-20126-tecken.mp4", gloss: "PERSON.FL" },
    { word: "jag", video: "jag-02798-tecken.mp4", gloss: "PRO1" },
    { word: "från", video: "fran-00320-tecken.mp4", gloss: "FRÅN" },
    { word: "men", video: "men-02173-tecken.mp4", gloss: "MEN" },
    { word: "vi", video: "vi-05491-tecken.mp4", gloss: "PRO1.FL" },
    { word: "hon", video: "hon-05389-tecken.mp4", gloss: "HON@b" },
    { word: "också", video: "ocksa-04263-tecken.mp4", gloss: "OCKSÅ" },
    { word: "när", video: "nar-03954-tecken.mp4", gloss: "NÄR" },
    { word: "eller", video: "eller-04471-tecken.mp4", gloss: "ELLER" },
    { word: "mot", video: "mot-03109-tecken.mp4", gloss: "MOT" },
    { word: "under", video: "under-00464-tecken.mp4", gloss: "UNDER" },
    { word: "nu", video: "nu-03965-tecken.mp4", gloss: "NU@b" },
    { word: "efter", video: "efter-00289-tecken.mp4", gloss: "EFTER" },
    { word: "över", video: "over-00472-tecken.mp4", gloss: "ÖVER" },
    { word: "du", video: "du-02817-tecken.mp4", gloss: "PEK" },
    { word: "där", video: "dar-04726-tecken.mp4", gloss: "PEK-PLATS-DÄR" },
    { word: "mellan", video: "mellan-00374-tecken.mp4", gloss: "MELLAN" },
    { word: "vad", video: "vad-00644-tecken.mp4", gloss: "VAD" },
    { word: "då", video: "da-04724-tecken.mp4", gloss: "DÅ@b" },
    { word: "genom", video: "genom-00402-tecken.mp4", gloss: "GENOM" },
    { word: "sedan", video: "sedan-02845-tecken.mp4", gloss: "SEDAN(L)" },
    { word: "här", video: "har-02866-tecken.mp4", gloss: "PEK-PLATS-HÄR" },
    { word: "aldrig", video: "aldrig-00452-tecken.mp4", gloss: "ALDRIG-NÅGONSIN" },
    { word: "redan", video: "redan-00317-tecken.mp4", gloss: "REDAN" },
    { word: "utan", video: "utan-00382-tecken.mp4", gloss: "UTAN(ml)" },
    { word: "hos", video: "hos-03166-tecken.mp4", gloss: "HOS" },
    { word: "alltid", video: "alltid-02711-tecken.mp4", gloss: "ALLTID" },
    { word: "innan", video: "innan-00299-tecken.mp4", gloss: "INNAN" },
    { word: "ofta", video: "ofta-02966-tecken.mp4", gloss: "OFTA" },
    { word: "bakom", video: "bakom-00297-tecken.mp4", gloss: "BAKOM" },
    { word: "igen", video: "igen-03176-tecken.mp4", gloss: "IGEN" },
    { word: "ni", video: "ni-15855-tecken.mp4", gloss: "PEK.FL" },
    { word: "ibland", video: "ibland-03026-tecken.mp4", gloss: "IBLAND(L)" },
    { word: "framför", video: "framfor-00290-tecken.mp4", gloss: "FRAMFÖR" },
    { word: "vem", video: "vem-00123-tecken.mp4", gloss: "VEM(J)" },
    { word: "tills", video: "tills-09042-tecken.mp4", gloss: "TILL" },
    { word: "bredvid", video: "bredvid-03143-tecken.mp4" },
    { word: "är", video: "ar-00239-tecken.mp4", gloss: "VARA" },
    { word: "år", video: "ar-02861-tecken.mp4", gloss: "ÅR" },
    { word: "har", video: "ha-00958-tecken.mp4", gloss: "HA" },
    { word: "får", video: "far-04143-tecken.mp4", gloss: "FÅR(V)" },
    { word: "måste", video: "maste-02237-tecken.mp4", gloss: "MÅSTE" },
    { word: "kronor", video: "kronor-09044-tecken.mp4", gloss: "KR@b" },
    { word: "bli", video: "bli-03181-tecken.mp4", gloss: "BLI(L)" },
    { word: "många", video: "manga-01061-tecken.mp4", gloss: "MÅNGA" },
    { word: "sa", video: "sa-02749-tecken.mp4", gloss: "SA" },
    { word: "någon", video: "nagon-00483-tecken.mp4", gloss: "NÅGON" },
    { word: "gör", video: "gora-00563-tecken.mp4", gloss: "GÖRA" },
    { word: "mig", video: "mig-03622-tecken.mp4", gloss: "OBJPRO1" },
    { word: "vet", video: "vet-01862-tecken.mp4", gloss: "VETA-PERF" },
    { word: "inget", video: "ingen-10029-tecken.mp4", gloss: "INGEN" },
    { word: "min", video: "min-00187-tecken.mp4", gloss: "POSS1" },
    { word: "alla", video: "alla-07844-tecken.mp4", gloss: "ALLA" },
    { word: "ut", video: "ut-05459-tecken.mp4", gloss: "UT@b" },
    { word: "varje", video: "varje-02855-tecken.mp4", gloss: "VARJE(L)" },
    { word: "upp", video: "upp-05446-tecken.mp4", gloss: "UPP" },
    { word: "pengar", video: "pengar-01282-tecken.mp4", gloss: "PENGAR(ea)" },
    { word: "bättre", video: "battre-07101-tecken.mp4", gloss: "BÄTTRE(J>B)" },
    { word: "såg", video: "sag-00356-tecken.mp4", gloss: "SÅGA" },
    { word: "fortfarande", video: "fortfarande-00983-tecken.mp4", gloss: "FORTFARANDE(da)" },
    { word: "nästa", video: "nasta-05125-tecken.mp4", gloss: "NÄSTA(L)" },
    { word: "fler", video: "fler-04771-tecken.mp4" },
    { word: "inga", video: "noll-01789-tecken.mp4", gloss: "NOLL" },
    { word: "verkligen", video: "verkligen-03960-tecken.mp4", gloss: "VERKLIG" },
    { word: "dagar", video: "dagar-14989-tecken.mp4", gloss: "DAG.PL" },
    { word: "snart", video: "snart-03171-tecken.mp4", gloss: "SNART" },
    { word: "varför", video: "varfor-00561-tecken.mp4", gloss: "VARFÖR" },
    { word: "det", video: "den-03690-tecken.mp4" },
    { word: "dig", video: "dig-03639-tecken.mp4", gloss: "OBJPRO" },
    { word: "din", video: "din-00275-tecken.mp4", gloss: "POSS" },
    { word: "ditt", video: "din-00275-tecken.mp4", gloss: "POSS" },
    { word: "er", video: "er-15857-tecken.mp4", gloss: "POSS.FL" },
    { word: "hen", video: "hen-20131-tecken.mp4", gloss: "PEK" },
    { word: "mitt", video: "min-00187-tecken.mp4", gloss: "POSS1" },
    { word: "vilka", video: "vilka-05496-tecken.mp4", gloss: "VILKEN" },
    { word: "vilken", video: "vilken-00124-tecken.mp4", gloss: "VILKEN" },
    { word: "våra", video: "var-00186-tecken.mp4", gloss: "POSS1.FL" }
  ]
});
