(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "smaord",
  name: "Småord",
  words: [
    { word: "och", video: "och-00579-tecken.mp4" },
    { word: "i", video: "i-04473-tecken.mp4" },
    { word: "på", video: "pa-00469-tecken.mp4" },
    { word: "att", video: "att-00224-tecken.mp4" },
    { word: "som", video: "som-04289-tecken.mp4" },
    { word: "av", video: "av-00335-tecken.mp4" },
    { word: "för", video: "for-02850-tecken.mp4" },
    { word: "med", video: "med-05055-tecken.mp4" },
    { word: "inte", video: "inte-00646-tecken.mp4" },
    { word: "till", video: "till-00328-tecken.mp4" },
    { word: "den", video: "den-03690-tecken.mp4" },
    { word: "han", video: "han-00479-tecken.mp4" },
    { word: "om", video: "om-05133-tecken.mp4" },
    { word: "de", video: "de-20126-tecken.mp4" },
    { word: "jag", video: "jag-02798-tecken.mp4" },
    { word: "från", video: "fran-00320-tecken.mp4" },
    { word: "man", video: "man-05036-tecken.mp4" },
    { word: "men", video: "men-02173-tecken.mp4" },
    { word: "vi", video: "vi-05491-tecken.mp4" },
    { word: "hon", video: "hon-05389-tecken.mp4" },
    { word: "också", video: "ocksa-04263-tecken.mp4" },
    { word: "när", video: "nar-03954-tecken.mp4" },
    { word: "eller", video: "eller-04471-tecken.mp4" },
    { word: "mot", video: "mot-03109-tecken.mp4" },
    { word: "under", video: "under-00464-tecken.mp4" },
    { word: "nu", video: "nu-03965-tecken.mp4" },
    { word: "efter", video: "efter-00289-tecken.mp4" },
    { word: "över", video: "over-00472-tecken.mp4" },
    { word: "du", video: "du-02817-tecken.mp4" },
    { word: "där", video: "dar-04726-tecken.mp4" },
    { word: "mellan", video: "mellan-00374-tecken.mp4" },
    { word: "vad", video: "vad-00644-tecken.mp4" },
    { word: "då", video: "da-04724-tecken.mp4" },
    { word: "genom", video: "genom-00402-tecken.mp4" },
    { word: "sedan", video: "sedan-02845-tecken.mp4" },
    { word: "här", video: "har-02866-tecken.mp4" },
    { word: "aldrig", video: "aldrig-00452-tecken.mp4" },
    { word: "redan", video: "redan-00317-tecken.mp4" },
    { word: "utan", video: "utan-00382-tecken.mp4" },
    { word: "hos", video: "hos-03166-tecken.mp4" },
    { word: "alltid", video: "alltid-02711-tecken.mp4" },
    { word: "innan", video: "innan-00299-tecken.mp4" },
    { word: "ofta", video: "ofta-02966-tecken.mp4" },
    { word: "bakom", video: "bakom-00297-tecken.mp4" },
    { word: "igen", video: "igen-03176-tecken.mp4" },
    { word: "ni", video: "ni-15855-tecken.mp4" },
    { word: "ibland", video: "ibland-03026-tecken.mp4" },
    { word: "framför", video: "framfor-00290-tecken.mp4" },
    { word: "vem", video: "vem-00123-tecken.mp4" },
    { word: "tills", video: "tills-09042-tecken.mp4" },
    { word: "bredvid", video: "bredvid-03143-tecken.mp4" }
  ],
  phrases: [
    { word: "att", phrase: "Jag minns inte var jag har sett citatet ”[Att] vara eller inte vara”.", video: "att-00224-fras-1.mp4" },
    { word: "som", phrase: "Det händer ofta att barn tar efter samma beteende [som] föräldrarna har.", video: "som-04289-fras-1.mp4" },
    { word: "av", phrase: "När det gäller provet var det 12 [av] 20 som klarade det.", video: "av-00335-fras-1.mp4" },
    { word: "inte", phrase: "Många tror att jag är gift men det är faktiskt [inte] så.", video: "inte-00646-fras-1.mp4" },
    { word: "inte", phrase: "Jag klarar mig [inte] utan min mobil.", video: "inte-00646-fras-2.mp4" },
    { word: "inte", phrase: "Du lyssnar [inte].", video: "inte-00646-fras-3.mp4" },
    { word: "inte", phrase: "Kalle är [inte] godkänd.", video: "inte-00646-fras-4.mp4" },
    { word: "till", phrase: "Vilken sida i matteboken är det jag ska läsa [till] imorgon?", video: "till-00328-fras-1.mp4" },
    { word: "till", phrase: "Vilket stort paket! Vem ska få presenten?", video: "till-00328-fras-2.mp4" },
    { word: "han", phrase: "Kommer hen imorgon?", video: "han-00479-fras-1.mp4" },
    { word: "han", phrase: "Hen är väldigt snäll.", video: "han-00479-fras-3.mp4" },
    { word: "han", phrase: "Hen är från Norrland.", video: "han-00479-fras-4.mp4" },
    { word: "om", phrase: "[Om] det kommer 20 personer, då går jag.", video: "om-05133-fras-1.mp4" },
    { word: "om", phrase: "En kompis berättade för mig att hen sett en grön orm inne på toaletten. [Om] det det hade varit jag så hade jag svimmat!", video: "om-05133-fras-2.mp4" },
    { word: "jag", phrase: "[Jag] är inte hemma ikväll.", video: "jag-02798-fras-1.mp4" },
    { word: "jag", phrase: "[Jag] är inte godkänd.", video: "jag-02798-fras-2.mp4" },
    { word: "från", phrase: "[Från] Visby till Nynäshamn tar det ungefär tre timmar med båt.", video: "fran-00320-fras-1.mp4" },
    { word: "man", phrase: "Min systers [man] vet inte om att jag har fyra barn.", video: "man-05036-fras-1.mp4" },
    { word: "men", phrase: "Våren är så mysig. Man får vårkänslor och känner sig gladare. [Men] hösten är också härlig med starka färger som lyser upp tillvaron.", video: "men-02173-fras-1.mp4" },
    { word: "också", phrase: "Min dotter går på simskola. Min son vill [också] gå men han är för liten.", video: "ocksa-04263-fras-1.mp4" },
    { word: "också", phrase: "Jag vill resa och så vill jag köpa en bil.", video: "ocksa-04263-fras-2.mp4" },
    { word: "när", phrase: "Jag vet inte [när] filmen startar.", video: "nar-03954-fras-1.mp4" },
    { word: "när", phrase: "[När] kommer min bror hem ikväll?", video: "nar-03954-fras-2.mp4" },
    { word: "när", phrase: "[När] ska du träna?", video: "nar-03954-fras-3.mp4" },
    { word: "under", phrase: "Cigaretterna finns [under] bordet.", video: "under-00464-fras-1.mp4" },
    { word: "under", phrase: "Du får inte komma in där eftersom du är [under] arton år.", video: "under-00464-fras-2.mp4" },
    { word: "nu", phrase: "Var snäll och sluta tjata [nu].", video: "nu-03965-fras-1.mp4" },
    { word: "nu", phrase: "Jag måste sticka [nu].", video: "nu-03965-fras-2.mp4" },
    { word: "nu", phrase: "Sov [nu]!", video: "nu-03965-fras-3.mp4" },
    { word: "efter", phrase: "Jag har bestämt mig för att titta på TV först [efter] klockan åtta och inte före.", video: "efter-00289-fras-1.mp4" },
    { word: "över", phrase: "Du kan köra [över] bron från Sverige till Danmark.", video: "over-00472-fras-1.mp4" },
    { word: "över", phrase: "Vem bestämmer [över] mig på min arbetsplats? Jo, det är min chef.", video: "over-00472-fras-2.mp4" },
    { word: "över", phrase: "Lugna dig. Nu har du gått [över] gränsen, du måste sluta nu.", video: "over-00472-fras-3.mp4" },
    { word: "över", phrase: "Äntligen är utbildningen [över] efter 4 år.", video: "over-00472-fras-4.mp4" },
    { word: "du", phrase: "Jag har inte gjort det. Det var [du] som skulle göra det.", video: "du-02817-fras-1.mp4" },
    { word: "du", phrase: "Är [du] sjuk?", video: "du-02817-fras-2.mp4" },
    { word: "du", phrase: "Har [du] feber?", video: "du-02817-fras-3.mp4" },
    { word: "du", phrase: "[Du] har glömt att meddela mig.", video: "du-02817-fras-4.mp4" },
    { word: "mellan", phrase: "Vill du sitta [mellan] mig och pappa?", video: "mellan-00374-fras-1.mp4" },
    { word: "vad", phrase: "Vilken sport är du intresserad av?", video: "vad-00644-fras-1.mp4" },
    { word: "vad", phrase: "[Vad] har du för hobby eller intresse?", video: "vad-00644-fras-2.mp4" },
    { word: "vad", phrase: "[Vad] brukar du göra på fredagarna?", video: "vad-00644-fras-3.mp4" },
    { word: "vad", phrase: "[Vad] ska du göra imorgon kväll?", video: "vad-00644-fras-4.mp4" },
    { word: "då", phrase: "När jag var liten [då] var jag riktigt besvärlig.", video: "da-04724-fras-1.mp4" },
    { word: "då", phrase: "Om du inte betalar parkeringsavgiften [då] finns det risk att du får böter.", video: "da-04724-fras-2.mp4" },
    { word: "då", phrase: "Om du skvaller [då] blir jag förbannad.", video: "da-04724-fras-3.mp4" },
    { word: "då", phrase: "När jag och min bror var barn var jag längre än honom. Nu är han längre än mig.", video: "da-04724-fras-4.mp4" },
    { word: "här", phrase: "Är det hen som är nyanställd [här] på jobbet?", video: "har-02866-fras-1.mp4" },
    { word: "aldrig", phrase: "Jag har [aldrig] varit i Japan.", video: "aldrig-00452-fras-1.mp4" },
    { word: "aldrig", phrase: "Jag skulle [aldrig] våga klappa en orm.", video: "aldrig-00452-fras-2.mp4" },
    { word: "redan", phrase: "Tidningen annonserade om en skorea så jag skyndade mig till affären. Men det var [redan] slutsålt när jag kom dit.", video: "redan-00317-fras-1.mp4" },
    { word: "utan", phrase: "Vad är livet [utan] kärlek?", video: "utan-00382-fras-1.mp4" },
    { word: "alltid", phrase: "Min kompis kommer [alltid] sent.", video: "alltid-02711-fras-1.mp4" },
    { word: "alltid", phrase: "Jag åker [alltid] till sommarstugan varje sommar.", video: "alltid-02711-fras-2.mp4" },
    { word: "alltid", phrase: "Jag äter [alltid] gröt på morgonen för då klarar jag mig fram till lunch.", video: "alltid-02711-fras-3.mp4" },
    { word: "innan", phrase: "Vi gick och tog ett glas vin [innan] var och en åkte hem efter bion.", video: "innan-00299-fras-1.mp4" },
    { word: "ofta", phrase: "Förut var jag [ofta] sjuk men nu har jag inte varit det på länge.", video: "ofta-02966-fras-1.mp4" },
    { word: "bakom", phrase: "[Bakom] bordet finns det en låda som innehåller massor med saker.", video: "bakom-00297-fras-1.mp4" },
    { word: "bakom", phrase: "Förut fanns det en madrass placerad [bakom] soffan. Men den är borta nu. Var är den nånstans?", video: "bakom-00297-fras-2.mp4" },
    { word: "bakom", phrase: "Katten är [bakom] soffan.", video: "bakom-00297-fras-3.mp4" },
    { word: "ni", phrase: "När kan jag komma till er?", video: "ni-15855-fras-1.mp4" },
    { word: "ni", phrase: "Paketet är till er.", video: "ni-15855-fras-2.mp4" },
    { word: "ni", phrase: "Jag önskar er God Jul och Gott Nytt År.", video: "ni-15855-fras-3.mp4" },
    { word: "ni", phrase: "Jag har en fråga till er.", video: "ni-15855-fras-4.mp4" },
    { word: "vem", phrase: "[Vem] har tagit mina strumpor?", video: "vem-00123-fras-1.mp4" },
    { word: "vem", phrase: "Tanten som står där borta känner jag igen. [Vem] kan det vara?", video: "vem-00123-fras-2.mp4" },
    { word: "vem", phrase: "Nummerpresentatören är till för att man ska kunna se [vem] som har ringt.", video: "vem-00123-fras-3.mp4" }
  ]
});
