(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "sport1",
  name: "Sport 1",
  words: [
    { word: "spela", video: "spela-01162-tecken.mp4" },
    { word: "mål", video: "mal-02985-tecken.mp4" },
    { word: "vinna", video: "vinna-13561-tecken.mp4" },
    { word: "vm", video: "vm-08678-tecken.mp4" },
    { word: "match", video: "match-00979-tecken.mp4" },
    { word: "spelare", video: "spelare-14823-tecken.mp4" },
    { word: "pris", video: "pris-04328-tecken.mp4" },
    { word: "lag", video: "lag-08531-tecken.mp4" },
    { word: "start", video: "start-14854-tecken.mp4" },
    { word: "möta", video: "mota-02260-tecken.mp4" },
    { word: "period", video: "period-14590-tecken.mp4" },
    { word: "mil", video: "mil-02392-tecken.mp4" },
    { word: "publik", video: "publik-02218-tecken.mp4" },
    { word: "klass", video: "klass-05660-tecken.mp4" },
    { word: "tränare", video: "tranare-08652-tecken.mp4" },
    { word: "kamp", video: "kamp-02044-tecken.mp4" },
    { word: "säsong", video: "sasong-01110-tecken.mp4" },
    { word: "serie", video: "serie-01738-tecken.mp4" },
    { word: "förlora", video: "forlora-00810-tecken.mp4" },
    { word: "division", video: "division-08861-tecken.mp4" },
    { word: "plan", video: "plan-14599-tecken.mp4" },
    { word: "träning", video: "traning-13038-tecken.mp4" },
    { word: "genomsnitt", video: "genomsnitt-00404-tecken.mp4" },
    { word: "cup", video: "cup-08464-tecken.mp4" },
    { word: "final", video: "final-00251-tecken.mp4" },
    { word: "träna", video: "trana-01288-tecken.mp4" },
    { word: "springa", video: "springa-02208-tecken.mp4" },
    { word: "herrar", video: "herrar-14207-tecken.mp4" },
    { word: "straff", video: "straff-00345-tecken.mp4" },
    { word: "damer", video: "damer-13985-tecken.mp4" },
    { word: "skjuta", video: "skjuta-07690-tecken.mp4" },
    { word: "döma", video: "doma-11842-tecken.mp4" },
    { word: "tempo", video: "tempo-08640-tecken.mp4" },
    { word: "förbundskapten", video: "forbundskapten-14123-tecken.mp4" },
    { word: "rekord", video: "rekord-04184-tecken.mp4" },
    { word: "bana", video: "bana-03645-tecken.mp4" },
    { word: "sport", video: "sport-02521-tecken.mp4" },
    { word: "passa", video: "passa-05161-tecken.mp4" },
    { word: "målvakt", video: "malvakt-07725-tecken.mp4" },
    { word: "tävla", video: "tavla-02500-tecken.mp4" },
    { word: "idrott", video: "idrott-02519-tecken.mp4" },
    { word: "varv", video: "varv-13242-tecken.mp4" },
    { word: "dubbel", video: "dubbel-04256-tecken.mp4" },
    { word: "semifinal", video: "semifinal-08608-tecken.mp4" },
    { word: "omgång", video: "omgang-14556-tecken.mp4" },
    { word: "inomhus", video: "inomhus-02983-tecken.mp4" },
    { word: "mästare", video: "mastare-00219-tecken.mp4" },
    { word: "varning", video: "varning-13487-tecken.mp4" },
    { word: "anfall", video: "anfall-07671-tecken.mp4" },
    { word: "domare", video: "domare-03605-tecken.mp4" }
  ],
  phrases: [
    { word: "match", phrase: "Jag spelade [match] förra helgen och domaren avbröt spelet hela tiden genom att blåsa av samt utdela gula kort till mitt lag.", video: "match-00979-fras-1.mp4" },
    { word: "serie", phrase: "Jag spelar padel i [seriespel], nu är vi i [serie] 5.", video: "serie-01738-fras-1.mp4" },
    { word: "serie", phrase: "Det finns olika tävlingsformer, [serie] eller cup.", video: "serie-01738-fras-2.mp4" },
    { word: "förlora", phrase: "Attans! Vi [förlorade] i går.", video: "forlora-00810-fras-1.mp4" },
    { word: "cup", phrase: "Världens största fotbollscup för ungdomar 11 - 19 år heter Gothia [Cup].", video: "cup-08464-fras-1.mp4" },
    { word: "cup", phrase: "Svartberga Basketcup äger rum nästa helg.", video: "cup-08464-fras-2.mp4" },
    { word: "final", phrase: "Snart börjar [finalen].", video: "final-00251-fras-1.mp4" },
    { word: "final", phrase: "Snart börjar fotbollsfinalen.", video: "final-00251-fras-2.mp4" },
    { word: "final", phrase: "Imorgon är det [final] kl 14.", video: "final-00251-fras-3.mp4" },
    { word: "final", phrase: "Det blir en väldigt spännande [final] eftersom båda lagen är lika starka.", video: "final-00251-fras-4.mp4" },
    { word: "damer", phrase: "Det svenska damlaget i curling är oerhört skickliga.", video: "damer-13985-fras-1.mp4" },
    { word: "damer", phrase: "Nu i helgen är det fotbollsturnering för både herr- och damlag.", video: "damer-13985-fras-2.mp4" },
    { word: "rekord", phrase: "Göran älskar pizza. Hans [rekord] ligger på fem pizzor.", video: "rekord-04184-fras-1.mp4" },
    { word: "bana", phrase: "I bowlinghallen finns det många banor att spela på. Jag gillar inte de yttersta utan föredrar de i mitten.", video: "bana-03645-fras-1.mp4" },
    { word: "bana", phrase: "Det finns en golfbana som har en [bana] som är väldigt lång.", video: "bana-03645-fras-2.mp4" },
    { word: "idrott", phrase: "När det gäller [idrottsspelen] tycker jag inte man ska blanda in kultur, det ska bara handla om [idrott].", video: "idrott-02519-fras-1.mp4" },
    { word: "dubbel", phrase: "På förmiddagen startade man med att spela singelmatcher i tennis och sedan på eftermiddagen spelades det [dubbelmatcher].", video: "dubbel-04256-fras-1.mp4" },
    { word: "dubbel", phrase: "Vill du vara med och spela [dubbel] i pingis idag? Vi ska spela mot två väldigt duktiga spelare.", video: "dubbel-04256-fras-2.mp4" },
    { word: "mästare", phrase: "Jag har varit svensk [mästare] i bridge många gånger.", video: "mastare-00219-fras-1.mp4" },
    { word: "mästare", phrase: "Det finns ett tv-program som heter Mästarnas [mästare]. Brukar du titta på det?", video: "mastare-00219-fras-2.mp4" },
    { word: "anfall", phrase: "Jag började spela innebandy som back men numera är jag [anfallsspelare] för det är roligare att gå till [anfall].", video: "anfall-07671-fras-1.mp4" },
    { word: "anfall", phrase: "Det finns ett fotbollslag i England som har ett vasst [anfallsspel] med snabba passningar och många mål.", video: "anfall-07671-fras-2.mp4" },
    { word: "domare", phrase: "Igår tittade jag på en basketmatch, både matchen och [domaren] var verkligen bra!", video: "domare-03605-fras-1.mp4" },
    { word: "domare", phrase: "Att vara [domare] kan vara jobbigt ibland eftersom de får mycket kritik.", video: "domare-03605-fras-2.mp4" }
  ]
});
