(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "sport2",
  name: "Sport 2",
  words: [
    { word: "kvartsfinal", video: "kvartsfinal-08530-tecken.mp4", gloss: "KVART^FINAL" },
    { word: "proffs", video: "proffs-02790-tecken.mp4", gloss: "PROFFS" },
    { word: "kapten", video: "kapten-04136-tecken.mp4", gloss: "KAPTEN" },
    { word: "medalj", video: "medalj-07871-tecken.mp4", gloss: "MEDALJ" },
    { word: "klasser", video: "klasser-14059-tecken.mp4", gloss: "KLASS.PL" },
    { word: "världsmästare", video: "varldsmastare-08677-tecken.mp4", gloss: "VÄRLD^MÄSTARE" },
    { word: "regel", video: "regel-11564-tecken.mp4", gloss: "REGEL" },
    { word: "set", video: "set-14724-tecken.mp4", gloss: "SET@b" },
    { word: "debut", video: "debut-13988-tecken.mp4", gloss: "DEBUT@b" },
    { word: "gren", video: "gren-10704-tecken.mp4" },
    { word: "fysik", video: "fysik-14115-tecken.mp4" },
    { word: "center", video: "center-13968-tecken.mp4" },
    { word: "ip", video: "ip-14266-tecken.mp4" },
    { word: "stadium", video: "stadium-20032-tecken.mp4" },
    { word: "besegra", video: "besegra-14794-tecken.mp4", gloss: "BESEGRA" },
    { word: "individuell", video: "individuell-08509-tecken.mp4", gloss: "INDIVIDUELL(J)" },
    { word: "fans", video: "fans-10064-tecken.mp4" },
    { word: "landslag", video: "landslag-03367-tecken.mp4", gloss: "LANDSLAG(7o)" },
    { word: "markering", video: "markering-14452-tecken.mp4" },
    { word: "övergång", video: "overgang-08279-tecken.mp4" },
    { word: "mästerskap", video: "masterskap-14515-tecken.mp4" },
    { word: "hörna", video: "horna-00584-tecken.mp4" },
    { word: "utvisning", video: "utvisning-13549-tecken.mp4" },
    { word: "slutspel", video: "slutspel-14793-tecken.mp4" },
    { word: "reducera", video: "reducera-14646-tecken.mp4" },
    { word: "bortaplan", video: "bortaplan-14250-tecken.mp4" },
    { word: "världsrekord", video: "varldsrekord-18774-tecken.mp4" },
    { word: "oavgjort", video: "oavgjort-14546-tecken.mp4" },
    { word: "turnering", video: "turnering-13056-tecken.mp4", gloss: "TURNERING" },
    { word: "marsch", video: "marsch-14456-tecken.mp4" },
    { word: "elit", video: "elit-08481-tecken.mp4", gloss: "ELIT@b" },
    { word: "kval", video: "kval-08528-tecken.mp4" },
    { word: "tillägg", video: "tillagg-13769-tecken.mp4" },
    { word: "obligatorisk", video: "obligatorisk-02046-tecken.mp4", gloss: "OBLIGATORISK" },
    { word: "träningsläger", video: "traningslager-20220-tecken.mp4", gloss: "TRÄNA^LÄGER" },
    { word: "passning", video: "passning-14581-tecken.mp4" },
    { word: "landskamp", video: "landskamp-02062-tecken.mp4" },
    { word: "forward", video: "forward-07642-tecken.mp4", gloss: "FORWARD" },
    { word: "coach", video: "coach-08463-tecken.mp4" },
    { word: "reserv", video: "reserv-04405-tecken.mp4", gloss: "RESERV" },
    { word: "löpa", video: "lopa-03173-tecken.mp4", gloss: "SPRINGA(Lb)" },
    { word: "veteran", video: "veteran-08671-tecken.mp4" },
    { word: "hjälm", video: "hjalm-01076-tecken.mp4", gloss: "HJÄLM" },
    { word: "back", video: "back-01195-tecken.mp4" },
    { word: "kryss", video: "kryss-14370-tecken.mp4", gloss: "KRYSS" },
    { word: "mental", video: "mental-14479-tecken.mp4", gloss: "MENTAL" },
    { word: "invigning", video: "invigning-14292-tecken.mp4" }
  ],
  phrases: [
    { word: "debut", phrase: "En svensk person gjorde nyss sin [debut] i en UFC-match, det blev omedelbar vinst.", video: "debut-13988-fras-1.mp4" },
    { word: "debut", phrase: "Min systerson gör sin fotbollsdebut i allsvenskan nästa helg.", video: "debut-13988-fras-2.mp4" },
    { word: "fans", phrase: "När en känd spelare anländer med buss eller flyg så brukar det alltid stå [fans] och vänta på att få se dem.", video: "fans-10064-fras-1.mp4" },
    { word: "fans", phrase: "[Fans] är viktiga för ett lag, både för support och även för ekonomisk stöd i form av de köper entrébiljetter till matcher.", video: "fans-10064-fras-2.mp4" },
    { word: "bortaplan", phrase: "Förra helgen spelade AIK bortamatch och förlorade.", video: "bortaplan-14250-fras-1.mp4" },
    { word: "bortaplan", phrase: "De flesta lag brukar vinna sina hemmamatcher och förlora sina bortamatch.", video: "bortaplan-14250-fras-2.mp4" },
    { word: "kval", phrase: "Vårt fotbollslag måste [kvala] inför OS nästa år.", video: "kval-08528-fras-1.mp4" },
    { word: "forward", phrase: "Min kompis är verkligen en skicklig [forward] i fotboll.", video: "forward-07642-fras-1.mp4" },
    { word: "forward", phrase: "När jag var yngre så var jag fotbollsmålvakt men sedan när jag blev äldre så bytte jag position och började spela som [forward] istället.", video: "forward-07642-fras-2.mp4" },
    { word: "coach", phrase: "Min [coach] sa till mig att jag måste träna hårdare.", video: "coach-08463-fras-1.mp4" },
    { word: "coach", phrase: "Det händer att aktiva spelare blir [coach] när idrottskarriären är över.", video: "coach-08463-fras-2.mp4" },
    { word: "back", phrase: "När jag spelar fotboll är jag [back].", video: "back-01195-fras-1.mp4" }
  ]
});
