(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "teknik2",
  name: "Teknik 2",
  words: [
    { word: "surfa", video: "surfa-05343-tecken.mp4" },
    { word: "hacka", video: "hacka-10861-tecken.mp4" },
    { word: "mus", video: "mus-03635-tecken.mp4" },
    { word: "mobil", video: "mobil-05076-tecken.mp4" },
    { word: "modem", video: "modem-02100-tecken.mp4" },
    { word: "dataspel", video: "dataspel-11443-tecken.mp4" },
    { word: "www", video: "www-09271-tecken.mp4" },
    { word: "dataprogram", video: "dataprogram-11442-tecken.mp4" },
    { word: "kabel", video: "kabel-03199-tecken.mp4" },
    { word: "kod", video: "kod-09050-tecken.mp4" },
    { word: "hybrid", video: "hybrid-20125-tecken.mp4" },
    { word: "doc", video: "doc-09994-tecken.mp4" },
    { word: "filter", video: "filter-19848-tecken.mp4" },
    { word: "mekanik", video: "mekanik-19241-tecken.mp4" },
    { word: "tredimensionell", video: "tredimensionell-05032-tecken.mp4" },
    { word: "dvd", video: "dvd-08770-tecken.mp4" },
    { word: "beta", video: "beta-04301-tecken.mp4" },
    { word: "bärbar", video: "barbar-10500-tecken.mp4" },
    { word: "vidarebefordra", video: "vidarebefordra-17570-tecken.mp4" },
    { word: "gsm", video: "gsm-09630-tecken.mp4" },
    { word: "webb", video: "webb-09268-tecken.mp4" },
    { word: "dropp", video: "dropp-07506-tecken.mp4" },
    { word: "hårddisk", video: "harddisk-08966-tecken.mp4" },
    { word: "wish", video: "wish-11196-tecken.mp4" },
    { word: "programmerare", video: "programmerare-09741-tecken.mp4" },
    { word: "macintosh", video: "macintosh-05925-tecken.mp4" },
    { word: "omstart", video: "omstart-04710-tecken.mp4" },
    { word: "online", video: "online-17593-tecken.mp4" },
    { word: "operativsystem", video: "operativsystem-19281-tecken.mp4" },
    { word: "strömbrytare", video: "strombrytare-09543-tecken.mp4" },
    { word: "diskett", video: "diskett-01286-tecken.mp4" },
    { word: "tangentbord", video: "tangentbord-18753-tecken.mp4" },
    { word: "textad", video: "textad-03667-tecken.mp4" },
    { word: "plasma", video: "plasma-08315-tecken.mp4" },
    { word: "vista", video: "vista-10731-tecken.mp4" },
    { word: "gps", video: "gps-03704-tecken.mp4" },
    { word: "uppgradera", video: "uppgradera-04190-tecken.mp4" },
    { word: "tv-spel", video: "tv-spel-12294-tecken.mp4" },
    { word: "bildspel", video: "bildspel-10776-tecken.mp4" },
    { word: "word", video: "word-19472-tecken.mp4" },
    { word: "cd-spelare", video: "cd-spelare-08184-tecken.mp4" },
    { word: "antenn", video: "antenn-01048-tecken.mp4" },
    { word: "zoom", video: "zoom-17590-tecken.mp4" },
    { word: "cd-skiva", video: "cd-skiva-11343-tecken.mp4" },
    { word: "elan", video: "elan-11749-tecken.mp4" },
    { word: "konvertera", video: "konvertera-19471-tecken.mp4" },
    { word: "server", video: "server-19306-tecken.mp4" },
    { word: "navigera", video: "navigera-19526-tecken.mp4" },
    { word: "processor", video: "processor-11539-tecken.mp4" },
    { word: "datorskärm", video: "datorskarm-11449-tecken.mp4" }
  ],
  phrases: [
    { word: "surfa", phrase: "Om man vill [surfa] krävs det bra vindar.", video: "surfa-05343-fras-1.mp4" },
    { word: "mus", phrase: "Jag är inte ett dugg rädd för möss.", video: "mus-03635-fras-1.mp4" },
    { word: "mobil", phrase: "Min [mobil] är borta, har du sett den?", video: "mobil-05076-fras-1.mp4" },
    { word: "mobil", phrase: "Vad har du för märke på din [mobil]?", video: "mobil-05076-fras-2.mp4" },
    { word: "dataspel", phrase: "Mina barn älskar att spela [dataspel].", video: "dataspel-11443-fras-1.mp4" },
    { word: "dataspel", phrase: "Att spela [dataspel] är verkligen roligt, men det är lätt att bli helt uppslukad.", video: "dataspel-11443-fras-2.mp4" },
    { word: "dataprogram", phrase: "Det finns många gratis [dataprogram] som du själv kan ladda ner.", video: "dataprogram-11442-fras-1.mp4" },
    { word: "dataprogram", phrase: "Det finns både bra och dåliga [dataprogram].", video: "dataprogram-11442-fras-2.mp4" },
    { word: "kod", phrase: "Vad är det för portkod till din dörr?", video: "kod-09050-fras-1.mp4" },
    { word: "kod", phrase: "Jag har glömt bort [koden] till mitt bankkort, så jag måste beställa en ny [kod].", video: "kod-09050-fras-2.mp4" },
    { word: "tredimensionell", phrase: "Det kommer fler och fler \"skrivare\" som kan göra 3D produkter idag.", video: "tredimensionell-05032-fras-1.mp4" },
    { word: "tredimensionell", phrase: "I helgen var jag för första gången på 3D bio. Det var verkligen roligt. Det kändes som man var med i filmen.", video: "tredimensionell-05032-fras-2.mp4" },
    { word: "hårddisk", phrase: "Vilken typ av [hårddisk] vill ha du? Extern eller intern?", video: "harddisk-08966-fras-1.mp4" },
    { word: "hårddisk", phrase: "[Hårddisken] som heter SSD jobbar verkligen snabbt.", video: "harddisk-08966-fras-2.mp4" },
    { word: "macintosh", phrase: "Av olika datormärken föredrar jag en Mac.", video: "macintosh-05925-fras-1.mp4" },
    { word: "diskett", phrase: "[Disketter] är gammal teknik som inte används längre", video: "diskett-01286-fras-1.mp4" },
    { word: "diskett", phrase: "Idag är [disketter] omodern teknik, nu för tiden använder man USB eller molnet istället.", video: "diskett-01286-fras-2.mp4" },
    { word: "gps", phrase: "De flesta sportklockor har inbyggd [GPS].", video: "gps-03704-fras-1.mp4" },
    { word: "gps", phrase: "Idag finns [GPS] överallt, till exempel i mobiler, bilar, båtar och flyg.", video: "gps-03704-fras-2.mp4" },
    { word: "tv-spel", phrase: "Nu till jul funderar jag på att köpa ett [tv-spel] till min son.", video: "tv-spel-12294-fras-1.mp4" },
    { word: "tv-spel", phrase: "Min son brukar ofta vilja spela [tv-spel] med mig.", video: "tv-spel-12294-fras-2.mp4" },
    { word: "bildspel", phrase: "På min TV har jag ett [bildspel] som visar bilder på min dotter.", video: "bildspel-10776-fras-1.mp4" },
    { word: "bildspel", phrase: "En digital fotoram med [bildspel] är bra för då behöver man inte ha en massa andra foton på väggarna.", video: "bildspel-10776-fras-2.mp4" },
    { word: "antenn", phrase: "Användandet av [antenner] har börjat minska eftersom alla nya produkter har inbyggd [antenn] som ansluts via kabel.", video: "antenn-01048-fras-1.mp4" },
    { word: "antenn", phrase: "Jag har nyss köpt en [antenn] som jag tänker installera på sommarstugans tak.", video: "antenn-01048-fras-2.mp4" },
    { word: "konvertera", phrase: "Kan du hjälpa mig att [konvertera] den här filen från MOV. till MP4?", video: "konvertera-19471-fras-1.mp4" },
    { word: "konvertera", phrase: "Det finns några bra appar som du kan använda för att [konvertera] vilket format som helst.", video: "konvertera-19471-fras-2.mp4" },
    { word: "datorskärm", phrase: "På jobbet har jag två dataskärmar, en för e-post och en för redigering.", video: "datorskarm-11449-fras-1.mp4" },
    { word: "datorskärm", phrase: "På jobbet är min dataskärm 27 tum, hemma är min dataskärm 24 tum.", video: "datorskarm-11449-fras-2.mp4" }
  ]
});
