(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "teknik1",
  name: "Teknik 1",
  words: [
    { word: "tv", video: "tv-05428-tecken.mp4" },
    { word: "foto", video: "foto-00751-tecken.mp4" },
    { word: "tag", video: "tag-17510-tecken.mp4" },
    { word: "teknik", video: "teknik-04215-tecken.mp4" },
    { word: "internet", video: "internet-04907-tecken.mp4" },
    { word: "inställning", video: "installning-03174-tecken.mp4" },
    { word: "telefon", video: "telefon-03776-tecken.mp4" },
    { word: "radio", video: "radio-01498-tecken.mp4" },
    { word: "kurs", video: "kurs-01259-tecken.mp4" },
    { word: "version", video: "version-09270-tecken.mp4" },
    { word: "band", video: "band-16648-tecken.mp4" },
    { word: "dator", video: "dator-00304-tecken.mp4" },
    { word: "led", video: "led-08499-tecken.mp4" },
    { word: "nätverk", video: "natverk-12464-tecken.mp4" },
    { word: "ström", video: "strom-00871-tecken.mp4" },
    { word: "nät", video: "nat-00914-tecken.mp4" },
    { word: "ram", video: "ram-05208-tecken.mp4" },
    { word: "toner", video: "toner-05404-tecken.mp4" },
    { word: "data", video: "data-04706-tecken.mp4" },
    { word: "x", video: "x-11944-tecken.mp4" },
    { word: "morse", video: "morse-22969-tecken.mp4" },
    { word: "fält", video: "falt-19958-tecken.mp4" },
    { word: "konto", video: "konto-04525-tecken.mp4" },
    { word: "kamera", video: "kamera-03530-tecken.mp4" },
    { word: "plattform", video: "plattform-19795-tecken.mp4" },
    { word: "cd", video: "cd-04694-tecken.mp4" },
    { word: "fax", video: "fax-04761-tecken.mp4" },
    { word: "format", video: "format-19466-tecken.mp4" },
    { word: "fil", video: "fil-04011-tecken.mp4" },
    { word: "nokia", video: "nokia-16739-tecken.mp4" },
    { word: "digital", video: "digital-05734-tecken.mp4" },
    { word: "telefonsamtal", video: "telefonsamtal-19398-tecken.mp4" },
    { word: "play", video: "play-20219-tecken.mp4" },
    { word: "inspelning", video: "inspelning-00194-tecken.mp4" },
    { word: "gilla", video: "gilla-01777-tecken.mp4" },
    { word: "grafik", video: "grafik-04820-tecken.mp4" },
    { word: "högtalare", video: "hogtalare-05658-tecken.mp4" },
    { word: "box", video: "box-04435-tecken.mp4" },
    { word: "windows", video: "windows-17554-tecken.mp4" },
    { word: "installera", video: "installera-01343-tecken.mp4" },
    { word: "ladda", video: "ladda-19127-tecken.mp4" },
    { word: "kabel-tv", video: "kabel-tv-02639-tecken.mp4" },
    { word: "skärm", video: "skarm-01795-tecken.mp4" },
    { word: "växel", video: "vaxel-02000-tecken.mp4" },
    { word: "pc", video: "pc-09157-tecken.mp4" },
    { word: "bandspelare", video: "bandspelare-03233-tecken.mp4" },
    { word: "klicka", video: "klicka-17314-tecken.mp4" },
    { word: "batteri", video: "batteri-00493-tecken.mp4" },
    { word: "telefonsvarare", video: "telefonsvarare-19498-tecken.mp4" },
    { word: "cd-rom", video: "cd-rom-11342-tecken.mp4" }
  ],
  phrases: [
    { word: "tv", phrase: "[TV] utan textremsa, det är fullständigt oacceptabelt!", video: "tv-05428-fras-1.mp4" },
    { word: "foto", phrase: "Förut hade jag [fotoalbum] med massor av bilder men nu är alla [foton] i datorn.", video: "foto-00751-fras-1.mp4" },
    { word: "foto", phrase: "Jag har nyss tittat på mina föräldrars [foton], alla [foton] är svartvita. Det är fint tycker jag.", video: "foto-00751-fras-2.mp4" },
    { word: "teknik", phrase: "Det är inte lätt att dreja, du måste ha bra [teknik].", video: "teknik-04215-fras-1.mp4" },
    { word: "internet", phrase: "[Internetuppkopplingen] i lägenheten som jag nyss flyttat in i är verkligen värdelös!", video: "internet-04907-fras-1.mp4" },
    { word: "internet", phrase: "Vid mitt lantställe i skogen finns det ingen [internetuppkoppling], det är skönt ibland att det är så.", video: "internet-04907-fras-2.mp4" },
    { word: "inställning", phrase: "Hon är av åsikten att man bara stretchar före träningen och inte efteråt.", video: "installning-03174-fras-1.mp4" },
    { word: "radio", phrase: "Eftersom jag är döv så har jag ingen [radio] hemma.", video: "radio-01498-fras-1.mp4" },
    { word: "radio", phrase: "Förut var [radioapparaterna] väldigt stora, nu har de minskat väsentligt i storlek och är bara i storlek av en liten hörlur som du kan ha i örat.", video: "radio-01498-fras-2.mp4" },
    { word: "kurs", phrase: "När slutar [kursen]?", video: "kurs-01259-fras-1.mp4" },
    { word: "dator", phrase: "Jag behöver en ny [dator].", video: "dator-00304-fras-1.mp4" },
    { word: "dator", phrase: "Vilken [dator] är bäst? Är det en PC eller en Mac?", video: "dator-00304-fras-2.mp4" },
    { word: "dator", phrase: "Är du duktig på att installera program i [datorn]?", video: "dator-00304-fras-3.mp4" },
    { word: "data", phrase: "[Datauppgifterna] på pappret, var har du fått dem ifrån?", video: "data-04706-fras-1.mp4" },
    { word: "data", phrase: "Varifrån har du fått dessa [datauppgifter]?", video: "data-04706-fras-2.mp4" },
    { word: "konto", phrase: "Hos SE-banken har jag tre sorters [konton]; lönekonto, nöjeskonto samt ett buffertkonto.", video: "konto-04525-fras-1.mp4" },
    { word: "konto", phrase: "Min son börjar bli stor, han måste snart få ett eget bankkonto.", video: "konto-04525-fras-2.mp4" },
    { word: "cd", phrase: "Tidigare brukade jag bränna bilder på [cd]-skivor. Nu bränner jag på dvd-skivor istället.", video: "cd-04694-fras-1.mp4" },
    { word: "fax", phrase: "Förut använde jag [faxen] ofta men nu när email finns så gör jag inte det längre.", video: "fax-04761-fras-1.mp4" },
    { word: "fax", phrase: "Många skrivare har idag inbyggd [fax]-funktion.", video: "fax-04761-fras-2.mp4" },
    { word: "digital", phrase: "Förut sändes TV:n analogt men nu är det nedlagt och allt sänds numera [digitalt].", video: "digital-05734-fras-1.mp4" },
    { word: "inspelning", phrase: "När man ville spela in film förr i tiden så använde man sig av en VHS-spelare.", video: "inspelning-00194-fras-1.mp4" },
    { word: "inspelning", phrase: "Hörande personer brukar använda sig av en telefonsvarare, via den kan man spela in ett meddelande.", video: "inspelning-00194-fras-2.mp4" },
    { word: "inspelning", phrase: "VHS-spelare användes förr i tiden för att spela in film.", video: "inspelning-00194-fras-3.mp4" },
    { word: "högtalare", phrase: "Förut hade jag en [högtalare] hemma, jag tyckte det såg coolt ut men den användes aldrig.", video: "hogtalare-05658-fras-1.mp4" },
    { word: "högtalare", phrase: "Min bror är väldigt intresserade av olika typer av [högtalare], själv är jag helt ointresserad av det.", video: "hogtalare-05658-fras-2.mp4" },
    { word: "installera", phrase: "Imorgon bitti ska det komma en elektriker till min lägenhet för att [installera] ett nytt el-system.", video: "installera-01343-fras-1.mp4" },
    { word: "installera", phrase: "Jag ska [installera] ett nytt redigerings-program i min dator.", video: "installera-01343-fras-2.mp4" },
    { word: "ladda", phrase: "Elbilarna blir bättre och bättre, nu behöver du inte [ladda] dem lika ofta som förut.", video: "ladda-19127-fras-1.mp4" },
    { word: "ladda", phrase: "Min gamla mobil är verkligen kass, den behöver [laddas] hela tiden. Jag behöver köpa en ny mobil!", video: "ladda-19127-fras-2.mp4" },
    { word: "kabel-tv", phrase: "Förut fanns det bara två kanaler, men nu i och med [kabel-tv] så har utbudet av kanaler blivit enormt.", video: "kabel-tv-02639-fras-1.mp4" },
    { word: "kabel-tv", phrase: "I de flesta nybyggda lägenheter ingår det [kabel-tv].", video: "kabel-tv-02639-fras-2.mp4" },
    { word: "växel", phrase: "Det var svårt att lägga in backen i den gamla bilen.", video: "vaxel-02000-fras-1.mp4" },
    { word: "pc", phrase: "De flesta på mitt jobb använder [Pc] men jag använder Mac.", video: "pc-09157-fras-1.mp4" },
    { word: "bandspelare", phrase: "Om du vill ha tag på en gammal [bandspelare] så kan du kolla på Blocket. Kanske finns det någon som säljer en [bandspelare] där?", video: "bandspelare-03233-fras-1.mp4" },
    { word: "bandspelare", phrase: "Gamla bilar har fortfarande stereo med kasettband, men i nya bilar finns inte det. Där är allt digitalt istället.", video: "bandspelare-03233-fras-2.mp4" },
    { word: "klicka", phrase: "Om du vill tömma papperskorgen i datorn så är det bara att föra musen till den ikonen och [klicka].", video: "klicka-17314-fras-1.mp4" },
    { word: "klicka", phrase: "För att öppna en fil i datorn så måste du dubbelklicka på den.", video: "klicka-17314-fras-2.mp4" },
    { word: "klicka", phrase: "Hittar du inte min fil? Öppna mappen som heter \"Peter\", där finns filen.", video: "klicka-17314-fras-3.mp4" }
  ]
});
