(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "verb",
  name: "Verb",
  words: [
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "ha", video: "ha-00958-tecken.mp4" },
    { word: "få", video: "fa-00193-tecken.mp4" },
    { word: "bli", video: "bli-03181-tecken.mp4" },
    { word: "kunna", video: "kunna-05045-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "se", video: "se-04104-tecken.mp4" },
    { word: "gå", video: "ga-04238-tecken.mp4" },
    { word: "ge", video: "ge-00721-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "komma", video: "komma-09684-tecken.mp4" },
    { word: "betala", video: "betala-02433-tecken.mp4" },
    { word: "spela", video: "spela-01876-tecken.mp4" },
    { word: "försöka", video: "forsoka-04350-tecken.mp4" },
    { word: "skapa", video: "skapa-00933-tecken.mp4" },
    { word: "tala", video: "tala-02696-tecken.mp4" },
    { word: "börja", video: "borja-03852-tecken.mp4" },
    { word: "stå", video: "sta-03035-tecken.mp4" },
    { word: "fortsätta", video: "fortsatta-00331-tecken.mp4" },
    { word: "hitta", video: "hitta-01495-tecken.mp4" },
    { word: "hålla", video: "halla-02177-tecken.mp4" },
    { word: "köpa", video: "kopa-01301-tecken.mp4" },
    { word: "låta", video: "lata-05599-tecken.mp4" },
    { word: "använda", video: "anvanda-02375-tecken.mp4" },
    { word: "bygga", video: "bygga-00557-tecken.mp4" },
    { word: "visa", video: "visa-00649-tecken.mp4" },
    { word: "öka", video: "oka-00995-tecken.mp4" },
    { word: "höra", video: "hora-02663-tecken.mp4" },
    { word: "arbeta", video: "arbeta-08062-tecken.mp4" },
    { word: "tro", video: "tro-07173-tecken.mp4" },
    { word: "förstå", video: "forsta-02570-tecken.mp4" },
    { word: "lämna", video: "lamna-02056-tecken.mp4" },
    { word: "skriva", video: "skriva-03410-tecken.mp4" },
    { word: "leva", video: "leva-00849-tecken.mp4" },
    { word: "läsa", video: "lasa-00277-tecken.mp4" },
    { word: "vinna", video: "vinna-01585-tecken.mp4" },
    { word: "åka", video: "aka-04036-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" },
    { word: "sälja", video: "salja-01571-tecken.mp4" },
    { word: "nå", video: "na-00358-tecken.mp4" },
    { word: "bo", video: "bo-00050-tecken.mp4" },
    { word: "minska", video: "minska-01152-tecken.mp4" },
    { word: "sitta", video: "sitta-04009-tecken.mp4" },
    { word: "välja", video: "valja-03284-tecken.mp4" },
    { word: "leda", video: "leda-01706-tecken.mp4" },
    { word: "vilja", video: "vilja-00534-tecken.mp4" },
    { word: "vänta", video: "vanta-00207-tecken.mp4" },
    { word: "hjälpa", video: "hjalpa-00625-tecken.mp4" },
    { word: "ligga", video: "ligga-00411-tecken.mp4" },
    { word: "berätta", video: "beratta-00333-tecken.mp4" },
    { word: "behöva", video: "behova-04769-tecken.mp4" },
    { word: "satsa", video: "satsa-03628-tecken.mp4" },
    { word: "ske", video: "ske-11080-tecken.mp4" },
    { word: "prata", video: "prata-00835-tecken.mp4" },
    { word: "flytta", video: "flytta-01873-tecken.mp4" },
    { word: "titta", video: "titta-04101-tecken.mp4" },
    { word: "köra", video: "kora-02160-tecken.mp4" },
    { word: "diskutera", video: "diskutera-02702-tecken.mp4" },
    { word: "stanna", video: "stanna-00684-tecken.mp4" },
    { word: "känna", video: "kanna-04004-tecken.mp4" },
    { word: "behålla", video: "behalla-01972-tecken.mp4" },
    { word: "söka", video: "soka-04382-tecken.mp4" },
    { word: "äta", video: "ata-01267-tecken.mp4" },
    { word: "lösa", video: "losa-01869-tecken.mp4" },
    { word: "lägga", video: "lagga-00427-tecken.mp4" },
    { word: "utveckla", video: "utveckla-03100-tecken.mp4" },
    { word: "fungera", video: "fungera-00969-tecken.mp4" },
    { word: "hända", video: "handa-03023-tecken.mp4" },
    { word: "dra", video: "dra-02113-tecken.mp4" },
    { word: "jobba", video: "jobba-02063-tecken.mp4" },
    { word: "möta", video: "mota-02260-tecken.mp4" },
    { word: "svara", video: "svara-05673-tecken.mp4" },
    { word: "påverka", video: "paverka-01899-tecken.mp4" },
    { word: "rädda", video: "radda-01684-tecken.mp4" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4" },
    { word: "sluta", video: "sluta-00312-tecken.mp4" },
    { word: "förklara", video: "forklara-01820-tecken.mp4" },
    { word: "räkna", video: "rakna-01614-tecken.mp4" },
    { word: "slå", video: "sla-11468-tecken.mp4" },
    { word: "acceptera", video: "acceptera-09672-tecken.mp4" },
    { word: "delta", video: "delta-12376-tecken.mp4" },
    { word: "handla", video: "handla-02539-tecken.mp4" }
  ],
  phrases: [
    { word: "ha", phrase: "Jag [har] en stor lägenhet på åttio kvadratmeter.", video: "ha-00958-fras-1.mp4" },
    { word: "få", phrase: "Jag har inte [fått] ditt mail. Hur kommer det sig?", video: "fa-00193-fras-1.mp4" },
    { word: "få", phrase: "Jag ska [få] kattungar.", video: "fa-00193-fras-2.mp4" },
    { word: "få", phrase: "När jag var liten [fick] jag väldigt mycket i veckopeng. Det var för att jag var yngst i familjen.", video: "fa-00193-fras-3.mp4" },
    { word: "bli", phrase: "I framtiden vill jag [bli] doktor.", video: "bli-03181-fras-1.mp4" },
    { word: "bli", phrase: "Om du steker köttet för länge [blir] det alldeles för hårt.", video: "bli-03181-fras-2.mp4" },
    { word: "kunna", phrase: "Om man vill vara med på simlägret måste man [kunna] simma minst 200 meter.", video: "kunna-05045-fras-1.mp4" },
    { word: "göra", phrase: "1. Vad ska du [göra]? 2. Vad [gör] du?", video: "gora-00563-fras-1.mp4" },
    { word: "göra", phrase: "Vad brukar du [göra] på torsdagarna?", video: "gora-00563-fras-2.mp4" },
    { word: "göra", phrase: "Vad [gör] du på lördag kväll?", video: "gora-00563-fras-3.mp4" },
    { word: "göra", phrase: "1. Vad ska du [göra]? 2. Vad [gör] du?", video: "gora-00563-fras-1.mp4" },
    { word: "göra", phrase: "Vad brukar du [göra] på torsdagarna?", video: "gora-00563-fras-2.mp4" },
    { word: "göra", phrase: "Vad [gör] du på lördag kväll?", video: "gora-00563-fras-3.mp4" },
    { word: "se", phrase: "Jag har inte [sett] filmen.", video: "se-04104-fras-1.mp4" },
    { word: "se", phrase: "Det var roligt att [se] dig!", video: "se-04104-fras-2.mp4" },
    { word: "se", phrase: "Vad roligt att du [såg] mig på TV.", video: "se-04104-fras-3.mp4" },
    { word: "gå", phrase: "Om vi [går] i minst en halvtimme blir vi piggare.", video: "ga-04238-fras-1.mp4" },
    { word: "gå", phrase: "[Gå] nu!", video: "ga-04238-fras-2.mp4" },
    { word: "ge", phrase: "Jag har alltid svårt att bestämma mig för vad jag ska [ge] mina syskonbarn i [julklapp].", video: "ge-00721-fras-1.mp4" },
    { word: "ta", phrase: "Har du [tagit] med dig nycklarna och mobilen?", video: "ta-01548-fras-1.mp4" },
    { word: "ta", phrase: "Har du [tagit] med dig nycklarna och mobilen?", video: "ta-01548-fras-1.mp4" },
    { word: "betala", phrase: "Vem ska [betala]? Du eller jag?", video: "betala-02433-fras-1.mp4" },
    { word: "betala", phrase: "Man måste [betala] [avgiften]", video: "betala-02433-fras-2.mp4" },
    { word: "betala", phrase: "Du måste [betala] medlemsavgiften till dövföreningen.", video: "betala-02433-fras-3.mp4" },
    { word: "betala", phrase: "Det finns mycket vi måste [betala] för, el, mat, boende m.m.", video: "betala-02433-fras-4.mp4" },
    { word: "tala", phrase: "När jag var liten fick jag öva [talet] i skolan. Jag minns att jag avskydde [talövningarna].", video: "tala-02696-fras-1.mp4" },
    { word: "börja", phrase: "Teatern [börjar] klockan sju.", video: "borja-03852-fras-1.mp4" },
    { word: "börja", phrase: "Vi [börjar] styrelsemötet när alla har kommit.", video: "borja-03852-fras-2.mp4" },
    { word: "börja", phrase: "Starta nu!\n\n(Note: \"starta\" is not an inflected or derived form of \"börja\". The phrase contains no forms of \"börja\".)", video: "borja-03852-fras-3.mp4" },
    { word: "börja", phrase: "Mötet skulle [börja] kl 13.00 men är nu fram[flyttat] till kl. 15.00.\n\nWait, let me reconsider. The base word is \"börja\" (to begin/start). I need to find \"börja\" and its inflected or derived forms.\n\nLooking at the phrase: \"starta\" is not a form of \"börja\", and \"framflyttat\" is not a form of \"börja\" either.\n\nActually, there are no occurrences of \"börja\" or its inflected/derived forms in this phrase.\n\nMötet skulle starta kl 13.00 men är nu framflyttat till kl. 15.00.", video: "borja-03852-fras-4.mp4" },
    { word: "stå", phrase: "Det är helt omöjligt för mig att [stå] [still] en lång stund. Jag är tvungen att röra på mig.", video: "sta-03035-fras-1.mp4" },
    { word: "fortsätta", phrase: "För att hålla en brasa vid liv måste man då och då se till att fylla på med ved\n\n(The word \"fortsätta\" does not appear in this phrase.)", video: "fortsatta-00331-fras-1.mp4" },
    { word: "fortsätta", phrase: "Om jag inte blir godkänd, så tänker jag inte [fortsätta].", video: "fortsatta-00331-fras-2.mp4" },
    { word: "köpa", phrase: "Jag är sugen på att [köpa] en ny TV.", video: "kopa-01301-fras-1.mp4" },
    { word: "köpa", phrase: "Du kan [köpa] en bok men du kan aldrig [köpa] kunskap.", video: "kopa-01301-fras-2.mp4" },
    { word: "använda", phrase: "När jag har rakat mig brukar jag [använda] Boss, en aftershave, för att det inte ska klia så mycket.", video: "anvanda-02375-fras-1.mp4" },
    { word: "använda", phrase: "Många döva [använder] bildtelefon för jämnan.", video: "anvanda-02375-fras-2.mp4" },
    { word: "använda", phrase: "Jag älskar mina jeans och jag [använder] dem hela tiden.", video: "anvanda-02375-fras-3.mp4" },
    { word: "använda", phrase: "Jag [använder] datorn varje dag.", video: "anvanda-02375-fras-4.mp4" },
    { word: "bygga", phrase: "Stockholms invånarantal ökar och är snart uppe i två miljoner. Det medför att fler bostäder måste [byggas].", video: "bygga-00557-fras-1.mp4" },
    { word: "öka", phrase: "Användningen av 3D-skrivare har [ökat].", video: "oka-00995-fras-1.mp4" },
    { word: "arbeta", phrase: "Vad [arbetar] du med?", video: "arbeta-08062-fras-1.mp4" },
    { word: "arbeta", phrase: "Jag har mycket [arbete] att göra idag.", video: "arbeta-08062-fras-2.mp4" },
    { word: "förstå", phrase: "[Förstod] du det jag nyss förklarade?", video: "forsta-02570-fras-1.mp4" },
    { word: "skriva", phrase: "Att [skriva] brev är inte lika vanligt nu som det var förut.", video: "skriva-03410-fras-1.mp4" },
    { word: "skriva", phrase: "Jag läser hellre än [skriver].", video: "skriva-03410-fras-2.mp4" },
    { word: "läsa", phrase: "Jag brukar [läsa] sagor för mina barn innan de ska sova.", video: "lasa-00277-fras-1.mp4" },
    { word: "läsa", phrase: "Det är viktigt att [läsa] för att kunna samla på sig mycket kunskap.", video: "lasa-00277-fras-2.mp4" },
    { word: "vinna", phrase: "Jag [vann] på lotteri igår så nu är jag rik.", video: "vinna-01585-fras-1.mp4" },
    { word: "vinna", phrase: "Personen som [vann] 100 meter igår hade innan dess haft en dålig säsong. Känns inte rimligt att hen kunde [vinna], kanske var hen dopad?", video: "vinna-01585-fras-2.mp4" },
    { word: "tänka", phrase: "Från början [tänkte] jag vara med på klassträffen men efter en viss tvekan struntade jag i den.", video: "tanka-02584-fras-1.mp4" },
    { word: "tänka", phrase: "Från början [tänkte] jag vara med på klassträffen men efter en viss tvekan struntade jag i den.", video: "tanka-02584-fras-1.mp4" },
    { word: "sälja", phrase: "Om jag skulle [sälja] nu så skulle jag inte få ut lika mycket pengar som jag köpte varan för.", video: "salja-01571-fras-1.mp4" },
    { word: "bo", phrase: "[Var] [bor] du?\n\nWait, let me reconsider. \"Var\" is not derived from \"bo\". Let me correct:\n\nVar [bor] du?", video: "bo-00050-fras-1.mp4" },
    { word: "bo", phrase: "Var [bor] du?", video: "bo-00050-fras-2.mp4" },
    { word: "vänta", phrase: "Jag har [väntat] i tjugo minuter.", video: "vanta-00207-fras-1.mp4" },
    { word: "hjälpa", phrase: "Jag förstår mig inte på deklarationen, kan du [hjälpa] mig?", video: "hjalpa-00625-fras-1.mp4" },
    { word: "hjälpa", phrase: "Min styvfar [hjälper] alltid mig med att fylla i deklarationen.", video: "hjalpa-00625-fras-2.mp4" },
    { word: "hjälpa", phrase: "Vi mår bra om vi [hjälper] varandra.", video: "hjalpa-00625-fras-3.mp4" },
    { word: "hjälpa", phrase: "Han vill inte [hjälpa] mig vilket gör mig deppad.", video: "hjalpa-00625-fras-4.mp4" },
    { word: "berätta", phrase: "Jag tycker det är roligt att [berätta] sagor.", video: "beratta-00333-fras-1.mp4" },
    { word: "berätta", phrase: "Sluta fråga så mycket. Jag tänker inte [berätta] något.", video: "beratta-00333-fras-2.mp4" },
    { word: "behöva", phrase: "Jag [behöver] 100 kronor!", video: "behova-04769-fras-1.mp4" },
    { word: "titta", phrase: "[Titta]!", video: "titta-04101-fras-1.mp4" },
    { word: "diskutera", phrase: "Elevrådet [diskuterar] alltid viktiga skolfrågor.", video: "diskutera-02702-fras-1.mp4" },
    { word: "diskutera", phrase: "Regeringen har nu stora [diskussioner] angående budgeten.", video: "diskutera-02702-fras-2.mp4" },
    { word: "behålla", phrase: "Egentligen tänkte jag kasta alla papper men jag [behåller] nog några i alla fall.", video: "behalla-01972-fras-1.mp4" },
    { word: "äta", phrase: "Igår kväll efter mitt hårda träningspass mådde jag inte alls bra, det beror på att jag inte hade [ätit] och druckit ordentligt innan träningen.", video: "ata-01267-fras-1.mp4" },
    { word: "lösa", phrase: "Jag mår så dåligt eftersom vi har bråkat. Kan vi [lösa] det tillsammans?", video: "losa-01869-fras-1.mp4" },
    { word: "lösa", phrase: "Det ser ut som du inte vet riktigt hur du ska göra. Jag [löser] det.", video: "losa-01869-fras-2.mp4" },
    { word: "utveckla", phrase: "En del studenter [utvecklas] snabbt medan andra behöver längre tid på sig. Det är lite olika.", video: "utveckla-03100-fras-1.mp4" },
    { word: "utveckla", phrase: "De företag som vill överleva idag måste [utveckla] sina produkter.", video: "utveckla-03100-fras-2.mp4" },
    { word: "jobba", phrase: "[Jobbar] du i natt?", video: "jobba-02063-fras-1.mp4" },
    { word: "jobba", phrase: "Min dotter [jobbar] varannan helg.", video: "jobba-02063-fras-2.mp4" },
    { word: "jobba", phrase: "Varför måste du [jobba] ikväll?", video: "jobba-02063-fras-3.mp4" },
    { word: "jobba", phrase: "Jag [jobbar] inte imorgon.", video: "jobba-02063-fras-4.mp4" },
    { word: "svara", phrase: "Jag fick en [svår] fråga som jag blev helt ställd av, jag visste inte hur jag skulle [svara].", video: "svara-05673-fras-1.mp4" },
    { word: "svara", phrase: "Jag hade ett prov nyss och jag lyckades [svara] på några av frågorna som var med på provet.", video: "svara-05673-fras-2.mp4" },
    { word: "svara", phrase: "Jag kan inte [svara] på det just nu, jag måste få fundera lite först.", video: "svara-05673-fras-3.mp4" },
    { word: "svara", phrase: "Jag måste [svara] i bildtelefonen.", video: "svara-05673-fras-4.mp4" },
    { word: "påverka", phrase: "Finanskrisen kan [påverka] din ekonomi.", video: "paverka-01899-fras-1.mp4" },
    { word: "lyssna", phrase: "Det är verkligen viktigt att vi [lyssnar] på våra mammor.", video: "lyssna-00044-fras-1.mp4" },
    { word: "lyssna", phrase: "Barnen älskar att [lyssna] på musik.", video: "lyssna-00044-fras-2.mp4" },
    { word: "lyssna", phrase: "Snälla, ni måste [lyssna] på läraren.", video: "lyssna-00044-fras-3.mp4" },
    { word: "lyssna", phrase: "[Lyssna]!", video: "lyssna-00044-fras-4.mp4" },
    { word: "sluta", phrase: "Kan du [sluta] skrika!", video: "sluta-00312-fras-1.mp4" },
    { word: "sluta", phrase: "Jag [slutade] skolan när jag var 17 år gammal.", video: "sluta-00312-fras-2.mp4" },
    { word: "sluta", phrase: "När [slutar] du idag?", video: "sluta-00312-fras-3.mp4" },
    { word: "sluta", phrase: "[Sluta] med dina frågor, jag tänker ändå inte berätta.", video: "sluta-00312-fras-4.mp4" },
    { word: "förklara", phrase: "Kan du [förklara] för mig?", video: "forklara-01820-fras-1.mp4" },
    { word: "förklara", phrase: "Jag minns att jag för längesedan hade en bänkkamrat som jag ofta fick [förklara] en massa saker för när vi hade matte.", video: "forklara-01820-fras-2.mp4" },
    { word: "förklara", phrase: "Jag har [förklarat] hur datorer fungerar.", video: "forklara-01820-fras-3.mp4" },
    { word: "räkna", phrase: "Han hade lätt för att [räkna].", video: "rakna-01614-fras-1.mp4" },
    { word: "acceptera", phrase: "Jag [accepterar].", video: "acceptera-09672-fras-1.mp4" },
    { word: "acceptera", phrase: "Du får [acceptera] att man har olika åsikter.", video: "acceptera-09672-fras-2.mp4" },
    { word: "acceptera", phrase: "Okej, jag går med på det. Men på ett villkor och det är att jag får betala mindre.", video: "acceptera-09672-fras-3.mp4" },
    { word: "acceptera", phrase: "Varför kan du inte [acceptera] att vi två är tillsammans?", video: "acceptera-09672-fras-4.mp4" }
  ]
});
