(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "verb2",
  name: "Verb 2",
  words: [
    { word: "sälja", video: "salja-01571-tecken.mp4", gloss: "SÄLJA(5)" },
    { word: "nå", video: "na-00358-tecken.mp4", gloss: "KOMMA-FRAM-TILL" },
    { word: "bo", video: "bo-00050-tecken.mp4", gloss: "BO" },
    { word: "minska", video: "minska-01152-tecken.mp4", gloss: "MINSKA(Jvs)" },
    { word: "sitta", video: "sitta-04009-tecken.mp4", gloss: "SITTA" },
    { word: "välja", video: "valja-03284-tecken.mp4", gloss: "VÄLJA" },
    { word: "leda", video: "leda-01706-tecken.mp4", gloss: "LEDA-NÅGON" },
    { word: "vilja", video: "vilja-00534-tecken.mp4" },
    { word: "vänta", video: "vanta-00207-tecken.mp4", gloss: "VÄNTA" },
    { word: "hjälpa", video: "hjalpa-00625-tecken.mp4", gloss: "HJÄLPA" },
    { word: "ligga", video: "ligga-00411-tecken.mp4", gloss: "LIGGA(J)" },
    { word: "berätta", video: "beratta-00333-tecken.mp4", gloss: "BERÄTTA" },
    { word: "behöva", video: "behova-04769-tecken.mp4", gloss: "BEHÖVA(B)" },
    { word: "satsa", video: "satsa-03628-tecken.mp4", gloss: "SATSA" },
    { word: "ske", video: "ske-11080-tecken.mp4" },
    { word: "prata", video: "prata-00835-tecken.mp4", gloss: "PRATA(5)" },
    { word: "flytta", video: "flytta-01873-tecken.mp4", gloss: "FLYTTA-UT" },
    { word: "titta", video: "titta-04101-tecken.mp4", gloss: "TITTA" },
    { word: "köra", video: "kora-02160-tecken.mp4", gloss: "KÖRA-RATT" },
    { word: "diskutera", video: "diskutera-02702-tecken.mp4", gloss: "DISKUTERA" },
    { word: "stanna", video: "stanna-00684-tecken.mp4", gloss: "KVARSTANNA" },
    { word: "känna", video: "kanna-04004-tecken.mp4", gloss: "KÄNNA" },
    { word: "behålla", video: "behalla-01972-tecken.mp4", gloss: "BEHÅLLA" },
    { word: "söka", video: "soka-04382-tecken.mp4", gloss: "SÖKA" },
    { word: "äta", video: "ata-01267-tecken.mp4", gloss: "ÄTA(A)" },
    { word: "lösa", video: "losa-01869-tecken.mp4", gloss: "LÖSA" },
    { word: "lägga", video: "lagga-00427-tecken.mp4", gloss: "LÄGGA" },
    { word: "utveckla", video: "utveckla-03100-tecken.mp4", gloss: "UTVECKLA" },
    { word: "fungera", video: "fungera-00969-tecken.mp4", gloss: "FUNGERA" },
    { word: "hända", video: "handa-03023-tecken.mp4", gloss: "HÄNDA" },
    { word: "dra", video: "dra-02113-tecken.mp4", gloss: "DRA-AV" },
    { word: "jobba", video: "jobba-02063-tecken.mp4", gloss: "JOBBA" },
    { word: "möta", video: "mota-02260-tecken.mp4", gloss: "MOTSPELA" },
    { word: "svara", video: "svara-05673-tecken.mp4", gloss: "SVARA" },
    { word: "påverka", video: "paverka-01899-tecken.mp4", gloss: "PÅVERKA" },
    { word: "rädda", video: "radda-01684-tecken.mp4", gloss: "RÄDDA" },
    { word: "lyssna", video: "lyssna-00044-tecken.mp4", gloss: "LYSSNA" },
    { word: "sluta", video: "sluta-00312-tecken.mp4", gloss: "SLUTA" },
    { word: "förklara", video: "forklara-01820-tecken.mp4", gloss: "FÖRKLARA" },
    { word: "räkna", video: "rakna-01614-tecken.mp4" },
    { word: "slå", video: "sla-11468-tecken.mp4", gloss: "SLÅ(G)" },
    { word: "acceptera", video: "acceptera-09672-tecken.mp4", gloss: "ACCEPTERA(Jv)" },
    { word: "delta", video: "delta-12376-tecken.mp4" },
    { word: "handla", video: "handla-02539-tecken.mp4" }
  ],
  phrases: [
    { word: "sälja", phrase: "Om jag skulle [sälja] nu så skulle jag inte få ut lika mycket pengar som jag köpte varan för.", video: "salja-01571-fras-1.mp4" },
    { word: "bo", phrase: "Var [bor] du?", video: "bo-00050-fras-1.mp4" },
    { word: "vänta", phrase: "Jag har [väntat] i tjugo minuter.", video: "vanta-00207-fras-1.mp4" },
    { word: "hjälpa", phrase: "Jag förstår mig inte på deklarationen, kan du [hjälpa] mig?", video: "hjalpa-00625-fras-1.mp4" },
    { word: "hjälpa", phrase: "Min styvfar hjälper alltid mig med att fylla i deklarationen.", video: "hjalpa-00625-fras-2.mp4" },
    { word: "hjälpa", phrase: "Vi mår bra om vi hjälper varandra.", video: "hjalpa-00625-fras-3.mp4" },
    { word: "hjälpa", phrase: "Han vill inte [hjälpa] mig vilket gör mig deppad.", video: "hjalpa-00625-fras-4.mp4" },
    { word: "berätta", phrase: "Jag tycker det är roligt att [berätta] sagor.", video: "beratta-00333-fras-1.mp4" },
    { word: "berätta", phrase: "Sluta fråga så mycket. Jag tänker inte [berätta] något.", video: "beratta-00333-fras-2.mp4" },
    { word: "behöva", phrase: "Jag behöver 100 kronor!", video: "behova-04769-fras-1.mp4" },
    { word: "titta", phrase: "[Titta]!", video: "titta-04101-fras-1.mp4" },
    { word: "diskutera", phrase: "Elevrådet [diskuterar] alltid viktiga skolfrågor.", video: "diskutera-02702-fras-1.mp4" },
    { word: "diskutera", phrase: "Regeringen har nu stora diskussioner angående budgeten.", video: "diskutera-02702-fras-2.mp4" },
    { word: "behålla", phrase: "Egentligen tänkte jag kasta alla papper men jag behåller nog några i alla fall.", video: "behalla-01972-fras-1.mp4" },
    { word: "äta", phrase: "Igår kväll efter mitt hårda träningspass mådde jag inte alls bra, det beror på att jag inte hade ätit och druckit ordentligt innan träningen.", video: "ata-01267-fras-1.mp4" },
    { word: "lösa", phrase: "Jag mår så dåligt eftersom vi har bråkat. Kan vi [lösa] det tillsammans?", video: "losa-01869-fras-1.mp4" },
    { word: "lösa", phrase: "Det ser ut som du inte vet riktigt hur du ska göra. Jag löser det.", video: "losa-01869-fras-2.mp4" },
    { word: "utveckla", phrase: "En del studenter [utvecklas] snabbt medan andra behöver längre tid på sig. Det är lite olika.", video: "utveckla-03100-fras-1.mp4" },
    { word: "utveckla", phrase: "De företag som vill överleva idag måste [utveckla] sina produkter.", video: "utveckla-03100-fras-2.mp4" },
    { word: "jobba", phrase: "[Jobbar] du i natt?", video: "jobba-02063-fras-1.mp4" },
    { word: "jobba", phrase: "Min dotter [jobbar] varannan helg.", video: "jobba-02063-fras-2.mp4" },
    { word: "jobba", phrase: "Varför måste du [jobba] ikväll?", video: "jobba-02063-fras-3.mp4" },
    { word: "jobba", phrase: "Jag [jobbar] inte imorgon.", video: "jobba-02063-fras-4.mp4" },
    { word: "svara", phrase: "Jag fick en svår fråga som jag blev helt ställd av, jag visste inte hur jag skulle [svara].", video: "svara-05673-fras-1.mp4" },
    { word: "svara", phrase: "Jag hade ett prov nyss och jag lyckades [svara] på några av frågorna som var med på provet.", video: "svara-05673-fras-2.mp4" },
    { word: "svara", phrase: "Jag kan inte [svara] på det just nu, jag måste få fundera lite först.", video: "svara-05673-fras-3.mp4" },
    { word: "svara", phrase: "Jag måste [svara] i bildtelefonen.", video: "svara-05673-fras-4.mp4" },
    { word: "påverka", phrase: "Finanskrisen kan [påverka] din ekonomi.", video: "paverka-01899-fras-1.mp4" },
    { word: "lyssna", phrase: "Det är verkligen viktigt att vi [lyssnar] på våra mammor.", video: "lyssna-00044-fras-1.mp4" },
    { word: "lyssna", phrase: "Barnen älskar att [lyssna] på musik.", video: "lyssna-00044-fras-2.mp4" },
    { word: "lyssna", phrase: "Snälla, ni måste [lyssna] på läraren.", video: "lyssna-00044-fras-3.mp4" },
    { word: "lyssna", phrase: "[Lyssna]!", video: "lyssna-00044-fras-4.mp4" },
    { word: "sluta", phrase: "Kan du [sluta] skrika!", video: "sluta-00312-fras-1.mp4" },
    { word: "sluta", phrase: "Jag [slutade] skolan när jag var 17 år gammal.", video: "sluta-00312-fras-2.mp4" },
    { word: "sluta", phrase: "När [slutar] du idag?", video: "sluta-00312-fras-3.mp4" },
    { word: "sluta", phrase: "[Sluta] med dina frågor, jag tänker ändå inte berätta.", video: "sluta-00312-fras-4.mp4" },
    { word: "förklara", phrase: "Kan du [förklara] för mig?", video: "forklara-01820-fras-1.mp4" },
    { word: "förklara", phrase: "Jag minns att jag för längesedan hade en bänkkamrat som jag ofta fick [förklara] en massa saker för när vi hade matte.", video: "forklara-01820-fras-2.mp4" },
    { word: "förklara", phrase: "Jag har [förklarat] hur datorer fungerar.", video: "forklara-01820-fras-3.mp4" },
    { word: "räkna", phrase: "Han hade lätt för att [räkna].", video: "rakna-01614-fras-1.mp4" },
    { word: "acceptera", phrase: "Jag [accepterar].", video: "acceptera-09672-fras-1.mp4" },
    { word: "acceptera", phrase: "Du får [acceptera] att man har olika åsikter.", video: "acceptera-09672-fras-2.mp4" },
    { word: "acceptera", phrase: "Okej, jag går med på det. Men på ett villkor och det är att jag får betala mindre.", video: "acceptera-09672-fras-3.mp4" },
    { word: "acceptera", phrase: "Varför kan du inte [acceptera] att vi två är tillsammans?", video: "acceptera-09672-fras-4.mp4" }
  ]
});
