(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "verb1",
  name: "Verb 1",
  words: [
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "vara", video: "vara-05475-tecken.mp4" },
    { word: "ha", video: "ha-00958-tecken.mp4" },
    { word: "få", video: "fa-00193-tecken.mp4" },
    { word: "bli", video: "bli-03181-tecken.mp4" },
    { word: "kunna", video: "kunna-05045-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "göra", video: "gora-00563-tecken.mp4" },
    { word: "se", video: "se-04104-tecken.mp4" },
    { word: "gå", video: "ga-04238-tecken.mp4" },
    { word: "ge", video: "ge-00721-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "ta", video: "ta-01548-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "säga", video: "saga-02694-tecken.mp4" },
    { word: "komma", video: "komma-09684-tecken.mp4" },
    { word: "betala", video: "betala-02433-tecken.mp4" },
    { word: "spela", video: "spela-01876-tecken.mp4" },
    { word: "försöka", video: "forsoka-04350-tecken.mp4" },
    { word: "skapa", video: "skapa-00933-tecken.mp4" },
    { word: "tala", video: "tala-02696-tecken.mp4" },
    { word: "börja", video: "borja-03852-tecken.mp4" },
    { word: "stå", video: "sta-03035-tecken.mp4" },
    { word: "fortsätta", video: "fortsatta-00331-tecken.mp4" },
    { word: "hitta", video: "hitta-01495-tecken.mp4" },
    { word: "hålla", video: "halla-02177-tecken.mp4" },
    { word: "köpa", video: "kopa-01301-tecken.mp4" },
    { word: "låta", video: "lata-05599-tecken.mp4" },
    { word: "använda", video: "anvanda-02375-tecken.mp4" },
    { word: "bygga", video: "bygga-00557-tecken.mp4" },
    { word: "visa", video: "visa-00649-tecken.mp4" },
    { word: "öka", video: "oka-00995-tecken.mp4" },
    { word: "höra", video: "hora-02663-tecken.mp4" },
    { word: "arbeta", video: "arbeta-08062-tecken.mp4" },
    { word: "tro", video: "tro-07173-tecken.mp4" },
    { word: "förstå", video: "forsta-02570-tecken.mp4" },
    { word: "lämna", video: "lamna-02056-tecken.mp4" },
    { word: "skriva", video: "skriva-03410-tecken.mp4" },
    { word: "leva", video: "leva-00849-tecken.mp4" },
    { word: "läsa", video: "lasa-00277-tecken.mp4" },
    { word: "vinna", video: "vinna-01585-tecken.mp4" },
    { word: "åka", video: "aka-04036-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" },
    { word: "tänka", video: "tanka-02584-tecken.mp4" }
  ],
  phrases: [
    { word: "ha", phrase: "Jag [har] en stor lägenhet på åttio kvadratmeter.", video: "ha-00958-fras-1.mp4" },
    { word: "få", phrase: "Jag har inte [fått] ditt mail. Hur kommer det sig?", video: "fa-00193-fras-1.mp4" },
    { word: "få", phrase: "Jag ska [få] kattungar.", video: "fa-00193-fras-2.mp4" },
    { word: "få", phrase: "När jag var liten fick jag väldigt mycket i veckopeng. Det var för att jag var yngst i familjen.", video: "fa-00193-fras-3.mp4" },
    { word: "bli", phrase: "I framtiden vill jag [bli] doktor.", video: "bli-03181-fras-1.mp4" },
    { word: "bli", phrase: "Om du steker köttet för länge [blir] det alldeles för hårt.", video: "bli-03181-fras-2.mp4" },
    { word: "kunna", phrase: "Om man vill vara med på simlägret måste man [kunna] simma minst 200 meter.", video: "kunna-05045-fras-1.mp4" },
    { word: "göra", phrase: "1. Vad ska du [göra]? 2. Vad gör du?", video: "gora-00563-fras-1.mp4" },
    { word: "göra", phrase: "Vad brukar du [göra] på torsdagarna?", video: "gora-00563-fras-2.mp4" },
    { word: "göra", phrase: "Vad gör du på lördag kväll?", video: "gora-00563-fras-3.mp4" },
    { word: "se", phrase: "Jag har inte [sett] filmen.", video: "se-04104-fras-1.mp4" },
    { word: "se", phrase: "Det var roligt att [se] dig!", video: "se-04104-fras-2.mp4" },
    { word: "se", phrase: "Vad roligt att du såg mig på TV.", video: "se-04104-fras-3.mp4" },
    { word: "gå", phrase: "Om vi [går] i minst en halvtimme blir vi piggare.", video: "ga-04238-fras-1.mp4" },
    { word: "gå", phrase: "[Gå] nu!", video: "ga-04238-fras-2.mp4" },
    { word: "ge", phrase: "Jag har alltid svårt att bestämma mig för vad jag ska [ge] mina syskonbarn i julklapp.", video: "ge-00721-fras-1.mp4" },
    { word: "ta", phrase: "Har du [tagit] med dig nycklarna och mobilen?", video: "ta-01548-fras-1.mp4" },
    { word: "betala", phrase: "Vem ska [betala]? Du eller jag?", video: "betala-02433-fras-1.mp4" },
    { word: "betala", phrase: "Man måste [betala] avgiften", video: "betala-02433-fras-2.mp4" },
    { word: "betala", phrase: "Du måste [betala] medlemsavgiften till dövföreningen.", video: "betala-02433-fras-3.mp4" },
    { word: "betala", phrase: "Det finns mycket vi måste [betala] för, el, mat, boende m.m.", video: "betala-02433-fras-4.mp4" },
    { word: "tala", phrase: "När jag var liten fick jag öva talet i skolan. Jag minns att jag avskydde talövningarna.", video: "tala-02696-fras-1.mp4" },
    { word: "börja", phrase: "Teatern [börjar] klockan sju.", video: "borja-03852-fras-1.mp4" },
    { word: "börja", phrase: "Vi [börjar] styrelsemötet när alla har kommit.", video: "borja-03852-fras-2.mp4" },
    { word: "börja", phrase: "Starta nu!", video: "borja-03852-fras-3.mp4" },
    { word: "börja", phrase: "Mötet skulle starta kl 13.00 men är nu framflyttat till kl. 15.00.", video: "borja-03852-fras-4.mp4" },
    { word: "stå", phrase: "Det är helt omöjligt för mig att [stå] still en lång stund. Jag är tvungen att röra på mig.", video: "sta-03035-fras-1.mp4" },
    { word: "fortsätta", phrase: "För att hålla en brasa vid liv måste man då och då se till att fylla på med ved", video: "fortsatta-00331-fras-1.mp4" },
    { word: "fortsätta", phrase: "Om jag inte blir godkänd, så tänker jag inte [fortsätta].", video: "fortsatta-00331-fras-2.mp4" },
    { word: "köpa", phrase: "Jag är sugen på att [köpa] en ny TV.", video: "kopa-01301-fras-1.mp4" },
    { word: "köpa", phrase: "Du kan [köpa] en bok men du kan aldrig [köpa] kunskap.", video: "kopa-01301-fras-2.mp4" },
    { word: "använda", phrase: "När jag har rakat mig brukar jag [använda] Boss, en aftershave, för att det inte ska klia så mycket.", video: "anvanda-02375-fras-1.mp4" },
    { word: "använda", phrase: "Många döva använder bildtelefon för jämnan.", video: "anvanda-02375-fras-2.mp4" },
    { word: "använda", phrase: "Jag älskar mina jeans och jag använder dem hela tiden.", video: "anvanda-02375-fras-3.mp4" },
    { word: "använda", phrase: "Jag använder datorn varje dag.", video: "anvanda-02375-fras-4.mp4" },
    { word: "bygga", phrase: "Stockholms invånarantal ökar och är snart uppe i två miljoner. Det medför att fler bostäder måste [byggas].", video: "bygga-00557-fras-1.mp4" },
    { word: "öka", phrase: "Användningen av 3D-skrivare har [ökat].", video: "oka-00995-fras-1.mp4" },
    { word: "arbeta", phrase: "Vad [arbetar] du med?", video: "arbeta-08062-fras-1.mp4" },
    { word: "arbeta", phrase: "Jag har mycket arbete att göra idag.", video: "arbeta-08062-fras-2.mp4" },
    { word: "förstå", phrase: "Förstod du det jag nyss förklarade?", video: "forsta-02570-fras-1.mp4" },
    { word: "skriva", phrase: "Att [skriva] brev är inte lika vanligt nu som det var förut.", video: "skriva-03410-fras-1.mp4" },
    { word: "skriva", phrase: "Jag läser hellre än skriver.", video: "skriva-03410-fras-2.mp4" },
    { word: "läsa", phrase: "Jag brukar [läsa] sagor för mina barn innan de ska sova.", video: "lasa-00277-fras-1.mp4" },
    { word: "läsa", phrase: "Det är viktigt att [läsa] för att kunna samla på sig mycket kunskap.", video: "lasa-00277-fras-2.mp4" },
    { word: "vinna", phrase: "Jag vann på lotteri igår så nu är jag rik.", video: "vinna-01585-fras-1.mp4" },
    { word: "vinna", phrase: "Personen som vann 100 meter igår hade innan dess haft en dålig säsong. Känns inte rimligt att hen kunde [vinna], kanske var hen dopad?", video: "vinna-01585-fras-2.mp4" },
    { word: "tänka", phrase: "Från början tänkte jag vara med på klassträffen men efter en viss tvekan struntade jag i den.", video: "tanka-02584-fras-1.mp4" }
  ]
});
