(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "verb3",
  name: "Verb 3",
  words: [
    { word: "älska", video: "alska-06012-tecken.mp4", gloss: "ÄLSKA" },
    { word: "tycka", video: "tycka-00182-tecken.mp4", gloss: "TYCKA" },
    { word: "heta", video: "heta-02892-tecken.mp4", gloss: "HETA" },
    { word: "bruka", video: "bruka-02712-tecken.mp4", gloss: "BRUKA" },
    { word: "mena", video: "mena-02993-tecken.mp4", gloss: "MENA" },
    { word: "kosta", video: "kosta-01281-tecken.mp4", gloss: "KOSTA(A)" },
    { word: "skratta", video: "skratta-01704-tecken.mp4", gloss: "SKRATTA(5b)" },
    { word: "störa", video: "stora-00353-tecken.mp4", gloss: "STÖRA" },
    { word: "laga", video: "laga-02064-tecken.mp4", gloss: "LAGA" },
    { word: "simma", video: "simma-00666-tecken.mp4", gloss: "SIMMA" },
    { word: "promenera", video: "promenera-04240-tecken.mp4", gloss: "PROMENERA" },
    { word: "städa", video: "stada-00446-tecken.mp4", gloss: "STÄDA" },
    { word: "teckna", video: "teckna-00998-tecken.mp4", gloss: "TECKNA" },
    { word: "starta", video: "starta-03854-tecken.mp4", gloss: "STARTA" },
    { word: "skynda", video: "skynda-02244-tecken.mp4", gloss: "SKYNDA" },
    { word: "skrika", video: "skrika-04424-tecken.mp4", gloss: "SKRIKA" },
    { word: "stänga", video: "stangd-10148-tecken.mp4" },
    { word: "öppna", video: "oppna-00292-tecken.mp4", gloss: "ÖPPNA" },
    { word: "väga", video: "vaga-12239-tecken.mp4" },
    { word: "samla", video: "samla-01716-tecken.mp4", gloss: "SAMLA" },
    { word: "ursäkta", video: "ursakta-10234-tecken.mp4" },
    { word: "lyckas", video: "lyckas-01553-tecken.mp4", gloss: "LYCKAS(ea)" },
    { word: "glömma", video: "glomma-00824-tecken.mp4", gloss: "GLÖMMA" },
    { word: "ses", video: "ses-19004-tecken.mp4" },
    { word: "avsky", video: "avsky-00819-tecken.mp4", gloss: "AVSKY" },
    { word: "beställa", video: "bestalla-02739-tecken.mp4", gloss: "BESTÄLLA" },
    { word: "byta", video: "byta-03115-tecken.mp4", gloss: "BYTA(L)" },
    { word: "fixa", video: "fixa-04602-tecken.mp4", gloss: "FIXA" },
    { word: "föredra", video: "foredra-02616-tecken.mp4", gloss: "FÖREDRA" }
  ]
});
