(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "yrken2",
  name: "Yrken 2",
  words: [
    { word: "civilingenjör", video: "civilingenjor-20136-tecken.mp4" },
    { word: "säljare", video: "saljare-04279-tecken.mp4" },
    { word: "leverantör", video: "leverantor-04296-tecken.mp4" },
    { word: "kock", video: "kock-00503-tecken.mp4" },
    { word: "handläggare", video: "handlaggare-07511-tecken.mp4" },
    { word: "husmor", video: "husmor-03030-tecken.mp4" },
    { word: "försäljare", video: "forsaljare-01572-tecken.mp4" },
    { word: "tjuv", video: "tjuv-25010-tecken.mp4" },
    { word: "spion", video: "spion-07657-tecken.mp4" },
    { word: "vaktmästare", video: "vaktmastare-10035-tecken.mp4" },
    { word: "brandman", video: "brandman-03586-tecken.mp4" },
    { word: "entreprenör", video: "entreprenor-19058-tecken.mp4" },
    { word: "piga", video: "piga-04097-tecken.mp4" },
    { word: "hora", video: "hora-03463-tecken.mp4" },
    { word: "biträde", video: "bitrade-03076-tecken.mp4" },
    { word: "dräng", video: "drang-01957-tecken.mp4" },
    { word: "veterinär", video: "veterinar-04300-tecken.mp4" },
    { word: "skräddare", video: "skraddare-03385-tecken.mp4" },
    { word: "kontorist", video: "kontorist-16549-tecken.mp4" },
    { word: "dagmamma", video: "dagmamma-24167-tecken.mp4" },
    { word: "dykare", video: "dykare-00728-tecken.mp4" },
    { word: "lektor", video: "lektor-14320-tecken.mp4" },
    { word: "jungfru", video: "jungfru-05589-tecken.mp4" },
    { word: "pedagog", video: "pedagog-05165-tecken.mp4" },
    { word: "prostituerad", video: "prostituerad-19304-tecken.mp4" },
    { word: "betjänt", video: "betjant-10729-tecken.mp4" },
    { word: "snickare", video: "snickare-02191-tecken.mp4" },
    { word: "sköterska", video: "skoterska-04992-tecken.mp4" },
    { word: "servitris", video: "servitris-00226-tecken.mp4" },
    { word: "överbefälhavare", video: "overbefalhavare-09153-tecken.mp4" },
    { word: "prinsessa", video: "prinsessa-02566-tecken.mp4" },
    { word: "undersköterska", video: "underskoterska-04294-tecken.mp4" },
    { word: "trollkarl", video: "trollkarl-08611-tecken.mp4" },
    { word: "vikarie", video: "vikarie-04406-tecken.mp4" },
    { word: "designer", video: "designer-11490-tecken.mp4" },
    { word: "terapeut", video: "terapeut-08799-tecken.mp4" },
    { word: "sjöman", video: "sjoman-02473-tecken.mp4" },
    { word: "elektriker", video: "elektriker-04384-tecken.mp4" },
    { word: "instruktör", video: "instruktor-12094-tecken.mp4" },
    { word: "skeppare", video: "skeppare-03270-tecken.mp4" },
    { word: "frisör", video: "frisor-04112-tecken.mp4" },
    { word: "pilot", video: "pilot-02196-tecken.mp4" },
    { word: "övervakare", video: "overvakare-09948-tecken.mp4" },
    { word: "prefekt", video: "prefekt-15299-tecken.mp4" },
    { word: "förman", video: "forman-00218-tecken.mp4" },
    { word: "inspektör", video: "inspektor-04369-tecken.mp4" },
    { word: "riddare", video: "riddare-05220-tecken.mp4" },
    { word: "frilans", video: "frilans-17742-tecken.mp4" },
    { word: "avbytare", video: "avbytare-08456-tecken.mp4" },
    { word: "komiker", video: "komiker-17576-tecken.mp4" },
    { word: "socionom", video: "socionom-15943-tecken.mp4" },
    { word: "bankman", video: "bankman-10476-tecken.mp4" },
    { word: "kokerska", video: "kokerska-03783-tecken.mp4" },
    { word: "clown", video: "clown-04045-tecken.mp4" },
    { word: "reseledare", video: "reseledare-12507-tecken.mp4" },
    { word: "arkeolog", video: "arkeolog-15936-tecken.mp4" },
    { word: "administratör", video: "administrator-10014-tecken.mp4" },
    { word: "smed", video: "smed-02013-tecken.mp4" },
    { word: "projektansvarig", video: "projektansvarig-23042-tecken.mp4" },
    { word: "sömmerska", video: "sommerska-00398-tecken.mp4" }
  ],
  phrases: [
    { word: "säljare", phrase: "Min dotter jobbar som [säljare] i en klädaffär.", video: "saljare-04279-fras-1.mp4" },
    { word: "säljare", phrase: "Jag har jobbat som en [säljare] i ett stort företag under många år.", video: "saljare-04279-fras-2.mp4" },
    { word: "säljare", phrase: "Det finns vissa affärer som har väldigt påstridiga försäljare, jobbigt!", video: "saljare-04279-fras-3.mp4" },
    { word: "säljare", phrase: "Försäljare sa att hen måste först kolla av med sin chef om hen får sänka priset.", video: "saljare-04279-fras-4.mp4" },
    { word: "kock", phrase: "[Kockyrket] är verkligen tråkigt.", video: "kock-00503-fras-1.mp4" },
    { word: "kock", phrase: "Jag jobbar själv som [kock].", video: "kock-00503-fras-2.mp4" },
    { word: "kock", phrase: "Vill du fortfarande bli [kock] eller har du ändrat dig?", video: "kock-00503-fras-3.mp4" },
    { word: "vaktmästare", phrase: "På min arbetsplats finns det en [vaktmästare].", video: "vaktmastare-10035-fras-1.mp4" },
    { word: "brandman", phrase: "Brandmännen släcker inte bara eld utan de gör mycket annat också.", video: "brandman-03586-fras-1.mp4" },
    { word: "servitris", phrase: "På en populär restaurang här i Stockholm finns det en [servitris] som kan teckenspråk.", video: "servitris-00226-fras-1.mp4" },
    { word: "servitris", phrase: "Min mormor har arbetat som [servitris] i många år.", video: "servitris-00226-fras-2.mp4" },
    { word: "sjöman", phrase: "[Sjömansyrket] är ett av världens äldsta yrken.", video: "sjoman-02473-fras-1.mp4" },
    { word: "övervakare", phrase: "Min pappa jobbar som [övervakare] på Securitas", video: "overvakare-09948-fras-1.mp4" },
    { word: "förman", phrase: "Min pappa avskydde sin [förman] för han var alltid elak.", video: "forman-00218-fras-1.mp4" },
    { word: "administratör", phrase: "Jag är [administratör] i en grupp på facebook.", video: "administrator-10014-fras-1.mp4" },
    { word: "sömmerska", phrase: "Min farmor är väldigt duktig på att sy så när jag behöver hjälp med att laga något klädesplagg som gått sönder, lämnar jag det alltid till henne.", video: "sommerska-00398-fras-1.mp4" },
    { word: "sömmerska", phrase: "Mina jeans har gått sönder. Känner du till någon [sömmerska] som skulle kunna hjälpa mig att laga dem?", video: "sommerska-00398-fras-2.mp4" }
  ]
});
