(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "yrken1",
  name: "Yrken 1",
  words: [
    { word: "chef", video: "chef-02383-tecken.mp4" },
    { word: "president", video: "president-01395-tecken.mp4" },
    { word: "professor", video: "professor-01446-tecken.mp4" },
    { word: "forskare", video: "forskare-07273-tecken.mp4" },
    { word: "författare", video: "forfattare-12289-tecken.mp4" },
    { word: "premiärminister", video: "premiarminister-15861-tecken.mp4" },
    { word: "läkare", video: "lakare-06723-tecken.mp4" },
    { word: "advokat", video: "advokat-18688-tecken.mp4" },
    { word: "doktor", video: "doktor-00033-tecken.mp4" },
    { word: "journalist", video: "journalist-12288-tecken.mp4" },
    { word: "militär", video: "militar-04630-tecken.mp4" },
    { word: "arbetare", video: "arbetare-00999-tecken.mp4" },
    { word: "generalsekreterare", video: "generalsekreterare-19888-tecken.mp4" },
    { word: "yrke", video: "yrke-04655-tecken.mp4" },
    { word: "direktör", video: "direktor-02364-tecken.mp4" },
    { word: "arbetsgivare", video: "arbetsgivare-10244-tecken.mp4" },
    { word: "vakt", video: "vakt-04373-tecken.mp4" },
    { word: "generaldirektör", video: "generaldirektor-15821-tecken.mp4" },
    { word: "docent", video: "docent-14326-tecken.mp4" },
    { word: "general", video: "general-04395-tecken.mp4" },
    { word: "tekniker", video: "tekniker-04211-tecken.mp4" },
    { word: "åklagare", video: "aklagare-03504-tecken.mp4" },
    { word: "kapten", video: "kapten-04145-tecken.mp4" },
    { word: "rådgivare", video: "radgivare-07306-tecken.mp4" },
    { word: "tjänsteman", video: "tjansteman-15180-tecken.mp4" },
    { word: "fotograf", video: "fotograf-03528-tecken.mp4" },
    { word: "arkitekt", video: "arkitekt-04553-tecken.mp4" },
    { word: "landshövding", video: "landshovding-01394-tecken.mp4" },
    { word: "jurist", video: "jurist-04031-tecken.mp4" },
    { word: "soldat", video: "soldat-02141-tecken.mp4" },
    { word: "minister", video: "minister-09969-tecken.mp4" },
    { word: "konsult", video: "konsult-01531-tecken.mp4" },
    { word: "reporter", video: "reporter-05215-tecken.mp4" },
    { word: "mäklare", video: "maklare-03871-tecken.mp4" },
    { word: "producent", video: "producent-00725-tecken.mp4" },
    { word: "programledare", video: "programledare-20552-tecken.mp4" },
    { word: "bonde", video: "bonde-01489-tecken.mp4" },
    { word: "överste", video: "overste-18260-tecken.mp4" },
    { word: "borgmästare", video: "borgmastare-17170-tecken.mp4" },
    { word: "agent", video: "agent-24561-tecken.mp4" },
    { word: "befäl", video: "befal-04658-tecken.mp4" },
    { word: "dirigent", video: "dirigent-03132-tecken.mp4" },
    { word: "officer", video: "officer-04396-tecken.mp4" },
    { word: "fiskare", video: "fiskare-01718-tecken.mp4" },
    { word: "affärsman", video: "affarsman-08764-tecken.mp4" },
    { word: "ingenjör", video: "ingenjor-00845-tecken.mp4" },
    { word: "hantverkare", video: "hantverkare-23292-tecken.mp4" },
    { word: "polisman", video: "polisman-20560-tecken.mp4" },
    { word: "assistent", video: "assistent-10025-tecken.mp4" },
    { word: "diplomat", video: "diplomat-02129-tecken.mp4" },
    { word: "ekonom", video: "ekonom-19090-tecken.mp4" },
    { word: "guide", video: "guide-01322-tecken.mp4" },
    { word: "föreståndare", video: "forestandare-02385-tecken.mp4" },
    { word: "medium", video: "medium-20385-tecken.mp4" },
    { word: "deckare", video: "deckare-04441-tecken.mp4" },
    { word: "målare", video: "malare-03820-tecken.mp4" },
    { word: "uppfinnare", video: "uppfinnare-16327-tecken.mp4" },
    { word: "chaufför", video: "chauffor-02159-tecken.mp4" },
    { word: "handledare", video: "handledare-15346-tecken.mp4" },
    { word: "utgivare", video: "utgivare-23189-tecken.mp4" }
  ],
  phrases: [
    { word: "chef", phrase: "Till eftermiddagsfika ska [chefen] bjuda på tårta.", video: "chef-02383-fras-1.mp4" },
    { word: "president", phrase: "USA har haft 44 olika [presidenter] och det är val vart fjärde år.", video: "president-01395-fras-1.mp4" },
    { word: "president", phrase: "USA:s [president] ska göra ett besök i Sverige.", video: "president-01395-fras-2.mp4" },
    { word: "författare", phrase: "Jag tycker att Stephen King är en bra [författare].", video: "forfattare-12289-fras-1.mp4" },
    { word: "läkare", phrase: "För att bli [läkare] måste man studera länge.", video: "lakare-06723-fras-1.mp4" },
    { word: "läkare", phrase: "[Läkaren] är riktigt orolig över biverkningen.", video: "lakare-06723-fras-2.mp4" },
    { word: "läkare", phrase: "Nä, min fru är [läkare].", video: "lakare-06723-fras-3.mp4" },
    { word: "advokat", phrase: "Mitt drömyrke är [advokat].", video: "advokat-18688-fras-1.mp4" },
    { word: "doktor", phrase: "Läkaren sa att jag är frisk nu.", video: "doktor-00033-fras-1.mp4" },
    { word: "doktor", phrase: "Undersökte läkaren dig?", video: "doktor-00033-fras-2.mp4" },
    { word: "journalist", phrase: "[Journalistens] jobb är att jaga nyheter.", video: "journalist-12288-fras-1.mp4" },
    { word: "militär", phrase: "Den första [militärhögskolan] startades 1818 här i Stockholm.", video: "militar-04630-fras-1.mp4" },
    { word: "militär", phrase: "Idag är det möjligt för tjejer att rycka in och göra lumpen.", video: "militar-04630-fras-2.mp4" },
    { word: "vakt", phrase: "När jag var liten ville jag antingen bli väktare eller polis.", video: "vakt-04373-fras-1.mp4" },
    { word: "vakt", phrase: "De flesta nattklubbar har [vakter] för att förhindra bråk.", video: "vakt-04373-fras-2.mp4" },
    { word: "jurist", phrase: "Om du är osäker på hur du upprättar ett testamente kan du ta kontakt med en [jurist] för rådgivning.", video: "jurist-04031-fras-1.mp4" },
    { word: "minister", phrase: "I regeringen finns det olika ministrar.", video: "minister-09969-fras-1.mp4" },
    { word: "konsult", phrase: "Om jag skulle starta eget skulle det helt klart bli en [konsultfirma]. För då skulle jag ha större möjligheter på ett bredare arbetsområde.", video: "konsult-01531-fras-1.mp4" },
    { word: "mäklare", phrase: "Jag vill sälja min lägenhet så jag tänker kontakta en [mäklare] i morgon.", video: "maklare-03871-fras-1.mp4" },
    { word: "producent", phrase: "Känner du [producenten]?", video: "producent-00725-fras-1.mp4" },
    { word: "producent", phrase: "Filmens [producent] heter Kevin.", video: "producent-00725-fras-2.mp4" },
    { word: "producent", phrase: "Min dröm är att bli filmproducent.", video: "producent-00725-fras-3.mp4" },
    { word: "bonde", phrase: "Jag är uppvuxen på en bondgård så när jag flyttade hit till Stockholm var jag väldigt ovan vid det höga tempot.", video: "bonde-01489-fras-1.mp4" },
    { word: "fiskare", phrase: "Min morbror är en inbiten [fiskare]. Han reser ofta till Norrland för att fiska.", video: "fiskare-01718-fras-1.mp4" },
    { word: "fiskare", phrase: "Fiskaryrket är hårt och tungt men man tjänar bra.", video: "fiskare-01718-fras-2.mp4" },
    { word: "affärsman", phrase: "Min dröm är att jobba som [affärsman] eftersom man nog får resa mycket i jobbet.", video: "affarsman-08764-fras-1.mp4" },
    { word: "assistent", phrase: "På dövskolorna finns det många [assistenter] som är döva.", video: "assistent-10025-fras-1.mp4" },
    { word: "assistent", phrase: "De som är äldre behöver [assistenter] som följer med dem.", video: "assistent-10025-fras-2.mp4" },
    { word: "assistent", phrase: "Det finns personer som behöver [assistenter].", video: "assistent-10025-fras-3.mp4" },
    { word: "målare", phrase: "Jag känner många [målare] som kan hjälpa oss med köket.", video: "malare-03820-fras-1.mp4" },
    { word: "uppfinnare", phrase: "Du vet väl vem som uppfann mobilen!?", video: "uppfinnare-16327-fras-1.mp4" },
    { word: "uppfinnare", phrase: "I Sveriges historia fram till idag kan man hitta många [uppfinnare].", video: "uppfinnare-16327-fras-2.mp4" }
  ]
});
