(window.WORDLISTS = window.WORDLISTS || []).push({
  id: "familj",
  name: "Familj",
  words: [
    { word: "man", video: "man-05036-tecken.mp4" },
    { word: "barn", video: "barn-00257-tecken.mp4" },
    { word: "mamma", video: "mamma-00188-tecken.mp4" },
    { word: "pappa", video: "pappa-02557-tecken.mp4" },
    { word: "föräldrar", video: "foraldrar-13821-tecken.mp4" },
    { word: "familj", video: "familj-00773-tecken.mp4" },
    { word: "son", video: "son-01944-tecken.mp4" },
    { word: "fru", video: "fru-04582-tecken.mp4" },
    { word: "dotter", video: "dotter-00111-tecken.mp4" },
    { word: "syster", video: "syster-03513-tecken.mp4" },
    { word: "bror", video: "bror-03462-tecken.mp4" },
    { word: "mormor", video: "mormor-01938-tecken.mp4" },
    { word: "farfar", video: "farfar-01932-tecken.mp4" },
    { word: "farbror", video: "farbror-02752-tecken.mp4" },
    { word: "farmor", video: "farmor-01933-tecken.mp4" },
    { word: "släkt", video: "slakt-03156-tecken.mp4" },
    { word: "barnbarn", video: "barnbarn-04647-tecken.mp4" },
    { word: "moster", video: "moster-00176-tecken.mp4" },
    { word: "syskon", video: "syskon-03564-tecken.mp4" },
    { word: "morfar", video: "morfar-01937-tecken.mp4" },
    { word: "lillebror", video: "lillebror-16156-tecken.mp4" },
    { word: "kusin", video: "kusin-03155-tecken.mp4" },
    { word: "sambo", video: "sambo-05067-tecken.mp4" },
    { word: "flickvän", video: "flickvan-11970-tecken.mp4" },
    { word: "pojkvän", video: "pojkvan-12482-tecken.mp4" },
    { word: "storebror", video: "storebror-15963-tecken.mp4" },
    { word: "släkting", video: "slakting-20134-tecken.mp4" },
    { word: "faster", video: "faster-01399-tecken.mp4" },
    { word: "morbror", video: "morbror-05083-tecken.mp4" },
    { word: "svärmor", video: "svarmor-05352-tecken.mp4" },
    { word: "fästmö", video: "fastmo-02487-tecken.mp4" },
    { word: "svåger", video: "svager-03157-tecken.mp4" },
    { word: "svärfar", video: "svarfar-05350-tecken.mp4" },
    { word: "storasyster", video: "storasyster-15946-tecken.mp4" },
    { word: "styvmor", video: "styvmor-08496-tecken.mp4" },
    { word: "fästman", video: "fastman-15888-tecken.mp4" },
    { word: "brorson", video: "brorson-18608-tecken.mp4" },
    { word: "styvfar", video: "styvfar-00433-tecken.mp4" },
    { word: "halvbror", video: "halvbror-19344-tecken.mp4" },
    { word: "systerdotter", video: "systerdotter-18612-tecken.mp4" },
    { word: "systerson", video: "systerson-18613-tecken.mp4" },
    { word: "svärföräldrar", video: "svarforaldrar-05351-tecken.mp4" },
    { word: "halvsyster", video: "halvsyster-24352-tecken.mp4" },
    { word: "brorsdotter", video: "brorsdotter-18609-tecken.mp4" },
    { word: "måg", video: "mag-19339-tecken.mp4" },
    { word: "sladdbarn", video: "sladdbarn-16325-tecken.mp4" },
    { word: "släktmiddag", video: "slaktmiddag-24729-tecken.mp4" },
    { word: "morförälder", video: "morforalder-04257-tecken.mp4" },
    { word: "gammelfarmor", video: "gammelfarmor-08414-tecken.mp4" },
    { word: "långsläkt", video: "langslakt-24771-tecken.mp4" }
  ]
});
